#!/usr/bin/env bash
# GENERATED by board_zybo.py. The Zybo Z7-20, 32 lanes bitstream without Vivado: Yosys,
# nextpnr-xilinx and Project X-Ray (openXC7). One-off setup, tested on an
# ARM Mac (Apple clang, no OpenMP):
#   git clone --recurse-submodules https://github.com/openXC7/nextpnr-xilinx
#     (tested at bc9b2346), git apply nextpnr-xilinx-dsp.patch, then
#   cmake -B build -DARCH=xilinx -DBUILD_GUI=OFF -DBUILD_PYTHON=OFF -DUSE_OPENMP=OFF
#   cmake --build build
#   python3 xilinx/python/bbaexport.py --device xc7z020clg400-1 --bba xilinx/xc7z020.bba
#   build/bbasm --l xilinx/xc7z020.bba xilinx/xc7z020.bin
#   git clone --recurse-submodules https://github.com/openXC7/prjxray
#     (tested at 9553f1ad), git apply prjxray-glue.patch, cmake -B build,
#     cmake --build build
# Set NEXTPNR_XILINX to the
# nextpnr-xilinx checkout (with xilinx/xc7z020.bin built) and XRAY_DIR to
# a built prjxray checkout, and PYTHON to a python3 that has prjxray's
# packages (pip install -e "$XRAY_DIR/third_party/fasm" -e "$XRAY_DIR").
# The PS7's own setup (DDR, clocks, level
# shifters) is software's job, done by ps7_init from any Zybo Z7-20, 32 lanes Vivado
# project with its board preset, as on any Zynq.
set -euo pipefail
cd "$(dirname "$0")"
: "${NEXTPNR_XILINX:?set NEXTPNR_XILINX}" "${XRAY_DIR:?set XRAY_DIR}"
cp ../rtl/gains.hex .
yosys -q -l yosys.log -p "read_verilog fpgai_ps7.v $(ls ../rtl/*.v | tr '\n' ' '); \
  synth_xilinx -flatten -abc9 -arch xc7 -top fpgai_ps7 -run :map_dsp; \
  select -set soft t:\$mul c:*slane?0?.* c:*slane?1?.* c:*slane?2?.* c:*slane?3?.* c:*slane?4?.* c:*slane?5?.* c:*slane?6?.* c:*slane?7?.* c:*slane?8?.* c:*slane?9?.* c:*slane?10?.* c:*slane?11?.* c:*slane?12?.* c:*slane?13?.* c:*slane?14?.* c:*slane?15?.* c:*slane?16?.* c:*slane?17?.* c:*slane?18?.* c:*slane?19?.* c:*slane?20?.* c:*slane?21?.* c:*slane?22?.* c:*slane?23?.* %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %u %i; chtype -set \$__soft_mul @soft; \
  synth_xilinx -flatten -abc9 -arch xc7 -top fpgai_ps7 -run map_dsp:; write_json fpgai.json"
"$NEXTPNR_XILINX/build/nextpnr-xilinx" --chipdb "$NEXTPNR_XILINX/xilinx/xc7z020.bin" \
  --xdc open.xdc --json fpgai.json --fasm fpgai.fasm --freq 50 \
  --report report.json --log nextpnr.log
"${PYTHON:-python3}" "$XRAY_DIR/utils/fasm2frames.py" --part xc7z020clg400-1 \
  --db-root "$NEXTPNR_XILINX/xilinx/external/prjxray-db/zynq7" fpgai.fasm > fpgai.frames
"$XRAY_DIR/build/tools/xc7frames2bit" \
  --part_file "$NEXTPNR_XILINX/xilinx/external/prjxray-db/zynq7/xc7z020clg400-1/part.yaml" \
  --part_name xc7z020clg400-1 --frm_file fpgai.frames --output_file fpgai.bit
echo "bitstream: $(pwd)/fpgai.bit"
