// GENERATED by board_zybo.py: do not edit by hand.
// fpgai_zybo on the Zynq's PS7 without Vivado's block design, for the
// open flow in open/. Vivado uses build.tcl instead.
module fpgai_ps7 (output busy_led);
  wire [3:0] fclk, frstn;
  wire clk;
  BUFG bg_fclk (.I(fclk[0]), .O(clk));
  reg [2:0] rs;
  always @(posedge clk) rs <= {rs[1:0], frstn[0]};
  wire rst_n = rs[2];

  // GP0, AXI3 from the CPU, to the register block's AXI-Lite.
  wire [31:0] gp_awaddr, gp_araddr, gp_wdata, gp_rdata;
  wire [11:0] gp_awid, gp_arid;
  wire gp_awvalid, gp_awready, gp_wvalid, gp_wready, gp_bvalid, gp_bready;
  wire gp_arvalid, gp_arready, gp_rvalid, gp_rready;
  wire [3:0] gp_wstrb;
  wire [1:0] gp_bresp, gp_rresp;
  reg [11:0] bid, rid;
  always @(posedge clk) begin
    if (gp_awvalid && gp_awready) bid <= gp_awid;
    if (gp_arvalid && gp_arready) rid <= gp_arid;
  end

  wire [31:0] w0_araddr; wire [7:0] w0_arlen; wire [2:0] w0_arsize, w0_arprot;
  wire [1:0] w0_arburst, w0_rresp; wire [3:0] w0_arcache, w0_arqos;
  wire w0_arlock, w0_arvalid, w0_arready, w0_rlast, w0_rvalid, w0_rready;
  wire [63:0] w0_rdata;
  wire [31:0] w1_araddr; wire [7:0] w1_arlen; wire [2:0] w1_arsize, w1_arprot;
  wire [1:0] w1_arburst, w1_rresp; wire [3:0] w1_arcache, w1_arqos;
  wire w1_arlock, w1_arvalid, w1_arready, w1_rlast, w1_rvalid, w1_rready;
  wire [63:0] w1_rdata;
  wire [31:0] w2_araddr; wire [7:0] w2_arlen; wire [2:0] w2_arsize, w2_arprot;
  wire [1:0] w2_arburst, w2_rresp; wire [3:0] w2_arcache, w2_arqos;
  wire w2_arlock, w2_arvalid, w2_arready, w2_rlast, w2_rvalid, w2_rready;
  wire [63:0] w2_rdata;
  wire [31:0] w3_araddr; wire [7:0] w3_arlen; wire [2:0] w3_arsize, w3_arprot;
  wire [1:0] w3_arburst, w3_rresp; wire [3:0] w3_arcache, w3_arqos;
  wire w3_arlock, w3_arvalid, w3_arready, w3_rlast, w3_rvalid, w3_rready;
  wire [63:0] w3_rdata;
  wire [31:0] kv_araddr, kv_awaddr; wire [7:0] kv_arlen, kv_awlen;
  wire [2:0] kv_arsize, kv_arprot, kv_awsize, kv_awprot;
  wire [1:0] kv_arburst, kv_awburst, kv_rresp, kv_bresp;
  wire [3:0] kv_arcache, kv_arqos, kv_awcache, kv_awqos;
  wire kv_arlock, kv_awlock, kv_arvalid, kv_arready, kv_rlast, kv_rvalid, kv_rready;
  wire kv_awvalid, kv_awready, kv_wlast, kv_wvalid, kv_wready, kv_bvalid, kv_bready;
  wire [63:0] kv_rdata, kv_wdata; wire [7:0] kv_wstrb;

  fpgai_zybo u (.aclk(clk), .aresetn(rst_n),
    .s_axi_awaddr(gp_awaddr[5:0]), .s_axi_awvalid(gp_awvalid), .s_axi_awready(gp_awready),
    .s_axi_wdata(gp_wdata), .s_axi_wstrb(gp_wstrb), .s_axi_wvalid(gp_wvalid),
    .s_axi_wready(gp_wready), .s_axi_bresp(gp_bresp), .s_axi_bvalid(gp_bvalid),
    .s_axi_bready(gp_bready), .s_axi_araddr(gp_araddr[5:0]), .s_axi_arvalid(gp_arvalid),
    .s_axi_arready(gp_arready), .s_axi_rdata(gp_rdata), .s_axi_rresp(gp_rresp),
    .s_axi_rvalid(gp_rvalid), .s_axi_rready(gp_rready),
    .m_axi_w0_araddr(w0_araddr), .m_axi_w0_arlen(w0_arlen),
    .m_axi_w0_arsize(w0_arsize), .m_axi_w0_arburst(w0_arburst),
    .m_axi_w0_arcache(w0_arcache), .m_axi_w0_arprot(w0_arprot),
    .m_axi_w0_arlock(w0_arlock), .m_axi_w0_arqos(w0_arqos),
    .m_axi_w0_arvalid(w0_arvalid), .m_axi_w0_arready(w0_arready),
    .m_axi_w0_rdata(w0_rdata), .m_axi_w0_rresp(w0_rresp),
    .m_axi_w0_rlast(w0_rlast), .m_axi_w0_rvalid(w0_rvalid),
    .m_axi_w0_rready(w0_rready),
    .m_axi_w1_araddr(w1_araddr), .m_axi_w1_arlen(w1_arlen),
    .m_axi_w1_arsize(w1_arsize), .m_axi_w1_arburst(w1_arburst),
    .m_axi_w1_arcache(w1_arcache), .m_axi_w1_arprot(w1_arprot),
    .m_axi_w1_arlock(w1_arlock), .m_axi_w1_arqos(w1_arqos),
    .m_axi_w1_arvalid(w1_arvalid), .m_axi_w1_arready(w1_arready),
    .m_axi_w1_rdata(w1_rdata), .m_axi_w1_rresp(w1_rresp),
    .m_axi_w1_rlast(w1_rlast), .m_axi_w1_rvalid(w1_rvalid),
    .m_axi_w1_rready(w1_rready),
    .m_axi_w2_araddr(w2_araddr), .m_axi_w2_arlen(w2_arlen),
    .m_axi_w2_arsize(w2_arsize), .m_axi_w2_arburst(w2_arburst),
    .m_axi_w2_arcache(w2_arcache), .m_axi_w2_arprot(w2_arprot),
    .m_axi_w2_arlock(w2_arlock), .m_axi_w2_arqos(w2_arqos),
    .m_axi_w2_arvalid(w2_arvalid), .m_axi_w2_arready(w2_arready),
    .m_axi_w2_rdata(w2_rdata), .m_axi_w2_rresp(w2_rresp),
    .m_axi_w2_rlast(w2_rlast), .m_axi_w2_rvalid(w2_rvalid),
    .m_axi_w2_rready(w2_rready),
    .m_axi_w3_araddr(w3_araddr), .m_axi_w3_arlen(w3_arlen),
    .m_axi_w3_arsize(w3_arsize), .m_axi_w3_arburst(w3_arburst),
    .m_axi_w3_arcache(w3_arcache), .m_axi_w3_arprot(w3_arprot),
    .m_axi_w3_arlock(w3_arlock), .m_axi_w3_arqos(w3_arqos),
    .m_axi_w3_arvalid(w3_arvalid), .m_axi_w3_arready(w3_arready),
    .m_axi_w3_rdata(w3_rdata), .m_axi_w3_rresp(w3_rresp),
    .m_axi_w3_rlast(w3_rlast), .m_axi_w3_rvalid(w3_rvalid),
    .m_axi_w3_rready(w3_rready),
    .m_axi_kv_araddr(kv_araddr), .m_axi_kv_arlen(kv_arlen), .m_axi_kv_arsize(kv_arsize),
    .m_axi_kv_arburst(kv_arburst), .m_axi_kv_arcache(kv_arcache), .m_axi_kv_arprot(kv_arprot),
    .m_axi_kv_arlock(kv_arlock), .m_axi_kv_arqos(kv_arqos), .m_axi_kv_arvalid(kv_arvalid),
    .m_axi_kv_arready(kv_arready), .m_axi_kv_rdata(kv_rdata), .m_axi_kv_rresp(kv_rresp),
    .m_axi_kv_rlast(kv_rlast), .m_axi_kv_rvalid(kv_rvalid), .m_axi_kv_rready(kv_rready),
    .m_axi_kv_awaddr(kv_awaddr), .m_axi_kv_awlen(kv_awlen), .m_axi_kv_awsize(kv_awsize),
    .m_axi_kv_awburst(kv_awburst), .m_axi_kv_awcache(kv_awcache), .m_axi_kv_awprot(kv_awprot),
    .m_axi_kv_awlock(kv_awlock), .m_axi_kv_awqos(kv_awqos), .m_axi_kv_awvalid(kv_awvalid),
    .m_axi_kv_awready(kv_awready), .m_axi_kv_wdata(kv_wdata), .m_axi_kv_wstrb(kv_wstrb),
    .m_axi_kv_wlast(kv_wlast), .m_axi_kv_wvalid(kv_wvalid), .m_axi_kv_wready(kv_wready),
    .m_axi_kv_bresp(kv_bresp), .m_axi_kv_bvalid(kv_bvalid), .m_axi_kv_bready(kv_bready),
    .busy_led(busy_led));

  (* keep *) PS7 ps7 (
    .FCLKCLK(fclk), .FCLKRESETN(frstn),
    .MAXIGP0ACLK(clk), .MAXIGP0AWADDR(gp_awaddr), .MAXIGP0AWID(gp_awid),
    .MAXIGP0AWVALID(gp_awvalid), .MAXIGP0AWREADY(gp_awready),
    .MAXIGP0WDATA(gp_wdata), .MAXIGP0WSTRB(gp_wstrb), .MAXIGP0WVALID(gp_wvalid),
    .MAXIGP0WREADY(gp_wready), .MAXIGP0BID(bid), .MAXIGP0BRESP(gp_bresp),
    .MAXIGP0BVALID(gp_bvalid), .MAXIGP0BREADY(gp_bready),
    .MAXIGP0ARADDR(gp_araddr), .MAXIGP0ARID(gp_arid), .MAXIGP0ARVALID(gp_arvalid),
    .MAXIGP0ARREADY(gp_arready), .MAXIGP0RDATA(gp_rdata), .MAXIGP0RID(rid),
    .MAXIGP0RRESP(gp_rresp), .MAXIGP0RLAST(1'b1), .MAXIGP0RVALID(gp_rvalid),
    .MAXIGP0RREADY(gp_rready),
    .SAXIHP0ACLK(clk), .SAXIHP0ARADDR(w0_araddr), .SAXIHP0ARLEN(w0_arlen[3:0]),
    .SAXIHP0ARSIZE(w0_arsize[1:0]), .SAXIHP0ARBURST(w0_arburst),
    .SAXIHP0ARCACHE(w0_arcache), .SAXIHP0ARPROT(w0_arprot),
    .SAXIHP0ARLOCK({1'b0, w0_arlock}), .SAXIHP0ARQOS(w0_arqos), .SAXIHP0ARID(6'd0),
    .SAXIHP0ARVALID(w0_arvalid), .SAXIHP0ARREADY(w0_arready),
    .SAXIHP0RDATA(w0_rdata), .SAXIHP0RRESP(w0_rresp), .SAXIHP0RLAST(w0_rlast),
    .SAXIHP0RVALID(w0_rvalid), .SAXIHP0RREADY(w0_rready),
    .SAXIHP0RDISSUECAP1EN(1'b0), .SAXIHP0WRISSUECAP1EN(1'b0),
    .SAXIHP0AWVALID(1'b0), .SAXIHP0WVALID(1'b0), .SAXIHP0BREADY(1'b1),
    .SAXIHP1ACLK(clk), .SAXIHP1ARADDR(w1_araddr), .SAXIHP1ARLEN(w1_arlen[3:0]),
    .SAXIHP1ARSIZE(w1_arsize[1:0]), .SAXIHP1ARBURST(w1_arburst),
    .SAXIHP1ARCACHE(w1_arcache), .SAXIHP1ARPROT(w1_arprot),
    .SAXIHP1ARLOCK({1'b0, w1_arlock}), .SAXIHP1ARQOS(w1_arqos), .SAXIHP1ARID(6'd0),
    .SAXIHP1ARVALID(w1_arvalid), .SAXIHP1ARREADY(w1_arready),
    .SAXIHP1RDATA(w1_rdata), .SAXIHP1RRESP(w1_rresp), .SAXIHP1RLAST(w1_rlast),
    .SAXIHP1RVALID(w1_rvalid), .SAXIHP1RREADY(w1_rready),
    .SAXIHP1RDISSUECAP1EN(1'b0), .SAXIHP1WRISSUECAP1EN(1'b0),
    .SAXIHP1AWVALID(1'b0), .SAXIHP1WVALID(1'b0), .SAXIHP1BREADY(1'b1),
    .SAXIHP2ACLK(clk), .SAXIHP2ARADDR(w2_araddr), .SAXIHP2ARLEN(w2_arlen[3:0]),
    .SAXIHP2ARSIZE(w2_arsize[1:0]), .SAXIHP2ARBURST(w2_arburst),
    .SAXIHP2ARCACHE(w2_arcache), .SAXIHP2ARPROT(w2_arprot),
    .SAXIHP2ARLOCK({1'b0, w2_arlock}), .SAXIHP2ARQOS(w2_arqos), .SAXIHP2ARID(6'd0),
    .SAXIHP2ARVALID(w2_arvalid), .SAXIHP2ARREADY(w2_arready),
    .SAXIHP2RDATA(w2_rdata), .SAXIHP2RRESP(w2_rresp), .SAXIHP2RLAST(w2_rlast),
    .SAXIHP2RVALID(w2_rvalid), .SAXIHP2RREADY(w2_rready),
    .SAXIHP2RDISSUECAP1EN(1'b0), .SAXIHP2WRISSUECAP1EN(1'b0),
    .SAXIHP2AWVALID(1'b0), .SAXIHP2WVALID(1'b0), .SAXIHP2BREADY(1'b1),
    .SAXIHP3ACLK(clk), .SAXIHP3ARADDR(w3_araddr), .SAXIHP3ARLEN(w3_arlen[3:0]),
    .SAXIHP3ARSIZE(w3_arsize[1:0]), .SAXIHP3ARBURST(w3_arburst),
    .SAXIHP3ARCACHE(w3_arcache), .SAXIHP3ARPROT(w3_arprot),
    .SAXIHP3ARLOCK({1'b0, w3_arlock}), .SAXIHP3ARQOS(w3_arqos), .SAXIHP3ARID(6'd0),
    .SAXIHP3ARVALID(w3_arvalid), .SAXIHP3ARREADY(w3_arready),
    .SAXIHP3RDATA(w3_rdata), .SAXIHP3RRESP(w3_rresp), .SAXIHP3RLAST(w3_rlast),
    .SAXIHP3RVALID(w3_rvalid), .SAXIHP3RREADY(w3_rready),
    .SAXIHP3RDISSUECAP1EN(1'b0), .SAXIHP3WRISSUECAP1EN(1'b0),
    .SAXIHP3AWVALID(1'b0), .SAXIHP3WVALID(1'b0), .SAXIHP3BREADY(1'b1),
    .SAXIACPACLK(clk), .SAXIACPARADDR(kv_araddr), .SAXIACPARLEN(kv_arlen[3:0]),
    .SAXIACPARSIZE(kv_arsize[1:0]), .SAXIACPARBURST(kv_arburst), .SAXIACPARCACHE(kv_arcache),
    .SAXIACPARPROT(kv_arprot), .SAXIACPARLOCK({1'b0, kv_arlock}), .SAXIACPARQOS(kv_arqos),
    .SAXIACPARID(3'd0), .SAXIACPARUSER(5'd0), .SAXIACPARVALID(kv_arvalid),
    .SAXIACPARREADY(kv_arready), .SAXIACPRDATA(kv_rdata), .SAXIACPRRESP(kv_rresp),
    .SAXIACPRLAST(kv_rlast), .SAXIACPRVALID(kv_rvalid), .SAXIACPRREADY(kv_rready),
    .SAXIACPAWADDR(kv_awaddr), .SAXIACPAWLEN(kv_awlen[3:0]), .SAXIACPAWSIZE(kv_awsize[1:0]),
    .SAXIACPAWBURST(kv_awburst), .SAXIACPAWCACHE(kv_awcache), .SAXIACPAWPROT(kv_awprot),
    .SAXIACPAWLOCK({1'b0, kv_awlock}), .SAXIACPAWQOS(kv_awqos), .SAXIACPAWID(3'd0),
    .SAXIACPAWUSER(5'd0), .SAXIACPAWVALID(kv_awvalid), .SAXIACPAWREADY(kv_awready),
    .SAXIACPWDATA(kv_wdata), .SAXIACPWSTRB(kv_wstrb), .SAXIACPWLAST(kv_wlast),
    .SAXIACPWID(3'd0), .SAXIACPWVALID(kv_wvalid), .SAXIACPWREADY(kv_wready),
    .SAXIACPBRESP(kv_bresp), .SAXIACPBVALID(kv_bvalid), .SAXIACPBREADY(kv_bready));
endmodule
