# GENERATED by board.py. Build the Basys 3 bitstream:
#   vivado -mode batch -source build.tcl
# Vivado needs an x86 host; everything this reads is in this directory.
create_project -force fpgai ./vivado -part xc7a35tcpg236-1
add_files [glob ./rtl/*.v]
add_files -fileset constrs_1 ./basys3.xdc
add_files ./qwen_params.hex
set_property file_type {Memory Initialization Files} [get_files qwen_params.hex]
set_property top fpgai_top [current_fileset]
launch_runs synth_1 -jobs 4
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
open_run impl_1
report_timing_summary -file timing.rpt
report_utilization -file utilization.rpt
puts "bitstream: [glob ./vivado/fpgai.runs/impl_1/*.bit]"
