`timescale 1ns/1ps
// GENERATED by board.py: the whole top level over its UART.
module tb_fpgai_top;
  reg clk = 0, btnC = 1, rx = 1;
  wire tx;
  wire [15:0] led;
  always #10 clk = ~clk;
  fpgai_top #(.DIV(8)) top (.clk(clk), .btnC(btnC), .RsRx(rx),
    .RsTx(tx), .led(led));
  reg [7:0] want [0:16];
  integer i, b, got = 0, checks = 0;
  reg [7:0] c;
  task send(input [7:0] ch);
    begin
      rx = 0; repeat (8) @(posedge clk);
      for (b = 0; b < 8; b = b + 1) begin
        rx = ch[b]; repeat (8) @(posedge clk);
      end
      rx = 1; repeat (16) @(posedge clk);
    end
  endtask
  // The receiver: sample each bit mid-way, as the board's does.
  initial begin
    forever begin
      @(negedge tx);
      repeat (12) @(posedge clk);
      for (b = 0; b < 8; b = b + 1) begin
        c[b] = tx; repeat (8) @(posedge clk);
      end
      checks = checks + 1;
      if (got >= 17 || c !== want[got]) begin
        $display("TB_FAIL test=uart idx=%0d expected_chr=%0d got_chr=%0d", got, want[got], c);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      $write("%c", c);
      got = got + 1;
      if (got == 17) begin
        $display("TB_PASS checks=%0d", checks);
        $display("TB_RESULT: PASS");
        $finish;
      end
    end
  end
  initial begin
    want[0] = 8'd32;
    want[1] = 8'd119;
    want[2] = 8'd114;
    want[3] = 8'd105;
    want[4] = 8'd116;
    want[5] = 8'd101;
    want[6] = 8'd115;
    want[7] = 8'd32;
    want[8] = 8'd116;
    want[9] = 8'd104;
    want[10] = 8'd101;
    want[11] = 8'd32;
    want[12] = 8'd114;
    want[13] = 8'd116;
    want[14] = 8'd108;
    want[15] = 8'd32;
    want[16] = 8'd10;
    repeat (10) @(posedge clk); btnC = 0;
    repeat (10) @(posedge clk);
    $write("  the agent");
    send(8'd116);
    send(8'd104);
    send(8'd101);
    send(8'd32);
    send(8'd97);
    send(8'd103);
    send(8'd101);
    send(8'd110);
    send(8'd116);
    send(8'd13);
    #2000000000;
    $display("TB_FAIL test=uart idx=%0d expected_chr=more got_chr=none", got);
    $display("TB_RESULT: FAIL");
    $finish;
  end
endmodule
