"""A board package for a Zynq UltraScale+ board (the AUP-ZU3, XCZU3EG),
derived from a Zynq-7000 package of the same core.

The core, its register block and its masters are the same RTL; what
changes is the processing system around them. On the PS8 the registers
sit behind M_AXI_HPM0_FPD at 0xA0000000, the four weight masters on
S_AXI_HP0..3_FPD at 64 bits, and the constants/KV master on
S_AXI_HPC0_FPD: the UltraScale+ ACP takes only whole cache-line
bursts, and the KV master writes single beats with byte strobes. DDR
is at 0 as on the Zynq-7000, so the layout, the model files and
sw/main.c are unchanged; only the register base and the board name in
its header differ. The open flow has no UltraScale+ database, so the
bitstream is Vivado's.

  python3 board_zu.py                       board_zc706_qwen3 -> board_aupzu3_qwen3

then, on an x86 machine with Vivado and Vitis (see the package's README):

  vivado -mode batch -source build.tcl      bitstream, fpgai.xsa, psu_init.tcl
  xsct sw/build_app.tcl                     the ARM program (standalone A53, xilffs)
  xsct sw/run_jtag.tcl                      program the PL, psu_init, load, run
"""
import argparse
import os
import re
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))
REGS = 0xA0000000
MHZ = 50

BOARDS = {
    "aup_zu3": {
        "title": "AUP-ZU3",
        "chip": "xczu3eg",
        "board_glob": "*aup*zu3*",
        "board_files": "Real Digital's AUP-ZU3 board files (realdigital.org, the AUP-ZU3 "
                       "page), in <Vivado>/data/boards/board_files/",
    },
}

BUILD = """# GENERATED by board_zu.py. Build the {title} bitstream and platform:
#   vivado -mode batch -source build.tcl
# Needs an x86 Vivado (2022.1 or later) with
#   {board_files},
# for the PS8's DDR4 and MIO preset. The free edition covers the XCZU3EG.
# Writes fpgai.xsa (for sw/build_app.tcl), fpgai.bit and psu_init.tcl
# (for sw/run_jtag.tcl), timing.rpt and utilization.rpt.
set bp [lindex [lsort [get_board_parts -quiet {board_glob}]] end]
if {{$bp eq ""}} {{
  puts "ERROR: no {title} board in this Vivado: install {board_files},"
  puts "then restart Vivado. get_board_parts *zu3* lists what it has."
  exit 1
}}
set part [get_property PART_NAME [get_board_parts $bp]]
puts "board $bp, part $part"
create_project -force fpgai ./vivado -part $part
set_property board_part $bp [current_project]
add_files [glob ./rtl/*.v]
add_files ./rtl/gains.hex
set_property file_type {{Memory Initialization Files}} [get_files gains.hex]
update_compile_order -fileset sources_1

create_bd_design system
create_bd_cell -type ip -vlnv xilinx.com:ip:zynq_ultra_ps_e ps
apply_bd_automation -rule xilinx.com:bd_rule:zynq_ultra_ps_e \\
  -config {{apply_board_preset "1"}} [get_bd_cells ps]
# HPM0_FPD for the registers; HP0-3 (S_AXI_GP2-5) for the weights and
# HPC0 (S_AXI_GP0) for constants and KV, all 64 bits; pl_clk0 at {mhz} MHz.
set_property -dict [list \\
  CONFIG.PSU__USE__M_AXI_GP0 {{1}} CONFIG.PSU__MAXIGP0__DATA_WIDTH {{32}} \\
  CONFIG.PSU__USE__M_AXI_GP1 {{0}} CONFIG.PSU__USE__M_AXI_GP2 {{0}} \\
  CONFIG.PSU__USE__S_AXI_GP0 {{1}} CONFIG.PSU__SAXIGP0__DATA_WIDTH {{64}} \\
  CONFIG.PSU__USE__S_AXI_GP2 {{1}} CONFIG.PSU__SAXIGP2__DATA_WIDTH {{64}} \\
  CONFIG.PSU__USE__S_AXI_GP3 {{1}} CONFIG.PSU__SAXIGP3__DATA_WIDTH {{64}} \\
  CONFIG.PSU__USE__S_AXI_GP4 {{1}} CONFIG.PSU__SAXIGP4__DATA_WIDTH {{64}} \\
  CONFIG.PSU__USE__S_AXI_GP5 {{1}} CONFIG.PSU__SAXIGP5__DATA_WIDTH {{64}} \\
  CONFIG.PSU__FPGA_PL0_ENABLE {{1}} \\
  CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ {{{mhz}}}] [get_bd_cells ps]
create_bd_cell -type module -reference fpgai_zybo fpgai

apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config {{Clk_master {{/ps/pl_clk0}} \\
  Clk_slave {{/ps/pl_clk0}} Clk_xbar {{/ps/pl_clk0}} Master {{/ps/M_AXI_HPM0_FPD}} \\
  Slave {{/fpgai/s_axi}} ddr_seg {{Auto}} intc_ip {{New AXI SmartConnect}} master_apm {{0}}}} \\
  [get_bd_intf_pins fpgai/s_axi]
foreach {{m s}} {{m_axi_w0 S_AXI_HP0_FPD m_axi_w1 S_AXI_HP1_FPD m_axi_w2 S_AXI_HP2_FPD
                m_axi_w3 S_AXI_HP3_FPD m_axi_kv S_AXI_HPC0_FPD}} {{
  apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config [list Clk_master /ps/pl_clk0 \\
    Clk_slave /ps/pl_clk0 Clk_xbar /ps/pl_clk0 Master /fpgai/$m Slave /ps/$s \\
    ddr_seg Auto intc_ip {{New AXI SmartConnect}} master_apm 0] [get_bd_intf_pins ps/$s]
}}
assign_bd_address
set seg [get_bd_addr_segs -of_objects [get_bd_addr_spaces ps/Data] -filter {{NAME =~ "*fpgai*"}}]
set_property offset 0x{regs:08X} $seg
set_property range 64K $seg
validate_bd_design
save_bd_design

set w [make_wrapper -files [get_files system.bd] -top]
add_files -norecurse $w
set_property top system_wrapper [current_fileset]
generate_target all [get_files system.bd]
launch_runs synth_1 -jobs 4
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
open_run impl_1
report_timing_summary -file timing.rpt
report_utilization -file utilization.rpt
write_hw_platform -fixed -include_bit -force ./fpgai.xsa
file copy -force [glob ./vivado/fpgai.runs/impl_1/*.bit] ./fpgai.bit
set psu [glob -nocomplain ./vivado/*/sources_1/bd/system/ip/*/psu_init.tcl]
if {{[llength $psu]}} {{ file copy -force [lindex $psu 0] ./psu_init.tcl }}
puts "platform: ./fpgai.xsa, bitstream: ./fpgai.bit, PS init: ./psu_init.tcl"
"""

BUILD_APP = """# GENERATED by board_zu.py: the ARM program, sw/main.c unchanged, for the
# {title}'s Cortex-A53 #0, standalone, with the BSP's FatFs (xilffs), from
# the package's fpgai.xsa:
#   xsct sw/build_app.tcl
# Classic XSCT (Vitis up to 2023.2; later Vitis still ships xsct). Writes
# sw/vitis/ and sw/halo.elf. The same in the Vitis GUI: a platform from
# fpgai.xsa (psu_cortexa53_0, standalone, xilffs enabled), an empty C
# application with sw/main.c and sw/fpgai_layout.h.
set sw [file dirname [file normalize [info script]]]
set xsa [file join $sw .. fpgai.xsa]
if {{![file exists $xsa]}} {{ error "no $xsa: run vivado -mode batch -source build.tcl first" }}
set ws [file join $sw vitis]
file delete -force $ws
setws $ws
platform create -name halo_plat -hw $xsa -proc psu_cortexa53_0 -os standalone -out $ws
bsp setlib -name xilffs
bsp write
bsp reload
platform generate
app create -name halo -platform halo_plat -domain [domain active] -template {{Empty Application(C)}}
importsources -name halo -path [file join $sw main.c]
importsources -name halo -path [file join $sw fpgai_layout.h]
app build -name halo
file copy -force [file join $ws halo Debug halo.elf] [file join $sw halo.elf]
puts "program: [file join $sw halo.elf]"
"""

BUILD_APP_PY = """# GENERATED by board_zu.py: the ARM program, sw/main.c unchanged, for the
# {title}'s Cortex-A53 #0, standalone, with the BSP's FatFs (xilffs), from
# the package's fpgai.xsa, for Vitis 2024.1 and later (Python scripting;
# sw/build_app.tcl is the same for the classic XSCT of 2023.2 and before):
#   vitis -s sw/build_app.py
# Writes sw/vitis/ and sw/halo.elf.
import glob
import os
import shutil
import vitis

sw = os.path.dirname(os.path.abspath(__file__))
xsa = os.path.join(sw, "..", "fpgai.xsa")
if not os.path.exists(xsa):
    raise SystemExit("no %s: run vivado -mode batch -source build.tcl first" % xsa)
ws = os.path.join(sw, "vitis")
shutil.rmtree(ws, ignore_errors=True)
client = vitis.create_client()
client.set_workspace(path=ws)
kw = dict(name="halo_plat", os="standalone", cpu="psu_cortexa53_0",
          domain_name="standalone_a53")
try:                                    # the argument's name changed in 2024.1
    plat = client.create_platform_component(hw_design=xsa, **kw)
except TypeError:
    plat = client.create_platform_component(hw=xsa, **kw)
dom = plat.get_domain(name="standalone_a53")
dom.set_lib(lib_name="xilffs")
plat.build()
xpfm = client.find_platform_in_repos("halo_plat")
app = client.create_app_component(name="halo", platform=xpfm, domain="standalone_a53",
                                  template="empty_application")
app.import_files(from_loc=sw, files=["main.c", "fpgai_layout.h"], dest_dir_in_cmp="src")
app.build()
elf = (glob.glob(os.path.join(ws, "halo", "build", "*.elf"))
       + glob.glob(os.path.join(ws, "halo", "**", "halo.elf"), recursive=True))
shutil.copyfile(elf[0], os.path.join(sw, "halo.elf"))
print("program:", os.path.join(sw, "halo.elf"))
vitis.dispose()
"""

RUN_JTAG = """# GENERATED by board_zu.py: the {title} over JTAG, with no SD card:
#   xsct sw/run_jtag.tcl
# Boot mode switches to JTAG, the JTAG/UART USB connected, the UART open
# at 115200 8N1. It resets the board, programs the PL, runs psu_init
# (DDR4, clocks, MIO) and removes the PS-PL isolation, starts the
# program, which waits with no card, then writes the model files from
# ../sd into DDR (minutes for the weights), their sizes and the marker
# the program waits for, and lets it go on.
set sw [file dirname [file normalize [info script]]]
set pkg [file dirname $sw]
set sd [file join $pkg sd]
foreach f [list [file join $pkg fpgai.bit] [file join $pkg psu_init.tcl] [file join $sw halo.elf]] {{
    if {{![file exists $f]}} {{ error "no $f: build.tcl, then sw/build_app.tcl, first" }}
}}
foreach f {{weights8.bin cparams.bin vocab.bin prompt.bin}} {{
    if {{![file exists [file join $sd $f]]}} {{ error "no $sd/$f: make the model files first" }}
}}
connect
targets -set -nocase -filter {{name =~ "*PSU*"}}
rst -system
after 1000
puts "programming the PL"
fpga -file [file join $pkg fpgai.bit]
targets -set -nocase -filter {{name =~ "*APU*"}}
source [file join $pkg psu_init.tcl]
puts "psu_init: DDR4, clocks, MIO"
psu_init
after 1000
psu_ps_pl_isolation_removal
after 1000
psu_ps_pl_reset_config
catch {{psu_protection}}
targets -set -nocase -filter {{name =~ "*A53*#0"}}
rst -processor
dow [file join $sw halo.elf]
con
after 3000
stop
foreach {{name addr}} {{weights8.bin 0x{wb:08X} cparams.bin 0x{cb:08X} vocab.bin 0x{vb:08X} prompt.bin 0x{jp:08X}}} {{
    puts "  $name to $addr"
    dow -data [file join $sd $name] $addr
}}
mwr 0x{jm4:08X} [list [file size [file join $sd weights8.bin]] [file size [file join $sd cparams.bin]]]
mwr 0x{jm:08X} 0x{magic:08X}
con
puts "running: the output is on the UART"
"""

README = """# fpgai on the {title}

GENERATED by `board_zu.py` from `{src}/`: the same core (its RTL in
`rtl/` is `{src}`'s), the same ARM program and the same model files, on
a Zynq UltraScale+ XCZU3EG. The registers are at 0x{regs:08X} (the PS8's
HPM0_FPD), the weight masters on HP0-3, constants and KV on HPC0; DDR
is at 0, so the layout is unchanged.

The open flow has no UltraScale+ database: the bitstream comes from
Vivado, on an x86 machine (Linux or Windows) with Vivado and Vitis
2022.1 or later (2024.1 or 2023.2 suggested) and {board_files}.

1. The model files, in `sd/`: the same four as `{src}/sd/` (copy them,
   or make them with `HANDOFF.md` step 1 for `{src}`).
2. `vivado -mode batch -source build.tcl` in this folder: `fpgai.bit`,
   `fpgai.xsa`, `psu_init.tcl`, `timing.rpt` (WNS must be positive).
3. `vitis -s sw/build_app.py` (Vitis 2024.1 and later), or
   `xsct sw/build_app.tcl` (2023.2 and before): `sw/halo.elf`, `sw/main.c`
   on the A53's standalone BSP with xilffs.
4. Boot mode to JTAG, JTAG and UART USB connected, the UART at 115200
   8N1, then `xsct sw/run_jtag.tcl`. With no SD card the program waits;
   the script writes the model files into DDR over JTAG (minutes) and
   it goes on, printing the prompt and the generated tokens.

The prompt in `sd/prompt.bin` decides the text; for "The capital of
France is" the RTL prints "The capital of France is Paris. The capital
of the United States is Washington, D.C. The capital".
"""


def package(src, board="aup_zu3", out=None):
    pk = BOARDS[board]
    src = os.path.abspath(src)
    out = os.path.abspath(out or os.path.join(ROOT, "board_aupzu3_" + os.path.basename(src)
                                              .replace("board_zc706_", "").replace("board_", "")))
    os.makedirs(os.path.join(out, "sw"), exist_ok=True)
    shutil.rmtree(os.path.join(out, "rtl"), ignore_errors=True)
    shutil.copytree(os.path.join(src, "rtl"), os.path.join(out, "rtl"))
    shutil.copyfile(os.path.join(src, "sw", "main.c"), os.path.join(out, "sw", "main.c"))
    h = open(os.path.join(src, "sw", "fpgai_layout.h")).read()
    h = re.sub(r"#define FPGAI_REGS\s+0x[0-9A-Fa-f]+U", "#define FPGAI_REGS      0x%08XU" % REGS, h)
    h = re.sub(r'#define FPGAI_BOARD\s+"[^"]*"', '#define FPGAI_BOARD     "%s"' % pk["title"], h)
    with open(os.path.join(out, "sw", "fpgai_layout.h"), "w") as f:
        f.write(h)
    get = lambda n: int(re.search(r"#define %s\s+0x([0-9A-Fa-f]+)U" % n, h).group(1), 16)
    with open(os.path.join(out, "build.tcl"), "w") as f:
        f.write(BUILD.format(regs=REGS, mhz=MHZ, **pk))
    with open(os.path.join(out, "sw", "build_app.tcl"), "w") as f:
        f.write(BUILD_APP.format(**pk))
    with open(os.path.join(out, "sw", "build_app.py"), "w") as f:
        f.write(BUILD_APP_PY.format(**pk))
    with open(os.path.join(out, "sw", "run_jtag.tcl"), "w") as f:
        f.write(RUN_JTAG.format(wb=get("WBASE"), cb=get("CBASE"), vb=get("VOCAB_BASE"),
                                jp=get("JTAG_PROMPT"), jm=get("JTAG_MARK"),
                                jm4=get("JTAG_MARK") + 4, magic=get("JTAG_MAGIC"), **pk))
    with open(os.path.join(out, "README.md"), "w") as f:
        f.write(README.format(src=os.path.basename(src), regs=REGS, **pk))
    # The model files are the source package's: linked where it has them.
    sd_src, sd = os.path.join(src, "sd"), os.path.join(out, "sd")
    if os.path.isdir(sd_src):
        os.makedirs(sd, exist_ok=True)
        for name in ("weights8.bin", "cparams.bin", "vocab.bin", "prompt.bin"):
            s, d = os.path.join(sd_src, name), os.path.join(sd, name)
            if os.path.exists(s) and not os.path.exists(d):
                try:
                    os.link(s, d)
                except OSError:
                    shutil.copyfile(s, d)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--src", default=os.path.join(ROOT, "board_zc706_qwen3"),
                    help="the Zynq-7000 package whose core to use")
    ap.add_argument("--board", default="aup_zu3", choices=sorted(BOARDS))
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    print("package in", package(a.src, a.board, a.out))


if __name__ == "__main__":
    main()
