"""Put the Qwen-shaped decoder on the team's Basys 3.

Everything here is generated and checked on this machine except the last
step, which needs Vivado on an x86 host: the decoder RTL and its blocks,
a top level that talks over the board's USB-UART, the weights as a block
RAM image, the Basys 3 pin constraints, and a Vivado script that builds
the bitstream. The top level is simulated end to end in iverilog, UART
frames in and out, against the integer reference.

On the board: open a serial terminal at 115200 8N1, type a prompt and
press enter. The board encodes the characters it knows, runs one decode
step per position, and sends back each character it generates until the
24-position context is full, then a newline. LED 0 is lit while it
decodes; LED 15 is the heartbeat.

Run: python3 board.py [--out board_basys3]
"""
import argparse
import os
import shutil
import subprocess

import qwen_decoder as qd

ROOT = os.path.dirname(os.path.abspath(__file__))
CORE_MHZ = 50          # the MMCM's output; the decoder closes at 110 in
                       # the generic library, and a real Artix-7 place and
                       # route is slower, so the board runs it at half


def _clog2(n):
    return max(1, (n - 1).bit_length())


UART = """// GENERATED by board.py: do not edit by hand.
// 8N1 UART, one start bit, eight data bits LSB first, one stop bit.
module uart_rx #(parameter DIV = 434) (
  input            clk,
  input            rst_n,
  input            rx,
  output reg [7:0] data,
  output reg       valid
);
  reg [1:0] sync;
  reg [15:0] cnt;
  reg [3:0] bitn;
  reg [7:0] sh;
  reg busy;
  always @(posedge clk) begin
    if (!rst_n) begin
      sync <= 2'b11; cnt <= 0; bitn <= 0; sh <= 0; busy <= 1'b0;
      data <= 0; valid <= 1'b0;
    end else begin
      sync <= {sync[0], rx};
      valid <= 1'b0;
      if (!busy) begin
        if (!sync[1]) begin
          // Start bit: sample the middle of each bit from here.
          busy <= 1'b1; cnt <= DIV / 2; bitn <= 0;
        end
      end else if (cnt != 0) begin
        cnt <= cnt - 1;
      end else begin
        cnt <= DIV - 1;
        if (bitn == 0) begin
          if (sync[1]) busy <= 1'b0;       // a glitch, not a start bit
          bitn <= 1;
        end else if (bitn <= 8) begin
          sh <= {sync[1], sh[7:1]};
          bitn <= bitn + 1;
        end else begin
          busy <= 1'b0;
          if (sync[1]) begin data <= sh; valid <= 1'b1; end
        end
      end
    end
  end
endmodule

module uart_tx #(parameter DIV = 434) (
  input        clk,
  input        rst_n,
  input  [7:0] data,
  input        send,
  output reg   tx,
  output       ready
);
  reg [15:0] cnt;
  reg [3:0] bitn;
  reg [9:0] sh;
  reg busy;
  assign ready = !busy && !send;
  always @(posedge clk) begin
    if (!rst_n) begin
      tx <= 1'b1; cnt <= 0; bitn <= 0; sh <= 10'h3ff; busy <= 1'b0;
    end else if (!busy) begin
      if (send) begin
        sh <= {1'b1, data, 1'b0}; busy <= 1'b1; cnt <= DIV - 1;
        bitn <= 0; tx <= 1'b0;
      end
    end else if (cnt != 0) begin
      cnt <= cnt - 1;
    end else begin
      cnt <= DIV - 1;
      if (bitn == 9) begin
        busy <= 1'b0; tx <= 1'b1;
      end else begin
        bitn <= bitn + 1;
        tx <= sh[bitn + 1];
      end
    end
  end
endmodule
"""


def render_top(dec, spec):
    """The board's top level: UART in, decode, UART out."""
    p = spec["parameters"]
    V, L = p["vocab"], p["context"]
    chars = dec.ck["chars"]
    tw, pw = _clog2(V), _clog2(L)
    paw = _clog2(p["param_words"])
    div = int(round(CORE_MHZ * 1e6 / 115200))
    A = []
    a = A.append
    a("// GENERATED by board.py: do not edit by hand.")
    a("// Basys 3 top level: prompt in over the USB-UART, generated text out.")
    a("module fpgai_top #(parameter DIV = %d) (" % div)
    a("  input         clk,        // 100 MHz board oscillator")
    a("  input         btnC,       // reset")
    a("  input         RsRx,")
    a("  output        RsTx,")
    a("  output [15:0] led")
    a(");")
    a("`ifdef SIM")
    a("  wire cclk = clk;")
    a("`else")
    a("  // 100 MHz in, %d MHz out: the decoder's clock." % CORE_MHZ)
    a("  wire fb, c0;")
    a("  MMCME2_BASE #(.CLKIN1_PERIOD(10.0), .CLKFBOUT_MULT_F(10.0),")
    a("                .CLKOUT0_DIVIDE_F(%0.1f)) mmcm (" % (1000.0 / CORE_MHZ))
    a("    .CLKIN1(clk), .CLKFBIN(fb), .CLKFBOUT(fb), .CLKOUT0(c0),")
    a("    .PWRDWN(1'b0), .RST(1'b0), .LOCKED());")
    a("  wire cclk;")
    a("  BUFG bg (.I(c0), .O(cclk));")
    a("`endif")
    a("  reg [2:0] rs = 3'b000;")
    a("  always @(posedge cclk) rs <= {rs[1:0], ~btnC};")
    a("  wire rst_n = rs[2];")
    a("")
    a("  // Weights, embeddings and gains: a ROM the decoder reads through")
    a("  // its parameter port, one cycle after the address.")
    a("  reg signed [7:0] prom [0:%d];" % (p["param_words"] - 1))
    a('  initial $readmemh("qwen_params.hex", prom);')
    a("  wire [%d:0] p_addr;" % (paw - 1))
    a("  reg signed [7:0] p_data;")
    a("  always @(posedge cclk) p_data <= prom[p_addr];")
    a("")
    a("  wire [7:0] rx_data;")
    a("  wire rx_valid;")
    a("  uart_rx #(.DIV(DIV)) urx (.clk(cclk), .rst_n(rst_n), .rx(RsRx),")
    a("    .data(rx_data), .valid(rx_valid));")
    a("  reg [7:0] tx_data;")
    a("  reg tx_send;")
    a("  wire tx_ready;")
    a("  uart_tx #(.DIV(DIV)) utx (.clk(cclk), .rst_n(rst_n), .data(tx_data),")
    a("    .send(tx_send), .tx(RsTx), .ready(tx_ready));")
    a("")
    a("  reg start;")
    a("  reg [%d:0] tok;" % (tw - 1))
    a("  reg [%d:0] pos;" % (pw - 1))
    a("  wire lg_valid, done, busy;")
    a("  wire [%d:0] lg_index, next_tok;" % (tw - 1))
    a("  wire signed [7:0] lg_data;")
    a("  qwen_decoder dec (.clk(cclk), .rst_n(rst_n), .start(start),")
    a("    .tok(tok), .pos(pos), .p_addr(p_addr), .p_data(p_data),")
    a("    .lg_valid(lg_valid), .lg_index(lg_index), .lg_data(lg_data),")
    a("    .next_tok(next_tok), .done(done), .busy(busy));")
    a("")
    a("  // Character to token and back: the checkpoint's own vocabulary.")
    a("  function [%d:0] to_tok(input [7:0] c);" % tw)
    a("    begin")
    a("      case (c)")
    for i, c in enumerate(chars):
        a("        8'd%d: to_tok = {1'b1, %d'd%d};" % (ord(c), tw, i))
    a("        default: to_tok = 0;")
    a("      endcase")
    a("    end")
    a("  endfunction")
    a("  function [7:0] to_chr(input [%d:0] t);" % (tw - 1))
    a("    begin")
    a("      case (t)")
    for i, c in enumerate(chars):
        a("        %d'd%d: to_chr = 8'd%d;" % (tw, i, ord(c)))
    a("        default: to_chr = 8'd63;")
    a("      endcase")
    a("    end")
    a("  endfunction")
    a("")
    a("  reg [%d:0] prompt [0:%d];" % (tw - 1, L - 1))
    a("  reg [%d:0] plen;" % pw)
    a("  reg [2:0] st;")
    a("  localparam T_IN = 3'd0, T_STEP = 3'd1, T_WAIT = 3'd2, T_SEND = 3'd3,")
    a("             T_NL = 3'd4;")
    a("  wire [%d:0] rt = to_tok(rx_data);" % tw)
    a("  always @(posedge cclk) begin")
    a("    if (!rst_n) begin")
    a("      st <= T_IN; plen <= 0; start <= 1'b0; tok <= 0; pos <= 0;")
    a("      tx_send <= 1'b0; tx_data <= 0;")
    a("    end else begin")
    a("      start <= 1'b0; tx_send <= 1'b0;")
    a("      case (st)")
    a("        // Collect the prompt; enter starts the decode.")
    a("        T_IN: if (rx_valid) begin")
    a("          if ((rx_data == 8'd13 || rx_data == 8'd10) && plen != 0) begin")
    a("            pos <= 0; tok <= prompt[0]; st <= T_STEP;")
    a("          end else if (rt[%d] && plen < %d) begin" % (tw, L))
    a("            prompt[plen] <= rt[%d:0]; plen <= plen + 1;" % (tw - 1))
    a("          end")
    a("        end")
    a("        T_STEP: begin start <= 1'b1; st <= T_WAIT; end")
    a("        T_WAIT: if (done) begin")
    a("          if (pos + 1 < plen) begin")
    a("            // Still in the prompt: feed the next character.")
    a("            pos <= pos + 1; tok <= prompt[pos + 1]; st <= T_STEP;")
    a("          end else begin")
    a("            tx_data <= to_chr(next_tok); st <= T_SEND;")
    a("          end")
    a("        end")
    a("        T_SEND: if (tx_ready) begin")
    a("          tx_send <= 1'b1;")
    a("          if (pos + 1 < %d) begin" % L)
    a("            pos <= pos + 1; tok <= next_tok; st <= T_STEP;")
    a("          end else begin")
    a("            st <= T_NL;")
    a("          end")
    a("        end")
    a("        // The newline goes once the last character has left: data")
    a("        // and send change together, or the UART sends the wrong one.")
    a("        T_NL: if (tx_ready && !tx_send) begin")
    a("          tx_data <= 8'd10; tx_send <= 1'b1; plen <= 0; st <= T_IN;")
    a("        end")
    a("        default: st <= T_IN;")
    a("      endcase")
    a("    end")
    a("  end")
    a("")
    a("  reg [25:0] beat;")
    a("  always @(posedge cclk) beat <= beat + 1;")
    a("  assign led = {beat[25], 14'd0, st != T_IN};")
    a("endmodule")
    return "\n".join(A) + "\n"


XDC = """## GENERATED by board.py. Basys 3 (XC7A35T-1CPG236C) pins.
set_property -dict { PACKAGE_PIN W5 IOSTANDARD LVCMOS33 } [get_ports clk]
create_clock -add -name sys_clk -period 10.00 -waveform {0 5} [get_ports clk]
set_property -dict { PACKAGE_PIN U18 IOSTANDARD LVCMOS33 } [get_ports btnC]
set_property -dict { PACKAGE_PIN B18 IOSTANDARD LVCMOS33 } [get_ports RsRx]
set_property -dict { PACKAGE_PIN A18 IOSTANDARD LVCMOS33 } [get_ports RsTx]
%s
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
""" % "\n".join(
    "set_property -dict { PACKAGE_PIN %s IOSTANDARD LVCMOS33 } "
    "[get_ports {led[%d]}]" % (pin, i) for i, pin in enumerate(
        ["U16", "E19", "U19", "V19", "W18", "U15", "U14", "V14", "V13",
         "V3", "W3", "U3", "P3", "N3", "P1", "L1"]))


TCL = """# GENERATED by board.py. Build the Basys 3 bitstream:
#   vivado -mode batch -source build.tcl
# Vivado needs an x86 host; everything this reads is in this directory.
create_project -force fpgai ./vivado -part xc7a35tcpg236-1
add_files [glob ./rtl/*.v]
add_files -fileset constrs_1 ./basys3.xdc
add_files ./qwen_params.hex
set_property file_type {Memory Initialization Files} [get_files qwen_params.hex]
set_property top fpgai_top [current_fileset]
launch_runs synth_1 -jobs 4
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
open_run impl_1
report_timing_summary -file timing.rpt
report_utilization -file utilization.rpt
puts "bitstream: [glob ./vivado/fpgai.runs/impl_1/*.bit]"
"""


def render_tb(dec, spec, prompt, div):
    """Types the prompt into the UART and checks every character sent
    back against the integer reference."""
    L = spec["parameters"]["context"]
    stoi = {c: i for i, c in enumerate(dec.ck["chars"])}
    ids = [stoi[c] for c in prompt if c in stoi]
    dec.reset()
    out = []
    feed = list(ids)
    for i in range(L):
        nxt, _, _ = dec.step(feed[i], i)
        if i + 1 >= len(ids):
            out.append(nxt)
        if i + 1 >= len(feed):
            feed.append(nxt)
    want = "".join(dec.ck["chars"][t] for t in out) + "\n"
    A = []
    a = A.append
    a("`timescale 1ns/1ps")
    a("// GENERATED by board.py: the whole top level over its UART.")
    a("module tb_fpgai_top;")
    a("  reg clk = 0, btnC = 1, rx = 1;")
    a("  wire tx;")
    a("  wire [15:0] led;")
    a("  always #10 clk = ~clk;")
    a("  fpgai_top #(.DIV(%d)) top (.clk(clk), .btnC(btnC), .RsRx(rx)," % div)
    a("    .RsTx(tx), .led(led));")
    a("  reg [7:0] want [0:%d];" % (len(want) - 1))
    a("  integer i, b, got = 0, checks = 0;")
    a("  reg [7:0] c;")
    a("  task send(input [7:0] ch);")
    a("    begin")
    a("      rx = 0; repeat (%d) @(posedge clk);" % div)
    a("      for (b = 0; b < 8; b = b + 1) begin")
    a("        rx = ch[b]; repeat (%d) @(posedge clk);" % div)
    a("      end")
    a("      rx = 1; repeat (%d) @(posedge clk);" % (2 * div))
    a("    end")
    a("  endtask")
    a("  // The receiver: sample each bit mid-way, as the board's does.")
    a("  initial begin")
    a("    forever begin")
    a("      @(negedge tx);")
    a("      repeat (%d) @(posedge clk);" % (div + div // 2))
    a("      for (b = 0; b < 8; b = b + 1) begin")
    a("        c[b] = tx; repeat (%d) @(posedge clk);" % div)
    a("      end")
    a("      checks = checks + 1;")
    a("      if (got >= %d || c !== want[got]) begin" % len(want))
    a('        $display("TB_FAIL test=uart idx=%0d expected_chr=%0d got_chr=%0d", got, want[got], c);')
    a('        $display("TB_RESULT: FAIL");')
    a("        $finish;")
    a("      end")
    a('      $write("%c", c);')
    a("      got = got + 1;")
    a("      if (got == %d) begin" % len(want))
    a('        $display("TB_PASS checks=%0d", checks);')
    a('        $display("TB_RESULT: PASS");')
    a("        $finish;")
    a("      end")
    a("    end")
    a("  end")
    a("  initial begin")
    for i, ch in enumerate(want):
        a("    want[%d] = 8'd%d;" % (i, ord(ch)))
    a("    repeat (10) @(posedge clk); btnC = 0;")
    a("    repeat (10) @(posedge clk);")
    a('    $write("  %s");' % prompt)
    for ch in prompt:
        a("    send(8'd%d);" % ord(ch))
    a("    send(8'd13);")
    a("    #%d;" % (2000 * 1000 * 1000))
    a('    $display("TB_FAIL test=uart idx=%0d expected_chr=more got_chr=none", got);')
    a('    $display("TB_RESULT: FAIL");')
    a("    $finish;")
    a("  end")
    a("endmodule")
    return "\n".join(A) + "\n", want


def build(out, sim=True, prompt="the agent"):
    """Write the board directory, and simulate the top level."""
    dec = qd.load()
    spec = qd.derive_spec(dec)
    rtl = os.path.join(out, "rtl")
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(rtl)
    deps = qd.write_deps(dec, rtl)
    with open(os.path.join(rtl, "qwen_decoder.v"), "w") as f:
        f.write(qd.render_qwen_decoder(spec))
    with open(os.path.join(rtl, "uart.v"), "w") as f:
        f.write(UART)
    with open(os.path.join(rtl, "fpgai_top.v"), "w") as f:
        f.write(render_top(dec, spec))
    img = qd.param_image(dec)
    with open(os.path.join(out, "qwen_params.hex"), "w") as f:
        f.write("\n".join("%02x" % (v & 0xff) for v in img) + "\n")
    with open(os.path.join(out, "basys3.xdc"), "w") as f:
        f.write(XDC)
    with open(os.path.join(out, "build.tcl"), "w") as f:
        f.write(TCL)
    if not sim:
        return None
    div = 8                      # a fast UART in simulation, same logic
    tb, want = render_tb(dec, spec, prompt, div)
    with open(os.path.join(out, "tb_fpgai_top.v"), "w") as f:
        f.write(tb)
    srcs = [os.path.join("rtl", s) for s in
            ["fpgai_top.v", "uart.v", "qwen_decoder.v"] + deps]
    r = subprocess.run(["iverilog", "-g2005", "-DSIM", "-o", "top.out",
                        "tb_fpgai_top.v"] + srcs, cwd=out,
                       capture_output=True, text=True)
    if r.returncode:
        return r.stdout + r.stderr
    r = subprocess.run(["vvp", "top.out"], cwd=out, capture_output=True,
                       text=True, timeout=1800)
    return r.stdout + r.stderr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "board_basys3"))
    ap.add_argument("--no-sim", action="store_true")
    a = ap.parse_args()
    out = build(a.out, sim=not a.no_sim)
    if out:
        print(out[-2000:])
    print("wrote", a.out)


if __name__ == "__main__":
    main()
