"""Formal proof that the derived MAC accumulator cannot overflow.

The accumulator width comes from a closed-form rule,

    acc_width = weight_bits + activation_bits + ceil(log2(depth)),

and every testbench in the repo checks it only on the vectors it happens
to drive. This proves it for every input sequence instead. A wrapper
around the design keeps the exact running sum of the products it has
been given, in a register wider than the accumulator, and counts the
accumulations since the last clear. It assumes at most depth of them
per clear, which is what the reduction depth means, and asserts two
things at every cycle:

  * the exact sum fits in acc_width signed bits, so the rule leaves no
    room for an overflow, and
  * the design's acc equals that exact sum, delayed by its pipeline,
    so the design really does carry every bit of it.

Both are proved by k-induction with yosys-smtbmc and z3, which covers
all reachable states and not just the first few cycles. Everything is
stated on the ports the spec defines, so the same proof applies to a
design an LLM wrote as to the reference one.

The one usage constraint is the one the matmul sequencer already obeys:
clear is not asserted while a product is still in the pipeline, so what
a clear discards is never ambiguous.
"""
import os
import re
import shutil
import subprocess

HARNESS = """// GENERATED by formal.py: proof that the accumulator cannot overflow.
module formal_mac (input clk, input rst_n, input clear,
                   input signed [{dwm}:0] a, input signed [{dwm}:0] b,
                   input valid_in);
  wire signed [{awm}:0] acc;
  wire valid_out;
  mac dut (.clk(clk), .rst_n(rst_n), .clear(clear), .a(a), .b(b),
           .valid_in(valid_in), .acc(acc), .valid_out(valid_out));

  // Exact sum of accepted products, two bits wider than the accumulator
  // so that an overflow of acc_width is visible rather than wrapped.
  reg signed [{swm}:0] sum = 0;
  reg [{cwm}:0] count = 0;
  // The same sum, delayed to line up with the accumulator.
  reg signed [{swm}:0] lag [0:{lagm}];
  // Recent valid_in, so clear can be kept clear of in-flight products.
  reg [{lagm}:0] recent = 0;
  reg init = 1;
  integer i;
  // The product at exactly its own width, the term the design computes.
  // Multiplying inside the wide sum instead gave the solver two
  // different multipliers to prove equal, and at 16-bit operands that
  // alone ran past four minutes.
  wire signed [{pwm}:0] prod = a * b;

  initial for (i = 0; i <= {lagm}; i = i + 1) lag[i] = 0;

  always @(posedge clk) begin
    init <= 0;
    recent <= {{recent[{lagm_1}:0], valid_in}};
    if (!rst_n || clear) begin
      sum <= 0; count <= 0;
      for (i = 0; i <= {lagm}; i = i + 1) lag[i] <= 0;
    end else begin
      if (valid_in) begin
        sum <= sum + prod;
        count <= count + 1;
      end
      // sum updates on the edge that accepts a product, the same edge the
      // design registers it on, and acc catches up pipeline_stages - 1
      // edges later. So the chain starts from the old sum.
      lag[0] <= sum;
      for (i = 1; i <= {lagm}; i = i + 1) lag[i] <= lag[i - 1];
    end
  end

  always @* begin
    // Reset in the first cycle, never again.
    assume(init ? !rst_n : rst_n);
    // Operands carry the quantized values the width rule assumes. The
    // ports are data_width wide, but with int4 weights the rule sizes the
    // accumulator for 4-bit weights, and the proof found that a full
    // 8-bit value on b overflows it. So the range is stated, not implied.
    assume(a >= -{amag} && a <= {amag} - 1);
    assume(b >= -{bmag} && b <= {bmag} - 1);
    // At most depth accumulations between clears: the reduction depth.
    assume(count < {depth} || !valid_in);
    // No clear while a product is in flight, and no new product on it.
    assume(!clear || (recent == 0 && !valid_in));
    if (!init) begin
      // The invariant that makes the step inductive: each product is
      // bounded, so the sum is bounded by how many there have been.
      assert(sum <= $signed({{1'b0, count}}) * {pmax}
             && sum >= -$signed({{1'b0, count}}) * {pmax});
      assert(count <= {depth});
      // The claim: the exact sum always fits the accumulator...
      assert(sum <= {amax} && sum >= -{amin});
      // ...and the design holds exactly that sum.
      if (lag_ok) assert(acc == lag[{lagm}][{awm}:0]);
    end
  end

  // The comparison starts once the pipeline has been through a reset.
  reg [{lagw}:0] settle = 0;
  wire lag_ok = settle > {lagm};
  always @(posedge clk)
    if (!rst_n) settle <= 0;
    else if (!lag_ok) settle <= settle + 1;
endmodule
"""


def harness(spec):
    p = spec["parameters"]
    dw, aw = p["data_width"], p["acc_width"]
    d = spec["derivation"]
    depth = d["reduction_depth"]
    ab, wb = d["activation_bits"], d["weight_bits"]
    lag = p["pipeline_stages"] - 1          # sum register is already one
    cw = max(1, depth.bit_length())
    return HARNESS.format(
        dwm=dw - 1, awm=aw - 1, swm=aw + 1, cwm=cw - 1, pwm=2 * dw - 1,
        lagm=lag - 1, lagm_1=max(0, lag - 2), lagw=max(1, lag.bit_length()),
        depth=depth, pmax=1 << (ab + wb - 2),
        amag=1 << (ab - 1), bmag=1 << (wb - 1),
        amax=(1 << (aw - 1)) - 1, amin=1 << (aw - 1))


def _run(cmd, cwd, timeout):
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True,
                           timeout=timeout)
        return r.returncode, r.stdout + r.stderr
    except subprocess.TimeoutExpired:
        return 124, "timeout"


def available():
    return all(shutil.which(t) for t in ("yosys", "yosys-smtbmc", "z3"))


def prove_mac(spec, rtl_path, work, depth=12, timeout=600):
    """Prove the accumulator claim for one MAC design.

    Returns {"status": "proved" | "failed" | "timeout" | "error", ...}. A failure
    carries the solver's counterexample trace summary.
    """
    os.makedirs(work, exist_ok=True)
    wrap = os.path.join(work, "formal_mac.v")
    with open(wrap, "w") as f:
        f.write(harness(spec))
    # Bare names inside the work directory: yosys scripts split on
    # spaces, and this repo lives under a path that has one.
    shutil.copyfile(rtl_path, os.path.join(work, "dut_mac.v"))
    smt = "formal_mac.smt2"
    rc, out = _run(["yosys", "-q", "-p",
                    "read_verilog -sv -formal formal_mac.v; "
                    "read_verilog dut_mac.v; "
                    "prep -top formal_mac; async2sync; dffunmap; "
                    "write_smt2 -wires %s" % smt],
                   work, timeout)
    if rc != 0:
        return {"status": "error", "phase": "elaborate",
                "detail": out.strip().splitlines()[-5:]}
    res = {}
    for mode, args in (("bmc", []), ("induction", ["-i"])):
        rc, out = _run(["yosys-smtbmc", "-s", "z3", "--presat"] + args +
                       ["-t", str(depth), smt], work, timeout)
        if rc == 124:
            # Out of time is not a counterexample. Reporting it as a
            # failure would claim a bug the solver never found.
            return {"status": "timeout", "phase": mode, "depth": depth}
        ok = rc == 0 and ("PASSED" in out or "Status: passed" in out)
        res[mode] = ok
        if not ok:
            fail = [l.strip() for l in out.splitlines()
                    if re.search(r"failed|Assert|FAILED", l)][:6]
            return {"status": "failed", "phase": mode, "detail": fail,
                    "depth": depth}
    return {"status": "proved", "depth": depth, **res}


def main():
    """Prove the accumulator claim for every model variant the sweep
    covers, against the reference MAC."""
    import sys
    import specgen
    import agent
    import sweep
    if not available():
        print("needs yosys, yosys-smtbmc and z3")
        return 2
    fixes = {getattr(agent, n) for n in dir(agent) if n.startswith("FIX_")}
    ref = agent.RuleBasedAgent()
    root = os.path.dirname(os.path.abspath(__file__))
    work = os.path.join(root, "build_formal")
    bad = 0
    for ms in sweep._models(specgen.load_model_spec()):
        spec = specgen.derive_chiplet_spec(ms)
        rtl = os.path.join(work, "mac_%s.v" % ms["name"])
        os.makedirs(work, exist_ok=True)
        with open(rtl, "w") as f:
            f.write(ref.render_mac(spec, fixes))
        p = spec["parameters"]
        wide = p["data_width"] > 8
        r = prove_mac(spec, rtl, work, timeout=60 if wide else 600)
        note = ""
        if r["status"] == "timeout":
            note = "  (not proved: split multiplier vs a*b is past z3's budget)"
        print("%-14s depth %5d  acc %2d bits  %s%s"
              % (ms["name"], spec["derivation"]["reduction_depth"],
                 p["acc_width"], r["status"], note))
        bad += r["status"] not in ("proved", "timeout") or \
            (r["status"] == "timeout" and not wide)
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
