"""Boards on their own clocks, splitting the model's layers: GALS.

Globally asynchronous, locally synchronous. Each board runs its stage,
a contiguous range of layers, on whatever clock it closes, and boards
share nothing but messages: the hidden state from one stage to the next,
and the chosen token back. No board waits on another's clock edge, so
any mix of boards works.

This is the link for boards without an ARM, the portable default: a
UART in the fabric on two pins, which any FPGA can build. (Zynq boards
carry the same messages over their ARM's Ethernet, see board_zybo.py.)
stage_ctrl sits beside each stage's sequencer. It receives a message,
checks its CRC32, loads a hidden state straight into the core, starts
it, and when the core is done sends the core's hidden state on, or, on
the last stage, the chosen token and its logit.

A message: A5 5A, type (1 token, 2 hidden state), position (2 bytes),
token (3 bytes), flags (bit 0: run the head), the payload (a token
message carries the logit, 2 bytes; a hidden-state message the vector,
2 bytes an element, low byte first), and the CRC32 of everything from
type on, as zlib computes it, low byte first.

The test runs the sequencer as two stages on unrelated clocks, 10 ns and
7.9 ns, whose UART dividers leave their bit times 1.25% apart, with a
host model at its own rate feeding the prompt and every generated token
back: the tokens and logits have to be one board's.

Run: python3 gals.py [--style qwen3]
"""
import argparse
import os
import shutil
import subprocess
import sys
import time
import zlib

import board
import qwen_full
import qwen_real as qr

ROOT = os.path.dirname(os.path.abspath(__file__))
HDR = 9                     # sync, sync, type, pos 2, token 3, flags


def _clog2(n):
    return max(1, (n - 1).bit_length())


def render_ctrl(D, tw, pw):
    aw = _clog2(D)
    return """// GENERATED by gals.py: do not edit by hand.
// One pipeline stage's link: UART messages in, the core run, the result
// out. HAS_EMB: this stage can take a token and look up its embedding;
// HAS_HEAD: it is the last stage and answers with the token it chose.
module stage_ctrl #(parameter DIV = 16, parameter HAS_EMB = 1, parameter HAS_HEAD = 0) (
  input clk, input rst_n, input rx, output tx,
  output reg start, output reg head_en, output reg emb_en,
  output reg [{twm}:0] tok, output reg [{pwm}:0] pos,
  output reg x_we, output reg [{awm}:0] x_addr, output reg signed [15:0] x_wdata,
  input signed [15:0] x_rdata,
  input [{twm}:0] next_tok, input signed [15:0] best, input done, input busy,
  output reg [15:0] crc_errors, output reg [15:0] messages
);
  localparam D = {D}, PAYH = 2 * D;
  function [31:0] crc8(input [31:0] c, input [7:0] d);
    integer i; reg [31:0] x;
    begin
      x = c ^ {{24'd0, d}};
      for (i = 0; i < 8; i = i + 1) x = x[0] ? (x >> 1) ^ 32'hEDB88320 : (x >> 1);
      crc8 = x;
    end
  endfunction

  wire [7:0] rb; wire rv, tr;
  reg [7:0] tb; reg ts;
  uart_rx #(.DIV(DIV)) urx (.clk(clk), .rst_n(rst_n), .rx(rx), .data(rb), .valid(rv));
  uart_tx #(.DIV(DIV)) utx (.clk(clk), .rst_n(rst_n), .data(tb), .send(ts), .tx(tx), .ready(tr));

  // ---- receive
  localparam R_S0 = 3'd0, R_S1 = 3'd1, R_HDR = 3'd2, R_PAY = 3'd3, R_CRC = 3'd4, R_GO = 3'd5;
  reg [2:0] rs;
  reg [15:0] rn, rlen;
  reg [7:0] rtype, rflags, rlo;
  reg [15:0] rpos;
  reg [23:0] rtok;
  reg [31:0] rcrc, rgot;

  // ---- send
  reg tx_on, tx_hid;
  reg [15:0] ti, tlen;
  reg [31:0] tcrc;
  reg [15:0] tpos;
  reg [23:0] ttok;
  reg [7:0] tflags;
  reg signed [15:0] tbest;
  reg [7:0] tbyte;
  // The byte at index ti of the message being sent.
  always @(*) begin
    case (ti)
      0: tbyte = 8'hA5;
      1: tbyte = 8'h5A;
      2: tbyte = tx_hid ? 8'd2 : 8'd1;
      3: tbyte = tpos[7:0];
      4: tbyte = tpos[15:8];
      5: tbyte = ttok[7:0];
      6: tbyte = ttok[15:8];
      7: tbyte = ttok[23:16];
      8: tbyte = tflags;
      default:
        if (ti < tlen - 4)
          tbyte = tx_hid ? (ti[0] ? x_rdata[7:0] : x_rdata[15:8])
                         : (ti[0] ? tbest[7:0] : tbest[15:8]);
        else tbyte = ~tcrc[(ti - (tlen - 4)) * 8 +: 8];
    endcase
  end
  wire [15:0] tword = (ti - {hdr}) >> 1;

  always @(posedge clk) begin
    if (!rst_n) begin
      rs <= R_S0; start <= 1'b0; head_en <= 1'b0; emb_en <= 1'b0; tok <= 0; pos <= 0;
      x_we <= 1'b0; x_addr <= 0; x_wdata <= 0; crc_errors <= 0; messages <= 0;
      tx_on <= 1'b0; ts <= 1'b0; ti <= 0; tlen <= 0; tcrc <= 32'hFFFFFFFF;
      rn <= 0; rlen <= 0; rcrc <= 32'hFFFFFFFF;
    end else begin
      x_we <= 1'b0; ts <= 1'b0;
      if (start && busy) start <= 1'b0;
      // ---- receive a message, writing a hidden state into the core
      if (rv) case (rs)
        // A message is taken only while the stage is idle: a resent one
        // that arrives while the stage still computes or sends is dropped,
        // so it can never write into state in use.
        R_S0: if (rb == 8'hA5 && !busy && !tx_on && !start) rs <= R_S1;
        R_S1: if (rb == 8'h5A) begin rs <= R_HDR; rn <= 0; rcrc <= 32'hFFFFFFFF; end
              else if (rb != 8'hA5) rs <= R_S0;
        R_HDR: begin
          rcrc <= crc8(rcrc, rb); rn <= rn + 1;
          case (rn)
            0: rtype <= rb; 1: rpos[7:0] <= rb; 2: rpos[15:8] <= rb;
            3: rtok[7:0] <= rb; 4: rtok[15:8] <= rb; 5: rtok[23:16] <= rb;
            default: begin
              rflags <= rb; rn <= 0; rs <= R_PAY;
              rlen <= (rtype == 8'd2) ? PAYH : 16'd2;
            end
          endcase
        end
        R_PAY: begin
          rcrc <= crc8(rcrc, rb); rn <= rn + 1;
          if (!rn[0]) rlo <= rb;
          else if (rtype == 8'd2) begin
            x_we <= 1'b1; x_addr <= rn >> 1; x_wdata <= {{rb, rlo}};
          end
          if (rn + 1 == rlen) begin rn <= 0; rs <= R_CRC; end
        end
        R_CRC: begin
          rgot[rn * 8 +: 8] <= rb; rn <= rn + 1;
          if (rn == 3) rs <= R_GO;
        end
        default: rs <= R_S0;
      endcase
      if (rs == R_GO) begin
        rs <= R_S0;
        if (rgot == ~rcrc && (rtype == 8'd2 || HAS_EMB)) begin
          tok <= rtok; pos <= rpos; head_en <= rflags[0] && HAS_HEAD;
          emb_en <= (rtype == 8'd1); start <= 1'b1; messages <= messages + 1;
          tflags <= rflags;
        end else crc_errors <= crc_errors + 1;
      end
      // ---- the core is done: send its hidden state, or the token
      if (done && !tx_on) begin
        tx_on <= 1'b1; ti <= 0; tcrc <= 32'hFFFFFFFF;
        tx_hid <= !HAS_HEAD;
        tlen <= HAS_HEAD ? {hdr} + 2 + 4 : {hdr} + PAYH + 4;
        tpos <= HAS_HEAD ? pos + 1 : pos;
        ttok <= HAS_HEAD ? next_tok : tok;
        tbest <= best;
        x_addr <= 0;
      end
      if (tx_on) begin
        if (ti >= {hdr}) x_addr <= tword;
        if (tr && !ts) begin
          tb <= tbyte; ts <= 1'b1;
          if (ti >= 2 && ti < tlen - 4) tcrc <= crc8(tcrc, tbyte);
          ti <= ti + 1;
          if (ti + 1 == tlen) tx_on <= 1'b0;
        end
      end
    end
  end
endmodule
""".format(D=D, twm=tw - 1, pwm=pw - 1, awm=aw - 1, hdr=HDR)


def _mem_block(p, w, lay, gn, half):
    """One stage's clock, core ports and memories: what that board's DDR
    and block RAM would be, as the direct testbench models them."""
    return """  // ---- stage {p}: its own clock and memories
  reg {p}_clk = 0;
  always #{half} {p}_clk = ~{p}_clk;
  reg {p}_rst_n = 0;
  wire [{WA}:0] {p}_w_addr; reg [{LW}:0] {p}_w_data, {p}_wtmp;
  wire [{CA}:0] {p}_c_addr; reg [{CW}:0] {p}_c_data;
  wire [{GA}:0] {p}_g_addr; reg signed [15:0] {p}_g_data;
  wire [{KA}:0] {p}_k_raddr, {p}_kw0_addr, {p}_kw1_addr;
  wire [{VA}:0] {p}_v_raddr, {p}_vw_addr;
  reg [{LW}:0] {p}_k_rdata, {p}_v_rdata, {p}_kt;
  wire {p}_kw0_en, {p}_kw1_en, {p}_vw_en;
  wire [{LB}:0] {p}_kw0_lane, {p}_kw1_lane, {p}_vw_lane;
  wire signed [15:0] {p}_kw0_data, {p}_kw1_data, {p}_vw_data;
  reg [{CW}:0] {p}_cmem [0:{cn}];
  reg signed [15:0] {p}_gmem [0:{gn}];
  reg [{LW}:0] {p}_km [0:{kn}];
  reg [{LW}:0] {p}_vm [0:{vn}];
  integer {p}_fd, {p}_r, {p}_i;
  reg [{WA}:0] {p}_wlast;
  always @(posedge {p}_clk) begin
    if ({p}_w_addr !== {p}_wlast) begin
      if ({p}_w_addr !== {p}_wlast + 1) {p}_r = $fseek({p}_fd, {p}_w_addr * {WB}, 0);
      {p}_r = $fread({p}_wtmp, {p}_fd);
      {p}_wlast = {p}_w_addr;
    end
    {p}_w_data <= {p}_wtmp;
    {p}_c_data <= {p}_cmem[{p}_c_addr];
    {p}_g_data <= {p}_gmem[{p}_g_addr];
    {p}_k_rdata <= {p}_km[{p}_k_raddr];
    {p}_v_rdata <= {p}_vm[{p}_v_raddr];
    if ({p}_kw0_en) begin {p}_kt = {p}_km[{p}_kw0_addr]; {p}_kt[{p}_kw0_lane * 16 +: 16] = {p}_kw0_data; {p}_km[{p}_kw0_addr] = {p}_kt; end
    if ({p}_kw1_en) begin {p}_kt = {p}_km[{p}_kw1_addr]; {p}_kt[{p}_kw1_lane * 16 +: 16] = {p}_kw1_data; {p}_km[{p}_kw1_addr] = {p}_kt; end
    if ({p}_vw_en) begin {p}_kt = {p}_vm[{p}_vw_addr]; {p}_kt[{p}_vw_lane * 16 +: 16] = {p}_vw_data; {p}_vm[{p}_vw_addr] = {p}_kt; end
  end
  wire {p}_start, {p}_head_en, {p}_emb_en, {p}_x_we, {p}_done, {p}_busy;
  // Its core's cycles with work to do, on its own clock: what the
  // planner's per-stage estimate is checked against.
  integer {p}_busyc = 0;
  always @(posedge {p}_clk) if ({p}_busy) {p}_busyc = {p}_busyc + 1;
  wire [{twm}:0] {p}_tok, {p}_next_tok;
  wire [{pwm}:0] {p}_pos;
  wire [{xam}:0] {p}_x_addr;
  wire signed [15:0] {p}_x_wdata, {p}_x_rdata, {p}_best;
  wire [15:0] {p}_crc_errors, {p}_messages;
  qwen_full_{p} {p}_core (.clk({p}_clk), .rst_n({p}_rst_n), .start({p}_start),
    .head_en({p}_head_en), .tok({p}_tok), .pos({p}_pos), .w_addr({p}_w_addr),
    .w_data({p}_w_data), .c_addr({p}_c_addr), .c_data({p}_c_data), .g_addr({p}_g_addr),
    .g_data({p}_g_data), .k_raddr({p}_k_raddr), .k_rdata({p}_k_rdata),
    .v_raddr({p}_v_raddr), .v_rdata({p}_v_rdata),
    .kw0_en({p}_kw0_en), .kw0_addr({p}_kw0_addr), .kw0_lane({p}_kw0_lane), .kw0_data({p}_kw0_data),
    .kw1_en({p}_kw1_en), .kw1_addr({p}_kw1_addr), .kw1_lane({p}_kw1_lane), .kw1_data({p}_kw1_data),
    .vw_en({p}_vw_en), .vw_addr({p}_vw_addr), .vw_lane({p}_vw_lane), .vw_data({p}_vw_data),
    .emb_en({p}_emb_en), .x_we({p}_x_we), .x_addr({p}_x_addr), .x_wdata({p}_x_wdata),
    .x_rdata({p}_x_rdata), .next_tok({p}_next_tok), .best({p}_best), .done({p}_done),
    .busy({p}_busy));
  initial begin
    {p}_fd = $fopen("{p}/weights.bin", "rb");
    {p}_wlast = {{{WA1}{{1'b1}}}};
    $readmemh("{p}/cparams.hex", {p}_cmem);
    $readmemh("{p}/gains.hex", {p}_gmem);
    for ({p}_i = 0; {p}_i <= {kn}; {p}_i = {p}_i + 1) {p}_km[{p}_i] = 0;
    for ({p}_i = 0; {p}_i <= {vn}; {p}_i = {p}_i + 1) {p}_vm[{p}_i] = 0;
    repeat (4) @(negedge {p}_clk); {p}_rst_n = 1;
  end
""".format(p=p, half=half, WA=w["WA"] - 1, WA1=w["WA"], CA=w["CA"] - 1,
           CW=w["CW"] - 1, GA=w["GA"] - 1, KA=w["KA"] - 1, VA=w["VA"] - 1,
           cn=lay.cwords - 1, gn=gn - 1, kn=w["KWN"] - 1, vn=w["VWN"] - 1,
           twm=w["tw"] - 1, pwm=w["pw"] - 1, xam=w["xa"] - 1,
           LW=16 * w["N"] - 1, LB=w["LB"] - 1, WB=2 * w["N"])


def _noise(out, src, seed):
    """A link's line with bit errors: flipped for one bit time at random,
    with probability 1/BER_INV each bit time (never, at BER_INV 0)."""
    return """  reg {o}_f = 0;
  integer {o}_seed = {seed};
  assign {o} = {src} ^ {o}_f;
  initial if (BER_INV > 0) forever begin
    #(BIT);
    if ({{$random({o}_seed)}} % BER_INV == 0) begin {o}_f = 1; #(BIT); {o}_f = 0; end
  end
""".format(o=out, src=src, seed=seed)


def render_tb(stages, bit_ns, seq, n_prompt, D, ber_inv=0, timeout_ns=10000000.0):
    """stages: (name, w, lay, gn, half period, divider, has_emb, has_head).
    The host sends every token to the first stage and reads the last
    stage's answer; the stages pass hidden states down the chain.
    ber_inv > 0 flips a link's line for one bit time with probability
    1/ber_inv each bit time, on every link, the host's included; the host
    then resends a position whose answer is lost or corrupt, after
    timeout_ns at first and twice as long each time it has to retry."""
    blocks, ctrls, noise = [], [], []
    # Every link's two ends up front: a stage's line out, and the line
    # the next one sees, through that link's bit errors.
    wires = "  wire %s;\n" % ", ".join(
        ["%s_tx" % st[0] for st in stages] + ["%s_rxn" % st[0] for st in stages]
        + ["host_rxn"])
    for i, (p, w, lay, gn, half, div, emb, head) in enumerate(stages):
        blocks.append(_mem_block(p, w, lay, gn, half))
        rx = "host_tx" if i == 0 else "%s_tx" % stages[i - 1][0]
        noise.append(_noise("%s_rxn" % p, rx, 1000 + i))
        rx = "%s_rxn" % p
        ctrls.append("""  stage_ctrl #(.DIV({div}), .HAS_EMB({emb}), .HAS_HEAD({head})) {p}_ctl (
    .clk({p}_clk), .rst_n({p}_rst_n), .rx({rx}), .tx({p}_tx), .start({p}_start),
    .head_en({p}_head_en), .emb_en({p}_emb_en), .tok({p}_tok), .pos({p}_pos),
    .x_we({p}_x_we), .x_addr({p}_x_addr), .x_wdata({p}_x_wdata), .x_rdata({p}_x_rdata),
    .next_tok({p}_next_tok), .best({p}_best), .done({p}_done), .busy({p}_busy),
    .crc_errors({p}_crc_errors), .messages({p}_messages));
""".format(p=p, div=div, emb=int(emb), head=int(head), rx=rx))
    last = stages[-1][0]
    noise.append(_noise("host_rxn", "%s_tx" % last, 999))
    steps = "\n".join("    host_step(%d, %d, %d);" % (seq[k], k, int(k >= n_prompt - 1))
                      for k in range(len(seq) - 1))
    errs = " + ".join("%s_crc_errors" % s[0] for s in stages)
    return """`timescale 1ns/1ps
module tb_gals;
  localparam real BIT = {bit};
  localparam integer BER_INV = {ber_inv};
  reg host_tx = 1;               // the host's UART line into the first stage
{wires}{blocks}{ctrls}{noise}
  // ---- the host: a UART at its own bit time, no clock shared with anyone
  real tmo = {tmo};
  function [31:0] crc8(input [31:0] c, input [7:0] d);
    integer i; reg [31:0] x;
    begin
      x = c ^ {{24'd0, d}};
      for (i = 0; i < 8; i = i + 1) x = x[0] ? (x >> 1) ^ 32'hEDB88320 : (x >> 1);
      crc8 = x;
    end
  endfunction
  task send_byte(input [7:0] b);
    integer i;
    begin
      host_tx = 0; #(BIT);
      for (i = 0; i < 8; i = i + 1) begin host_tx = b[i]; #(BIT); end
      host_tx = 1; #(BIT);
    end
  endtask
  reg [7:0] msg [0:15];
  reg [31:0] c;
  integer k;
  task recv_byte(output [7:0] b);
    integer i;
    begin
      @(negedge host_rxn); #(BIT * 1.5);
      for (i = 0; i < 8; i = i + 1) begin b[i] = host_rxn; #(BIT); end
    end
  endtask
  reg [7:0] rb;
  reg [7:0] tmsg [0:8];
  // One answer: find the A5 5A that starts it, then the 13 bytes after.
  task recv_msg;
    begin
      rb = 0;
      while (rb != 8'h5A) begin
        recv_byte(rb);
        while (rb != 8'hA5) recv_byte(rb);
        recv_byte(rb);
      end
      msg[0] = 8'hA5; msg[1] = 8'h5A;
      for (k = 2; k < 15; k = k + 1) begin recv_byte(rb); msg[k] = rb; end
    end
  endtask
  integer bad = 0, resends = 0, got, okm, j;
  task host_step(input integer t, input integer p, input integer he);
    begin
      tmsg[0] = 1; tmsg[1] = p & 255; tmsg[2] = p >> 8; tmsg[3] = t & 255;
      tmsg[4] = (t >> 8) & 255; tmsg[5] = t >> 16; tmsg[6] = he; tmsg[7] = 0; tmsg[8] = 0;
      okm = 0;
      while (!okm) begin
        c = 32'hFFFFFFFF;
        for (j = 0; j < 9; j = j + 1) c = crc8(c, tmsg[j]);
        c = ~c;
        send_byte(8'hA5); send_byte(8'h5A);
        for (j = 0; j < 9; j = j + 1) send_byte(tmsg[j]);
        for (j = 0; j < 4; j = j + 1) send_byte(c[j * 8 +: 8]);
        // The last stage answers every position, with a token when the
        // head ran. An answer lost or corrupt on any link is resent for:
        // running a position again rewrites its KV entries with the same
        // values. A late answer to an earlier try is known by position.
        got = 0;
        while (!got) begin
          fork : wait_answer
            begin recv_msg; got = 1; disable wait_answer; end
            begin #(tmo); got = 2; disable wait_answer; end
          join
          if (got == 1) begin
            c = 32'hFFFFFFFF;
            for (k = 2; k < 11; k = k + 1) c = crc8(c, msg[k]);
            if ({{msg[14], msg[13], msg[12], msg[11]}} !== ~c) begin
              bad = bad + 1; got = 2;
            end else if ({{msg[4], msg[3]}} != p + 1) got = 0;   // an earlier try's
          end
        end
        if (got == 1) okm = 1;
        else begin resends = resends + 1; tmo = tmo * 2.0; end
      end
      if (he) $display("TOKEN pos=%0d tok=%0d best=%0d", {{msg[4], msg[3]}},
                       {{msg[7], msg[6], msg[5]}}, $signed({{msg[10], msg[9]}}));
      $fflush;
    end
  endtask
  initial begin
    #2000;
{steps}
    $display("LINK crc_errors=%0d host_bad=%0d resends=%0d", {errs}, bad, resends);
{busy}
    $finish;
  end
endmodule
""".format(blocks="".join(blocks), ctrls="".join(ctrls), noise="".join(noise),
           wires=wires, bit="%.1f" % bit_ns,
           last=last, steps=steps, errs=errs, ber_inv=int(ber_inv),
           tmo="%.1f" % timeout_ns,
           busy="\n".join('    $display("STAGE %s busy_cycles=%%0d", %s_busyc);' % (st[0], st[0])
                          for st in stages))


def answer_ns(im, split, stages, bit_ns):
    """How long the host waits for an answer before it resends: twice a
    generous estimate of one position through every stage and link, so a
    run without bit errors never resends."""
    D, F, H, KV, hd, V = im.D, im.F, im.H, im.KV, im.hd, im.V
    lw = D * (H * hd + 2 * KV * hd) + H * hd * D + 3 * D * F
    ns = 0.0
    for (p, w, lay, gn, half, div, emb, head), layers in zip(stages, split):
        n = w["N"]
        cyc = len(layers) * (lw / n + 8 * D + 4 * F + 8 * H * hd + 4 * (H + KV) * hd)
        if head:
            cyc += V * D / n + V
        ns += 4 * cyc * 2 * half + (2 * D + 13) * 10 * bit_ns
    return 2 * ns + 1e6


def build(im, ids, n_gen, work, split, clocks=(10.0, 7.9, 12.3), bit_ns=160.0, log=print,
          lanes=None, ber_inv=0):
    """Build a pipeline of len(split) stages; split[i] is stage i's layers.
    lanes[i], if given, is stage i's projection width: boards of different
    sizes in one pipeline, which only share the hidden state. Returns the
    integer model's tokens and the testbench sources."""
    want = qr.greedy(im, ids, n_gen)
    own = im.ms.get("lanes")
    os.makedirs(work, exist_ok=True)
    stages, srcs = [], set()
    for i, layers in enumerate(split):
        p = chr(ord("a") + i)
        d = os.path.join(work, p)
        head = i == len(split) - 1
        if lanes:
            im.ms["lanes"] = lanes[i]
        # Only the first and last stage need the tied table.
        _, s, w = qwen_full.build_model(im, ids, n_gen, d, log=lambda *a: None,
                                        layers=layers, stage=True, want=want,
                                        table=i == 0 or head)
        # The blocks whose width is the stage's own get the stage's name.
        rtl = open(os.path.join(d, "qwen_full.v")).read().replace(
            "module qwen_full (", "module qwen_full_%s (" % p, 1).replace(
            "  projn u_proj (", "  projn_%s u_proj (" % p, 1).replace(
            "  attnn u_attn (", "  attnn_%s u_attn (" % p, 1)
        with open(os.path.join(work, "qwen_full_%s.v" % p), "w") as f:
            f.write(rtl)
        for f in s:
            if f in ("b_projn.v", "b_attnn.v"):
                m = f[2:-2]
                with open(os.path.join(work, "b_%s_%s.v" % (m, p)), "w") as g:
                    g.write(open(os.path.join(d, f)).read().replace(
                        "module %s (" % m, "module %s_%s (" % (m, p), 1))
                srcs.add("b_%s_%s.v" % (m, p))
            elif f not in ("tb_qfull.v", "qwen_full.v"):
                shutil.copyfile(os.path.join(d, f), os.path.join(work, f))
                srcs.add(f)
        w["xa"] = _clog2(im.D)
        half = clocks[i % len(clocks)] / 2
        div = int(round(bit_ns / clocks[i % len(clocks)]))
        stages.append((p, w, w["lay"], w["gn"], half, div, i == 0, head))
    if lanes:
        im.ms["lanes"] = own
    tw, pw = stages[0][1]["tw"], stages[0][1]["pw"]
    with open(os.path.join(work, "stage_ctrl.v"), "w") as f:
        f.write(board.UART + render_ctrl(im.D, tw, pw))
    with open(os.path.join(work, "tb_gals.v"), "w") as f:
        f.write(render_tb(stages, bit_ns, want, len(ids), im.D, ber_inv,
                          answer_ns(im, split, stages, bit_ns)))
    return want, (["tb_gals.v", "stage_ctrl.v"]
                  + ["qwen_full_%s.v" % s[0] for s in stages] + sorted(srcs))


def run(work, srcs, timeout=1800):
    r = subprocess.run(["iverilog", "-g2005", "-o", "g.out"] + srcs, cwd=work,
                       capture_output=True, text=True)
    if r.returncode:
        return r.stdout + r.stderr
    return subprocess.run(["vvp", "g.out"], cwd=work, capture_output=True,
                          text=True, timeout=timeout).stdout


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--style", default="qwen3", choices=("qwen3", "qwen2.5"))
    ap.add_argument("--work", default=os.path.join(ROOT, "build_gals"))
    a = ap.parse_args()
    import qwen_synth
    im, _ = qwen_synth.model(a.style)
    ids = [3, 77, 12, 140]
    t0 = time.time()
    want, srcs = build(im, ids, 3, a.work, [[0], [1]])
    out = run(a.work, srcs)
    print(out[-2000:])
    print("integer model:", want[len(ids):], "(%.0f s)" % (time.time() - t0))


if __name__ == "__main__":
    main()
