"""Does the generated hardware actually compute the model's arithmetic?

Every other check in this repo verifies the RTL against a testbench written
from the same spec. That is circular with respect to the one question that
decides whether any of this hosts an LLM: when the model needs a dot
product, does the agent-generated MAC return the number the model needs?

This closes that loop in three steps.

  1. A bit-accurate Python model of the generated MAC: signed operands,
     full-width signed product, wrapping N-bit accumulator.
  2. Co-simulation. Real quantized transformer dot products are pushed
     through the actual generated Verilog in iverilog, and every cycle is
     compared against the Python model. If they ever disagree the model is
     wrong and everything built on it is worthless.
  3. The validated model is then used at model scale, where running iverilog
     would take years, to answer the question the accumulator width rule
     exists for: does a real quantized layer ever overflow it?

Run: python3 inference.py [--layers 2] [--d-model 64]
"""
import argparse
import os
import random
import shutil
import subprocess
import sys

import specgen
from chiplet_flow import ROOT

WORK = os.path.join(ROOT, "build_infer")


class MacModel:
    """Bit-accurate model of the generated MAC.

    Signed two's complement in, signed product, and an accumulator that
    wraps at acc_width rather than growing without bound, because that is
    what the hardware does. Modelling it as a Python int would hide exactly
    the overflow this is meant to detect.
    """

    def __init__(self, data_width, acc_width):
        self.dw, self.aw = data_width, acc_width
        self.lo, self.hi = -(1 << (data_width - 1)), (1 << (data_width - 1)) - 1
        self.acc = 0
        self.overflows = 0

    def _wrap(self, v):
        m = 1 << self.aw
        v &= m - 1
        return v - m if v >= (m >> 1) else v

    def clear(self):
        self.acc = 0

    def mac(self, a, b):
        assert self.lo <= a <= self.hi, "operand %d outside int%d" % (a, self.dw)
        assert self.lo <= b <= self.hi, "operand %d outside int%d" % (b, self.dw)
        exact = self.acc + a * b
        self.acc = self._wrap(exact)
        if self.acc != exact:
            self.overflows += 1
        return self.acc

    def dot(self, xs, ws):
        self.clear()
        for x, w in zip(xs, ws):
            self.mac(x, w)
        return self.acc


def slit(v, w):
    """Signed Verilog literal. The sign goes outside the sized constant:
    8'sd-5 is a syntax error, -8'sd5 is what is meant. The most negative
    value is fine too, since -8'sd128 wraps back to -128 in 8 bits."""
    return "-%d'sd%d" % (w, -v) if v < 0 else "%d'sd%d" % (w, v)


def emit_cosim_tb(spec, vectors):
    """Testbench that drives real dot products through the generated MAC and
    prints the accumulator after each one, for comparison outside."""
    dw = spec["parameters"]["data_width"]
    aw = spec["parameters"]["acc_width"]
    lines = []
    for n, (xs, ws) in enumerate(vectors):
        lines.append('    dot_start;')
        for x, w in zip(xs, ws):
            lines.append("    push(%s, %s);" % (slit(x, dw), slit(w, dw)))
        lines.append("    dot_end(%d);" % n)
    return """`timescale 1ns/1ps
// GENERATED by inference.py: real quantized transformer dot products driven
// through the generated MAC, so the Python model can be checked against the
// hardware rather than against itself.
module tb_cosim;
  reg clk = 0, rst_n = 0, clear = 0, valid_in = 0;
  reg  signed [{dwm}:0] a = 0, b = 0;
  wire signed [{awm}:0] acc;
  wire valid_out;

  mac dut (.clk(clk), .rst_n(rst_n), .clear(clear), .a(a), .b(b),
           .valid_in(valid_in), .acc(acc), .valid_out(valid_out));
  always #5 clk = ~clk;

  task dot_start;
    begin
      @(negedge clk); valid_in = 0; clear = 1;
      @(negedge clk); clear = 0;
    end
  endtask

  task push(input signed [{dwm}:0] ai, input signed [{dwm}:0] bi);
    begin
      @(negedge clk); a = ai; b = bi; valid_in = 1;
    end
  endtask

  // Two pipeline stages, so the last product needs to be flushed out before
  // the accumulator holds the whole dot product.
  task dot_end(input integer idx);
    begin
      @(negedge clk); valid_in = 0;
      repeat (3) @(negedge clk);
      $display("DOT %0d %0d", idx, acc);
    end
  endtask

  initial begin
    repeat (3) @(negedge clk);
    rst_n = 1;
{body}
    $display("COSIM_DONE");
    $finish;
  end
endmodule
""".format(dwm=dw - 1, awm=aw - 1, body="\n".join(lines))


class RequantModel:
    """Bit-accurate model of the generated requantizer.

    Same contract as the RTL and the same golden rule the testbench uses:
    multiply by a fixed-point scale, add half an LSB, arithmetic shift, and
    saturate rather than wrap. Python's >> on a negative int floors, which
    is what Verilog's >>> on a signed value does, so the two agree.
    """

    def __init__(self, out_width, scale_width, shift_width):
        self.dw, self.mw, self.sw = out_width, scale_width, shift_width
        self.lo = -(1 << (out_width - 1))
        self.hi = (1 << (out_width - 1)) - 1
        self.saturations = 0

    def pick(self, maxabs):
        """Fixed-point (scale, shift) for a float scale of hi/maxabs. The
        hardware has no divider, so the reciprocal is resolved here, once
        per tensor, exactly as a real deployment resolves it offline."""
        if maxabs <= 0:
            return 1, 0
        want = float(self.hi) / float(maxabs)
        k = 0
        while k + 1 < (1 << self.sw) and want * (1 << (k + 1)) < (1 << (self.mw - 1)):
            k += 1
        m = int(round(want * (1 << k)))
        return max(1, min((1 << self.mw) - 1, m)), k

    def apply(self, acc, scale, shift):
        prod = acc * scale
        r = (prod + (1 << (shift - 1))) >> shift if shift > 0 else prod
        if r > self.hi:
            self.saturations += 1
            return self.hi
        if r < self.lo:
            self.saturations += 1
            return self.lo
        return r

    def vector(self, accs):
        """Requantize a whole activation vector, one shared scale, which is
        what per-tensor quantization means."""
        m = max((abs(a) for a in accs), default=0)
        sc, sh = self.pick(m)
        return [self.apply(a, sc, sh) for a in accs], sc, sh


def quantize(vals, bits):
    """Symmetric per-tensor quantization, the standard int8 scheme: one
    scale, zero maps to zero, so the hardware only needs signed multiply."""
    hi = (1 << (bits - 1)) - 1
    m = max(abs(v) for v in vals) or 1.0
    scale = m / hi
    return [max(-hi - 1, min(hi, int(round(v / scale)))) for v in vals], scale


class QuantLayer:
    """One real transformer block's worth of arithmetic, quantized to the
    datapath the spec derived: attention projections, the attention itself,
    and the MLP. Weights are random but the shapes, the reduction depths and
    the quantization are the model's."""

    def __init__(self, d_model, d_ff, n_head, bits, seed=0):
        self.d, self.f, self.h = d_model, d_ff, n_head
        rng = random.Random(seed)
        def mat(r, c):
            # Xavier-ish, so the quantized range is realistic rather than
            # uniformly saturated.
            s = (2.0 / (r + c)) ** 0.5
            return [[rng.gauss(0, s) for _ in range(c)] for _ in range(r)]
        self.wq, self.sq = self._q(mat(d_model, d_model), bits)
        self.wk, self.sk = self._q(mat(d_model, d_model), bits)
        self.wv, self.sv = self._q(mat(d_model, d_model), bits)
        self.wo, self.so = self._q(mat(d_model, d_model), bits)
        self.w1, self.s1 = self._q(mat(d_model, d_ff), bits)
        self.w2, self.s2 = self._q(mat(d_ff, d_model), bits)

    @staticmethod
    def _q(m, bits):
        flat = [v for row in m for v in row]
        qf, scale = quantize(flat, bits)
        c = len(m[0])
        return [qf[i * c:(i + 1) * c] for i in range(len(m))], scale

    def matvec(self, x, w, mac, taps=None, keep=2):
        """One matrix-vector product, every dot product run through the MAC
        model, which is what the hardware would do. A few columns are kept
        verbatim so the co-simulation replays real work rather than
        synthetic vectors."""
        cols = len(w[0])
        out = []
        for c in range(cols):
            col = [w[r][c] for r in range(len(w))]
            out.append(mac.dot(x, col))
            if taps is not None and c < keep:
                taps.append((list(x), col))
        return out

    def forward(self, x_q, mac, bits):
        """Returns the block output and the list of every dot product, so the
        co-simulation can replay real ones through the RTL."""
        taps = []
        def mv(v, w):
            # Requantize after every matmul. The accumulator is wide, the
            # next operand is not, and real int8 inference rescales between
            # every matmul. Skipping it would feed accumulator-width values
            # into an int8 port, which the hardware cannot accept.
            return requantize(self.matvec(v, w, mac, taps), bits)
        q, k = mv(x_q, self.wq), mv(x_q, self.wk)
        v = mv(x_q, self.wv)
        # Single-position decode: attention over one key reduces to a scaled
        # pass-through of v, so every MAC in this block is in the four
        # projections and the two MLP matmuls, which is where the real model
        # spends them too.
        att = mv(v, self.wo)
        h = mv(att, self.w1)
        h = requantize([max(0, u) for u in h], bits)
        return mv(h, self.w2), taps


def requantize(acc_vals, bits):
    """Accumulators are wide; the next layer's operands are not. Real
    quantized inference rescales between layers, and that rescale is what
    keeps the datapath narrow."""
    q, _ = quantize([float(v) for v in acc_vals], bits)
    return q


def emit_requant_tb(spec, vectors):
    """Drive real requantizations through the generated requantizer."""
    p = spec["parameters"]
    aw, dw, mw, sw = (p["acc_width"], p["out_width"], p["scale_width"],
                      p["shift_width"])
    lines = []
    for i, (acc, sc, sh) in enumerate(vectors):
        lines.append("    drive(%s, %d'd%d, %d'd%d, %d);"
                     % (slit(acc, aw), mw, sc, sw, sh, i))
    return """`timescale 1ns/1ps
// GENERATED by inference.py: requantizations taken from a real decode,
// driven through the generated requantizer.
module tb_rqcosim;
  reg clk = 0, rst_n = 0, valid_in = 0;
  reg  signed [{awm}:0] acc_in = 0;
  reg         [{mwm}:0] scale = 0;
  reg         [{swm}:0] shift = 0;
  wire signed [{dwm}:0] q_out;
  wire sat, valid_out;
  requant dut (.clk(clk), .rst_n(rst_n), .acc_in(acc_in), .scale(scale),
               .shift(shift), .valid_in(valid_in), .q_out(q_out),
               .sat(sat), .valid_out(valid_out));
  always #5 clk = ~clk;
  task drive(input signed [{awm}:0] a, input [{mwm}:0] sc,
             input [{swm}:0] sh, input integer idx);
    begin
      @(negedge clk); acc_in = a; scale = sc; shift = sh; valid_in = 1;
      @(negedge clk); valid_in = 0;
      repeat ({settle}) @(negedge clk);
      $display("RQ %0d %0d", idx, q_out);
    end
  endtask
  initial begin
    repeat (3) @(negedge clk);
    rst_n = 1;
    @(negedge clk);
{body}
    $display("COSIM_DONE");
    $finish;
  end
endmodule
""".format(awm=aw - 1, dwm=dw - 1, mwm=mw - 1, swm=sw - 1,
           settle=p["pipeline_stages"] - 1, body="\n".join(lines))


def run_requant_cosim(spec, vectors, rtl_src):
    shutil.rmtree(WORK, ignore_errors=True)
    os.makedirs(WORK)
    open(os.path.join(WORK, "requant.v"), "w").write(rtl_src)
    open(os.path.join(WORK, "tb.v"), "w").write(
        emit_requant_tb(spec, vectors))
    r = subprocess.run(["iverilog", "-g2005", "-o", "rq.out", "tb.v",
                        "requant.v"], cwd=WORK, capture_output=True,
                       text=True)
    if r.returncode:
        raise SystemExit("requant cosim compile failed:\n" + r.stdout + r.stderr)
    r = subprocess.run(["vvp", "rq.out"], cwd=WORK, capture_output=True,
                       text=True, timeout=600)
    got = {}
    for line in r.stdout.splitlines():
        if line.startswith("RQ "):
            _, idx, val = line.split()
            got[int(idx)] = int(val)
    if "COSIM_DONE" not in r.stdout:
        raise SystemExit("requant cosim did not finish:\n" + r.stdout[-800:])
    return got


def run_exp_cosim(spec, xs, rtl_src):
    """Drive real softmax arguments through the generated exponential."""
    p = spec["parameters"]
    iw, ow = p["in_width"], p["out_width"]
    body = "\n".join("    drive(%s, %d);" % (slit(x, iw), i)
                     for i, x in enumerate(xs))
    tb = """`timescale 1ns/1ps
module tb_expcosim;
  reg clk = 0, rst_n = 0, valid_in = 0;
  reg  signed [{iwm}:0] x = 0;
  wire        [{owm}:0] y;
  wire valid_out;
  expu dut (.clk(clk), .rst_n(rst_n), .x(x), .valid_in(valid_in),
            .y(y), .valid_out(valid_out));
  always #5 clk = ~clk;
  task drive(input signed [{iwm}:0] xi, input integer idx);
    begin
      @(negedge clk); x = xi; valid_in = 1;
      @(negedge clk); valid_in = 0;
      repeat ({settle}) @(negedge clk);
      $display("EX %0d %0d", idx, y);
    end
  endtask
  initial begin
    repeat (3) @(negedge clk); rst_n = 1; @(negedge clk);
{body}
    $display("COSIM_DONE");
    $finish;
  end
endmodule
""".format(iwm=iw - 1, owm=ow - 1, settle=p["pipeline_stages"] - 1,
           body=body)
    shutil.rmtree(WORK, ignore_errors=True)
    os.makedirs(WORK)
    open(os.path.join(WORK, "expu.v"), "w").write(rtl_src)
    open(os.path.join(WORK, "tb.v"), "w").write(tb)
    r = subprocess.run(["iverilog", "-g2005", "-o", "ex.out", "tb.v",
                        "expu.v"], cwd=WORK, capture_output=True, text=True)
    if r.returncode:
        raise SystemExit("exp cosim compile failed:\n" + r.stdout + r.stderr)
    r = subprocess.run(["vvp", "ex.out"], cwd=WORK, capture_output=True,
                       text=True, timeout=600)
    got = {}
    for line in r.stdout.splitlines():
        if line.startswith("EX "):
            _, idx, val = line.split()
            got[int(idx)] = int(val)
    if "COSIM_DONE" not in r.stdout:
        raise SystemExit("exp cosim did not finish:\n" + r.stdout[-800:])
    return got


def run_cosim(spec, vectors, rtl_src):
    shutil.rmtree(WORK, ignore_errors=True)
    os.makedirs(WORK)
    open(os.path.join(WORK, "mac.v"), "w").write(rtl_src)
    open(os.path.join(WORK, "tb.v"), "w").write(emit_cosim_tb(spec, vectors))
    r = subprocess.run(["iverilog", "-g2005", "-o", "cosim.out", "tb.v",
                        "mac.v"], cwd=WORK, capture_output=True, text=True)
    if r.returncode:
        raise SystemExit("cosim compile failed:\n" + r.stdout + r.stderr)
    r = subprocess.run(["vvp", "cosim.out"], cwd=WORK, capture_output=True,
                       text=True, timeout=600)
    got = {}
    for line in r.stdout.splitlines():
        if line.startswith("DOT "):
            _, idx, val = line.split()
            got[int(idx)] = int(val)
    if "COSIM_DONE" not in r.stdout:
        raise SystemExit("cosim did not finish:\n" + r.stdout[-800:])
    return got


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--d-model", type=int, default=64)
    ap.add_argument("--d-ff", type=int, default=256)
    ap.add_argument("--layers", type=int, default=2)
    ap.add_argument("--cosim-dots", type=int, default=24)
    a = ap.parse_args()

    ms = specgen.load_model_spec()
    spec = specgen.derive_chiplet_spec(ms)
    dw = spec["parameters"]["data_width"]
    aw = spec["parameters"]["acc_width"]
    print("chiplet: int%d operands, %d-bit %s accumulator\n"
          % (dw, aw, "signed" if spec["parameters"]["signed"] else "unsigned"))

    # The RTL the agent actually produces for this spec.
    from agent import RuleBasedAgent, FIX_WIDTH, FIX_CLEAR
    rtl = RuleBasedAgent().render_mac(spec, {FIX_WIDTH, FIX_CLEAR})

    print("running a real quantized transformer block through the model")
    mac = MacModel(dw, aw)
    layers = [QuantLayer(a.d_model, a.d_ff, 8, dw, seed=i)
              for i in range(a.layers)]
    rng = random.Random(99)
    x = [rng.gauss(0, 1) for _ in range(a.d_model)]
    x_q, _ = quantize(x, dw)
    taps = []
    for i, L in enumerate(layers):
        x_q, t = L.forward(x_q, mac, dw)
        taps.extend(t)
    print("  %d layers, d_model %d, d_ff %d" % (a.layers, a.d_model, a.d_ff))
    print("  %d dot products, deepest reduction %d terms"
          % (len(taps), max(len(t[0]) for t in taps)))
    print("  output range %d..%d" % (min(x_q), max(x_q)))

    # Step 2: check the model against the hardware on real vectors from that
    # run, not on synthetic ones.
    # Sample across depths, not just the first few, so the deep d_ff
    # reductions are represented rather than only the shallow ones.
    by_depth = {}
    for t in taps:
        by_depth.setdefault(len(t[0]), []).append(t)
    sample = []
    for d in sorted(by_depth):
        rng.shuffle(by_depth[d])
        sample.extend(by_depth[d][:max(1, a.cosim_dots // len(by_depth))])
    sample = sample[:a.cosim_dots]
    print("\nco-simulating %d of those dot products through the generated RTL"
          % len(sample))
    got = run_cosim(spec, sample, rtl)
    mismatches = []
    for i, (xs, ws) in enumerate(sample):
        want = MacModel(dw, aw).dot(xs, ws)
        if got.get(i) != want:
            mismatches.append((i, want, got.get(i)))
    if mismatches:
        print("  MISMATCH: the Python model does not match the hardware")
        for i, w_, g_ in mismatches[:5]:
            print("    dot %d: model %d, rtl %s" % (i, w_, g_))
        return 1
    print("  all %d agree bit for bit, reduction depths %s"
          % (len(sample), sorted(set(len(s[0]) for s in sample))))

    # Step 3: the question the accumulator rule exists to answer, now that
    # the model it is asked of has been shown to match the hardware.
    print("\naccumulator headroom at model scale")
    depth = max(ms["d_model"], ms["d_ff"])
    worst = depth * (1 << (dw - 1)) ** 2
    need = worst.bit_length() + 1
    print("  rule gives %d bits; worst case |sum| over %d terms needs %d"
          % (aw, depth, need))

    # Running the real dimensions is only affordable in the validated model,
    # which is the point of validating it. Same arithmetic, same widths.
    big = QuantLayer(ms["d_model"], ms["d_ff"], ms["n_head"], dw, seed=5)
    bmac = MacModel(dw, aw)
    bx, _ = quantize([rng.gauss(0, 1) for _ in range(ms["d_model"])], dw)
    big.forward(bx, bmac, dw)
    print("  full-size block (d_model %d, d_ff %d): %d overflows"
          % (ms["d_model"], ms["d_ff"], bmac.overflows))
    print("  small block: %d overflows" % mac.overflows)
    ok = aw >= need and mac.overflows == 0 and bmac.overflows == 0
    print("  %s" % ("accumulator is sufficient" if ok else "ACCUMULATOR TOO NARROW"))
    shutil.rmtree(WORK, ignore_errors=True)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
