"""Derive the compute chiplet spec from the model.

The model is the input: given model_spec.json, the MAC datapath width comes
from the model's deployment quantization (weight_bits x activation_bits) and
the accumulator width from the longest dot-product reduction in the network.
Accumulating up to max(d_model, d_ff) full-width products needs
ceil(log2(depth)) guard bits on top of the product width so the accumulation
can never overflow, so:

    data_width = max(weight_bits, activation_bits)
    acc_width  = weight_bits + activation_bits + ceil(log2(max(d_model, d_ff)))

Both the chiplet spec and its self-checking testbench are generated here, so
a different model (a 4-bit quantized network, a wider MLP) yields different
hardware through the identical agentic flow with no code changes. The golden
model, directed tests, and throughput burst in the testbench all follow the
derived widths. Pure Python 3 stdlib."""
import json
import math
import os

ROOT = os.path.dirname(os.path.abspath(__file__))


def derive_chiplet_spec(ms):
    """model spec -> chiplet spec. The derivation is recorded in the spec so
    the signed-off profile can carry its own provenance."""
    wb, ab = ms["weight_bits"], ms["activation_bits"]
    dw = max(wb, ab)
    assert dw >= 4, "testbench stimulus assumes at least a 4-bit datapath"
    depth = max(ms["d_model"], ms["d_ff"])
    guard = math.ceil(math.log2(depth))
    aw = wb + ab + guard
    return {
        "name": "mac%d_%s" % (dw, ms["name"]),
        "description": "%d-bit pipelined multiply-accumulate unit derived "
                       "from %s: datapath from the model quantization, "
                       "accumulator sized for its longest reduction"
                       % (dw, ms["name"]),
        "top_module": "mac",
        "parameters": {
            "data_width": dw,
            "acc_width": aw,
            "pipeline_stages": 2,
            "target_clock_mhz": 100,
        },
        "derivation": {
            "model": ms["name"],
            "weight_bits": wb,
            "activation_bits": ab,
            "reduction_depth": depth,
            "guard_bits": guard,
            "rule": "acc_width = weight_bits + activation_bits + "
                    "ceil(log2(max(d_model, d_ff)))",
        },
        "ports": [
            {"name": "clk", "dir": "input", "width": 1,
             "desc": "clock, rising edge"},
            {"name": "rst_n", "dir": "input", "width": 1,
             "desc": "active-low synchronous reset"},
            {"name": "clear", "dir": "input", "width": 1,
             "desc": "synchronous accumulator clear"},
            {"name": "a", "dir": "input", "width": dw,
             "desc": "multiplicand (activation)"},
            {"name": "b", "dir": "input", "width": dw,
             "desc": "multiplier (weight)"},
            {"name": "valid_in", "dir": "input", "width": 1,
             "desc": "input operands valid"},
            {"name": "acc", "dir": "output", "width": aw,
             "desc": "accumulator value"},
            {"name": "valid_out", "dir": "output", "width": 1,
             "desc": "acc updated this cycle"},
        ],
        "behavior": [
            "Stage 1 registers the full %d-bit product a*b and the valid "
            "flag." % (2 * dw),
            "Stage 2 adds the registered product into the %d-bit accumulator "
            "when the piped valid is set." % aw,
            "clear synchronously zeroes acc and valid_out, taking priority "
            "over accumulation.",
            "Latency from valid_in to valid_out is 2 cycles.",
            "%d accumulator bits = %d product bits + %d guard bits, enough "
            "for a %d-deep dot product with no overflow."
            % (aw, wb + ab, guard, depth),
        ],
    }


TB_TEMPLATE = """`timescale 1ns/1ps
// GENERATED by specgen.py from the model spec: do not edit by hand.
// Self-checking testbench for the {dw}-bit MAC with a {aw}-bit accumulator:
// golden pipeline mirror plus directed and random stimulus, machine-parseable
// TB_FAIL / TB_RESULT lines for the agent, and a final back-to-back burst
// that measures steady-state throughput (span cycles per MAC) and pipeline
// latency, printed as a TB_PROFILE line so the flow derives cycles_per_mac
// from simulation instead of hardcoding it.
module tb_mac;
  reg clk = 0, rst_n = 0, clear = 0, valid_in = 0;
  reg [{dwm}:0] a = 0, b = 0;
  wire [{awm}:0] acc;
  wire valid_out;
  integer checks = 0, i;
  reg [{awm}:0] m_acc;
  reg [{pwm}:0] m_prod;
  reg m_vpipe, m_vout;
  reg [127:0] testname;

  // Throughput profiling state
  integer cyc = 0;
  integer first_vin_cyc = 0, first_vout_cyc = 0, last_vout_cyc = 0;
  integer vout_count = 0;
  reg profiling = 0;

  mac dut (.clk(clk), .rst_n(rst_n), .clear(clear), .a(a), .b(b),
           .valid_in(valid_in), .acc(acc), .valid_out(valid_out));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    cyc = cyc + 1;
    if (profiling && valid_out) begin
      if (vout_count == 0) first_vout_cyc = cyc;
      last_vout_cyc = cyc;
      vout_count = vout_count + 1;
    end
  end

  // Golden model: full-width product, synchronous clear with priority.
  always @(posedge clk) begin
    if (!rst_n) begin
      m_prod <= 0; m_vpipe <= 0; m_acc <= 0; m_vout <= 0;
    end else begin
      m_prod  <= a * b;
      m_vpipe <= valid_in;
      if (clear) begin
        m_acc <= 0; m_vout <= 0;
      end else begin
        if (m_vpipe) m_acc <= m_acc + m_prod;
        m_vout <= m_vpipe;
      end
    end
  end

  task check;
    begin
      checks = checks + 1;
      if (acc !== m_acc || valid_out !== m_vout) begin
        $display("TB_FAIL test=%0s expected_acc=%0d got_acc=%0d expected_vout=%b got_vout=%b",
                 testname, m_acc, acc, m_vout, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  // One clock of stimulus: check state from prior edge, then drive new inputs.
  task step(input v, input [{dwm}:0] ai, input [{dwm}:0] bi, input c);
    begin
      @(negedge clk);
      check;
      valid_in = v; a = ai; b = bi; clear = c;
    end
  endtask

  task idle(input integer n);
    begin
      for (i = 0; i < n; i = i + 1) step(0, 0, 0, 0);
    end
  endtask

  initial begin
    testname = "reset";
    repeat (3) @(negedge clk);
    rst_n = 1;
    idle(2);

    testname = "small_values";
    step(1, {dw}'d3, {dw}'d5, 0);
    step(1, {dw}'d7, {dw}'d9, 0);
    step(1, {dw}'d15, {dw}'d15, 0);
    idle(4);

    // Max-value operands: the full product needs {pw} bits, so a truncated
    // product register cannot pass this test.
    testname = "wide_product";
    step(1, {dw}'d{maxv}, {dw}'d{maxv}, 0);
    step(1, {dw}'d{v1}, {dw}'d{v2}, 0);
    step(1, {dw}'d{maxv}, {dw}'d1, 0);
    idle(4);

    testname = "sync_clear";
    step(0, 0, 0, 1);
    idle(3);
    step(1, {dw}'d{c1}, {dw}'d{c2}, 0);
    idle(4);

    testname = "random";
    for (i = 0; i < 300; i = i + 1)
      step($random, $random, $random, ($random % 23) == 0);
    idle(4);

    // Throughput burst: 256 back-to-back valid MACs, every cycle still
    // checked against the golden model. span_cycles / macs is the measured
    // steady-state initiation interval (cycles per MAC).
    testname = "throughput_burst";
    step(0, 0, 0, 1);
    idle(2);
    profiling = 1;
    vout_count = 0;
    first_vin_cyc = cyc;
    for (i = 0; i < 256; i = i + 1)
      step(1, i, {dw}'d3, 0);
    idle(6);
    profiling = 0;
    $display("TB_PROFILE macs=%0d span_cycles=%0d latency_cycles=%0d",
             vout_count, last_vout_cyc - first_vout_cyc + 1,
             first_vout_cyc - first_vin_cyc);

    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
"""


def render_testbench(spec):
    dw = spec["parameters"]["data_width"]
    aw = spec["parameters"]["acc_width"]
    maxv = (1 << dw) - 1
    return TB_TEMPLATE.format(
        dw=dw, aw=aw, dwm=dw - 1, awm=aw - 1, pwm=2 * dw - 1, pw=2 * dw,
        maxv=maxv, v1=maxv - 1, v2=maxv - 2, c1=12 & maxv, c2=34 & maxv)


def load_model_spec(path=None):
    return json.load(open(path or os.path.join(ROOT, "model_spec.json")))


def generate(ms=None, spec_file="spec_mac.json", tb_file="tb_mac.v"):
    """Write the derived spec and testbench next to the flow inputs and
    return the spec. Called by the flow before every chiplet run, so the
    hardware always tracks the current model spec."""
    ms = ms or load_model_spec()
    spec = derive_chiplet_spec(ms)
    with open(os.path.join(ROOT, spec_file), "w") as f:
        json.dump(spec, f, indent=2)
    with open(os.path.join(ROOT, tb_file), "w") as f:
        f.write(render_testbench(spec))
    return spec


if __name__ == "__main__":
    s = generate()
    print("derived %s from %s: %d x %d bit MAC, %d bit accumulator "
          "(%d guard bits for a %d-deep reduction)"
          % (s["name"], s["derivation"]["model"],
             s["parameters"]["data_width"], s["parameters"]["data_width"],
             s["parameters"]["acc_width"], s["derivation"]["guard_bits"],
             s["derivation"]["reduction_depth"]))
