`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Self-checking testbench for the 16-byte-per-cycle CRC32 fabric endpoint.
// Golden values are computed by Python's zlib.crc32, so a design that
// matches them is wire-compatible with the Ethernet FCS it has to produce.
// Prints machine-parseable TB_FAIL / TB_PROFILE / TB_RESULT lines.
module tb_crc;
  reg clk = 0, rst_n = 0, clear = 0, valid_in = 0;
  reg [127:0] data = 0;
  wire [31:0] crc_out;
  wire valid_out;
  integer checks = 0, i;
  reg [127:0] testname;

  integer cyc = 0;
  integer first_vin_cyc = 0, first_vout_cyc = 0, last_vout_cyc = 0;
  integer vout_count = 0;
  reg profiling = 0;

  crc32 dut (.clk(clk), .rst_n(rst_n), .clear(clear), .data(data),
             .valid_in(valid_in), .crc_out(crc_out), .valid_out(valid_out));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    cyc = cyc + 1;
    if (profiling && valid_out) begin
      if (vout_count == 0) first_vout_cyc = cyc;
      last_vout_cyc = cyc;
      vout_count = vout_count + 1;
    end
  end

  task start_frame;
    begin
      @(negedge clk); clear = 1; valid_in = 0;
      @(negedge clk); clear = 0;
    end
  endtask

  task word(input [127:0] d);
    begin
      @(negedge clk); data = d; valid_in = 1;
    end
  endtask

  // valid_out must be low. Used after reset and between frames, and as the
  // settling check that makes wrong-edge clocking observable.
  task expect_quiet(input [127:0] why);
    begin
      checks = checks + 1;
      if (valid_out !== 1'b0) begin
        $display("TB_FAIL test=%0s expected_vout=0 got_vout=%b",
                 why, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  task expect_crc(input [31:0] want);
    begin
      @(negedge clk); valid_in = 0;
      checks = checks + 1;
      if (crc_out !== want) begin
        $display("TB_FAIL test=%0s expected_crc=%0d got_crc=%0d",
                 testname, want, crc_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  initial begin
    repeat (3) @(negedge clk);
    rst_n = 1;
    @(negedge clk);

    testname = "reset_init";
    expect_quiet(testname);
    word(128'h00000000000000000000000000000000);
    expect_crc(32'hecbb4b55);

    testname = "edge_discipline";
    start_frame;
    @(negedge clk); data = 128'h00000000000000000000000000000000; valid_in = 1;
    #1;
    expect_quiet(testname);
    @(posedge clk); #1;
    checks = checks + 1;
    if (crc_out !== 32'hecbb4b55 || valid_out !== 1'b1) begin
      $display("TB_FAIL test=%0s expected_crc=%0d got_crc=%0d expected_vout=1 got_vout=%b",
               testname, 32'hecbb4b55, crc_out, valid_out);
      $display("TB_RESULT: FAIL");
      $finish;
    end
    @(negedge clk); valid_in = 0;

    testname = "zero_word";
    start_frame;
    word(128'h00000000000000000000000000000000);
    expect_crc(32'hecbb4b55);

    testname = "ascii_word";
    start_frame;
    word(128'h67666564636261393837363534333231);
    expect_crc(32'ha2caafff);

    testname = "two_words";
    start_frame;
    word(128'h650d776f2f0f10d82c3447727d8c0c39);
    word(128'h31c22f34ac6e4f8eaed851038ee570d6);
    expect_crc(32'h8316515f);

    testname = "eight_words";
    start_frame;
    word(128'h289474172362b99628c13feb1687b0b7);
    word(128'hec537d5724886bb5bd53bae88ec23377);
    word(128'hcaff6ca16c2189cda110751ca6708ac2);
    word(128'h4e38182efc4670b9ccdb867e478749ea);
    word(128'he850de9639ae883a0580efc3c520d851);
    word(128'h9db93909faa50052bf4e6598365b8601);
    word(128'h9f666cd88754f3414023f82b287b1d7a);
    word(128'h751e240370750aad20737e3de7e0bfcc);
    expect_crc(32'hce4a6539);

    testname = "clear_reinit";
    start_frame;
    word(128'h00000000000000000000000000000000);
    expect_crc(32'hecbb4b55);

    // Throughput burst: 256 back-to-back words, measuring the steady-state
    // initiation interval in cycles per byte.
    testname = "throughput_burst";
    start_frame;
    profiling = 1;
    vout_count = 0;
    first_vin_cyc = cyc;
    for (i = 0; i < 256; i = i + 1) word(i);
    @(negedge clk); valid_in = 0;
    repeat (4) @(negedge clk);
    profiling = 0;
    $display("TB_PROFILE bytes=%0d span_cycles=%0d latency_cycles=%0d",
             vout_count * 16, last_vout_cyc - first_vout_cyc + 1,
             first_vout_cyc - first_vin_cyc);

    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
