`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Self-checking testbench for the fixed-point exponential. Golden values
// come from the Python fixed-point model, and tests.py separately checks
// that model against math.exp, so a design that merely reproduces its own
// approximation error cannot pass.
module tb_expu;
  reg clk = 0, rst_n = 0, valid_in = 0;
  reg  signed [15:0] x = 0;
  wire        [15:0] y;
  wire valid_out;
  integer checks = 0, i;
  reg [255:0] testname;

  expu dut (.clk(clk), .rst_n(rst_n), .x(x), .valid_in(valid_in),
            .y(y), .valid_out(valid_out));
  always #5 clk = ~clk;

  task expect_quiet;
    begin
      checks = checks + 1;
      if (valid_out !== 1'b0 || y !== 0) begin
        $display("TB_FAIL test=reset_init expected_y=0 got_y=%0d vout=%b",
                 y, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  task drive(input signed [15:0] xi, input [15:0] want);
    begin
      @(negedge clk); x = xi; valid_in = 1;
      @(negedge clk); valid_in = 0;
      repeat (2) @(negedge clk);
      checks = checks + 1;
      if (y !== want || valid_out !== 1'b1) begin
        $display("TB_FAIL test=%0s x=%0d expected_y=%0d got_y=%0d vout=%b",
                 testname, xi, want, y, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  initial begin
    testname = "reset_init";
    repeat (3) @(negedge clk);
    expect_quiet;
    rst_n = 1;
    @(negedge clk);
    expect_quiet;
    testname = "exp";
    drive(16'sd0, 16'd32768);
    drive(-16'sd1, 16'd32591);
    drive(-16'sd256, 16'd12032);
    drive(-16'sd512, 16'd4430);
    drive(-16'sd768, 16'd1631);
    drive(-16'sd128, 16'd19857);
    drive(-16'sd255, 16'd12098);
    drive(-16'sd3840, 16'd0);
    drive(-16'sd4096, 16'd0);
    drive(-16'sd4864, 16'd0);
    drive(-16'sd32768, 16'd0);
    drive(-16'sd2374, 16'd3);
    drive(-16'sd684, 16'd2263);
    drive(-16'sd139, 16'd19015);
    drive(-16'sd2512, 16'd1);
    drive(-16'sd3471, 16'd0);
    drive(-16'sd3106, 16'd0);
    drive(-16'sd4342, 16'd0);
    drive(-16'sd2933, 16'd0);
    drive(-16'sd1067, 16'd506);
    drive(-16'sd1572, 16'd70);
    drive(-16'sd2190, 16'd6);
    drive(-16'sd3641, 16'd0);
    drive(-16'sd115, 16'd20905);
    drive(-16'sd1810, 16'd27);
    drive(-16'sd3727, 16'd0);
    drive(-16'sd202, 16'd14862);
    drive(-16'sd867, 16'd1107);
    drive(-16'sd702, 16'd2109);
    drive(-16'sd4081, 16'd0);
    drive(-16'sd3450, 16'd0);
    drive(-16'sd160, 16'd17531);
    drive(-16'sd4199, 16'd0);
    drive(-16'sd3533, 16'd0);
    drive(-16'sd2940, 16'd0);
    drive(-16'sd471, 16'd5198);
    drive(-16'sd1684, 16'd45);
    drive(-16'sd289, 16'd10595);
    drive(-16'sd3023, 16'd0);
    drive(-16'sd1408, 16'd133);
    drive(-16'sd1769, 16'd32);
    drive(-16'sd2971, 16'd0);
    drive(-16'sd3020, 16'd0);
    drive(-16'sd2304, 16'd4);
    drive(-16'sd2575, 16'd1);
    drive(-16'sd702, 16'd2109);
    drive(-16'sd3883, 16'd0);
    drive(-16'sd1455, 16'd111);
    drive(-16'sd3957, 16'd0);
    drive(-16'sd3665, 16'd0);
    drive(-16'sd1340, 16'd174);
    drive(-16'sd1491, 16'd96);
    drive(-16'sd1462, 16'd108);
    drive(-16'sd2649, 16'd1);
    drive(-16'sd4260, 16'd0);
    drive(-16'sd1602, 16'd62);
    drive(-16'sd936, 16'd844);
    drive(-16'sd674, 16'd2351);
    drive(-16'sd807, 16'd1398);
    drive(-16'sd3490, 16'd0);
    drive(-16'sd318, 16'd9456);
    drive(-16'sd2257, 16'd4);
    drive(-16'sd2298, 16'd4);
    drive(-16'sd2709, 16'd0);
    drive(-16'sd893, 16'd999);
    drive(-16'sd3028, 16'd0);
    drive(-16'sd2363, 16'd3);
    drive(-16'sd2496, 16'd1);
    drive(-16'sd3725, 16'd0);
    drive(-16'sd1788, 16'd30);
    drive(-16'sd2116, 16'd8);
    drive(-16'sd1224, 16'd274);
    drive(-16'sd877, 16'd1063);
    drive(-16'sd978, 16'd718);
    drive(-16'sd4038, 16'd0);
    drive(-16'sd1949, 16'd16);
    drive(-16'sd2689, 16'd0);
    drive(-16'sd1166, 16'd343);
    drive(-16'sd822, 16'd1320);
    drive(-16'sd3137, 16'd0);
    drive(-16'sd1370, 16'd155);
    drive(-16'sd3680, 16'd0);
    drive(-16'sd276, 16'd11124);
    drive(-16'sd458, 16'd5472);
    drive(-16'sd3409, 16'd0);
    drive(-16'sd3222, 16'd0);
    drive(-16'sd191, 16'd15520);
    drive(-16'sd1331, 16'd180);
    drive(-16'sd1848, 16'd23);
    drive(-16'sd104, 16'd21771);
    drive(-16'sd1820, 16'd26);
    drive(-16'sd465, 16'd5326);
    drive(-16'sd3646, 16'd0);
    drive(-16'sd760, 16'd1680);
    drive(-16'sd2835, 16'd0);
    drive(-16'sd130, 16'd19696);
    drive(-16'sd3088, 16'd0);
    drive(-16'sd4018, 16'd0);
    drive(-16'sd1583, 16'd67);
    drive(-16'sd303, 16'd10009);
    drive(-16'sd621, 16'd2896);
    drive(-16'sd2165, 16'd6);
    drive(-16'sd3817, 16'd0);
    drive(-16'sd1610, 16'd60);
    drive(-16'sd3760, 16'd0);
    drive(-16'sd2421, 16'd2);
    drive(-16'sd1769, 16'd32);
    drive(-16'sd750, 16'd1745);
    drive(-16'sd847, 16'd1198);
    drive(-16'sd4333, 16'd0);
    drive(-16'sd1390, 16'd143);
    drive(-16'sd1954, 16'd15);
    drive(-16'sd2073, 16'd9);
    drive(-16'sd819, 16'd1335);
    drive(-16'sd3454, 16'd0);
    drive(-16'sd1351, 16'd166);
    drive(-16'sd96, 16'd22490);
    drive(-16'sd3642, 16'd0);
    drive(-16'sd2808, 16'd0);
    drive(-16'sd3395, 16'd0);
    drive(-16'sd1352, 16'd166);
    drive(-16'sd3380, 16'd0);
    drive(-16'sd569, 16'd3548);
    drive(-16'sd1953, 16'd15);
    drive(-16'sd2418, 16'd2);
    drive(-16'sd3482, 16'd0);
    drive(-16'sd3355, 16'd0);
    drive(-16'sd2448, 16'd2);
    drive(-16'sd422, 16'd6299);
    drive(-16'sd2333, 16'd3);
    drive(-16'sd888, 16'd1018);
    drive(-16'sd207, 16'd14583);
    drive(-16'sd1140, 16'd381);
    drive(-16'sd2723, 16'd0);
    drive(-16'sd3526, 16'd0);
    drive(-16'sd2034, 16'd11);
    drive(-16'sd1354, 16'd165);
    drive(-16'sd643, 16'd2655);
    drive(-16'sd2767, 16'd0);
    drive(-16'sd930, 16'd865);
    drive(-16'sd1925, 16'd17);
    drive(-16'sd3856, 16'd0);
    drive(-16'sd3683, 16'd0);
    drive(-16'sd2229, 16'd5);
    drive(-16'sd32, 16'd28852);
    drive(-16'sd2770, 16'd0);
    drive(-16'sd3089, 16'd0);
    drive(-16'sd193, 16'd15394);
    drive(-16'sd1162, 16'd349);
    drive(-16'sd3291, 16'd0);
    drive(-16'sd1667, 16'd48);

    $display("TB_PROFILE scores=%0d span_cycles=%0d latency_cycles=%0d",
             151, 151 * (2 + 2), 1 + 2);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
