`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Testbench for the gated MLP, with the real matmul sequencer, MAC, SiLU
// unit and requantizer under it. Golden values come from their models.
// The SiLU, up and product buffers are checked directly, in that order,
// before the outputs, because each is upstream of the next.
module tb_gmlp;
  reg clk = 0, rst_n = 0, start = 0, load_valid = 0;
  reg signed [7:0] load_data = 0;
  reg [12:0] depth = 0;
  reg [12:0] cols_ff = 0, cols_out = 0;
  reg [4:0] shift_g = 0;
  reg [17:0] scale_u = 0, scale_h = 0, scale_d = 0;
  reg [6:0] shift_u = 0, shift_h = 0, shift_d = 0;
  wire [13:0] w_addr;
  wire o_valid, busy;
  wire [5:0] o_index;
  wire signed [7:0] o_data;

  reg signed [7:0] acts [0:8-1];
  reg signed [7:0] wmem_tb [0:126-1];
  reg signed [12:0] expect_g [0:6-1];
  reg signed [7:0] expect_u [0:6-1];
  reg signed [7:0] expect_h [0:6-1];
  reg signed [7:0] expect_y [0:5-1];
  reg signed [7:0] w_data;
  integer checks = 0, seen = 0, i, nbad = 0, bad = 0;
  reg [255:0] testname;
  reg [7:0] bad_idx [0:7];
  reg signed [7:0] bad_exp [0:7], bad_got [0:7];
  // Cycles measured, not computed: the profile's cycles_per_unit and
  // latency come from here.
  integer cyc = 0, span = 0, t0 = 0, first_out = -1, lat = 0;
  always @(posedge clk) cyc = cyc + 1;

  always @(posedge clk) w_data <= wmem_tb[w_addr];

  gmlp dut (.clk(clk), .rst_n(rst_n), .load_valid(load_valid),
            .load_data(load_data), .start(start), .depth(depth),
            .cols_ff(cols_ff), .cols_out(cols_out), .shift_g(shift_g),
            .scale_u(scale_u), .shift_u(shift_u), .scale_h(scale_h),
            .shift_h(shift_h), .scale_d(scale_d), .shift_d(shift_d),
            .w_addr(w_addr), .w_data(w_data), .o_valid(o_valid),
            .o_index(o_index), .o_data(o_data), .busy(busy));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    if (rst_n && o_valid) begin
      checks = checks + 1;
      seen = seen + 1;
      if (first_out < 0) begin first_out = cyc; if (cyc - t0 > lat) lat = cyc - t0; end
      if (o_index >= 5) begin
        $display("TB_FAIL test=%0s out=%0d cols_out=5 expected=no_output_past_cols_out got_gy=%0d",
                 testname, o_index, o_data);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      if (o_data !== expect_y[o_index]) begin
        if (nbad < 8) begin
          bad_idx[nbad] = o_index; bad_exp[nbad] = expect_y[o_index];
          bad_got[nbad] = o_data;
        end
        nbad = nbad + 1;
      end
    end
  end

  initial begin
    acts[0] = 8'sd66;
    acts[1] = 8'sd70;
    acts[2] = -8'sd66;
    acts[3] = 8'sd59;
    acts[4] = -8'sd62;
    acts[5] = -8'sd9;
    acts[6] = -8'sd55;
    acts[7] = 8'sd59;
    wmem_tb[0] = 8'sd125;
    wmem_tb[1] = 8'sd125;
    wmem_tb[2] = -8'sd125;
    wmem_tb[3] = 8'sd125;
    wmem_tb[4] = -8'sd125;
    wmem_tb[5] = -8'sd125;
    wmem_tb[6] = -8'sd125;
    wmem_tb[7] = 8'sd125;
    wmem_tb[8] = 8'sd104;
    wmem_tb[9] = -8'sd84;
    wmem_tb[10] = -8'sd25;
    wmem_tb[11] = -8'sd32;
    wmem_tb[12] = -8'sd27;
    wmem_tb[13] = 8'sd26;
    wmem_tb[14] = -8'sd76;
    wmem_tb[15] = -8'sd119;
    wmem_tb[16] = 8'sd24;
    wmem_tb[17] = 8'sd96;
    wmem_tb[18] = 8'sd45;
    wmem_tb[19] = -8'sd106;
    wmem_tb[20] = -8'sd73;
    wmem_tb[21] = -8'sd110;
    wmem_tb[22] = 8'sd55;
    wmem_tb[23] = 8'sd50;
    wmem_tb[24] = 8'sd10;
    wmem_tb[25] = -8'sd47;
    wmem_tb[26] = -8'sd48;
    wmem_tb[27] = -8'sd124;
    wmem_tb[28] = -8'sd44;
    wmem_tb[29] = -8'sd107;
    wmem_tb[30] = -8'sd104;
    wmem_tb[31] = 8'sd95;
    wmem_tb[32] = 8'sd71;
    wmem_tb[33] = -8'sd79;
    wmem_tb[34] = -8'sd121;
    wmem_tb[35] = 8'sd58;
    wmem_tb[36] = 8'sd54;
    wmem_tb[37] = -8'sd67;
    wmem_tb[38] = 8'sd72;
    wmem_tb[39] = -8'sd43;
    wmem_tb[40] = 8'sd36;
    wmem_tb[41] = 8'sd65;
    wmem_tb[42] = -8'sd42;
    wmem_tb[43] = -8'sd104;
    wmem_tb[44] = 8'sd66;
    wmem_tb[45] = 8'sd24;
    wmem_tb[46] = 8'sd90;
    wmem_tb[47] = 8'sd42;
    wmem_tb[48] = 8'sd10;
    wmem_tb[49] = 8'sd10;
    wmem_tb[50] = -8'sd82;
    wmem_tb[51] = -8'sd79;
    wmem_tb[52] = -8'sd118;
    wmem_tb[53] = -8'sd99;
    wmem_tb[54] = 8'sd101;
    wmem_tb[55] = -8'sd124;
    wmem_tb[56] = 8'sd125;
    wmem_tb[57] = 8'sd125;
    wmem_tb[58] = -8'sd125;
    wmem_tb[59] = 8'sd125;
    wmem_tb[60] = -8'sd125;
    wmem_tb[61] = -8'sd125;
    wmem_tb[62] = -8'sd125;
    wmem_tb[63] = 8'sd125;
    wmem_tb[64] = 8'sd31;
    wmem_tb[65] = 8'sd0;
    wmem_tb[66] = -8'sd3;
    wmem_tb[67] = -8'sd54;
    wmem_tb[68] = -8'sd15;
    wmem_tb[69] = 8'sd37;
    wmem_tb[70] = -8'sd84;
    wmem_tb[71] = -8'sd29;
    wmem_tb[72] = 8'sd41;
    wmem_tb[73] = 8'sd69;
    wmem_tb[74] = 8'sd71;
    wmem_tb[75] = 8'sd27;
    wmem_tb[76] = -8'sd104;
    wmem_tb[77] = -8'sd55;
    wmem_tb[78] = -8'sd9;
    wmem_tb[79] = 8'sd7;
    wmem_tb[80] = 8'sd28;
    wmem_tb[81] = 8'sd25;
    wmem_tb[82] = 8'sd8;
    wmem_tb[83] = 8'sd6;
    wmem_tb[84] = 8'sd75;
    wmem_tb[85] = 8'sd77;
    wmem_tb[86] = 8'sd37;
    wmem_tb[87] = 8'sd81;
    wmem_tb[88] = -8'sd25;
    wmem_tb[89] = 8'sd0;
    wmem_tb[90] = 8'sd113;
    wmem_tb[91] = 8'sd113;
    wmem_tb[92] = -8'sd109;
    wmem_tb[93] = 8'sd85;
    wmem_tb[94] = -8'sd13;
    wmem_tb[95] = -8'sd47;
    wmem_tb[96] = -8'sd125;
    wmem_tb[97] = -8'sd125;
    wmem_tb[98] = 8'sd125;
    wmem_tb[99] = 8'sd125;
    wmem_tb[100] = 8'sd125;
    wmem_tb[101] = -8'sd125;
    wmem_tb[102] = 8'sd105;
    wmem_tb[103] = -8'sd69;
    wmem_tb[104] = -8'sd55;
    wmem_tb[105] = -8'sd97;
    wmem_tb[106] = -8'sd46;
    wmem_tb[107] = -8'sd63;
    wmem_tb[108] = 8'sd59;
    wmem_tb[109] = 8'sd25;
    wmem_tb[110] = 8'sd28;
    wmem_tb[111] = -8'sd67;
    wmem_tb[112] = -8'sd69;
    wmem_tb[113] = 8'sd102;
    wmem_tb[114] = 8'sd108;
    wmem_tb[115] = 8'sd44;
    wmem_tb[116] = -8'sd80;
    wmem_tb[117] = -8'sd25;
    wmem_tb[118] = -8'sd125;
    wmem_tb[119] = -8'sd87;
    wmem_tb[120] = -8'sd46;
    wmem_tb[121] = -8'sd93;
    wmem_tb[122] = -8'sd58;
    wmem_tb[123] = -8'sd36;
    wmem_tb[124] = -8'sd43;
    wmem_tb[125] = -8'sd58;
    expect_g[0] = 13'sd1741; expect_u[0] = -8'sd6; expect_h[0] = -8'sd126;
    expect_g[1] = -13'sd10; expect_u[1] = 8'sd126; expect_h[1] = -8'sd15;
    expect_g[2] = 13'sd89; expect_u[2] = 8'sd6; expect_h[2] = 8'sd6;
    expect_g[3] = 13'sd188; expect_u[3] = 8'sd28; expect_h[3] = 8'sd63;
    expect_g[4] = 13'sd22; expect_u[4] = 8'sd2; expect_h[4] = 8'sd1;
    expect_g[5] = -13'sd41; expect_u[5] = 8'sd3; expect_h[5] = -8'sd1;
    expect_y[0] = 8'sd126;
    expect_y[1] = -8'sd89;
    expect_y[2] = -8'sd57;
    expect_y[3] = -8'sd78;
    expect_y[4] = 8'sd22;
    testname = "gated_layer";
    repeat (3) @(negedge clk);
    rst_n = 1;
    @(negedge clk);
    for (i = 0; i < 8; i = i + 1) begin
      load_data = acts[i]; load_valid = 1;
      @(negedge clk);
    end
    load_valid = 0;
    depth = 8; cols_ff = 6; cols_out = 5;
    shift_g = 5; scale_u = 75836; shift_u = 25;
    scale_h = 101183; shift_h = 23; scale_d = 79770; shift_d = 24;
    @(negedge clk);
    start = 1;
      t0 = cyc; first_out = -1;
    @(negedge clk);
    start = 0;
    while (busy) @(negedge clk);
      span = span + (cyc - t0);
    repeat (8) @(negedge clk);
    for (i = 0; i < 6; i = i + 1) begin
      checks = checks + 1;
      if (dut.gbuf[i] !== expect_g[i]) begin
        $display("TB_FAIL test=%0s hidden=%0d expected_gs=%0d got_gs=%0d",
                 testname, i, expect_g[i], dut.gbuf[i]);
        bad = bad + 1;
      end
    end
    for (i = 0; i < 6; i = i + 1) begin
      checks = checks + 1;
      if (dut.ubuf[i] !== expect_u[i]) begin
        $display("TB_FAIL test=%0s hidden=%0d expected_u=%0d got_u=%0d",
                 testname, i, expect_u[i], dut.ubuf[i]);
        bad = bad + 1;
      end
    end
    for (i = 0; i < 6; i = i + 1) begin
      checks = checks + 1;
      if (dut.hbuf[i] !== expect_h[i]) begin
        $display("TB_FAIL test=%0s hidden=%0d expected_gh=%0d got_gh=%0d",
                 testname, i, expect_h[i], dut.hbuf[i]);
        bad = bad + 1;
      end
    end
    for (i = 0; i < nbad && i < 8; i = i + 1)
      $display("TB_FAIL test=%0s out=%0d expected_gy=%0d got_gy=%0d",
               testname, bad_idx[i], bad_exp[i], bad_got[i]);
    checks = checks + 1;
    if (!bad && !nbad && seen !== 5)
      $display("TB_FAIL test=output_count out=0 expected_gy_count=5 got_gy_count=%0d",
               seen);
    if (bad || nbad || seen !== 5) begin
      $display("TB_RESULT: FAIL");
      $finish;
    end
    $display("TB_PROFILE layers=%0d span_cycles=%0d latency_cycles=%0d",
             1, span, lat);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
