`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Testbench for the MLP layer sequencer, with the real matmul
// sequencer, the real MAC and the real requantizer under it. Golden
// values come from the shared requantization model, so the layer is
// checked against the arithmetic its parts are specified to do.
module tb_mlp;
  reg clk = 0, rst_n = 0, start = 0, load_valid = 0;
  reg signed [7:0] load_data = 0;
  reg [12:0] depth1 = 0;
  reg [12:0] cols1 = 0, cols2 = 0;
  reg [17:0] scale1 = 0, scale2 = 0;
  reg [6:0] shift1 = 0, shift2 = 0;
  wire [12:0] w_addr;
  wire o_valid, busy;
  wire [5:0] o_index;
  wire signed [7:0] o_data;

  reg signed [7:0] acts [0:8-1];
  reg signed [7:0] wmem_tb [0:78-1];
  reg signed [7:0] expect_y [0:5-1];
  reg signed [7:0] expect_h [0:6-1];
  integer nbad = 0, hbad = 0;
  reg [7:0] bad_idx [0:7];
  reg signed [7:0] bad_exp [0:7], bad_got [0:7];
  reg signed [7:0] w_data;
  integer checks = 0, seen = 0, i;
  reg [255:0] testname;

  always @(posedge clk) w_data <= wmem_tb[w_addr];

  mlp dut (.clk(clk), .rst_n(rst_n), .load_valid(load_valid),
           .load_data(load_data), .start(start), .depth1(depth1),
           .cols1(cols1), .cols2(cols2), .scale1(scale1),
           .shift1(shift1), .scale2(scale2), .shift2(shift2),
           .w_addr(w_addr), .w_data(w_data), .o_valid(o_valid),
           .o_index(o_index), .o_data(o_data), .busy(busy));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    if (rst_n && o_valid) begin
      checks = checks + 1;
      seen = seen + 1;
      if (o_index >= 5) begin
        $display("TB_FAIL test=%0s out=%0d cols2=%0d expected=no_output_past_cols2 got_y=%0d",
                 testname, o_index, 5, o_data);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      if (o_data !== expect_y[o_index]) begin
        // Held, not reported yet: a wrong hidden layer makes every output
        // wrong, and the hidden check below names the cause.
        if (nbad < 8) begin
          bad_idx[nbad] = o_index; bad_exp[nbad] = expect_y[o_index];
          bad_got[nbad] = o_data;
        end
        nbad = nbad + 1;
      end
    end
  end

  initial begin
    acts[0] = 8'sd1;
    acts[1] = -8'sd79;
    acts[2] = 8'sd17;
    acts[3] = -8'sd70;
    acts[4] = 8'sd82;
    acts[5] = 8'sd107;
    acts[6] = -8'sd43;
    acts[7] = -8'sd50;
    wmem_tb[0] = 8'sd125;
    wmem_tb[1] = -8'sd125;
    wmem_tb[2] = 8'sd125;
    wmem_tb[3] = -8'sd125;
    wmem_tb[4] = 8'sd125;
    wmem_tb[5] = 8'sd125;
    wmem_tb[6] = -8'sd125;
    wmem_tb[7] = -8'sd125;
    wmem_tb[8] = -8'sd22;
    wmem_tb[9] = -8'sd7;
    wmem_tb[10] = -8'sd41;
    wmem_tb[11] = 8'sd124;
    wmem_tb[12] = -8'sd83;
    wmem_tb[13] = -8'sd40;
    wmem_tb[14] = 8'sd36;
    wmem_tb[15] = -8'sd124;
    wmem_tb[16] = 8'sd103;
    wmem_tb[17] = 8'sd3;
    wmem_tb[18] = 8'sd51;
    wmem_tb[19] = -8'sd102;
    wmem_tb[20] = 8'sd37;
    wmem_tb[21] = -8'sd81;
    wmem_tb[22] = -8'sd39;
    wmem_tb[23] = -8'sd119;
    wmem_tb[24] = -8'sd15;
    wmem_tb[25] = 8'sd81;
    wmem_tb[26] = -8'sd89;
    wmem_tb[27] = -8'sd93;
    wmem_tb[28] = 8'sd61;
    wmem_tb[29] = -8'sd22;
    wmem_tb[30] = -8'sd50;
    wmem_tb[31] = 8'sd106;
    wmem_tb[32] = -8'sd51;
    wmem_tb[33] = 8'sd63;
    wmem_tb[34] = 8'sd91;
    wmem_tb[35] = -8'sd38;
    wmem_tb[36] = -8'sd13;
    wmem_tb[37] = -8'sd44;
    wmem_tb[38] = 8'sd33;
    wmem_tb[39] = -8'sd30;
    wmem_tb[40] = 8'sd69;
    wmem_tb[41] = 8'sd84;
    wmem_tb[42] = 8'sd35;
    wmem_tb[43] = 8'sd35;
    wmem_tb[44] = -8'sd80;
    wmem_tb[45] = 8'sd75;
    wmem_tb[46] = 8'sd57;
    wmem_tb[47] = 8'sd32;
    wmem_tb[48] = 8'sd125;
    wmem_tb[49] = 8'sd125;
    wmem_tb[50] = 8'sd125;
    wmem_tb[51] = 8'sd125;
    wmem_tb[52] = 8'sd125;
    wmem_tb[53] = 8'sd125;
    wmem_tb[54] = -8'sd111;
    wmem_tb[55] = 8'sd13;
    wmem_tb[56] = -8'sd31;
    wmem_tb[57] = -8'sd2;
    wmem_tb[58] = -8'sd122;
    wmem_tb[59] = 8'sd13;
    wmem_tb[60] = -8'sd27;
    wmem_tb[61] = -8'sd104;
    wmem_tb[62] = 8'sd92;
    wmem_tb[63] = -8'sd47;
    wmem_tb[64] = -8'sd124;
    wmem_tb[65] = -8'sd17;
    wmem_tb[66] = -8'sd80;
    wmem_tb[67] = -8'sd98;
    wmem_tb[68] = -8'sd6;
    wmem_tb[69] = -8'sd37;
    wmem_tb[70] = 8'sd57;
    wmem_tb[71] = -8'sd109;
    wmem_tb[72] = -8'sd25;
    wmem_tb[73] = -8'sd70;
    wmem_tb[74] = -8'sd96;
    wmem_tb[75] = 8'sd34;
    wmem_tb[76] = -8'sd35;
    wmem_tb[77] = 8'sd32;
    expect_y[0] = 8'sd126;
    expect_y[1] = -8'sd100;
    expect_y[2] = -8'sd9;
    expect_y[3] = -8'sd70;
    expect_y[4] = -8'sd36;
    expect_h[0] = 8'sd126;
    expect_h[1] = 8'sd0;
    expect_h[2] = 8'sd22;
    expect_h[3] = 8'sd0;
    expect_h[4] = 8'sd0;
    expect_h[5] = 8'sd0;
    testname = "layer";
    repeat (3) @(negedge clk);
    rst_n = 1;
    @(negedge clk);
    for (i = 0; i < 8; i = i + 1) begin
      load_data = acts[i]; load_valid = 1;
      @(negedge clk);
    end
    load_valid = 0;
    depth1 = 8; cols1 = 6; cols2 = 5;
    scale1 = 75329; shift1 = 25; scale2 = 114266; shift2 = 24;
    @(negedge clk);
    start = 1;
    @(negedge clk);
    start = 0;
    while (busy) @(negedge clk);
    repeat (8) @(negedge clk);
    // Whitebox check of the hidden layer, which the spec places in act at
    // 64..64+cols1-1. Reported before the outputs because it is
    // upstream of them: traced, a draft whose writeback was wrong sat for
    // six iterations on "output 0 wrong" and never looked at layer one.
    for (i = 0; i < 6; i = i + 1) begin
      checks = checks + 1;
      if (dut.act[64 + i] !== expect_h[i]) begin
        $display("TB_FAIL test=hidden_layer h_index=%0d expected_h=%0d got_h=%0d",
                 i, expect_h[i], dut.act[64 + i]);
        hbad = hbad + 1;
      end
    end
    for (i = 0; i < nbad && i < 8; i = i + 1)
      $display("TB_FAIL test=%0s out=%0d expected_y=%0d got_y=%0d",
               testname, bad_idx[i], bad_exp[i], bad_got[i]);
    if (hbad || nbad) begin
      $display("TB_RESULT: FAIL");
      $finish;
    end
    checks = checks + 1;
    if (seen !== 5) begin
      $display("TB_FAIL test=%0s out=0 expected_y=%0d got_y=%0d",
               "output_count", 5, seen);
      $display("TB_RESULT: FAIL");
      $finish;
    end
    $display("TB_PROFILE layers=%0d span_cycles=%0d latency_cycles=%0d",
             1, 8 * 6 + 6 * 5, 16);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
