`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Integration testbench: the weight-streaming sequencer driving the real
// generated MAC. Golden dot products are computed in Python, so this
// checks the pair against the arithmetic the model needs rather than
// against either block's own idea of itself.
module tb_matvec;
  reg clk = 0, rst_n = 0, start = 0;
  reg  [12:0] depth = 0;
  reg  [12:0] cols = 0;
  wire [12:0] a_addr;
  wire [25:0] w_addr;
  wire mac_valid, mac_clear, col_valid, busy;
  wire [12:0] col_index;

  reg signed [7:0] amem [0:68-1];
  reg signed [7:0] wmem [0:8296-1];
  reg signed [28:0] expect_col [0:122-1];

  // Block RAM: the read is registered, so data lands a cycle after the
  // address. An asynchronous model here would hide an off-by-one in the
  // sequencer's valid, which is the bug this block is most prone to.
  reg signed [7:0] a_data, w_data;
  always @(posedge clk) begin
    a_data <= amem[a_addr];
    w_data <= wmem[w_addr];
  end

  wire signed [28:0] acc;
  wire mac_vout;
  integer checks = 0, seen = 0, i;
  reg [255:0] testname;

  matvec seq (.clk(clk), .rst_n(rst_n), .start(start), .depth(depth),
              .cols(cols), .a_addr(a_addr), .w_addr(w_addr),
              .mac_valid(mac_valid), .mac_clear(mac_clear),
              .col_valid(col_valid), .col_index(col_index), .busy(busy));

  mac dut (.clk(clk), .rst_n(rst_n), .clear(mac_clear),
           .a(a_data), .b(w_data), .valid_in(mac_valid),
           .acc(acc), .valid_out(mac_vout));

  always #5 clk = ~clk;

  // Every flagged column is checked the moment it is flagged.
  always @(posedge clk) begin
    if (rst_n && col_valid) begin
      checks = checks + 1;
      seen = seen + 1;
      if (acc !== expect_col[col_index]) begin
        $display("TB_FAIL test=%0s col=%0d expected_acc=%0d got_acc=%0d",
                 testname, col_index, expect_col[col_index], acc);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  end

  initial begin
    // Filled by formula, matching the Python golden exactly.
    for (i = 0; i < 68; i = i + 1)
      amem[i] = (i * 104729 + 7) % 251 - 125;
    for (i = 0; i < 8296; i = i + 1)
      wmem[i] = (i * 7919 + 13) % 251 - 125;
    expect_col[0] = -29'sd12280;
    expect_col[1] = -29'sd91261;
    expect_col[2] = -29'sd31690;
    expect_col[3] = -29'sd69256;
    expect_col[4] = -29'sd24745;
    expect_col[5] = 29'sd17005;
    expect_col[6] = -29'sd12278;
    expect_col[7] = 29'sd17424;
    expect_col[8] = 29'sd50138;
    expect_col[9] = 29'sd3034;
    expect_col[10] = 29'sd49302;
    expect_col[11] = 29'sd17509;
    expect_col[12] = 29'sd20605;
    expect_col[13] = 29'sd31231;
    expect_col[14] = -29'sd11355;
    expect_col[15] = -29'sd30598;
    expect_col[16] = -29'sd68164;
    expect_col[17] = -29'sd44988;
    expect_col[18] = -29'sd7756;
    expect_col[19] = -29'sd11186;
    expect_col[20] = 29'sd11237;
    expect_col[21] = 29'sd8560;
    expect_col[22] = -29'sd9930;
    expect_col[23] = 29'sd50394;
    expect_col[24] = 29'sd31402;
    expect_col[25] = 29'sd41275;
    expect_col[26] = 29'sd32323;
    expect_col[27] = -29'sd10263;
    expect_col[28] = 29'sd30734;
    expect_col[29] = -29'sd11350;
    expect_col[30] = -29'sd43896;
    expect_col[31] = -29'sd28752;
    expect_col[32] = -29'sd92171;
    expect_col[33] = 29'sd13835;
    expect_col[34] = 29'sd9652;
    expect_col[35] = -29'sd25655;
    expect_col[36] = 29'sd16095;
    expect_col[37] = 29'sd15426;
    expect_col[38] = 29'sd42367;
    expect_col[39] = 29'sd49228;
    expect_col[40] = 29'sd2124;
    expect_col[41] = 29'sd31826;
    expect_col[42] = 29'sd15846;
    expect_col[43] = 29'sd19695;
    expect_col[44] = 29'sd7229;
    expect_col[45] = -29'sd91079;
    expect_col[46] = -29'sd31508;
    expect_col[47] = -29'sd69074;
    expect_col[48] = 29'sd6561;
    expect_col[49] = 29'sd17187;
    expect_col[50] = -29'sd12096;
    expect_col[51] = 29'sd10327;
    expect_col[52] = 29'sd50320;
    expect_col[53] = 29'sd3216;
    expect_col[54] = 29'sd49484;
    expect_col[55] = 29'sd22209;
    expect_col[56] = 29'sd20787;
    expect_col[57] = 29'sd31413;
    expect_col[58] = -29'sd11173;
    expect_col[59] = -29'sd14101;
    expect_col[60] = -29'sd67982;
    expect_col[61] = -29'sd44806;
    expect_col[62] = -29'sd29662;
    expect_col[63] = -29'sd11004;
    expect_col[64] = 29'sd11419;
    expect_col[65] = 29'sd8742;
    expect_col[66] = -29'sd20039;
    expect_col[67] = 29'sd50576;
    expect_col[68] = 29'sd31584;
    expect_col[69] = 29'sd41457;
    expect_col[70] = 29'sd34011;
    expect_col[71] = -29'sd10081;
    expect_col[72] = 29'sd30916;
    expect_col[73] = 29'sd14936;
    expect_col[74] = -29'sd43714;
    expect_col[75] = -29'sd28570;
    expect_col[76] = -29'sd91989;
    expect_col[77] = -29'sd11083;
    expect_col[78] = 29'sd9834;
    expect_col[79] = -29'sd25473;
    expect_col[80] = 29'sd16277;
    expect_col[81] = 29'sd2305;
    expect_col[82] = 29'sd42549;
    expect_col[83] = 29'sd49410;
    expect_col[84] = 29'sd2306;
    expect_col[85] = 29'sd30502;
    expect_col[86] = 29'sd16028;
    expect_col[87] = 29'sd19877;
    expect_col[88] = 29'sd30503;
    expect_col[89] = -29'sd90897;
    expect_col[90] = -29'sd31326;
    expect_col[91] = -29'sd68892;
    expect_col[92] = -29'sd21369;
    expect_col[93] = 29'sd17369;
    expect_col[94] = -29'sd11914;
    expect_col[95] = 29'sd10509;
    expect_col[96] = 29'sd34187;
    expect_col[97] = 29'sd3398;
    expect_col[98] = 29'sd49666;
    expect_col[99] = 29'sd30674;
    expect_col[100] = 29'sd20969;
    expect_col[101] = 29'sd31595;
    expect_col[102] = -29'sd10991;
    expect_col[103] = 29'sd6161;
    expect_col[104] = -29'sd67800;
    expect_col[105] = -29'sd44624;
    expect_col[106] = -29'sd29480;
    expect_col[107] = -29'sd41946;
    expect_col[108] = 29'sd11601;
    expect_col[109] = 29'sd8924;
    expect_col[110] = -29'sd26383;
    expect_col[111] = 29'sd50758;
    expect_col[112] = 29'sd31766;
    expect_col[113] = 29'sd41639;
    expect_col[114] = 29'sd39464;
    expect_col[115] = -29'sd9899;
    expect_col[116] = 29'sd31098;
    expect_col[117] = 29'sd15118;
    expect_col[118] = -29'sd26464;
    expect_col[119] = -29'sd28388;
    expect_col[120] = -29'sd91807;
    expect_col[121] = -29'sd32236;
    testname = "matvec";
    repeat (3) @(negedge clk);
    rst_n = 1;
    depth = 68;
    cols = 122;
    @(negedge clk);
    start = 1;
    @(negedge clk);
    start = 0;
    // Generous bound: depth+drain per column, plus slack.
    for (i = 0; i < 122 * (68 + 10) + 60; i = i + 1)
      @(negedge clk);
    checks = checks + 1;
    if (seen !== 122) begin
      $display("TB_FAIL test=%0s expected_acc=%0d got_acc=%0d",
               "column_count", 122, seen);
      $display("TB_RESULT: FAIL");
      $finish;
    end
    checks = checks + 1;
    if (busy !== 1'b0) begin
      $display("TB_FAIL test=%0s expected_acc=0 got_acc=1",
               "busy_deasserts");
      $display("TB_RESULT: FAIL");
      $finish;
    end
    $display("TB_PROFILE columns=%0d span_cycles=%0d latency_cycles=%0d",
             122, 122 * 68, 68);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
