`timescale 1ns/1ps
// GENERATED by specgen.py from the model spec: do not edit by hand.
// Self-checking testbench for the 8-bit MAC with a 28-bit accumulator:
// golden pipeline mirror plus directed and random stimulus, machine-parseable
// TB_FAIL / TB_RESULT lines for the agent, and a final back-to-back burst
// that measures steady-state throughput (span cycles per MAC) and pipeline
// latency, printed as a TB_PROFILE line so the flow derives cycles_per_mac
// from simulation instead of hardcoding it.
module tb_mac;
  reg clk = 0, rst_n = 0, clear = 0, valid_in = 0;
  reg  signed [7:0] a = 0, b = 0;
  wire signed [27:0] acc;
  wire valid_out;
  integer checks = 0, i;
  reg  signed [27:0] m_acc;
  reg  signed [15:0] m_prod;
  reg m_vpipe, m_vout;
  reg [255:0] testname;

  // Throughput profiling state
  integer cyc = 0;
  integer first_vin_cyc = 0, first_vout_cyc = 0, last_vout_cyc = 0;
  integer vout_count = 0;
  reg profiling = 0;

  mac dut (.clk(clk), .rst_n(rst_n), .clear(clear), .a(a), .b(b),
           .valid_in(valid_in), .acc(acc), .valid_out(valid_out));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    cyc = cyc + 1;
    if (profiling && valid_out) begin
      if (vout_count == 0) first_vout_cyc = cyc;
      last_vout_cyc = cyc;
      vout_count = vout_count + 1;
    end
  end

  // Golden model: full-width SIGNED product, sign-extended into the
  // accumulator, synchronous clear with priority. Signed matters: the
  // quantized weights are two's complement, so an unsigned multiplier
  // computes a large positive product for every negative weight.
  always @(posedge clk) begin
    if (!rst_n) begin
      m_prod <= 0; m_vpipe <= 0; m_acc <= 0; m_vout <= 0;
    end else begin
      m_prod  <= a * b;
      m_vpipe <= valid_in;
      if (clear) begin
        m_acc <= 0; m_vout <= 0;
      end else begin
        if (m_vpipe) m_acc <= m_acc + m_prod;
        m_vout <= m_vpipe;
      end
    end
  end

  task check;
    begin
      checks = checks + 1;
      if (acc !== m_acc || valid_out !== m_vout) begin
        $display("TB_FAIL test=%0s expected_acc=%0d got_acc=%0d expected_vout=%b got_vout=%b",
                 testname, m_acc, acc, m_vout, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  // One clock of stimulus: check state from prior edge, then drive new inputs.
  task step(input v, input signed [7:0] ai,
            input signed [7:0] bi, input c);
    begin
      @(negedge clk);
      check;
      valid_in = v; a = ai; b = bi; clear = c;
    end
  endtask

  task idle(input integer n);
    begin
      for (i = 0; i < n; i = i + 1) step(0, 0, 0, 0);
    end
  endtask

  initial begin
    testname = "reset";
    repeat (3) @(negedge clk);
    rst_n = 1;
    idle(2);

    testname = "small_values";
    step(1, 8'sd3, 8'sd5, 0);
    step(1, 8'sd7, 8'sd9, 0);
    step(1, 8'sd15, 8'sd15, 0);
    idle(4);

    // Negative operands. An unsigned multiplier reads -1 as 255 and
    // produces a large positive product, so it cannot pass this test, and
    // an accumulator that is not sign-extended cannot either.
    testname = "signed_operands";
    step(1, -8'sd1, 8'sd1, 0);
    step(1, 8'sd1, -8'sd1, 0);
    step(1, -8'sd1, -8'sd1, 0);
    step(1, -8'sd128, 8'sd3, 0);
    idle(4);

    // Extreme-magnitude operands: the full product needs 16 bits, so a
    // truncated product register cannot pass this test. -128 * -128
    // is the largest signed magnitude product.
    testname = "wide_product";
    step(1, -8'sd128, -8'sd128, 0);
    step(1, 8'sd127, 8'sd127, 0);
    step(1, -8'sd128, 8'sd127, 0);
    idle(4);

    testname = "sync_clear";
    step(0, 0, 0, 1);
    idle(3);
    step(1, 8'sd12, -8'sd34, 0);
    idle(4);

    // Accumulating past zero: the running sum has to go negative and come
    // back, which a truncated or unsigned accumulator gets wrong.
    testname = "clear_then_negative";
    step(0, 0, 0, 1);
    idle(2);
    step(1, -8'sd128, 8'sd127, 0);
    step(1, -8'sd128, 8'sd127, 0);
    step(1, 8'sd127, 8'sd127, 0);
    step(1, 8'sd127, 8'sd127, 0);
    idle(4);

    testname = "random";
    for (i = 0; i < 300; i = i + 1)
      step($random, $random, $random, ($random % 23) == 0);
    idle(4);

    // Throughput burst: 256 back-to-back valid MACs, every cycle still
    // checked against the golden model. span_cycles / macs is the measured
    // steady-state initiation interval (cycles per MAC).
    testname = "throughput_burst";
    step(0, 0, 0, 1);
    idle(2);
    profiling = 1;
    vout_count = 0;
    first_vin_cyc = cyc;
    for (i = 0; i < 256; i = i + 1)
      step(1, i, 8'd3, 0);
    idle(6);
    profiling = 0;
    $display("TB_PROFILE macs=%0d span_cycles=%0d latency_cycles=%0d",
             vout_count, last_vout_cyc - first_vout_cyc + 1,
             first_vout_cyc - first_vin_cyc);

    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
