`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Integration testbench: the weight-streaming sequencer driving the real
// generated MAC. Golden dot products are computed in Python, so this
// checks the pair against the arithmetic the model needs rather than
// against either block's own idea of itself.
module tb_matvec;
  reg clk = 0, rst_n = 0, start = 0;
  reg  [11:0] depth = 0;
  reg  [11:0] cols = 0;
  wire [11:0] a_addr;
  wire [23:0] w_addr;
  wire mac_valid, mac_clear, col_valid, busy;
  wire [11:0] col_index;

  reg signed [7:0] amem [0:68-1];
  reg signed [7:0] wmem [0:4216-1];
  reg signed [27:0] expect_col [0:62-1];

  // Block RAM: the read is registered, so data lands a cycle after the
  // address. An asynchronous model here would hide an off-by-one in the
  // sequencer's valid, which is the bug this block is most prone to.
  reg signed [7:0] a_data, w_data;
  always @(posedge clk) begin
    a_data <= amem[a_addr];
    w_data <= wmem[w_addr];
  end

  wire signed [27:0] acc;
  wire mac_vout;
  integer checks = 0, seen = 0, i;
  reg [255:0] testname;

  matvec seq (.clk(clk), .rst_n(rst_n), .start(start), .depth(depth),
              .cols(cols), .a_addr(a_addr), .w_addr(w_addr),
              .mac_valid(mac_valid), .mac_clear(mac_clear),
              .col_valid(col_valid), .col_index(col_index), .busy(busy));

  mac dut (.clk(clk), .rst_n(rst_n), .clear(mac_clear),
           .a(a_data), .b(w_data), .valid_in(mac_valid),
           .acc(acc), .valid_out(mac_vout));

  always #5 clk = ~clk;

  // Every flagged column is checked the moment it is flagged.
  always @(posedge clk) begin
    if (rst_n && col_valid) begin
      checks = checks + 1;
      seen = seen + 1;
      if (acc !== expect_col[col_index]) begin
        $display("TB_FAIL test=%0s col=%0d expected_acc=%0d got_acc=%0d",
                 testname, col_index, expect_col[col_index], acc);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  end

  initial begin
    // Filled by formula, matching the Python golden exactly.
    for (i = 0; i < 68; i = i + 1)
      amem[i] = (i * 104729 + 7) % 251 - 125;
    for (i = 0; i < 4216; i = i + 1)
      wmem[i] = (i * 7919 + 13) % 251 - 125;
    expect_col[0] = -28'sd12280;
    expect_col[1] = -28'sd91261;
    expect_col[2] = -28'sd31690;
    expect_col[3] = -28'sd69256;
    expect_col[4] = -28'sd24745;
    expect_col[5] = 28'sd17005;
    expect_col[6] = -28'sd12278;
    expect_col[7] = 28'sd17424;
    expect_col[8] = 28'sd50138;
    expect_col[9] = 28'sd3034;
    expect_col[10] = 28'sd49302;
    expect_col[11] = 28'sd17509;
    expect_col[12] = 28'sd20605;
    expect_col[13] = 28'sd31231;
    expect_col[14] = -28'sd11355;
    expect_col[15] = -28'sd30598;
    expect_col[16] = -28'sd68164;
    expect_col[17] = -28'sd44988;
    expect_col[18] = -28'sd7756;
    expect_col[19] = -28'sd11186;
    expect_col[20] = 28'sd11237;
    expect_col[21] = 28'sd8560;
    expect_col[22] = -28'sd9930;
    expect_col[23] = 28'sd50394;
    expect_col[24] = 28'sd31402;
    expect_col[25] = 28'sd41275;
    expect_col[26] = 28'sd32323;
    expect_col[27] = -28'sd10263;
    expect_col[28] = 28'sd30734;
    expect_col[29] = -28'sd11350;
    expect_col[30] = -28'sd43896;
    expect_col[31] = -28'sd28752;
    expect_col[32] = -28'sd92171;
    expect_col[33] = 28'sd13835;
    expect_col[34] = 28'sd9652;
    expect_col[35] = -28'sd25655;
    expect_col[36] = 28'sd16095;
    expect_col[37] = 28'sd15426;
    expect_col[38] = 28'sd42367;
    expect_col[39] = 28'sd49228;
    expect_col[40] = 28'sd2124;
    expect_col[41] = 28'sd31826;
    expect_col[42] = 28'sd15846;
    expect_col[43] = 28'sd19695;
    expect_col[44] = 28'sd7229;
    expect_col[45] = -28'sd91079;
    expect_col[46] = -28'sd31508;
    expect_col[47] = -28'sd69074;
    expect_col[48] = 28'sd6561;
    expect_col[49] = 28'sd17187;
    expect_col[50] = -28'sd12096;
    expect_col[51] = 28'sd10327;
    expect_col[52] = 28'sd50320;
    expect_col[53] = 28'sd3216;
    expect_col[54] = 28'sd49484;
    expect_col[55] = 28'sd22209;
    expect_col[56] = 28'sd20787;
    expect_col[57] = 28'sd31413;
    expect_col[58] = -28'sd11173;
    expect_col[59] = -28'sd14101;
    expect_col[60] = -28'sd67982;
    expect_col[61] = -28'sd44806;
    testname = "matvec";
    repeat (3) @(negedge clk);
    rst_n = 1;
    depth = 68;
    cols = 62;
    @(negedge clk);
    start = 1;
    @(negedge clk);
    start = 0;
    // Generous bound: depth+drain per column, plus slack.
    for (i = 0; i < 62 * (68 + 10) + 60; i = i + 1)
      @(negedge clk);
    checks = checks + 1;
    if (seen !== 62) begin
      $display("TB_FAIL test=%0s expected_acc=%0d got_acc=%0d",
               "column_count", 62, seen);
      $display("TB_RESULT: FAIL");
      $finish;
    end
    checks = checks + 1;
    if (busy !== 1'b0) begin
      $display("TB_FAIL test=%0s expected_acc=0 got_acc=1",
               "busy_deasserts");
      $display("TB_RESULT: FAIL");
      $finish;
    end
    $display("TB_PROFILE columns=%0d span_cycles=%0d latency_cycles=%0d",
             62, 62 * 68, 68);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
