`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Testbench for the full-size projection. Activations and weights are a
// hash of their address, computed here and in specgen.proj_x/proj_w the
// same way, so a projection of any size needs no memory initializer.
module tb_proj;
  reg clk = 0, rst_n = 0, start = 0;
  reg [12:0] depth = 0;
  reg [12:0] cols = 0;
  reg [17:0] scale = 0;
  reg [6:0] shift = 0;
  reg [31:0] seed = 0;
  wire [12:0] a_addr;
  wire [25:0] w_addr;
  wire o_valid, busy;
  wire [12:0] o_index;
  wire signed [7:0] o_data;
  reg signed [7:0] a_data, w_data;
  reg signed [7:0] expect_y [0:130-1];
  reg [130-1:0] seen_bits;
  integer checks = 0, seen = 0, nbad = 0;
  reg [255:0] testname;
  // Cycles measured, not computed: the profile's cycles_per_unit and
  // latency come from here.
  integer cyc = 0, span = 0, t0 = 0, first_out = -1, lat = 0;
  always @(posedge clk) cyc = cyc + 1;

  function signed [7:0] hx(input [31:0] i, input [31:0] s);
    reg [31:0] h;
    begin
      h = i * 32'd2246822519 + s * 32'd97 + 32'd7;
      hx = h[16 + 8 - 1:16];
    end
  endfunction
  function signed [7:0] hw(input [31:0] i, input [31:0] s);
    reg [31:0] h;
    begin
      h = i * 32'd2654435761 + s * 32'd131 + 32'd12345;
      hw = h[13 + 8 - 1:13];
    end
  endfunction

  always @(posedge clk) begin
    a_data <= hx(a_addr, seed);
    w_data <= hw(w_addr, seed);
  end

  proj dut (.clk(clk), .rst_n(rst_n), .start(start), .depth(depth),
            .cols(cols), .scale(scale), .shift(shift), .a_addr(a_addr),
            .a_data(a_data), .w_addr(w_addr), .w_data(w_data),
            .o_valid(o_valid), .o_index(o_index), .o_data(o_data),
            .busy(busy));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    if (rst_n && o_valid) begin
      checks = checks + 1;
      seen = seen + 1;
      if (first_out < 0) begin first_out = cyc; if (cyc - t0 > lat) lat = cyc - t0; end
      if (o_index >= cols || seen_bits[o_index]) begin
        $display("TB_FAIL test=%0s out=%0d cols=%0d expected=each_index_once got_proj=%0d",
                 testname, o_index, cols, o_data);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      seen_bits[o_index] = 1'b1;
      if (o_data !== expect_y[o_index] && nbad < 4) begin
        $display("TB_FAIL test=%0s out=%0d expected_proj=%0d got_proj=%0d",
                 testname, o_index, expect_y[o_index], o_data);
        nbad = nbad + 1;
      end
    end
  end

  task run_proj(input integer d, input integer c, input integer s,
                input integer sc, input integer sh);
    begin
      seen = 0; nbad = 0; seen_bits = 0;
      depth = d; cols = c; seed = s; scale = sc; shift = sh;
      @(negedge clk); start = 1;
      t0 = cyc; first_out = -1;
      @(negedge clk); start = 0;
      while (busy) @(negedge clk);
      span = span + (cyc - t0);
      repeat (8) @(negedge clk);
      checks = checks + 1;
      if (!nbad && seen !== c)
        $display("TB_FAIL test=%0s out=0 expected_count=%0d got_count=%0d",
                 testname, c, seen);
      if (nbad || seen !== c) begin
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  initial begin
    testname = "projection";
    repeat (3) @(negedge clk);
    rst_n = 1;
    @(negedge clk);
    // depth 16, cols 8
    expect_y[0] = -8'sd86;
    expect_y[1] = -8'sd126;
    expect_y[2] = -8'sd105;
    expect_y[3] = 8'sd58;
    expect_y[4] = -8'sd87;
    expect_y[5] = -8'sd91;
    expect_y[6] = -8'sd93;
    expect_y[7] = 8'sd70;
    run_proj(16, 8, 1, 115219, 24);
    // depth 100, cols 40
    expect_y[0] = 8'sd24;
    expect_y[1] = -8'sd15;
    expect_y[2] = -8'sd14;
    expect_y[3] = 8'sd29;
    expect_y[4] = -8'sd37;
    expect_y[5] = 8'sd80;
    expect_y[6] = -8'sd53;
    expect_y[7] = -8'sd71;
    expect_y[8] = 8'sd108;
    expect_y[9] = -8'sd22;
    expect_y[10] = -8'sd44;
    expect_y[11] = 8'sd32;
    expect_y[12] = 8'sd24;
    expect_y[13] = -8'sd17;
    expect_y[14] = 8'sd11;
    expect_y[15] = -8'sd52;
    expect_y[16] = 8'sd27;
    expect_y[17] = 8'sd16;
    expect_y[18] = -8'sd86;
    expect_y[19] = 8'sd87;
    expect_y[20] = -8'sd80;
    expect_y[21] = 8'sd51;
    expect_y[22] = 8'sd49;
    expect_y[23] = 8'sd3;
    expect_y[24] = -8'sd54;
    expect_y[25] = 8'sd51;
    expect_y[26] = -8'sd18;
    expect_y[27] = -8'sd18;
    expect_y[28] = 8'sd24;
    expect_y[29] = -8'sd40;
    expect_y[30] = 8'sd126;
    expect_y[31] = -8'sd55;
    expect_y[32] = -8'sd22;
    expect_y[33] = 8'sd58;
    expect_y[34] = -8'sd26;
    expect_y[35] = 8'sd22;
    expect_y[36] = 8'sd29;
    expect_y[37] = -8'sd20;
    expect_y[38] = -8'sd9;
    expect_y[39] = 8'sd8;
    run_proj(100, 40, 2, 125223, 26);
    // depth 7, cols 130
    expect_y[0] = -8'sd55;
    expect_y[1] = 8'sd100;
    expect_y[2] = 8'sd14;
    expect_y[3] = 8'sd19;
    expect_y[4] = -8'sd66;
    expect_y[5] = -8'sd32;
    expect_y[6] = -8'sd87;
    expect_y[7] = -8'sd21;
    expect_y[8] = -8'sd46;
    expect_y[9] = 8'sd48;
    expect_y[10] = 8'sd53;
    expect_y[11] = -8'sd33;
    expect_y[12] = 8'sd1;
    expect_y[13] = -8'sd84;
    expect_y[14] = 8'sd12;
    expect_y[15] = -8'sd13;
    expect_y[16] = 8'sd82;
    expect_y[17] = 8'sd86;
    expect_y[18] = 8'sd1;
    expect_y[19] = 8'sd35;
    expect_y[20] = -8'sd50;
    expect_y[21] = 8'sd46;
    expect_y[22] = -8'sd40;
    expect_y[23] = 8'sd115;
    expect_y[24] = 8'sd30;
    expect_y[25] = 8'sd35;
    expect_y[26] = -8'sd50;
    expect_y[27] = -8'sd17;
    expect_y[28] = -8'sd70;
    expect_y[29] = -8'sd6;
    expect_y[30] = -8'sd30;
    expect_y[31] = 8'sd64;
    expect_y[32] = 8'sd68;
    expect_y[33] = -8'sd17;
    expect_y[34] = 8'sd17;
    expect_y[35] = -8'sd68;
    expect_y[36] = 8'sd28;
    expect_y[37] = -8'sd57;
    expect_y[38] = 8'sd97;
    expect_y[39] = 8'sd12;
    expect_y[40] = 8'sd17;
    expect_y[41] = -8'sd68;
    expect_y[42] = -8'sd34;
    expect_y[43] = -8'sd89;
    expect_y[44] = -8'sd24;
    expect_y[45] = -8'sd49;
    expect_y[46] = 8'sd46;
    expect_y[47] = 8'sd50;
    expect_y[48] = -8'sd35;
    expect_y[49] = -8'sd1;
    expect_y[50] = -8'sd55;
    expect_y[51] = 8'sd10;
    expect_y[52] = -8'sd15;
    expect_y[53] = 8'sd79;
    expect_y[54] = 8'sd84;
    expect_y[55] = -8'sd1;
    expect_y[56] = 8'sd32;
    expect_y[57] = -8'sd52;
    expect_y[58] = 8'sd43;
    expect_y[59] = -8'sd41;
    expect_y[60] = 8'sd113;
    expect_y[61] = 8'sd28;
    expect_y[62] = 8'sd32;
    expect_y[63] = -8'sd53;
    expect_y[64] = -8'sd19;
    expect_y[65] = -8'sd73;
    expect_y[66] = -8'sd8;
    expect_y[67] = -8'sd33;
    expect_y[68] = 8'sd62;
    expect_y[69] = 8'sd66;
    expect_y[70] = -8'sd19;
    expect_y[71] = 8'sd15;
    expect_y[72] = -8'sd71;
    expect_y[73] = 8'sd25;
    expect_y[74] = -8'sd60;
    expect_y[75] = 8'sd95;
    expect_y[76] = 8'sd10;
    expect_y[77] = 8'sd14;
    expect_y[78] = -8'sd70;
    expect_y[79] = -8'sd37;
    expect_y[80] = -8'sd91;
    expect_y[81] = -8'sd26;
    expect_y[82] = -8'sd51;
    expect_y[83] = 8'sd43;
    expect_y[84] = 8'sd48;
    expect_y[85] = -8'sd37;
    expect_y[86] = -8'sd3;
    expect_y[87] = -8'sd57;
    expect_y[88] = 8'sd8;
    expect_y[89] = -8'sd17;
    expect_y[90] = 8'sd77;
    expect_y[91] = 8'sd82;
    expect_y[92] = -8'sd4;
    expect_y[93] = 8'sd30;
    expect_y[94] = -8'sd55;
    expect_y[95] = 8'sd41;
    expect_y[96] = -8'sd44;
    expect_y[97] = 8'sd111;
    expect_y[98] = 8'sd25;
    expect_y[99] = 8'sd30;
    expect_y[100] = -8'sd55;
    expect_y[101] = -8'sd21;
    expect_y[102] = -8'sd75;
    expect_y[103] = -8'sd11;
    expect_y[104] = -8'sd35;
    expect_y[105] = 8'sd59;
    expect_y[106] = 8'sd63;
    expect_y[107] = -8'sd21;
    expect_y[108] = 8'sd13;
    expect_y[109] = -8'sd72;
    expect_y[110] = 8'sd23;
    expect_y[111] = -8'sd62;
    expect_y[112] = 8'sd92;
    expect_y[113] = 8'sd7;
    expect_y[114] = 8'sd12;
    expect_y[115] = -8'sd73;
    expect_y[116] = -8'sd39;
    expect_y[117] = -8'sd93;
    expect_y[118] = -8'sd28;
    expect_y[119] = 8'sd126;
    expect_y[120] = 8'sd41;
    expect_y[121] = 8'sd46;
    expect_y[122] = -8'sd40;
    expect_y[123] = -8'sd5;
    expect_y[124] = -8'sd60;
    expect_y[125] = 8'sd5;
    expect_y[126] = -8'sd19;
    expect_y[127] = 8'sd74;
    expect_y[128] = 8'sd79;
    expect_y[129] = -8'sd6;
    run_proj(7, 130, 3, 96319, 24);
    // depth 3, cols 60
    expect_y[0] = -8'sd69;
    expect_y[1] = 8'sd73;
    expect_y[2] = 8'sd12;
    expect_y[3] = -8'sd50;
    expect_y[4] = -8'sd8;
    expect_y[5] = -8'sd70;
    expect_y[6] = 8'sd72;
    expect_y[7] = 8'sd10;
    expect_y[8] = -8'sd52;
    expect_y[9] = -8'sd9;
    expect_y[10] = -8'sd71;
    expect_y[11] = 8'sd71;
    expect_y[12] = 8'sd8;
    expect_y[13] = -8'sd53;
    expect_y[14] = -8'sd10;
    expect_y[15] = -8'sd72;
    expect_y[16] = 8'sd70;
    expect_y[17] = 8'sd7;
    expect_y[18] = -8'sd54;
    expect_y[19] = -8'sd12;
    expect_y[20] = -8'sd74;
    expect_y[21] = 8'sd68;
    expect_y[22] = 8'sd6;
    expect_y[23] = -8'sd55;
    expect_y[24] = -8'sd13;
    expect_y[25] = -8'sd75;
    expect_y[26] = 8'sd67;
    expect_y[27] = 8'sd5;
    expect_y[28] = -8'sd56;
    expect_y[29] = -8'sd15;
    expect_y[30] = -8'sd76;
    expect_y[31] = 8'sd66;
    expect_y[32] = 8'sd4;
    expect_y[33] = -8'sd58;
    expect_y[34] = -8'sd16;
    expect_y[35] = 8'sd126;
    expect_y[36] = 8'sd64;
    expect_y[37] = 8'sd2;
    expect_y[38] = -8'sd59;
    expect_y[39] = -8'sd17;
    expect_y[40] = 8'sd125;
    expect_y[41] = 8'sd63;
    expect_y[42] = 8'sd1;
    expect_y[43] = -8'sd60;
    expect_y[44] = -8'sd18;
    expect_y[45] = 8'sd124;
    expect_y[46] = 8'sd62;
    expect_y[47] = 8'sd0;
    expect_y[48] = -8'sd61;
    expect_y[49] = -8'sd20;
    expect_y[50] = 8'sd122;
    expect_y[51] = 8'sd60;
    expect_y[52] = -8'sd1;
    expect_y[53] = -8'sd63;
    expect_y[54] = -8'sd21;
    expect_y[55] = 8'sd121;
    expect_y[56] = 8'sd59;
    expect_y[57] = -8'sd2;
    expect_y[58] = -8'sd64;
    expect_y[59] = -8'sd22;
    run_proj(3, 60, 4, 81205, 22);
    // depth 128, cols 129
    expect_y[0] = 8'sd51;
    expect_y[1] = 8'sd17;
    expect_y[2] = 8'sd40;
    expect_y[3] = 8'sd12;
    expect_y[4] = -8'sd58;
    expect_y[5] = 8'sd2;
    expect_y[6] = -8'sd126;
    expect_y[7] = 8'sd1;
    expect_y[8] = -8'sd57;
    expect_y[9] = 8'sd12;
    expect_y[10] = 8'sd76;
    expect_y[11] = 8'sd14;
    expect_y[12] = 8'sd85;
    expect_y[13] = 8'sd9;
    expect_y[14] = 8'sd7;
    expect_y[15] = -8'sd1;
    expect_y[16] = -8'sd42;
    expect_y[17] = -8'sd3;
    expect_y[18] = 8'sd47;
    expect_y[19] = 8'sd9;
    expect_y[20] = 8'sd42;
    expect_y[21] = 8'sd49;
    expect_y[22] = 8'sd51;
    expect_y[23] = -8'sd4;
    expect_y[24] = -8'sd63;
    expect_y[25] = -8'sd27;
    expect_y[26] = -8'sd61;
    expect_y[27] = -8'sd6;
    expect_y[28] = 8'sd44;
    expect_y[29] = -8'sd33;
    expect_y[30] = 8'sd39;
    expect_y[31] = 8'sd27;
    expect_y[32] = 8'sd48;
    expect_y[33] = -8'sd7;
    expect_y[34] = -8'sd67;
    expect_y[35] = -8'sd10;
    expect_y[36] = -8'sd64;
    expect_y[37] = 8'sd30;
    expect_y[38] = 8'sd40;
    expect_y[39] = -8'sd35;
    expect_y[40] = 8'sd35;
    expect_y[41] = 8'sd50;
    expect_y[42] = 8'sd44;
    expect_y[43] = 8'sd43;
    expect_y[44] = -8'sd41;
    expect_y[45] = 8'sd48;
    expect_y[46] = 8'sd26;
    expect_y[47] = -8'sd59;
    expect_y[48] = -8'sd14;
    expect_y[49] = -8'sd64;
    expect_y[50] = -8'sd54;
    expect_y[51] = 8'sd47;
    expect_y[52] = -8'sd26;
    expect_y[53] = 8'sd40;
    expect_y[54] = -8'sd91;
    expect_y[55] = 8'sd44;
    expect_y[56] = -8'sd6;
    expect_y[57] = -8'sd63;
    expect_y[58] = -8'sd26;
    expect_y[59] = -8'sd67;
    expect_y[60] = 8'sd2;
    expect_y[61] = 8'sd43;
    expect_y[62] = 8'sd56;
    expect_y[63] = 8'sd36;
    expect_y[64] = 8'sd15;
    expect_y[65] = 8'sd41;
    expect_y[66] = 8'sd5;
    expect_y[67] = -8'sd46;
    expect_y[68] = 8'sd4;
    expect_y[69] = -8'sd22;
    expect_y[70] = 8'sd15;
    expect_y[71] = 8'sd51;
    expect_y[72] = 8'sd17;
    expect_y[73] = 8'sd40;
    expect_y[74] = 8'sd11;
    expect_y[75] = -8'sd58;
    expect_y[76] = 8'sd1;
    expect_y[77] = -8'sd126;
    expect_y[78] = 8'sd0;
    expect_y[79] = -8'sd57;
    expect_y[80] = 8'sd11;
    expect_y[81] = 8'sd42;
    expect_y[82] = 8'sd14;
    expect_y[83] = 8'sd56;
    expect_y[84] = 8'sd8;
    expect_y[85] = -8'sd16;
    expect_y[86] = -8'sd2;
    expect_y[87] = -8'sd58;
    expect_y[88] = -8'sd3;
    expect_y[89] = 8'sd47;
    expect_y[90] = 8'sd9;
    expect_y[91] = 8'sd42;
    expect_y[92] = 8'sd49;
    expect_y[93] = 8'sd50;
    expect_y[94] = -8'sd4;
    expect_y[95] = -8'sd64;
    expect_y[96] = -8'sd27;
    expect_y[97] = -8'sd62;
    expect_y[98] = -8'sd5;
    expect_y[99] = 8'sd44;
    expect_y[100] = -8'sd91;
    expect_y[101] = 8'sd39;
    expect_y[102] = -8'sd24;
    expect_y[103] = 8'sd48;
    expect_y[104] = -8'sd52;
    expect_y[105] = -8'sd67;
    expect_y[106] = -8'sd49;
    expect_y[107] = -8'sd64;
    expect_y[108] = 8'sd30;
    expect_y[109] = 8'sd40;
    expect_y[110] = -8'sd36;
    expect_y[111] = 8'sd36;
    expect_y[112] = 8'sd50;
    expect_y[113] = 8'sd44;
    expect_y[114] = 8'sd42;
    expect_y[115] = -8'sd41;
    expect_y[116] = 8'sd48;
    expect_y[117] = 8'sd26;
    expect_y[118] = -8'sd59;
    expect_y[119] = -8'sd14;
    expect_y[120] = -8'sd64;
    expect_y[121] = -8'sd6;
    expect_y[122] = 8'sd47;
    expect_y[123] = 8'sd28;
    expect_y[124] = 8'sd40;
    expect_y[125] = -8'sd31;
    expect_y[126] = 8'sd44;
    expect_y[127] = -8'sd7;
    expect_y[128] = -8'sd62;
    run_proj(128, 129, 5, 125005, 26);

    $display("TB_PROFILE projections=%0d span_cycles=%0d latency_cycles=%0d",
             5, span, lat);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
