`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Self-checking testbench for the RMSNorm inverse square root. Golden
// values come from the Python fixed-point model; tests.py separately
// checks that model against true 1/sqrt.
module tb_rsqrt;
  reg clk = 0, rst_n = 0, valid_in = 0;
  reg  [27:0] x = 0;
  wire [16:0] y;
  wire [4:0] e;
  wire valid_out;
  integer checks = 0;
  reg [255:0] testname;

  rsqrt dut (.clk(clk), .rst_n(rst_n), .x(x), .valid_in(valid_in),
             .y(y), .e(e), .valid_out(valid_out));
  always #5 clk = ~clk;

  task expect_idle;
    begin
      checks = checks + 1;
      if (valid_out !== 1'b0 || y !== 0 || e !== 0) begin
        $display("TB_FAIL test=reset_init expected_y=0 got_y=%0d vout=%b",
                 y, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  task drive(input [27:0] xi, input [16:0] want,
             input [4:0] wante);
    begin
      @(negedge clk); x = xi; valid_in = 1;
      @(negedge clk); valid_in = 0;
      repeat (2) @(negedge clk);
      checks = checks + 1;
      if (y !== want || e !== wante || valid_out !== 1'b1) begin
        $display("TB_FAIL test=%0s x=%0d expected_y=%0d got_y=%0d expected_e=%0d got_e=%0d vout=%b",
                 testname, xi, want, y, wante, e, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  initial begin
    testname = "reset_init";
    repeat (3) @(negedge clk);
    expect_idle;
    rst_n = 1;
    @(negedge clk);
    expect_idle;
    testname = "rsqrt";
    drive(28'd1, 17'd131071, 5'd0);
    drive(28'd2, 17'd92682, 5'd0);
    drive(28'd3, 17'd75674, 5'd0);
    drive(28'd4, 17'd131071, 5'd1);
    drive(28'd5, 17'd117234, 5'd1);
    drive(28'd1024, 17'd131071, 5'd5);
    drive(28'd1031, 17'd131071, 5'd5);
    drive(28'd134217728, 17'd92682, 5'd13);
    drive(28'd268435455, 17'd65664, 5'd13);
    drive(28'd183074206, 17'd79492, 5'd13);
    drive(28'd163143460, 17'd84224, 5'd13);
    drive(28'd24589387, 17'd108732, 5'd12);
    drive(28'd251071309, 17'd67827, 5'd13);
    drive(28'd165843813, 17'd83420, 5'd13);
    drive(28'd178625762, 17'd80422, 5'd13);
    drive(28'd226001153, 17'd71512, 5'd13);
    drive(28'd200469266, 17'd75872, 5'd13);
    drive(28'd224022888, 17'd71847, 5'd13);
    drive(28'd170302740, 17'd82384, 5'd13);
    drive(28'd138249019, 17'd91615, 5'd13);
    drive(28'd9513871, 17'd87079, 5'd11);
    drive(28'd169392963, 17'd82639, 5'd13);
    drive(28'd264067626, 17'd66186, 5'd13);
    drive(28'd99114380, 17'd108152, 5'd13);
    drive(28'd117505458, 17'd99081, 5'd13);
    drive(28'd141738919, 17'd90247, 5'd13);
    drive(28'd211825403, 17'd73778, 5'd13);
    drive(28'd28952557, 17'd99978, 5'd12);
    drive(28'd263740042, 17'd66186, 5'd13);
    drive(28'd183327977, 17'd79492, 5'd13);
    drive(28'd122636186, 17'd97358, 5'd13);
    drive(28'd161240685, 17'd84772, 5'd13);
    drive(28'd213550491, 17'd73596, 5'd13);
    drive(28'd75678538, 17'd123576, 5'd13);
    drive(28'd248375480, 17'd68256, 5'd13);
    drive(28'd101622373, 17'd107020, 5'd13);
    drive(28'd261205592, 17'd66451, 5'd13);
    drive(28'd197603806, 17'd76475, 5'd13);
    drive(28'd113609675, 17'd100899, 5'd13);
    drive(28'd119152446, 17'd98642, 5'd13);
    drive(28'd38761481, 17'd86485, 5'd12);
    drive(28'd257594976, 17'd66991, 5'd13);
    drive(28'd214796549, 17'd73415, 5'd13);
    drive(28'd260719538, 17'd66585, 5'd13);
    drive(28'd242372585, 17'd68991, 5'd13);
    drive(28'd225046250, 17'd71679, 5'd13);
    drive(28'd13290627, 17'd73778, 5'd11);
    drive(28'd24435009, 17'd108732, 5'd12);
    drive(28'd110892553, 17'd102331, 5'd13);
    drive(28'd20173631, 17'd120280, 5'd12);
    drive(28'd145940025, 17'd88939, 5'd13);
    drive(28'd77466710, 17'd122727, 5'd13);
    drive(28'd249565168, 17'd67969, 5'd13);
    drive(28'd96933940, 17'd109322, 5'd13);
    drive(28'd174008139, 17'd81632, 5'd13);
    drive(28'd189234352, 17'd78156, 5'd13);
    drive(28'd116058450, 17'd99978, 5'd13);
    drive(28'd221965645, 17'd72187, 5'd13);
    drive(28'd157783949, 17'd85616, 5'd13);
    drive(28'd151028324, 17'd87381, 5'd13);
    drive(28'd98290488, 17'd108732, 5'd13);
    drive(28'd171581545, 17'd82131, 5'd13);
    drive(28'd189295970, 17'd78156, 5'd13);
    drive(28'd153834927, 17'd86781, 5'd13);
    drive(28'd260497719, 17'd66585, 5'd13);
    drive(28'd9141997, 17'd88939, 5'd11);
    drive(28'd216652302, 17'd73058, 5'd13);
    drive(28'd141375123, 17'd90583, 5'd13);
    drive(28'd166268751, 17'd83420, 5'd13);
    drive(28'd57242201, 17'd71019, 5'd12);
    drive(28'd135612737, 17'd92322, 5'd13);
    drive(28'd111927611, 17'd101847, 5'd13);
    drive(28'd16917316, 17'd131071, 5'd12);
    drive(28'd2357950, 17'd87686, 5'd10);
    drive(28'd2034334, 17'd94165, 5'd10);
    drive(28'd176035000, 17'd81141, 5'd13);
    drive(28'd136936348, 17'd91966, 5'd13);
    drive(28'd244336168, 17'd68694, 5'd13);
    drive(28'd96877736, 17'd109322, 5'd13);
    drive(28'd18417600, 17'd125329, 5'd12);
    drive(28'd189826103, 17'd77940, 5'd13);
    drive(28'd155710481, 17'd86192, 5'd13);
    drive(28'd60360378, 17'd69141, 5'd12);
    drive(28'd6303150, 17'd107020, 5'd11);
    drive(28'd86947062, 17'd115796, 5'd13);
    drive(28'd94455192, 17'd110530, 5'd13);
    drive(28'd141600077, 17'd90247, 5'd13);
    drive(28'd42757957, 17'd82131, 5'd12);
    drive(28'd220356497, 17'd72359, 5'd13);
    drive(28'd231010710, 17'd70695, 5'd13);
    drive(28'd5825271, 17'd111779, 5'd11);
    drive(28'd195428201, 17'd76885, 5'd13);
    drive(28'd3625209, 17'd70535, 5'd10);
    drive(28'd240661827, 17'd69292, 5'd13);
    drive(28'd252912686, 17'd67545, 5'd13);
    drive(28'd58509296, 17'd70218, 5'd12);
    drive(28'd197527241, 17'd76475, 5'd13);
    drive(28'd192978116, 17'd77302, 5'd13);
    drive(28'd83634943, 17'd117974, 5'd13);
    drive(28'd187769804, 17'd78374, 5'd13);
    drive(28'd61001229, 17'd68842, 5'd12);
    drive(28'd137085421, 17'd91966, 5'd13);
    drive(28'd174328898, 17'd81385, 5'd13);
    drive(28'd245938905, 17'd68548, 5'd13);
    drive(28'd80991037, 17'd119496, 5'd13);
    drive(28'd167752362, 17'd83157, 5'd13);
    drive(28'd11292935, 17'd79953, 5'd11);
    drive(28'd75915725, 17'd123576, 5'd13);
    drive(28'd73177252, 17'd126234, 5'd13);
    drive(28'd192493140, 17'd77513, 5'd13);
    drive(28'd54652912, 17'd72706, 5'd12);
    drive(28'd129181026, 17'd94547, 5'd13);
    drive(28'd38425187, 17'd86781, 5'd12);
    drive(28'd57185484, 17'd71019, 5'd12);
    drive(28'd71508002, 17'd127159, 5'd13);
    drive(28'd165840760, 17'd83420, 5'd13);
    drive(28'd170371354, 17'd82384, 5'd13);
    drive(28'd12961764, 17'd74708, 5'd11);
    drive(28'd117777316, 17'd99081, 5'd13);
    drive(28'd120545395, 17'd98208, 5'd13);
    drive(28'd28177768, 17'd101370, 5'd12);
    drive(28'd149455823, 17'd87995, 5'd13);
    drive(28'd174142742, 17'd81385, 5'd13);
    drive(28'd681338, 17'd81385, 5'd9);
    drive(28'd71605845, 17'd127159, 5'd13);
    drive(28'd174099189, 17'd81385, 5'd13);
    drive(28'd64193688, 17'd67128, 5'd12);
    drive(28'd23675124, 17'd110530, 5'd12);
    drive(28'd119006569, 17'd98642, 5'd13);
    drive(28'd1, 17'd131071, 5'd0);
    drive(28'd2, 17'd92682, 5'd0);
    drive(28'd3, 17'd75674, 5'd0);
    drive(28'd3, 17'd75674, 5'd0);
    drive(28'd4, 17'd131071, 5'd1);
    drive(28'd5, 17'd117234, 5'd1);
    drive(28'd7, 17'd99081, 5'd1);
    drive(28'd8, 17'd92682, 5'd1);
    drive(28'd9, 17'd87381, 5'd1);
    drive(28'd15, 17'd67685, 5'd1);
    drive(28'd16, 17'd131071, 5'd2);
    drive(28'd17, 17'd127159, 5'd2);
    drive(28'd31, 17'd94165, 5'd2);
    drive(28'd32, 17'd92682, 5'd2);
    drive(28'd33, 17'd91267, 5'd2);
    drive(28'd63, 17'd66054, 5'd2);
    drive(28'd64, 17'd131071, 5'd3);
    drive(28'd65, 17'd130060, 5'd3);
    drive(28'd127, 17'd93046, 5'd3);
    drive(28'd128, 17'd92682, 5'd3);
    drive(28'd129, 17'd92322, 5'd3);
    drive(28'd255, 17'd65664, 5'd3);
    drive(28'd256, 17'd131071, 5'd4);
    drive(28'd257, 17'd131071, 5'd4);
    drive(28'd511, 17'd93046, 5'd4);
    drive(28'd512, 17'd92682, 5'd4);
    drive(28'd513, 17'd92682, 5'd4);
    drive(28'd1023, 17'd65664, 5'd4);
    drive(28'd1024, 17'd131071, 5'd5);
    drive(28'd1025, 17'd131071, 5'd5);
    drive(28'd2047, 17'd93046, 5'd5);
    drive(28'd2048, 17'd92682, 5'd5);
    drive(28'd2049, 17'd92682, 5'd5);
    drive(28'd4095, 17'd65664, 5'd5);
    drive(28'd4096, 17'd131071, 5'd6);
    drive(28'd4097, 17'd131071, 5'd6);
    drive(28'd8191, 17'd93046, 5'd6);
    drive(28'd8192, 17'd92682, 5'd6);
    drive(28'd8193, 17'd92682, 5'd6);
    drive(28'd16383, 17'd65664, 5'd6);
    drive(28'd16384, 17'd131071, 5'd7);
    drive(28'd16385, 17'd131071, 5'd7);
    drive(28'd32767, 17'd93046, 5'd7);
    drive(28'd32768, 17'd92682, 5'd7);
    drive(28'd32769, 17'd92682, 5'd7);
    drive(28'd65535, 17'd65664, 5'd7);
    drive(28'd65536, 17'd131071, 5'd8);
    drive(28'd65537, 17'd131071, 5'd8);
    drive(28'd131071, 17'd93046, 5'd8);
    drive(28'd131072, 17'd92682, 5'd8);
    drive(28'd131073, 17'd92682, 5'd8);
    drive(28'd262143, 17'd65664, 5'd8);
    drive(28'd262144, 17'd131071, 5'd9);
    drive(28'd262145, 17'd131071, 5'd9);
    drive(28'd524287, 17'd93046, 5'd9);
    drive(28'd524288, 17'd92682, 5'd9);
    drive(28'd524289, 17'd92682, 5'd9);
    drive(28'd1048575, 17'd65664, 5'd9);
    drive(28'd1048576, 17'd131071, 5'd10);
    drive(28'd1048577, 17'd131071, 5'd10);
    drive(28'd2097151, 17'd93046, 5'd10);
    drive(28'd2097152, 17'd92682, 5'd10);
    drive(28'd2097153, 17'd92682, 5'd10);
    drive(28'd4194303, 17'd65664, 5'd10);
    drive(28'd4194304, 17'd131071, 5'd11);
    drive(28'd4194305, 17'd131071, 5'd11);
    drive(28'd8388607, 17'd93046, 5'd11);
    drive(28'd8388608, 17'd92682, 5'd11);
    drive(28'd8388609, 17'd92682, 5'd11);
    drive(28'd16777215, 17'd65664, 5'd11);
    drive(28'd16777216, 17'd131071, 5'd12);
    drive(28'd16777217, 17'd131071, 5'd12);
    drive(28'd33554431, 17'd93046, 5'd12);
    drive(28'd33554432, 17'd92682, 5'd12);
    drive(28'd33554433, 17'd92682, 5'd12);
    drive(28'd67108863, 17'd65664, 5'd12);
    drive(28'd67108864, 17'd131071, 5'd13);
    drive(28'd67108865, 17'd131071, 5'd13);
    drive(28'd134217727, 17'd93046, 5'd13);
    drive(28'd134217728, 17'd92682, 5'd13);
    drive(28'd134217729, 17'd92682, 5'd13);

    $display("TB_PROFILE rows=%0d span_cycles=%0d latency_cycles=%0d",
             210, 210 * (2 + 2), 1 + 2);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
