`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Testbench for the residual add. Pairs stream one per cycle with gaps
// and are checked in order off valid_out.
module tb_resadd;
  reg clk = 0, rst_n = 0, valid_in = 0;
  reg signed [7:0] a = 0, b = 0;
  reg [17:0] scale_a = 574, scale_b = 1851;
  reg [6:0] shift = 12;
  wire signed [7:0] y;
  wire valid_out;
  reg signed [7:0] as_ [0:214-1];
  reg signed [7:0] bs_ [0:214-1];
  reg signed [7:0] ys [0:214-1];
  integer checks = 0, got = 0, i;

  resadd dut (.clk(clk), .rst_n(rst_n), .a(a), .b(b), .scale_a(scale_a),
              .scale_b(scale_b), .shift(shift), .valid_in(valid_in),
              .y(y), .valid_out(valid_out));
  always #5 clk = ~clk;

  always @(posedge clk) begin
    if (rst_n && valid_out) begin
      checks = checks + 1;
      if (got >= 214) begin
        $display("TB_FAIL test=resadd idx=%0d expected=no_more_outputs got_res=%0d", got, y);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      if (y !== ys[got]) begin
        $display("TB_FAIL test=resadd idx=%0d a=%0d b=%0d expected_res=%0d got_res=%0d",
                 got, as_[got], bs_[got], ys[got], y);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      got = got + 1;
    end
  end

  initial begin
    as_[0] = 8'sd0; bs_[0] = 8'sd0; ys[0] = 8'sd0;
    as_[1] = 8'sd127; bs_[1] = 8'sd127; ys[1] = 8'sd75;
    as_[2] = -8'sd128; bs_[2] = -8'sd128; ys[2] = -8'sd76;
    as_[3] = 8'sd127; bs_[3] = -8'sd128; ys[3] = -8'sd40;
    as_[4] = 8'sd1; bs_[4] = 8'sd0; ys[4] = 8'sd0;
    as_[5] = -8'sd1; bs_[5] = 8'sd0; ys[5] = 8'sd0;
    as_[6] = 8'sd0; bs_[6] = 8'sd1; ys[6] = 8'sd0;
    as_[7] = 8'sd0; bs_[7] = -8'sd1; ys[7] = 8'sd0;
    as_[8] = 8'sd63; bs_[8] = 8'sd90; ys[8] = 8'sd50;
    as_[9] = 8'sd49; bs_[9] = 8'sd70; ys[9] = 8'sd39;
    as_[10] = -8'sd7; bs_[10] = -8'sd10; ys[10] = -8'sd5;
    as_[11] = 8'sd118; bs_[11] = -8'sd124; ys[11] = -8'sd39;
    as_[12] = 8'sd21; bs_[12] = 8'sd30; ys[12] = 8'sd17;
    as_[13] = -8'sd21; bs_[13] = -8'sd30; ys[13] = -8'sd16;
    as_[14] = -8'sd78; bs_[14] = 8'sd124; ys[14] = 8'sd45;
    as_[15] = 8'sd3; bs_[15] = -8'sd19; ys[15] = -8'sd8;
    as_[16] = -8'sd26; bs_[16] = -8'sd128; ys[16] = -8'sd61;
    as_[17] = 8'sd89; bs_[17] = 8'sd116; ys[17] = 8'sd65;
    as_[18] = -8'sd104; bs_[18] = 8'sd24; ys[18] = -8'sd4;
    as_[19] = 8'sd124; bs_[19] = -8'sd38; ys[19] = 8'sd0;
    as_[20] = 8'sd23; bs_[20] = -8'sd64; ys[20] = -8'sd26;
    as_[21] = -8'sd20; bs_[21] = 8'sd116; ys[21] = 8'sd50;
    as_[22] = -8'sd40; bs_[22] = 8'sd80; ys[22] = 8'sd31;
    as_[23] = -8'sd67; bs_[23] = -8'sd8; ys[23] = -8'sd13;
    as_[24] = 8'sd51; bs_[24] = -8'sd100; ys[24] = -8'sd38;
    as_[25] = -8'sd107; bs_[25] = -8'sd43; ys[25] = -8'sd34;
    as_[26] = 8'sd41; bs_[26] = 8'sd38; ys[26] = 8'sd23;
    as_[27] = -8'sd117; bs_[27] = -8'sd16; ys[27] = -8'sd24;
    as_[28] = 8'sd1; bs_[28] = 8'sd58; ys[28] = 8'sd26;
    as_[29] = -8'sd117; bs_[29] = 8'sd118; ys[29] = 8'sd37;
    as_[30] = -8'sd58; bs_[30] = -8'sd34; ys[30] = -8'sd23;
    as_[31] = 8'sd52; bs_[31] = 8'sd49; ys[31] = 8'sd29;
    as_[32] = -8'sd47; bs_[32] = 8'sd55; ys[32] = 8'sd18;
    as_[33] = 8'sd75; bs_[33] = 8'sd41; ys[33] = 8'sd29;
    as_[34] = -8'sd2; bs_[34] = 8'sd2; ys[34] = 8'sd1;
    as_[35] = -8'sd67; bs_[35] = 8'sd115; ys[35] = 8'sd43;
    as_[36] = 8'sd77; bs_[36] = 8'sd96; ys[36] = 8'sd54;
    as_[37] = 8'sd92; bs_[37] = 8'sd25; ys[37] = 8'sd24;
    as_[38] = 8'sd78; bs_[38] = -8'sd95; ys[38] = -8'sd32;
    as_[39] = -8'sd37; bs_[39] = -8'sd84; ys[39] = -8'sd43;
    as_[40] = -8'sd32; bs_[40] = 8'sd9; ys[40] = 8'sd0;
    as_[41] = -8'sd34; bs_[41] = -8'sd106; ys[41] = -8'sd53;
    as_[42] = -8'sd69; bs_[42] = 8'sd38; ys[42] = 8'sd8;
    as_[43] = -8'sd99; bs_[43] = -8'sd111; ys[43] = -8'sd64;
    as_[44] = -8'sd14; bs_[44] = -8'sd28; ys[44] = -8'sd15;
    as_[45] = -8'sd44; bs_[45] = 8'sd56; ys[45] = 8'sd19;
    as_[46] = 8'sd75; bs_[46] = 8'sd9; ys[46] = 8'sd15;
    as_[47] = 8'sd54; bs_[47] = 8'sd107; ys[47] = 8'sd56;
    as_[48] = 8'sd13; bs_[48] = 8'sd87; ys[48] = 8'sd41;
    as_[49] = 8'sd25; bs_[49] = -8'sd99; ys[49] = -8'sd41;
    as_[50] = -8'sd81; bs_[50] = 8'sd24; ys[50] = -8'sd1;
    as_[51] = 8'sd103; bs_[51] = 8'sd60; ys[51] = 8'sd42;
    as_[52] = -8'sd11; bs_[52] = -8'sd106; ys[52] = -8'sd49;
    as_[53] = 8'sd64; bs_[53] = 8'sd61; ys[53] = 8'sd37;
    as_[54] = -8'sd57; bs_[54] = 8'sd48; ys[54] = 8'sd14;
    as_[55] = -8'sd88; bs_[55] = -8'sd58; ys[55] = -8'sd39;
    as_[56] = 8'sd115; bs_[56] = -8'sd76; ys[56] = -8'sd18;
    as_[57] = 8'sd3; bs_[57] = -8'sd28; ys[57] = -8'sd12;
    as_[58] = 8'sd80; bs_[58] = -8'sd71; ys[58] = -8'sd21;
    as_[59] = -8'sd85; bs_[59] = -8'sd87; ys[59] = -8'sd51;
    as_[60] = 8'sd20; bs_[60] = 8'sd102; ys[60] = 8'sd49;
    as_[61] = -8'sd11; bs_[61] = -8'sd25; ys[61] = -8'sd13;
    as_[62] = -8'sd5; bs_[62] = -8'sd10; ys[62] = -8'sd5;
    as_[63] = 8'sd46; bs_[63] = -8'sd47; ys[63] = -8'sd15;
    as_[64] = 8'sd46; bs_[64] = -8'sd127; ys[64] = -8'sd51;
    as_[65] = 8'sd92; bs_[65] = 8'sd113; ys[65] = 8'sd64;
    as_[66] = 8'sd75; bs_[66] = -8'sd65; ys[66] = -8'sd19;
    as_[67] = -8'sd24; bs_[67] = 8'sd32; ys[67] = 8'sd11;
    as_[68] = 8'sd46; bs_[68] = -8'sd21; ys[68] = -8'sd3;
    as_[69] = -8'sd32; bs_[69] = 8'sd107; ys[69] = 8'sd44;
    as_[70] = 8'sd113; bs_[70] = -8'sd123; ys[70] = -8'sd40;
    as_[71] = 8'sd116; bs_[71] = -8'sd109; ys[71] = -8'sd33;
    as_[72] = -8'sd87; bs_[72] = 8'sd45; ys[72] = 8'sd8;
    as_[73] = 8'sd118; bs_[73] = 8'sd100; ys[73] = 8'sd62;
    as_[74] = -8'sd122; bs_[74] = -8'sd39; ys[74] = -8'sd35;
    as_[75] = 8'sd1; bs_[75] = 8'sd33; ys[75] = 8'sd15;
    as_[76] = -8'sd13; bs_[76] = -8'sd10; ys[76] = -8'sd6;
    as_[77] = -8'sd105; bs_[77] = 8'sd68; ys[77] = 8'sd16;
    as_[78] = -8'sd60; bs_[78] = -8'sd117; ys[78] = -8'sd61;
    as_[79] = -8'sd83; bs_[79] = 8'sd25; ys[79] = 8'sd0;
    as_[80] = -8'sd12; bs_[80] = -8'sd112; ys[80] = -8'sd52;
    as_[81] = 8'sd34; bs_[81] = -8'sd80; ys[81] = -8'sd31;
    as_[82] = 8'sd93; bs_[82] = -8'sd14; ys[82] = 8'sd7;
    as_[83] = -8'sd14; bs_[83] = -8'sd13; ys[83] = -8'sd8;
    as_[84] = 8'sd71; bs_[84] = -8'sd14; ys[84] = 8'sd4;
    as_[85] = 8'sd109; bs_[85] = -8'sd118; ys[85] = -8'sd38;
    as_[86] = -8'sd29; bs_[86] = 8'sd116; ys[86] = 8'sd48;
    as_[87] = -8'sd94; bs_[87] = -8'sd111; ys[87] = -8'sd63;
    as_[88] = 8'sd48; bs_[88] = 8'sd13; ys[88] = 8'sd13;
    as_[89] = 8'sd72; bs_[89] = -8'sd91; ys[89] = -8'sd31;
    as_[90] = 8'sd100; bs_[90] = 8'sd102; ys[90] = 8'sd60;
    as_[91] = -8'sd118; bs_[91] = 8'sd54; ys[91] = 8'sd8;
    as_[92] = -8'sd105; bs_[92] = 8'sd6; ys[92] = -8'sd12;
    as_[93] = -8'sd58; bs_[93] = 8'sd112; ys[93] = 8'sd42;
    as_[94] = -8'sd5; bs_[94] = 8'sd57; ys[94] = 8'sd25;
    as_[95] = 8'sd21; bs_[95] = 8'sd75; ys[95] = 8'sd37;
    as_[96] = -8'sd78; bs_[96] = -8'sd83; ys[96] = -8'sd48;
    as_[97] = 8'sd69; bs_[97] = -8'sd98; ys[97] = -8'sd35;
    as_[98] = 8'sd64; bs_[98] = 8'sd25; ys[98] = 8'sd20;
    as_[99] = 8'sd105; bs_[99] = -8'sd12; ys[99] = 8'sd9;
    as_[100] = 8'sd75; bs_[100] = -8'sd113; ys[100] = -8'sd41;
    as_[101] = -8'sd48; bs_[101] = 8'sd2; ys[101] = -8'sd6;
    as_[102] = -8'sd8; bs_[102] = -8'sd81; ys[102] = -8'sd38;
    as_[103] = 8'sd46; bs_[103] = -8'sd28; ys[103] = -8'sd6;
    as_[104] = 8'sd118; bs_[104] = -8'sd126; ys[104] = -8'sd40;
    as_[105] = 8'sd88; bs_[105] = -8'sd15; ys[105] = 8'sd6;
    as_[106] = 8'sd7; bs_[106] = 8'sd44; ys[106] = 8'sd21;
    as_[107] = 8'sd79; bs_[107] = -8'sd88; ys[107] = -8'sd29;
    as_[108] = -8'sd128; bs_[108] = 8'sd59; ys[108] = 8'sd9;
    as_[109] = -8'sd20; bs_[109] = -8'sd106; ys[109] = -8'sd51;
    as_[110] = -8'sd80; bs_[110] = -8'sd86; ys[110] = -8'sd50;
    as_[111] = 8'sd57; bs_[111] = 8'sd1; ys[111] = 8'sd8;
    as_[112] = -8'sd97; bs_[112] = 8'sd95; ys[112] = 8'sd29;
    as_[113] = -8'sd120; bs_[113] = -8'sd59; ys[113] = -8'sd43;
    as_[114] = 8'sd93; bs_[114] = 8'sd55; ys[114] = 8'sd38;
    as_[115] = 8'sd94; bs_[115] = 8'sd82; ys[115] = 8'sd50;
    as_[116] = 8'sd76; bs_[116] = 8'sd117; ys[116] = 8'sd64;
    as_[117] = 8'sd53; bs_[117] = -8'sd17; ys[117] = 8'sd0;
    as_[118] = -8'sd112; bs_[118] = -8'sd36; ys[118] = -8'sd32;
    as_[119] = 8'sd87; bs_[119] = -8'sd63; ys[119] = -8'sd16;
    as_[120] = 8'sd116; bs_[120] = 8'sd28; ys[120] = 8'sd29;
    as_[121] = 8'sd72; bs_[121] = 8'sd58; ys[121] = 8'sd36;
    as_[122] = -8'sd7; bs_[122] = -8'sd81; ys[122] = -8'sd38;
    as_[123] = 8'sd57; bs_[123] = 8'sd103; ys[123] = 8'sd55;
    as_[124] = -8'sd76; bs_[124] = 8'sd57; ys[124] = 8'sd15;
    as_[125] = 8'sd87; bs_[125] = 8'sd103; ys[125] = 8'sd59;
    as_[126] = -8'sd61; bs_[126] = 8'sd111; ys[126] = 8'sd42;
    as_[127] = -8'sd73; bs_[127] = 8'sd35; ys[127] = 8'sd6;
    as_[128] = 8'sd14; bs_[128] = 8'sd88; ys[128] = 8'sd42;
    as_[129] = -8'sd47; bs_[129] = -8'sd115; ys[129] = -8'sd59;
    as_[130] = -8'sd30; bs_[130] = 8'sd52; ys[130] = 8'sd19;
    as_[131] = -8'sd36; bs_[131] = 8'sd94; ys[131] = 8'sd37;
    as_[132] = -8'sd124; bs_[132] = -8'sd60; ys[132] = -8'sd44;
    as_[133] = 8'sd14; bs_[133] = -8'sd45; ys[133] = -8'sd18;
    as_[134] = 8'sd77; bs_[134] = 8'sd118; ys[134] = 8'sd64;
    as_[135] = -8'sd39; bs_[135] = -8'sd23; ys[135] = -8'sd16;
    as_[136] = 8'sd23; bs_[136] = -8'sd87; ys[136] = -8'sd36;
    as_[137] = -8'sd48; bs_[137] = 8'sd44; ys[137] = 8'sd13;
    as_[138] = -8'sd83; bs_[138] = 8'sd66; ys[138] = 8'sd18;
    as_[139] = 8'sd57; bs_[139] = -8'sd89; ys[139] = -8'sd32;
    as_[140] = -8'sd110; bs_[140] = -8'sd45; ys[140] = -8'sd36;
    as_[141] = -8'sd113; bs_[141] = -8'sd54; ys[141] = -8'sd40;
    as_[142] = 8'sd74; bs_[142] = -8'sd24; ys[142] = 8'sd0;
    as_[143] = -8'sd89; bs_[143] = 8'sd44; ys[143] = 8'sd7;
    as_[144] = -8'sd4; bs_[144] = -8'sd50; ys[144] = -8'sd23;
    as_[145] = 8'sd6; bs_[145] = 8'sd43; ys[145] = 8'sd20;
    as_[146] = -8'sd86; bs_[146] = 8'sd38; ys[146] = 8'sd5;
    as_[147] = 8'sd113; bs_[147] = 8'sd55; ys[147] = 8'sd41;
    as_[148] = -8'sd10; bs_[148] = -8'sd34; ys[148] = -8'sd17;
    as_[149] = -8'sd61; bs_[149] = -8'sd108; ys[149] = -8'sd57;
    as_[150] = -8'sd6; bs_[150] = 8'sd81; ys[150] = 8'sd36;
    as_[151] = 8'sd98; bs_[151] = -8'sd21; ys[151] = 8'sd4;
    as_[152] = 8'sd67; bs_[152] = 8'sd24; ys[152] = 8'sd20;
    as_[153] = -8'sd17; bs_[153] = -8'sd67; ys[153] = -8'sd33;
    as_[154] = -8'sd36; bs_[154] = -8'sd14; ys[154] = -8'sd11;
    as_[155] = -8'sd66; bs_[155] = -8'sd81; ys[155] = -8'sd46;
    as_[156] = 8'sd113; bs_[156] = -8'sd25; ys[156] = 8'sd5;
    as_[157] = 8'sd74; bs_[157] = 8'sd69; ys[157] = 8'sd42;
    as_[158] = -8'sd87; bs_[158] = 8'sd13; ys[158] = -8'sd6;
    as_[159] = -8'sd99; bs_[159] = 8'sd86; ys[159] = 8'sd25;
    as_[160] = 8'sd80; bs_[160] = -8'sd87; ys[160] = -8'sd28;
    as_[161] = 8'sd82; bs_[161] = -8'sd66; ys[161] = -8'sd18;
    as_[162] = -8'sd16; bs_[162] = -8'sd43; ys[162] = -8'sd22;
    as_[163] = -8'sd53; bs_[163] = -8'sd47; ys[163] = -8'sd29;
    as_[164] = -8'sd122; bs_[164] = 8'sd71; ys[164] = 8'sd15;
    as_[165] = 8'sd76; bs_[165] = 8'sd54; ys[165] = 8'sd35;
    as_[166] = 8'sd84; bs_[166] = 8'sd21; ys[166] = 8'sd21;
    as_[167] = 8'sd2; bs_[167] = 8'sd9; ys[167] = 8'sd4;
    as_[168] = -8'sd40; bs_[168] = 8'sd65; ys[168] = 8'sd24;
    as_[169] = -8'sd52; bs_[169] = 8'sd84; ys[169] = 8'sd31;
    as_[170] = -8'sd93; bs_[170] = -8'sd13; ys[170] = -8'sd19;
    as_[171] = 8'sd85; bs_[171] = 8'sd51; ys[171] = 8'sd35;
    as_[172] = -8'sd20; bs_[172] = 8'sd30; ys[172] = 8'sd11;
    as_[173] = -8'sd4; bs_[173] = -8'sd19; ys[173] = -8'sd9;
    as_[174] = -8'sd121; bs_[174] = -8'sd6; ys[174] = -8'sd20;
    as_[175] = -8'sd118; bs_[175] = -8'sd114; ys[175] = -8'sd68;
    as_[176] = 8'sd68; bs_[176] = 8'sd32; ys[176] = 8'sd24;
    as_[177] = -8'sd54; bs_[177] = -8'sd80; ys[177] = -8'sd44;
    as_[178] = -8'sd60; bs_[178] = 8'sd27; ys[178] = 8'sd4;
    as_[179] = 8'sd78; bs_[179] = 8'sd48; ys[179] = 8'sd33;
    as_[180] = -8'sd71; bs_[180] = -8'sd37; ys[180] = -8'sd27;
    as_[181] = 8'sd24; bs_[181] = -8'sd101; ys[181] = -8'sd42;
    as_[182] = -8'sd87; bs_[182] = -8'sd34; ys[182] = -8'sd28;
    as_[183] = -8'sd107; bs_[183] = 8'sd123; ys[183] = 8'sd41;
    as_[184] = -8'sd87; bs_[184] = -8'sd11; ys[184] = -8'sd17;
    as_[185] = 8'sd61; bs_[185] = -8'sd99; ys[185] = -8'sd36;
    as_[186] = -8'sd88; bs_[186] = -8'sd126; ys[186] = -8'sd69;
    as_[187] = -8'sd112; bs_[187] = 8'sd64; ys[187] = 8'sd13;
    as_[188] = 8'sd102; bs_[188] = -8'sd58; ys[188] = -8'sd12;
    as_[189] = 8'sd81; bs_[189] = 8'sd53; ys[189] = 8'sd35;
    as_[190] = -8'sd14; bs_[190] = -8'sd79; ys[190] = -8'sd38;
    as_[191] = -8'sd72; bs_[191] = -8'sd48; ys[191] = -8'sd32;
    as_[192] = -8'sd126; bs_[192] = 8'sd110; ys[192] = 8'sd32;
    as_[193] = 8'sd116; bs_[193] = 8'sd119; ys[193] = 8'sd70;
    as_[194] = 8'sd66; bs_[194] = 8'sd15; ys[194] = 8'sd16;
    as_[195] = -8'sd75; bs_[195] = -8'sd120; ys[195] = -8'sd65;
    as_[196] = 8'sd50; bs_[196] = -8'sd117; ys[196] = -8'sd46;
    as_[197] = 8'sd103; bs_[197] = 8'sd112; ys[197] = 8'sd65;
    as_[198] = 8'sd45; bs_[198] = -8'sd105; ys[198] = -8'sd41;
    as_[199] = 8'sd123; bs_[199] = 8'sd14; ys[199] = 8'sd24;
    as_[200] = 8'sd46; bs_[200] = 8'sd50; ys[200] = 8'sd29;
    as_[201] = 8'sd21; bs_[201] = -8'sd17; ys[201] = -8'sd5;
    as_[202] = -8'sd20; bs_[202] = -8'sd41; ys[202] = -8'sd21;
    as_[203] = 8'sd114; bs_[203] = 8'sd74; ys[203] = 8'sd49;
    as_[204] = 8'sd107; bs_[204] = 8'sd68; ys[204] = 8'sd46;
    as_[205] = 8'sd27; bs_[205] = -8'sd78; ys[205] = -8'sd31;
    as_[206] = -8'sd94; bs_[206] = 8'sd45; ys[206] = 8'sd7;
    as_[207] = 8'sd23; bs_[207] = -8'sd87; ys[207] = -8'sd36;
    as_[208] = -8'sd52; bs_[208] = 8'sd127; ys[208] = 8'sd50;
    as_[209] = 8'sd111; bs_[209] = 8'sd40; ys[209] = 8'sd34;
    as_[210] = 8'sd37; bs_[210] = -8'sd39; ys[210] = -8'sd12;
    as_[211] = -8'sd94; bs_[211] = -8'sd2; ys[211] = -8'sd14;
    as_[212] = -8'sd38; bs_[212] = -8'sd106; ys[212] = -8'sd53;
    as_[213] = -8'sd20; bs_[213] = 8'sd70; ys[213] = 8'sd29;
    // valid_out must be low from the first cycle of reset, not merely
    // after enough idle cycles to flush the pipeline: checked only after
    // three, a shallow design with no reset at all passed.
    for (i = 0; i < 3; i = i + 1) begin
      @(negedge clk);
      checks = checks + 1;
      if (valid_out !== 1'b0) begin
        $display("TB_FAIL test=reset_init cycle=%0d expected_vout=0 got_vout=%b",
                 i, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
    rst_n = 1;
    for (i = 0; i < 214; i = i + 1) begin
      @(negedge clk);
      a = as_[i]; b = bs_[i]; valid_in = 1;
      if (i % 29 == 28) begin
        @(negedge clk); valid_in = 0;
      end
    end
    @(negedge clk); valid_in = 0;
    repeat (20) @(negedge clk);
    checks = checks + 1;
    if (got !== 214) begin
      $display("TB_FAIL test=resadd idx=0 expected_count=214 got_count=%0d", got);
      $display("TB_RESULT: FAIL");
      $finish;
    end
    $display("TB_PROFILE elements=%0d span_cycles=%0d latency_cycles=%0d",
             214, 214 + 214 / 29, 4);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
