`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Self-checking testbench for the softmax sequencer, which instantiates
// the generated exponential and reciprocal units. Golden weights are
// built from those same unit models, so this checks the composition
// rather than a fresh approximation of softmax.
module tb_softmax;
  reg clk = 0, rst_n = 0, start = 0;
  reg  [9-1:0] n = 0;
  wire [7:0] s_addr;
  wire w_valid, busy;
  wire [7:0] w_index;
  wire [15:0] w_data;

  reg signed [20:0] smem [0:256-1];
  reg        [15:0] expect_w [0:256-1];
  reg signed [20:0] s_data;
  integer checks = 0, seen = 0, i, j, other, best, dist, own;
  reg [255:0] testname;
  // Cycles measured, not computed: the profile's cycles_per_unit and
  // latency come from here.
  integer cyc = 0, span = 0, t0 = 0, first_out = -1, lat = 0;
  always @(posedge clk) cyc = cyc + 1;

  always @(posedge clk) s_data <= smem[s_addr];

  softmax dut (.clk(clk), .rst_n(rst_n), .start(start), .n(n),
               .s_addr(s_addr), .s_data(s_data), .w_valid(w_valid),
               .w_index(w_index), .w_data(w_data), .busy(busy));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    if (rst_n && w_valid) begin
      checks = checks + 1;
      seen = seen + 1;
      if (first_out < 0) begin first_out = cyc; if (cyc - t0 > lat) lat = cyc - t0; end
      // A weight for an index past the row has no expected value, and
      // comparing against one printed expected_w=x, which a traced agent
      // read as a datapath fault for three drafts running.
      if (w_index >= n) begin
        $display("TB_FAIL test=%0s idx=%0d n=%0d expected=no_weight_past_the_row got_w=%0d",
                 testname, w_index, n, w_data);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      if (w_data !== expect_w[w_index]) begin
        // A right value under the wrong index is a pipeline alignment
        // fault, not an arithmetic one. Traced, two different models
        // emitted weight 1 as weight 0 and read only "expected 14668 got
        // 18118", which says nothing about which of the two is wrong.
        // Nearest other index, reported only when the value is within
        // about 1.5% of it, which a coincidence rarely manages. Exact
        // equality missed a draft that was misaligned and also ten counts
        // off in its arithmetic.
        other = -1; best = 1 << 30;
        for (j = 0; j < n; j = j + 1) begin
          dist = (expect_w[j] > w_data) ? expect_w[j] - w_data
                                        : w_data - expect_w[j];
          if (j != w_index && dist < best) begin best = dist; other = j; end
        end
        own = (expect_w[w_index] > w_data) ? expect_w[w_index] - w_data
                                           : w_data - expect_w[w_index];
        if (other >= 0 && best < own && best <= expect_w[other] / 64 + 2)
          $display("TB_FAIL test=%0s idx=%0d expected_w=%0d got_w=%0d got_w_is_closest_to_the_expected_value_for_idx=%0d",
                   testname, w_index, expect_w[w_index], w_data, other);
        else
        $display("TB_FAIL test=%0s idx=%0d expected_w=%0d got_w=%0d",
                 testname, w_index, expect_w[w_index], w_data);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  end

  task run_row(input [9-1:0] cnt);
    begin
      seen = 0;
      n = cnt;
      @(negedge clk); start = 1;
      t0 = cyc; first_out = -1;
      @(negedge clk); start = 0;
      while (busy) @(negedge clk);
      span = span + (cyc - t0);
      repeat (4) @(negedge clk);
      checks = checks + 1;
      if (seen !== cnt) begin
        $display("TB_FAIL test=%0s idx=0 expected_w=%0d got_w=%0d",
                 "weight_count", cnt, seen);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  endtask

  initial begin
    testname = "softmax";
    repeat (3) @(negedge clk);
    rst_n = 1;
    @(negedge clk);
    // row 0, n=1
    smem[0] = 21'sd1465;
    expect_w[0] = 16'd32767;
    run_row(9'd1);
    // row 1, n=2
    smem[0] = 21'sd1957;
    smem[1] = 21'sd2011;
    expect_w[0] = 16'd14668;
    expect_w[1] = 16'd18118;
    run_row(9'd2);
    // row 2, n=5
    smem[0] = 21'sd1761;
    smem[1] = 21'sd1954;
    smem[2] = 21'sd1086;
    smem[3] = 21'sd1098;
    smem[4] = 21'sd1369;
    expect_w[0] = 16'd9405;
    expect_w[1] = 16'd20020;
    expect_w[2] = 16'd672;
    expect_w[3] = 16'd706;
    expect_w[4] = 16'd2036;
    run_row(9'd5);
    // row 3, n=16
    smem[0] = 21'sd1727;
    smem[1] = 21'sd1294;
    smem[2] = 21'sd1557;
    smem[3] = 21'sd1137;
    smem[4] = 21'sd1369;
    smem[5] = 21'sd1119;
    smem[6] = 21'sd1760;
    smem[7] = 21'sd1492;
    smem[8] = 21'sd1925;
    smem[9] = 21'sd1428;
    smem[10] = 21'sd1491;
    smem[11] = 21'sd1282;
    smem[12] = 21'sd1306;
    smem[13] = 21'sd1742;
    smem[14] = 21'sd1674;
    smem[15] = 21'sd1848;
    expect_w[0] = 16'd3159;
    expect_w[1] = 16'd581;
    expect_w[2] = 16'd1627;
    expect_w[3] = 16'd315;
    expect_w[4] = 16'd779;
    expect_w[5] = 16'd293;
    expect_w[6] = 16'd3588;
    expect_w[7] = 16'd1261;
    expect_w[8] = 16'd6853;
    expect_w[9] = 16'd980;
    expect_w[10] = 16'd1254;
    expect_w[11] = 16'd555;
    expect_w[12] = 16'd609;
    expect_w[13] = 16'd3344;
    expect_w[14] = 16'd2564;
    expect_w[15] = 16'd5060;
    run_row(9'd16);
    // row 4, n=64
    smem[0] = 21'sd1135;
    smem[1] = 21'sd1703;
    smem[2] = 21'sd1593;
    smem[3] = 21'sd1336;
    smem[4] = 21'sd1208;
    smem[5] = 21'sd1867;
    smem[6] = 21'sd1815;
    smem[7] = 21'sd1922;
    smem[8] = 21'sd1529;
    smem[9] = 21'sd1340;
    smem[10] = 21'sd1129;
    smem[11] = 21'sd1939;
    smem[12] = 21'sd2006;
    smem[13] = 21'sd1496;
    smem[14] = 21'sd1727;
    smem[15] = 21'sd1490;
    smem[16] = 21'sd1317;
    smem[17] = 21'sd1185;
    smem[18] = 21'sd1088;
    smem[19] = 21'sd1218;
    smem[20] = 21'sd1128;
    smem[21] = 21'sd2002;
    smem[22] = 21'sd1834;
    smem[23] = 21'sd1694;
    smem[24] = 21'sd1549;
    smem[25] = 21'sd1504;
    smem[26] = 21'sd1137;
    smem[27] = 21'sd1810;
    smem[28] = 21'sd1876;
    smem[29] = 21'sd1312;
    smem[30] = 21'sd1403;
    smem[31] = 21'sd1430;
    smem[32] = 21'sd1697;
    smem[33] = 21'sd1771;
    smem[34] = 21'sd1414;
    smem[35] = 21'sd1994;
    smem[36] = 21'sd1477;
    smem[37] = 21'sd2006;
    smem[38] = 21'sd1742;
    smem[39] = 21'sd1378;
    smem[40] = 21'sd2016;
    smem[41] = 21'sd1433;
    smem[42] = 21'sd1641;
    smem[43] = 21'sd1220;
    smem[44] = 21'sd1890;
    smem[45] = 21'sd1158;
    smem[46] = 21'sd1821;
    smem[47] = 21'sd1796;
    smem[48] = 21'sd1181;
    smem[49] = 21'sd1630;
    smem[50] = 21'sd1281;
    smem[51] = 21'sd1841;
    smem[52] = 21'sd1491;
    smem[53] = 21'sd1966;
    smem[54] = 21'sd1509;
    smem[55] = 21'sd1660;
    smem[56] = 21'sd1503;
    smem[57] = 21'sd1414;
    smem[58] = 21'sd1984;
    smem[59] = 21'sd2019;
    smem[60] = 21'sd1895;
    smem[61] = 21'sd1491;
    smem[62] = 21'sd1390;
    smem[63] = 21'sd1467;
    expect_w[0] = 16'd53;
    expect_w[1] = 16'd488;
    expect_w[2] = 16'd317;
    expect_w[3] = 16'd116;
    expect_w[4] = 16'd70;
    expect_w[5] = 16'd926;
    expect_w[6] = 16'd755;
    expect_w[7] = 16'd1150;
    expect_w[8] = 16'd247;
    expect_w[9] = 16'd118;
    expect_w[10] = 16'd51;
    expect_w[11] = 16'd1227;
    expect_w[12] = 16'd1596;
    expect_w[13] = 16'd217;
    expect_w[14] = 16'd535;
    expect_w[15] = 16'd212;
    expect_w[16] = 16'd108;
    expect_w[17] = 16'd64;
    expect_w[18] = 16'd44;
    expect_w[19] = 16'd73;
    expect_w[20] = 16'd51;
    expect_w[21] = 16'd1570;
    expect_w[22] = 16'd815;
    expect_w[23] = 16'd471;
    expect_w[24] = 16'd267;
    expect_w[25] = 16'd224;
    expect_w[26] = 16'd53;
    expect_w[27] = 16'd741;
    expect_w[28] = 16'd959;
    expect_w[29] = 16'd106;
    expect_w[30] = 16'd151;
    expect_w[31] = 16'd168;
    expect_w[32] = 16'd477;
    expect_w[33] = 16'd637;
    expect_w[34] = 16'd158;
    expect_w[35] = 16'd1520;
    expect_w[36] = 16'd202;
    expect_w[37] = 16'd1596;
    expect_w[38] = 16'd568;
    expect_w[39] = 16'd137;
    expect_w[40] = 16'd1657;
    expect_w[41] = 16'd170;
    expect_w[42] = 16'd383;
    expect_w[43] = 16'd74;
    expect_w[44] = 16'd1012;
    expect_w[45] = 16'd57;
    expect_w[46] = 16'd774;
    expect_w[47] = 16'd702;
    expect_w[48] = 16'd63;
    expect_w[49] = 16'd366;
    expect_w[50] = 16'd93;
    expect_w[51] = 16'd837;
    expect_w[52] = 16'd213;
    expect_w[53] = 16'd1364;
    expect_w[54] = 16'd229;
    expect_w[55] = 16'd413;
    expect_w[56] = 16'd223;
    expect_w[57] = 16'd158;
    expect_w[58] = 16'd1463;
    expect_w[59] = 16'd1680;
    expect_w[60] = 16'd1034;
    expect_w[61] = 16'd213;
    expect_w[62] = 16'd143;
    expect_w[63] = 16'd194;
    run_row(9'd64);
    // row 5, n=8
    smem[0] = 21'sd1234;
    smem[1] = 21'sd1234;
    smem[2] = 21'sd1234;
    smem[3] = 21'sd1234;
    smem[4] = 21'sd1234;
    smem[5] = 21'sd1234;
    smem[6] = 21'sd1234;
    smem[7] = 21'sd1234;
    expect_w[0] = 16'd4095;
    expect_w[1] = 16'd4095;
    expect_w[2] = 16'd4095;
    expect_w[3] = 16'd4095;
    expect_w[4] = 16'd4095;
    expect_w[5] = 16'd4095;
    expect_w[6] = 16'd4095;
    expect_w[7] = 16'd4095;
    run_row(9'd8);
    // row 6, n=8
    smem[0] = 21'sd2047;
    smem[1] = 21'sd511;
    smem[2] = 21'sd511;
    smem[3] = 21'sd511;
    smem[4] = 21'sd511;
    smem[5] = 21'sd511;
    smem[6] = 21'sd511;
    smem[7] = 21'sd511;
    expect_w[0] = 16'd32264;
    expect_w[1] = 16'd79;
    expect_w[2] = 16'd79;
    expect_w[3] = 16'd79;
    expect_w[4] = 16'd79;
    expect_w[5] = 16'd79;
    expect_w[6] = 16'd79;
    expect_w[7] = 16'd79;
    run_row(9'd8);
    // row 7, n=4
    smem[0] = -21'sd1024;
    smem[1] = 21'sd0;
    smem[2] = 21'sd1023;
    smem[3] = 21'sd7;
    expect_w[0] = 16'd10;
    expect_w[1] = 16'd581;
    expect_w[2] = 16'd31655;
    expect_w[3] = 16'd597;
    run_row(9'd4);
    // row 8, n=4
    smem[0] = 21'sd536633;
    smem[1] = -21'sd511943;
    smem[2] = -21'sd524288;
    smem[3] = 21'sd533633;
    expect_w[0] = 16'd32767;
    expect_w[1] = 16'd0;
    expect_w[2] = 16'd0;
    expect_w[3] = 16'd0;
    run_row(9'd4);
    // row 9, n=5
    smem[0] = 21'sd536633;
    smem[1] = 21'sd532537;
    smem[2] = 21'sd532536;
    smem[3] = 21'sd532538;
    smem[4] = 21'sd536628;
    expect_w[0] = 16'd16578;
    expect_w[1] = 16'd0;
    expect_w[2] = 16'd0;
    expect_w[3] = 16'd0;
    expect_w[4] = 16'd16223;
    run_row(9'd5);
    // row 10, n=4
    smem[0] = -21'sd1500;
    smem[1] = 21'sd1067;
    smem[2] = -21'sd1309;
    smem[3] = -21'sd902;
    expect_w[0] = 16'd0;
    expect_w[1] = 16'd32767;
    expect_w[2] = 16'd2;
    expect_w[3] = 16'd13;
    run_row(9'd4);

    $display("TB_PROFILE rows=%0d span_cycles=%0d latency_cycles=%0d",
             11, span, lat);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
