`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// Testbench for the streaming SiLU unit. Golden values come from the
// exponential and reciprocal models. Inputs stream one per cycle with
// occasional gaps, and outputs are checked in order off valid_out, so the
// latency is the design's choice but the order and the count are not.
module tb_silu;
  reg clk = 0, rst_n = 0, valid_in = 0;
  reg signed [12:0] x = 0;
  wire signed [12:0] y;
  wire valid_out;
  reg signed [12:0] xs [0:314-1];
  reg signed [12:0] ys [0:314-1];
  integer checks = 0, got = 0, i;
  // Cycles measured, not computed: the profile's cycles_per_unit and
  // latency come from here.
  integer cyc = 0, span = 0, t0 = 0, first_out = -1, lat = 0;
  always @(posedge clk) cyc = cyc + 1;

  silu dut (.clk(clk), .rst_n(rst_n), .x(x), .valid_in(valid_in),
            .y(y), .valid_out(valid_out));
  always #5 clk = ~clk;

  always @(posedge clk) begin
    if (rst_n && valid_out) begin
      checks = checks + 1;
      if (got >= 314) begin
        $display("TB_FAIL test=silu idx=%0d expected=no_more_outputs got_silu=%0d",
                 got, y);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      if (y !== ys[got]) begin
        $display("TB_FAIL test=silu idx=%0d x=%0d expected_silu=%0d got_silu=%0d",
                 got, xs[got], ys[got], y);
        $display("TB_RESULT: FAIL");
        $finish;
      end
      if (got == 0) lat = cyc - t0;
      got = got + 1;
      span = cyc - t0 + 1;
    end
  end

  initial begin
    xs[0] = 13'sd0; ys[0] = 13'sd0;
    xs[1] = 13'sd1; ys[1] = 13'sd0;
    xs[2] = -13'sd1; ys[2] = -13'sd1;
    xs[3] = 13'sd256; ys[3] = 13'sd187;
    xs[4] = -13'sd256; ys[4] = -13'sd69;
    xs[5] = 13'sd512; ys[5] = 13'sd451;
    xs[6] = -13'sd512; ys[6] = -13'sd62;
    xs[7] = 13'sd1280; ys[7] = 13'sd1275;
    xs[8] = -13'sd1280; ys[8] = -13'sd9;
    xs[9] = -13'sd4096; ys[9] = 13'sd0;
    xs[10] = 13'sd4095; ys[10] = 13'sd4094;
    xs[11] = -13'sd4095; ys[11] = 13'sd0;
    xs[12] = -13'sd128; ys[12] = -13'sd49;
    xs[13] = 13'sd128; ys[13] = 13'sd79;
    xs[14] = -13'sd909; ys[14] = -13'sd26;
    xs[15] = 13'sd2932; ys[15] = 13'sd2931;
    xs[16] = 13'sd1999; ys[16] = 13'sd1998;
    xs[17] = -13'sd3262; ys[17] = 13'sd0;
    xs[18] = -13'sd3736; ys[18] = 13'sd0;
    xs[19] = -13'sd3415; ys[19] = 13'sd0;
    xs[20] = -13'sd3825; ys[20] = 13'sd0;
    xs[21] = 13'sd366; ys[21] = 13'sd295;
    xs[22] = 13'sd1935; ys[22] = 13'sd1934;
    xs[23] = -13'sd3671; ys[23] = 13'sd0;
    xs[24] = -13'sd2936; ys[24] = 13'sd0;
    xs[25] = 13'sd3078; ys[25] = 13'sd3077;
    xs[26] = 13'sd3628; ys[26] = 13'sd3627;
    xs[27] = -13'sd2243; ys[27] = -13'sd1;
    xs[28] = 13'sd1069; ys[28] = 13'sd1056;
    xs[29] = -13'sd127; ys[29] = -13'sd49;
    xs[30] = 13'sd910; ys[30] = 13'sd885;
    xs[31] = -13'sd1102; ys[31] = -13'sd15;
    xs[32] = 13'sd37; ys[32] = 13'sd19;
    xs[33] = 13'sd2655; ys[33] = 13'sd2654;
    xs[34] = -13'sd1020; ys[34] = -13'sd19;
    xs[35] = -13'sd1208; ys[35] = -13'sd11;
    xs[36] = -13'sd2339; ys[36] = -13'sd1;
    xs[37] = -13'sd255; ys[37] = -13'sd69;
    xs[38] = -13'sd1994; ys[38] = -13'sd1;
    xs[39] = -13'sd3026; ys[39] = 13'sd0;
    xs[40] = -13'sd1805; ys[40] = -13'sd2;
    xs[41] = -13'sd2306; ys[41] = -13'sd1;
    xs[42] = -13'sd3043; ys[42] = 13'sd0;
    xs[43] = 13'sd458; ys[43] = 13'sd393;
    xs[44] = -13'sd2763; ys[44] = 13'sd0;
    xs[45] = -13'sd3080; ys[45] = 13'sd0;
    xs[46] = 13'sd3322; ys[46] = 13'sd3321;
    xs[47] = -13'sd2839; ys[47] = 13'sd0;
    xs[48] = -13'sd165; ys[48] = -13'sd57;
    xs[49] = -13'sd1129; ys[49] = -13'sd14;
    xs[50] = -13'sd3756; ys[50] = 13'sd0;
    xs[51] = -13'sd1610; ys[51] = -13'sd3;
    xs[52] = -13'sd857; ys[52] = -13'sd30;
    xs[53] = 13'sd1867; ys[53] = 13'sd1866;
    xs[54] = -13'sd2801; ys[54] = 13'sd0;
    xs[55] = -13'sd101; ys[55] = -13'sd41;
    xs[56] = -13'sd3904; ys[56] = 13'sd0;
    xs[57] = -13'sd1790; ys[57] = -13'sd2;
    xs[58] = -13'sd4062; ys[58] = 13'sd0;
    xs[59] = -13'sd1545; ys[59] = -13'sd4;
    xs[60] = 13'sd4022; ys[60] = 13'sd4021;
    xs[61] = -13'sd3945; ys[61] = 13'sd0;
    xs[62] = 13'sd3635; ys[62] = 13'sd3634;
    xs[63] = -13'sd3717; ys[63] = 13'sd0;
    xs[64] = -13'sd3304; ys[64] = 13'sd0;
    xs[65] = 13'sd3120; ys[65] = 13'sd3119;
    xs[66] = 13'sd2971; ys[66] = 13'sd2970;
    xs[67] = -13'sd2528; ys[67] = 13'sd0;
    xs[68] = -13'sd3362; ys[68] = 13'sd0;
    xs[69] = -13'sd3910; ys[69] = 13'sd0;
    xs[70] = -13'sd3310; ys[70] = 13'sd0;
    xs[71] = -13'sd196; ys[71] = -13'sd63;
    xs[72] = 13'sd2883; ys[72] = 13'sd2882;
    xs[73] = 13'sd2591; ys[73] = 13'sd2590;
    xs[74] = 13'sd1775; ys[74] = 13'sd1774;
    xs[75] = -13'sd1191; ys[75] = -13'sd12;
    xs[76] = 13'sd3125; ys[76] = 13'sd3124;
    xs[77] = -13'sd2084; ys[77] = -13'sd1;
    xs[78] = 13'sd1751; ys[78] = 13'sd1750;
    xs[79] = 13'sd521; ys[79] = 13'sd461;
    xs[80] = 13'sd1498; ys[80] = 13'sd1497;
    xs[81] = -13'sd3326; ys[81] = 13'sd0;
    xs[82] = -13'sd687; ys[82] = -13'sd44;
    xs[83] = -13'sd143; ys[83] = -13'sd52;
    xs[84] = -13'sd1028; ys[84] = -13'sd19;
    xs[85] = 13'sd1329; ys[85] = 13'sd1323;
    xs[86] = 13'sd741; ys[86] = 13'sd702;
    xs[87] = -13'sd2735; ys[87] = 13'sd0;
    xs[88] = -13'sd2396; ys[88] = -13'sd1;
    xs[89] = -13'sd664; ys[89] = -13'sd47;
    xs[90] = 13'sd3829; ys[90] = 13'sd3828;
    xs[91] = -13'sd2707; ys[91] = 13'sd0;
    xs[92] = -13'sd3722; ys[92] = 13'sd0;
    xs[93] = 13'sd3181; ys[93] = 13'sd3180;
    xs[94] = -13'sd3762; ys[94] = 13'sd0;
    xs[95] = 13'sd3330; ys[95] = 13'sd3329;
    xs[96] = 13'sd709; ys[96] = 13'sd667;
    xs[97] = -13'sd3440; ys[97] = 13'sd0;
    xs[98] = -13'sd1162; ys[98] = -13'sd13;
    xs[99] = 13'sd813; ys[99] = 13'sd782;
    xs[100] = -13'sd3571; ys[100] = 13'sd0;
    xs[101] = -13'sd2480; ys[101] = -13'sd1;
    xs[102] = 13'sd327; ys[102] = 13'sd255;
    xs[103] = 13'sd2530; ys[103] = 13'sd2529;
    xs[104] = -13'sd1019; ys[104] = -13'sd19;
    xs[105] = 13'sd2024; ys[105] = 13'sd2023;
    xs[106] = -13'sd2696; ys[106] = 13'sd0;
    xs[107] = -13'sd1464; ys[107] = -13'sd5;
    xs[108] = 13'sd2236; ys[108] = 13'sd2235;
    xs[109] = -13'sd3936; ys[109] = 13'sd0;
    xs[110] = -13'sd1573; ys[110] = -13'sd4;
    xs[111] = 13'sd3117; ys[111] = 13'sd3116;
    xs[112] = -13'sd755; ys[112] = -13'sd38;
    xs[113] = 13'sd3033; ys[113] = 13'sd3032;
    xs[114] = -13'sd4043; ys[114] = 13'sd0;
    xs[115] = -13'sd1941; ys[115] = -13'sd1;
    xs[116] = -13'sd964; ys[116] = -13'sd22;
    xs[117] = -13'sd1284; ys[117] = -13'sd9;
    xs[118] = 13'sd3633; ys[118] = 13'sd3632;
    xs[119] = -13'sd1201; ys[119] = -13'sd11;
    xs[120] = -13'sd2944; ys[120] = 13'sd0;
    xs[121] = 13'sd2072; ys[121] = 13'sd2071;
    xs[122] = 13'sd797; ys[122] = 13'sd764;
    xs[123] = -13'sd1452; ys[123] = -13'sd5;
    xs[124] = -13'sd1023; ys[124] = -13'sd19;
    xs[125] = -13'sd3576; ys[125] = 13'sd0;
    xs[126] = -13'sd4062; ys[126] = 13'sd0;
    xs[127] = 13'sd117; ys[127] = 13'sd71;
    xs[128] = -13'sd969; ys[128] = -13'sd22;
    xs[129] = 13'sd28; ys[129] = 13'sd14;
    xs[130] = -13'sd2566; ys[130] = 13'sd0;
    xs[131] = 13'sd3628; ys[131] = 13'sd3627;
    xs[132] = 13'sd309; ys[132] = 13'sd238;
    xs[133] = -13'sd1859; ys[133] = -13'sd2;
    xs[134] = -13'sd2350; ys[134] = -13'sd1;
    xs[135] = -13'sd3122; ys[135] = 13'sd0;
    xs[136] = 13'sd371; ys[136] = 13'sd301;
    xs[137] = 13'sd1007; ys[137] = 13'sd987;
    xs[138] = -13'sd1815; ys[138] = -13'sd2;
    xs[139] = -13'sd2167; ys[139] = -13'sd1;
    xs[140] = -13'sd1815; ys[140] = -13'sd2;
    xs[141] = -13'sd1795; ys[141] = -13'sd2;
    xs[142] = 13'sd3017; ys[142] = 13'sd3016;
    xs[143] = -13'sd1559; ys[143] = -13'sd4;
    xs[144] = 13'sd1022; ys[144] = 13'sd1006;
    xs[145] = -13'sd2051; ys[145] = -13'sd1;
    xs[146] = -13'sd2011; ys[146] = -13'sd1;
    xs[147] = 13'sd42; ys[147] = 13'sd22;
    xs[148] = -13'sd1385; ys[148] = -13'sd7;
    xs[149] = -13'sd2126; ys[149] = -13'sd1;
    xs[150] = -13'sd1494; ys[150] = -13'sd5;
    xs[151] = -13'sd446; ys[151] = -13'sd67;
    xs[152] = -13'sd1597; ys[152] = -13'sd4;
    xs[153] = 13'sd2584; ys[153] = 13'sd2583;
    xs[154] = -13'sd4057; ys[154] = 13'sd0;
    xs[155] = 13'sd3741; ys[155] = 13'sd3740;
    xs[156] = 13'sd2283; ys[156] = 13'sd2282;
    xs[157] = 13'sd2484; ys[157] = 13'sd2483;
    xs[158] = -13'sd1548; ys[158] = -13'sd4;
    xs[159] = 13'sd3634; ys[159] = 13'sd3633;
    xs[160] = 13'sd2308; ys[160] = 13'sd2307;
    xs[161] = 13'sd3156; ys[161] = 13'sd3155;
    xs[162] = 13'sd565; ys[162] = 13'sd509;
    xs[163] = 13'sd2819; ys[163] = 13'sd2818;
    xs[164] = 13'sd2202; ys[164] = 13'sd2201;
    xs[165] = 13'sd2058; ys[165] = 13'sd2057;
    xs[166] = -13'sd339; ys[166] = -13'sd72;
    xs[167] = -13'sd468; ys[167] = -13'sd65;
    xs[168] = 13'sd3141; ys[168] = 13'sd3140;
    xs[169] = 13'sd693; ys[169] = 13'sd649;
    xs[170] = -13'sd752; ys[170] = -13'sd38;
    xs[171] = 13'sd3395; ys[171] = 13'sd3394;
    xs[172] = 13'sd4045; ys[172] = 13'sd4044;
    xs[173] = 13'sd3674; ys[173] = 13'sd3673;
    xs[174] = -13'sd1471; ys[174] = -13'sd5;
    xs[175] = -13'sd615; ys[175] = -13'sd51;
    xs[176] = -13'sd1115; ys[176] = -13'sd15;
    xs[177] = -13'sd684; ys[177] = -13'sd45;
    xs[178] = 13'sd3200; ys[178] = 13'sd3199;
    xs[179] = -13'sd387; ys[179] = -13'sd70;
    xs[180] = 13'sd3073; ys[180] = 13'sd3072;
    xs[181] = -13'sd616; ys[181] = -13'sd51;
    xs[182] = -13'sd477; ys[182] = -13'sd65;
    xs[183] = -13'sd2862; ys[183] = 13'sd0;
    xs[184] = 13'sd1805; ys[184] = 13'sd1804;
    xs[185] = 13'sd2302; ys[185] = 13'sd2301;
    xs[186] = -13'sd1769; ys[186] = -13'sd2;
    xs[187] = -13'sd2499; ys[187] = 13'sd0;
    xs[188] = -13'sd1292; ys[188] = -13'sd9;
    xs[189] = 13'sd2932; ys[189] = 13'sd2931;
    xs[190] = -13'sd2442; ys[190] = -13'sd1;
    xs[191] = -13'sd2314; ys[191] = -13'sd1;
    xs[192] = 13'sd3374; ys[192] = 13'sd3373;
    xs[193] = 13'sd1314; ys[193] = 13'sd1308;
    xs[194] = 13'sd3959; ys[194] = 13'sd3958;
    xs[195] = 13'sd3973; ys[195] = 13'sd3972;
    xs[196] = 13'sd43; ys[196] = 13'sd23;
    xs[197] = 13'sd3299; ys[197] = 13'sd3298;
    xs[198] = -13'sd3695; ys[198] = 13'sd0;
    xs[199] = 13'sd283; ys[199] = 13'sd213;
    xs[200] = -13'sd3646; ys[200] = 13'sd0;
    xs[201] = 13'sd415; ys[201] = 13'sd347;
    xs[202] = 13'sd1546; ys[202] = 13'sd1545;
    xs[203] = -13'sd765; ys[203] = -13'sd37;
    xs[204] = -13'sd16; ys[204] = -13'sd8;
    xs[205] = 13'sd1220; ys[205] = 13'sd1210;
    xs[206] = -13'sd2825; ys[206] = 13'sd0;
    xs[207] = 13'sd2385; ys[207] = 13'sd2384;
    xs[208] = 13'sd3839; ys[208] = 13'sd3838;
    xs[209] = 13'sd2826; ys[209] = 13'sd2825;
    xs[210] = 13'sd1302; ys[210] = 13'sd1296;
    xs[211] = -13'sd762; ys[211] = -13'sd37;
    xs[212] = -13'sd4038; ys[212] = 13'sd0;
    xs[213] = 13'sd1288; ys[213] = 13'sd1282;
    xs[214] = 13'sd401; ys[214] = 13'sd332;
    xs[215] = -13'sd1557; ys[215] = -13'sd4;
    xs[216] = 13'sd1472; ys[216] = 13'sd1471;
    xs[217] = -13'sd588; ys[217] = -13'sd54;
    xs[218] = -13'sd3183; ys[218] = 13'sd0;
    xs[219] = -13'sd2127; ys[219] = -13'sd1;
    xs[220] = -13'sd778; ys[220] = -13'sd36;
    xs[221] = 13'sd160; ys[221] = 13'sd104;
    xs[222] = -13'sd2849; ys[222] = 13'sd0;
    xs[223] = -13'sd614; ys[223] = -13'sd52;
    xs[224] = -13'sd136; ys[224] = -13'sd51;
    xs[225] = 13'sd886; ys[225] = 13'sd859;
    xs[226] = 13'sd376; ys[226] = 13'sd306;
    xs[227] = -13'sd2182; ys[227] = -13'sd1;
    xs[228] = -13'sd224; ys[228] = -13'sd66;
    xs[229] = 13'sd743; ys[229] = 13'sd704;
    xs[230] = -13'sd1332; ys[230] = -13'sd8;
    xs[231] = -13'sd1207; ys[231] = -13'sd11;
    xs[232] = -13'sd3761; ys[232] = 13'sd0;
    xs[233] = 13'sd3033; ys[233] = 13'sd3032;
    xs[234] = -13'sd182; ys[234] = -13'sd60;
    xs[235] = -13'sd501; ys[235] = -13'sd62;
    xs[236] = 13'sd3819; ys[236] = 13'sd3818;
    xs[237] = 13'sd2696; ys[237] = 13'sd2695;
    xs[238] = -13'sd2287; ys[238] = -13'sd1;
    xs[239] = 13'sd786; ys[239] = 13'sd753;
    xs[240] = 13'sd2834; ys[240] = 13'sd2833;
    xs[241] = -13'sd347; ys[241] = -13'sd72;
    xs[242] = -13'sd464; ys[242] = -13'sd66;
    xs[243] = 13'sd2720; ys[243] = 13'sd2719;
    xs[244] = 13'sd1057; ys[244] = 13'sd1040;
    xs[245] = -13'sd2179; ys[245] = -13'sd1;
    xs[246] = 13'sd1765; ys[246] = 13'sd1764;
    xs[247] = -13'sd3153; ys[247] = 13'sd0;
    xs[248] = -13'sd697; ys[248] = -13'sd44;
    xs[249] = -13'sd2667; ys[249] = 13'sd0;
    xs[250] = -13'sd3621; ys[250] = 13'sd0;
    xs[251] = -13'sd849; ys[251] = -13'sd30;
    xs[252] = -13'sd1681; ys[252] = -13'sd3;
    xs[253] = 13'sd473; ys[253] = 13'sd409;
    xs[254] = 13'sd3263; ys[254] = 13'sd3262;
    xs[255] = -13'sd3293; ys[255] = 13'sd0;
    xs[256] = 13'sd1636; ys[256] = 13'sd1635;
    xs[257] = 13'sd2559; ys[257] = 13'sd2558;
    xs[258] = -13'sd1101; ys[258] = -13'sd15;
    xs[259] = -13'sd1072; ys[259] = -13'sd17;
    xs[260] = 13'sd2004; ys[260] = 13'sd2003;
    xs[261] = 13'sd1125; ys[261] = 13'sd1111;
    xs[262] = -13'sd714; ys[262] = -13'sd42;
    xs[263] = -13'sd1932; ys[263] = -13'sd1;
    xs[264] = -13'sd1680; ys[264] = -13'sd3;
    xs[265] = -13'sd1113; ys[265] = -13'sd15;
    xs[266] = -13'sd3531; ys[266] = 13'sd0;
    xs[267] = -13'sd1902; ys[267] = -13'sd2;
    xs[268] = -13'sd2140; ys[268] = -13'sd1;
    xs[269] = -13'sd1552; ys[269] = -13'sd4;
    xs[270] = -13'sd3876; ys[270] = 13'sd0;
    xs[271] = 13'sd2367; ys[271] = 13'sd2366;
    xs[272] = -13'sd1853; ys[272] = -13'sd2;
    xs[273] = -13'sd1821; ys[273] = -13'sd2;
    xs[274] = 13'sd78; ys[274] = 13'sd44;
    xs[275] = -13'sd2838; ys[275] = 13'sd0;
    xs[276] = -13'sd3629; ys[276] = 13'sd0;
    xs[277] = -13'sd248; ys[277] = -13'sd69;
    xs[278] = 13'sd3983; ys[278] = 13'sd3982;
    xs[279] = 13'sd2011; ys[279] = 13'sd2010;
    xs[280] = -13'sd2325; ys[280] = -13'sd1;
    xs[281] = -13'sd4000; ys[281] = 13'sd0;
    xs[282] = -13'sd3127; ys[282] = 13'sd0;
    xs[283] = -13'sd313; ys[283] = -13'sd72;
    xs[284] = -13'sd3626; ys[284] = 13'sd0;
    xs[285] = -13'sd1875; ys[285] = -13'sd2;
    xs[286] = 13'sd3438; ys[286] = 13'sd3437;
    xs[287] = 13'sd1256; ys[287] = 13'sd1251;
    xs[288] = -13'sd2789; ys[288] = 13'sd0;
    xs[289] = -13'sd1303; ys[289] = -13'sd8;
    xs[290] = 13'sd996; ys[290] = 13'sd976;
    xs[291] = 13'sd1723; ys[291] = 13'sd1722;
    xs[292] = 13'sd1531; ys[292] = 13'sd1530;
    xs[293] = -13'sd1475; ys[293] = -13'sd5;
    xs[294] = -13'sd973; ys[294] = -13'sd22;
    xs[295] = -13'sd2702; ys[295] = 13'sd0;
    xs[296] = -13'sd3200; ys[296] = 13'sd0;
    xs[297] = 13'sd1703; ys[297] = 13'sd1702;
    xs[298] = 13'sd1549; ys[298] = 13'sd1548;
    xs[299] = 13'sd2281; ys[299] = 13'sd2280;
    xs[300] = 13'sd2571; ys[300] = 13'sd2570;
    xs[301] = -13'sd1376; ys[301] = -13'sd7;
    xs[302] = -13'sd3121; ys[302] = 13'sd0;
    xs[303] = -13'sd1739; ys[303] = -13'sd2;
    xs[304] = -13'sd1400; ys[304] = -13'sd6;
    xs[305] = -13'sd2032; ys[305] = -13'sd1;
    xs[306] = -13'sd3873; ys[306] = 13'sd0;
    xs[307] = -13'sd3269; ys[307] = 13'sd0;
    xs[308] = -13'sd819; ys[308] = -13'sd33;
    xs[309] = 13'sd2820; ys[309] = 13'sd2819;
    xs[310] = -13'sd644; ys[310] = -13'sd49;
    xs[311] = 13'sd2137; ys[311] = 13'sd2136;
    xs[312] = -13'sd566; ys[312] = -13'sd56;
    xs[313] = 13'sd229; ys[313] = 13'sd162;
    // valid_out must be low from the first cycle of reset, not merely
    // after enough idle cycles to flush the pipeline: checked only after
    // three, a shallow design with no reset at all passed.
    for (i = 0; i < 3; i = i + 1) begin
      @(negedge clk);
      checks = checks + 1;
      if (valid_out !== 1'b0) begin
        $display("TB_FAIL test=reset_init cycle=%0d expected_vout=0 got_vout=%b",
                 i, valid_out);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
    rst_n = 1;
    t0 = cyc + 1;
    for (i = 0; i < 314; i = i + 1) begin
      @(negedge clk);
      x = xs[i]; valid_in = 1;
      if (i % 37 == 36) begin
        @(negedge clk); valid_in = 0;
      end
    end
    @(negedge clk); valid_in = 0;
    repeat (40) @(negedge clk);
    checks = checks + 1;
    if (got !== 314) begin
      $display("TB_FAIL test=silu idx=0 expected_count=314 got_count=%0d", got);
      $display("TB_RESULT: FAIL");
      $finish;
    end
    $display("TB_PROFILE elements=%0d span_cycles=%0d latency_cycles=%0d",
             314, span, lat);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
