`timescale 1ns/1ps
// GENERATED by specgen.py: do not edit by hand.
// System testbench: the weight loader and memory feeding the sequencer
// and the MAC. Weights are streamed in through the load port the way
// they would reach a device, then walked and reduced, and the column
// results are checked against values computed in Python.
module tb_wmem;
  reg clk = 0, rst_n = 0;
  reg load_start = 0, load_valid = 0;
  reg signed [7:0] load_data = 0;
  wire [10:0] load_count;
  wire signed [7:0] rd_data;

  reg start = 0;
  reg  [11:0] depth = 0;
  reg  [11:0] cols = 0;
  wire [11:0] a_addr;
  wire [23:0] w_addr;
  wire mac_valid, mac_clear, col_valid, busy;
  wire [11:0] col_index;
  wire signed [27:0] acc;
  wire mac_vout;

  reg signed [7:0] amem [0:64-1];
  reg signed [27:0] expect_col [0:16-1];
  reg signed [7:0] a_data;
  integer checks = 0, seen = 0, i;
  reg [255:0] testname;

  // The activation side stays a simple registered read; the weight side
  // is the generated memory.
  always @(posedge clk) a_data <= amem[a_addr];

  wmem wm (.clk(clk), .rst_n(rst_n), .load_start(load_start),
           .load_valid(load_valid), .load_data(load_data),
           .load_count(load_count), .rd_addr(w_addr[9:0]),
           .rd_data(rd_data));

  matvec seq (.clk(clk), .rst_n(rst_n), .start(start), .depth(depth),
              .cols(cols), .a_addr(a_addr), .w_addr(w_addr),
              .mac_valid(mac_valid), .mac_clear(mac_clear),
              .col_valid(col_valid), .col_index(col_index), .busy(busy));

  mac dut (.clk(clk), .rst_n(rst_n), .clear(mac_clear),
           .a(a_data), .b(rd_data), .valid_in(mac_valid),
           .acc(acc), .valid_out(mac_vout));

  always #5 clk = ~clk;

  always @(posedge clk) begin
    if (rst_n && col_valid) begin
      checks = checks + 1;
      seen = seen + 1;
      if (acc !== expect_col[col_index]) begin
        $display("TB_FAIL test=%0s col=%0d expected_acc=%0d got_acc=%0d",
                 testname, col_index, expect_col[col_index], acc);
        $display("TB_RESULT: FAIL");
        $finish;
      end
    end
  end

  initial begin
    for (i = 0; i < 64; i = i + 1)
      amem[i] = (i * 104729 + 7) % 251 - 125;
    expect_col[0] = -28'sd2803;
    expect_col[1] = -28'sd51558;
    expect_col[2] = -28'sd99560;
    expect_col[3] = -28'sd51178;
    expect_col[4] = 28'sd28077;
    expect_col[5] = 28'sd26008;
    expect_col[6] = 28'sd24692;
    expect_col[7] = -28'sd21051;
    expect_col[8] = -28'sd2538;
    expect_col[9] = 28'sd27270;
    expect_col[10] = 28'sd57831;
    expect_col[11] = 28'sd58774;
    expect_col[12] = 28'sd7509;
    expect_col[13] = -28'sd17401;
    expect_col[14] = 28'sd14666;
    expect_col[15] = 28'sd37697;
    testname = "load";
    repeat (3) @(negedge clk);
    rst_n = 1;
    @(negedge clk);

    // Stream the tile in, as a host or a DMA engine would.
    load_start = 1;
    @(negedge clk);
    load_start = 0;
    for (i = 0; i < 1024; i = i + 1) begin
      load_data = (i * 7919 + 13) % 251 - 125;
      load_valid = 1;
      @(negedge clk);
    end
    load_valid = 0;
    @(negedge clk);
    checks = checks + 1;
    if (load_count !== 1024) begin
      $display("TB_FAIL test=%0s expected_acc=%0d got_acc=%0d",
               "load_count", 1024, load_count);
      $display("TB_RESULT: FAIL");
      $finish;
    end

    testname = "system";
    depth = 64;
    cols = 16;
    @(negedge clk);
    start = 1;
    @(negedge clk);
    start = 0;
    for (i = 0; i < 16 * (64 + 10) + 60; i = i + 1)
      @(negedge clk);
    checks = checks + 1;
    if (seen !== 16) begin
      $display("TB_FAIL test=%0s expected_acc=%0d got_acc=%0d",
               "column_count", 16, seen);
      $display("TB_RESULT: FAIL");
      $finish;
    end
    $display("TB_PROFILE tiles=%0d span_cycles=%0d latency_cycles=%0d",
             1, 1024, 64);
    $display("TB_PASS checks=%0d", checks);
    $display("TB_RESULT: PASS");
    $finish;
  end
endmodule
