"""The Qwen sequencer on a DDR bus, as the Zybo would run it.

qwen_full.py's testbench answers every memory port the next cycle, which
no DDR does. This wraps the same generated core, unchanged, for a real
memory system: the weights, the column constants and the KV cache sit in
DDR behind one 64-bit AXI3 master, the shape of a Zynq-7000 HP port, and
the norm gains in block RAM. Each DDR-backed port gets a line buffer
filled by 16-beat bursts. When a port's word is not there yet, the core's
clock is held, which on the FPGA is a BUFGCE, so none of the generated
blocks needed a stall input: they see memory that answers the next edge
of their own clock, however long that edge takes to come. KV writes go
out as single beats with byte strobes and update any line holding them.

The testbench's DDR model has a fixed latency and serves the weights from
the same 1 GB image through $fread. With --jitter every port also stalls
its ready and gaps its beats at random, as an interconnect shared with
the ARM would. The decoded token has to be the one the integer model and
the direct testbench chose.

Run: python3 zybo.py --work build_qfull1   (a qwen_full.py build)
"""
import argparse
import os
import re
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.abspath(__file__))


def widths(core_src):
    """Port widths as the generated core declares them."""
    def w(name):
        m = re.search(r"\[(\d+):0\]\s+%s\b" % name, core_src)
        return int(m.group(1)) + 1
    out = {n: w(n) for n in ("tok", "pos", "w_addr", "c_addr", "g_addr",
                              "k_raddr", "v_raddr", "c_data", "w_data")}
    out["N"] = out["w_data"] // 16         # lanes
    if "input emb_en" in core_src:
        out["x_addr"] = w("x_addr")          # a pipeline stage's core
    if "output reg g_req" in core_src:
        out["gx_addr"] = w("gx_addr")        # a tensor-parallel rank's
    return out


def _bits(v, hi, lo):
    return "%s[%d]" % (v, hi) if hi == lo else "%s[%d:%d]" % (v, hi, lo)


def render_top(W, gwords, cb, kb, vb, np_=4, wbase=0, ns=32):
    """The bridge for a core of N lanes: a weight word is N int8s in DDR
    and a KV word N 16-bit lanes. Weight lines are one 8-beat burst, 64
    bytes, and KV lines one 16-beat burst, 128, so both hold 64 / N
    words."""
    wa, ca, ga, ka, va = (W["w_addr"], W["c_addr"], W["g_addr"],
                          W["k_raddr"], W["v_raddr"])
    n = W["N"]
    assert n in (8, 16, 32)
    lb = (n - 1).bit_length()                # lane index bits
    wpl = 64 // n                            # words a line
    wlb = max(1, (wpl - 1).bit_length())
    kbb = (n // 4 - 1).bit_length()          # beat bits within a KV word
    stage = "x_addr" in W
    sports = ("  // A pipeline stage: the hidden state in and out, on the core's edges.\n"
              "  input emb_en, input x_we, input [%d:0] x_addr, input signed [15:0] x_wdata,\n"
              "  output signed [15:0] x_rdata,\n" % (W["x_addr"] - 1)) if stage else ""
    sconn = ("    .emb_en(emb_en), .x_we(x_we), .x_addr(x_addr), .x_wdata(x_wdata),\n"
             "    .x_rdata(x_rdata),\n") if stage else ""
    if "gx_addr" in W:
        sports += ("  // A tensor-parallel rank: its gathers, on the core's edges.\n"
                   "  output g_req, output [2:0] g_vec, input g_done,\n"
                   "  input gx_we, input [%d:0] gx_addr, input signed [15:0] gx_wdata,\n"
                   "  output signed [15:0] gx_rdata,\n" % (W["gx_addr"] - 1))
        sconn += ("    .g_req(g_req), .g_vec(g_vec), .g_done(g_done), .gx_we(gx_we),\n"
                  "    .gx_addr(gx_addr), .gx_wdata(gx_wdata), .gx_rdata(gx_rdata),\n")
    return """// GENERATED by zybo.py: do not edit by hand.
// The generated Qwen sequencer on one 64-bit AXI3 master. Weights,
// column constants and the KV cache are in DDR; the gains in block RAM.
// The core's clock is held while any port's word is still on the bus.
module qwen_zybo (
  input clk, input rst_n, input start, input head_en,
  input [{twm}:0] tok, input [{pwm}:0] pos,
  output [{twm}:0] next_tok, output signed [15:0] best,
  output done, output busy,
{sports}{wports}  // Constants and the KV cache.
  output reg [31:0] araddr, output [3:0] arlen, output reg arvalid,
  input arready, input [63:0] rdata, input rvalid, input rlast,
  output rready,
  output reg [31:0] awaddr, output [3:0] awlen, output reg awvalid,
  input awready, output reg [63:0] wdata, output reg [7:0] wstrb,
  output wlast, output reg wvalid, input wready, input bvalid,
  output bready,
  output reg [31:0] core_cycles
);
  assign arlen = 4'd15; assign awlen = 4'd0; assign wlast = 1'b1;
{wassign}
  assign rready = 1'b1; assign bready = 1'b1;

  // ---- the core, on a clock held while memory catches up
  reg ce_l;
`ifdef SIM
  wire cclk = clk & ce_l;
`else
  wire cclk;
  BUFGCE bg (.I(clk), .CE(ce_l), .O(cclk));
`endif
  wire [{wam}:0] w_addr; wire [{cam}:0] c_addr; wire [{gam}:0] g_addr;
  wire [{kam}:0] k_raddr, kw0_addr, kw1_addr;
  wire [{vam}:0] v_raddr, vw_addr;
  wire kw0_en, kw1_en, vw_en;
  wire [{lbm}:0] kw0_lane, kw1_lane, vw_lane;
  wire signed [15:0] kw0_data, kw1_data, vw_data;
  wire [{lwm}:0] w_data, k_rdata, v_rdata;
  wire [{cdm}:0] c_data;
  reg signed [15:0] g_data;
  qwen_full core (.clk(cclk), .rst_n(rst_n), .start(start), .head_en(head_en),
    .tok(tok), .pos(pos), .w_addr(w_addr), .w_data(w_data), .c_addr(c_addr),
    .c_data(c_data), .g_addr(g_addr), .g_data(g_data), .k_raddr(k_raddr),
    .k_rdata(k_rdata), .v_raddr(v_raddr), .v_rdata(v_rdata),
    .kw0_en(kw0_en), .kw0_addr(kw0_addr), .kw0_lane(kw0_lane), .kw0_data(kw0_data),
    .kw1_en(kw1_en), .kw1_addr(kw1_addr), .kw1_lane(kw1_lane), .kw1_data(kw1_data),
    .vw_en(vw_en), .vw_addr(vw_addr), .vw_lane(vw_lane), .vw_data(vw_data),
{sconn}    .next_tok(next_tok), .best(best), .done(done), .busy(busy));

  // ---- gains: block RAM, read on the core's own edge
  reg signed [15:0] gmem [0:{gn}];
  initial $readmemh("gains.hex", gmem);

  // ---- line buffers: the address each port was given at the core's
  // last edge, and the line that holds it.
  reg [{wam}:0] wq; reg [{cam}:0] cq; reg [{kam}:0] kq; reg [{vam}:0] vq;
  reg [{lwm}:0] kl [0:{kpm}], vl [0:{kpm}];
  reg [63:0] cl [0:15];
  reg [{cam}:0] cbase; reg [{kam}:0] kbl; reg [{vam}:0] vbl;
  reg cv, kv, vv;

{streamer}  wire hc = cv && (cq >> 4) == (cbase >> 4);
  wire hk = kv && (kq >> {wlb}) == (kbl >> {wlb});
  wire hv = vv && (vq >> {wlb}) == (vbl >> {wlb});
{wdata}
  assign c_data = cl[cq[3:0]][{cdm}:0];
  assign k_rdata = kl[kq[{wlbm}:0]];
  assign v_rdata = vl[vq[{wlbm}:0]];

  // Writes the core has issued since its last edge, not yet on the bus.
  reg d0, d1, d2;
  wire p0 = kw0_en && !d0, p1 = kw1_en && !d1, p2 = vw_en && !d2;
  wire ce_n = hw && hc && hk && hv && !p0 && !p1 && !p2;
  always @(negedge clk) ce_l <= rst_n ? ce_n : 1'b1;

  // ---- one AXI master, one transaction at a time
  localparam F_IDLE = 3'd0, F_AR = 3'd1, F_R = 3'd2, F_AW = 3'd3, F_W = 3'd4, F_B = 3'd5;
  reg [2:0] fs;
  reg [1:0] port;               // 0 weights, 1 constants, 2 K, 3 V
  reg [3:0] beat;
  reg [1:0] wsel;
  reg [{kam}:0] waddr_w;
  reg [{lbm}:0] wlane;
  reg signed [15:0] wval;
  reg wisv;
  wire [{lwm}:0] lane_mask = {lw}'hffff << (wlane * 16);
  always @(posedge clk) begin
    if (!rst_n) begin
      fs <= F_IDLE; arvalid <= 1'b0; awvalid <= 1'b0; wvalid <= 1'b0;
      cv <= 1'b0; kv <= 1'b0; vv <= 1'b0; d0 <= 1'b0; d1 <= 1'b0;
      d2 <= 1'b0; wq <= 0; curns <= NS; cq <= 0; kq <= 0; vq <= 0; core_cycles <= 0;
    end else begin
      // The core takes an edge now: capture its addresses as a registered
      // memory would, and clear the write flags for its new outputs.
      if (ce_l) begin
        wq <= w_addr; cq <= c_addr; kq <= k_raddr; vq <= v_raddr;
        curns <= (w_addr >> {wlb}) + NS;
        g_data <= gmem[g_addr];
        d0 <= 1'b0; d1 <= 1'b0; d2 <= 1'b0;
        core_cycles <= core_cycles + 1;
      end
      case (fs)
        F_IDLE: if (!ce_l) begin
          if (p0 || p1 || p2) begin
            // A KV write: one beat, the lane's two bytes strobed.
            wsel <= p0 ? 2'd0 : p1 ? 2'd1 : 2'd2;
            waddr_w <= p0 ? kw0_addr : p1 ? kw1_addr : vw_addr;
            wlane <= p0 ? kw0_lane : p1 ? kw1_lane : vw_lane;
            wval <= p0 ? kw0_data : p1 ? kw1_data : vw_data;
            wisv <= !(p0 || p1);
            awaddr <= (p0 || p1 ? 32'd{kb} : 32'd{vb})
                      + (p0 ? kw0_addr : p1 ? kw1_addr : vw_addr) * {kvb}
                      + ((p0 ? kw0_lane : p1 ? kw1_lane : vw_lane) >> 2) * 8;
            awvalid <= 1'b1; fs <= F_AW;
          end else if (!hc) begin
            port <= 2'd1; araddr <= 32'd{cb} + (cq >> 4) * 128; cbase <= cq; cv <= 1'b0;
            arvalid <= 1'b1; beat <= 0; fs <= F_AR;
          end else if (!hk) begin
            port <= 2'd2; araddr <= 32'd{kb} + (kq >> {wlb}) * 128; kbl <= kq; kv <= 1'b0;
            arvalid <= 1'b1; beat <= 0; fs <= F_AR;
          end else if (!hv) begin
            port <= 2'd3; araddr <= 32'd{vb} + (vq >> {wlb}) * 128; vbl <= vq; vv <= 1'b0;
            arvalid <= 1'b1; beat <= 0; fs <= F_AR;
          end
        end
        F_AR: if (arready) begin arvalid <= 1'b0; fs <= F_R; end
        F_R: if (rvalid) begin
          case (port)
            2'd1: cl[beat] <= rdata;
            2'd2: kl[{kbw}][{kbp} * 64 +: 64] <= rdata;
            2'd3: vl[{kbw}][{kbp} * 64 +: 64] <= rdata;
          endcase
          beat <= beat + 1;
          if (rlast) begin
            fs <= F_IDLE;
            case (port) 2'd1: cv <= 1'b1; 2'd2: kv <= 1'b1;
                        2'd3: vv <= 1'b1; endcase
          end
        end
        F_AW: if (awready) begin
          awvalid <= 1'b0; wvalid <= 1'b1;
          wdata <= {{48'd0, wval}} << (wlane[1:0] * 16);
          wstrb <= 8'b11 << (wlane[1:0] * 2);
          // A line already holding this word takes the write too.
          if (!wisv && kv && (waddr_w >> {wlb}) == (kbl >> {wlb}))
            kl[waddr_w[{wlbm}:0]] <= (kl[waddr_w[{wlbm}:0]] & ~lane_mask)
                                | ({{{pad}'d0, wval}} << (wlane * 16));
          if (wisv && vv && (waddr_w >> {wlb}) == (vbl >> {wlb}))
            vl[waddr_w[{wlbm}:0]] <= (vl[waddr_w[{wlbm}:0]] & ~lane_mask)
                                | ({{{pad}'d0, wval}} << (wlane * 16));
          fs <= F_W;
        end
        F_W: if (wready) begin wvalid <= 1'b0; fs <= F_B; end
        F_B: if (bvalid) begin
          case (wsel) 2'd0: d0 <= 1'b1; 2'd1: d1 <= 1'b1; default: d2 <= 1'b1; endcase
          fs <= F_IDLE;
        end
        default: fs <= F_IDLE;
      endcase
    end
  end
endmodule
""".format(twm=W["tok"] - 1, pwm=W["pos"] - 1, wam=wa - 1, cam=ca - 1,
           gam=ga - 1, kam=ka - 1, vam=va - 1, gn=gwords - 1, cb=cb, kb=kb,
           vb=vb, streamer=render_streamer(np_, wa - 1, ns=ns, wbase=wbase, n=n),
           sports=sports, sconn=sconn, cdm=W["c_data"] - 1,
           wports=render_wports(np_, n)[0], wassign=render_wports(np_, n)[1],
           wdata=render_wports(np_, n)[2], lbm=lb - 1, lwm=16 * n - 1,
           lw=16 * n, pad=16 * n - 16, kpm=wpl - 1, wlb=wlb, wlbm=wlb - 1,
           kvb=2 * n, kbw=_bits("beat", 3, kbb), kbp=_bits("beat", kbb - 1, 0))


def render_streamer(np_, wam, ns=32, wbase=0, n=16):
    """The weight streamer over np_ read masters: line L on master L % np_,
    ns slots, slot s always filled through master s % np_, so each slot's
    requests and responses stay in one in-order stream. Slot memory is
    banked by master, so np_ arrivals a cycle never share a bank. With 8
    slots over four masters each had two lines in flight, too few to cover
    the latency: 2.77 bus cycles a core cycle. 32 gives each eight."""
    per = ns // np_
    sb = (ns - 1).bit_length()
    wpl = 64 // n                   # weight words a 64-byte line
    wlb = (wpl - 1).bit_length()
    bb = (n // 8 - 1).bit_length()  # beat bits within a word
    L = []
    a = L.append
    a("  // ---- the weight streamer: %d line slots, direct mapped, filled up" % ns)
    a("  // to 4 bursts per master ahead of the line the core is on, lines")
    a("  // striped over %d read masters. Each slot is filled through one" % np_)
    a("  // master only, so a line requested later always lands later.")
    a("  localparam NS = %d, MAXO = 8;" % ns)
    for p in range(np_):
        a("  reg [%d:0] swb%d [0:%d];" % (8 * n - 1, p, per * wpl - 1))
    a("  reg [%d:0] stag [0:NS - 1];" % wam)
    a("  reg sval [0:NS - 1];")
    a("  // A slot with a burst still in flight takes no second request: two")
    a("  // for one slot (X, then Y after the stream moved on, then X again")
    a("  // after a jump back) let X's first copy mark the slot valid and")
    a("  // Y's beats then overwrite it, and the core read Y's weights as X's.")
    a("  // With one burst a slot, the only one that can land in a slot is")
    a("  // the line its tag names.")
    a("  reg pend [0:NS - 1];")
    a("  wire [%d:0] cur = wq >> %d;" % (wam, wlb))
    a("  wire [%d:0] cs = cur[%d:0];" % (sb - 1, sb - 1))
    a("  wire hw = sval[cs] && stag[cs] == cur;")
    a("  reg [%d:0] nreq;" % wam)
    a("  wire [%d:0] ns = nreq[%d:0];" % (sb - 1, sb - 1))
    a("  // The window's end and the next line, registered with the values")
    a("  // they come from, so the issue decision has no adder in it: with")
    a("  // them the bridge clock's worst path was 11 LUTs through two adders.")
    a("  reg [%d:0] curns, pcur1;" % (wam + 1))
    a("  wire in_win = nreq >= cur && nreq < curns;")
    a("  // A full window is a reason to wait, not to restart. Treating it as")
    a("  // a jump restarted the stream at the core's line and re-walked 32")
    a("  // lines it already held before issuing a new one: 2.15 bus cycles a")
    a("  // core cycle, all of the excess weight misses in the head.")
    a("  reg [%d:0] pcur;" % wam)
    a("  // A jump seen while a request waits for arready is kept until the")
    a("  // stream can restart: seen for one cycle only, a jump back under a")
    a("  // stalled arready was lost and left nreq past the window for good,")
    a("  // a deadlock the always-ready DDR model never showed. A stream past")
    a("  // the window can only follow a jump back, so it counts as one too.")
    a("  reg jl;")
    a("  wire jumped = jl || (cur != pcur && cur != pcur1) || nreq < cur")
    a("               || nreq > curns;")
    a("  // What the stream knows of the slot nreq names, registered: its tag")
    a("  // is nreq (tm_r), the line is held or on its way (sp_r), a burst is")
    a("  // still in flight to it (pd_r). Each is computed a cycle ahead for")
    a("  // the line nreq moves to, the next one or the core's on a restart,")
    a("  // so the issue decision reads flip-flops rather than a 32-way tag")
    a("  // mux and compare: that path, into every tag's enable, held the")
    a("  // 32-lane ZC706 build's bus clock to 47 MHz. tm_r and sp_r are")
    a("  // exact; pd_r can lag a landing burst by a cycle, which only")
    a("  // delays an issue, never lets one into a slot still in flight.")
    a("  reg tm_r, sp_r, pd_r;")
    a("  wire [%d:0] ns1 = ns + 1'b1;" % (sb - 1))
    a("  wire [%d:0] cs_ = cur[%d:0];" % (sb - 1, sb - 1))
    a("  // Held, or on its way: either way the stream moves past it.")
    a("  wire have = tm_r && sp_r;")
    anyv = " || ".join("w%d_arvalid" % p for p in range(np_))
    a("  wire anyv = %s;" % anyv)
    for p in range(np_):
        a("  reg [3:0] out%d;" % p)
        a("  reg [%d:0] inf%d [0:MAXO - 1];" % (wam, p))
        a("  reg [2:0] ih%d, it%d;" % (p, p))
        a("  reg [3:0] wb%d;" % p)
    pb = max(1, (np_ - 1).bit_length())
    a("  wire [%d:0] np_sel = nreq[%d:0];" % (pb - 1, pb - 1) if np_ > 1
      else "  wire np_sel = 1'b0;")
    a("  integer si;")
    a("  always @(posedge clk) begin")
    a("    if (!rst_n) begin")
    a("      nreq <= 0; pcur <= 0; pcur1 <= 1; jl <= 1'b0;")
    a("      tm_r <= 1'b1; sp_r <= 1'b0; pd_r <= 1'b0;")
    for p in range(np_):
        a("      w%d_arvalid <= 1'b0; out%d <= 0; ih%d <= 0; it%d <= 0; wb%d <= 0;"
          % (p, p, p, p, p))
    a("      for (si = 0; si < NS; si = si + 1) begin sval[si] <= 1'b0; pend[si] <= 1'b0; stag[si] <= 0; end")
    a("    end else begin")
    for p in range(np_):
        a("      if (w%d_arvalid && w%d_arready) w%d_arvalid <= 1'b0;" % (p, p, p))
    a("      // A jump, to a new projection or back to the start of one:")
    a("      // restart the stream at the core's line.")
    a("      pcur <= cur; pcur1 <= cur + 1;")
    a("      jl <= jumped && anyv;")
    a("      // nreq held: its slot's flags stand, but a burst may land.")
    a("      pd_r <= pend[ns];")
    a("      if (jumped && !anyv) begin")
    a("        nreq <= cur;")
    a("        tm_r <= stag[cs_] == cur; sp_r <= sval[cs_] || pend[cs_]; pd_r <= pend[cs_];")
    a("      end else if (in_win && have) begin")
    a("        nreq <= nreq + 1;")
    a("        tm_r <= stag[ns1] == nreq + 1; sp_r <= sval[ns1] || pend[ns1]; pd_r <= pend[ns1];")
    a("      end else if (in_win) begin")
    a("        case (np_sel)")
    for p in range(np_):
        a("          %d: if (!w%d_arvalid && out%d < MAXO && !pd_r) begin" % (p, p, p))
        a("            w%d_araddr <= 32'd%d + nreq * 64; w%d_arvalid <= 1'b1;" % (p, wbase, p))
        a("            sval[ns] <= 1'b0; pend[ns] <= 1'b1; stag[ns] <= nreq;")
        a("            inf%d[it%d] <= nreq; it%d <= it%d + 1; nreq <= nreq + 1;" % (p, p, p, p))
        a("            tm_r <= stag[ns1] == nreq + 1; sp_r <= sval[ns1] || pend[ns1]; pd_r <= pend[ns1];")
        a("          end")
    a("          default: ;")
    a("        endcase")
    a("      end")
    for p in range(np_):
        a("      if (w%d_rvalid) begin" % p)
        a("        swb%d[(inf%d[ih%d][%d:0] / %d) * %d + %s][%s * 64 +: 64] <= w%d_rdata;"
          % (p, p, p, sb - 1, np_, wpl, _bits("wb%d" % p, 2, bb), _bits("wb%d" % p, bb - 1, 0), p))
        a("        wb%d <= wb%d + 1;" % (p, p))
        a("        if (w%d_rlast) begin" % p)
        a("          sval[inf%d[ih%d][%d:0]] <= 1'b1; pend[inf%d[ih%d][%d:0]] <= 1'b0;"
          % (p, p, sb - 1, p, p, sb - 1))
        a("          ih%d <= ih%d + 1;" % (p, p))
        a("        end")
        a("      end")
        a("      case ({w%d_arvalid && w%d_arready, w%d_rvalid && w%d_rlast})"
          % (p, p, p, p))
        a("        2'b10: out%d <= out%d + 1;" % (p, p))
        a("        2'b01: out%d <= out%d - 1;" % (p, p))
        a("        default: ;")
        a("      endcase")
    a("    end")
    a("  end")
    return "\n".join(L) + "\n"


def render_wports(np_, n=16):
    ports = "".join(
        "  output reg [31:0] w%d_araddr, output [3:0] w%d_arlen, output reg w%d_arvalid,\n"
        "  input w%d_arready, input [63:0] w%d_rdata, input w%d_rvalid, input w%d_rlast,\n"
        "  output w%d_rready,\n" % ((p,) * 8) for p in range(np_))
    assign = " ".join("assign w%d_arlen = 4'd7; assign w%d_rready = 1'b1;" % (p, p)
                      for p in range(np_))
    sel = "cs %% %d" % np_
    wpl = 64 // n
    wsel = _bits("wq", (wpl - 1).bit_length() - 1, 0)
    arms = " : ".join("(%s == %d) ? swb%d[(cs / %d) * %d + %s]" % (sel, p, p, np_, wpl, wsel)
                      for p in range(np_ - 1))
    last = "swb%d[(cs / %d) * %d + %s]" % (np_ - 1, np_, wpl, wsel)
    # DDR holds the weights as int8, N to a word; the core's word has
    # them in 16-bit lanes, so each byte is sign-extended here. Half the
    # memory, and half the bus traffic, of storing the lanes.
    ext = ", ".join("{{8{wpk[%d]}}, wpk[%d:%d]}" % (8 * j + 7, 8 * j + 7, 8 * j)
                    for j in range(n - 1, -1, -1))
    wdata = ("  wire [%d:0] wpk = %s;\n  assign w_data = {%s};"
             % (8 * n - 1, (arms + " : " + last) if np_ > 1 else last, ext))
    return ("  // Weights: their own read masters, streaming ahead of the core.\n"
            + ports), "  " + assign, wdata


TB = """`timescale 1ns/1ps
module tb_zybo;
  reg clk = 0, rst_n = 0, start = 0, head_en = 0;
  reg [%(twm)d:0] tok = 0;
  reg [%(pwm)d:0] pos = 0;
  wire [%(twm)d:0] next_tok;
  wire signed [15:0] best;
  wire done, busy;
  wire [31:0] araddr, awaddr, core_cycles;
  wire [3:0] arlen, awlen;
  wire arvalid, rready, awvalid, wvalid, wlast, bready;
  reg arready = 0, rvalid = 0, rlast = 0, awready = 0, wready = 0, bvalid = 0;
  reg [63:0] rdata = 0;
%(wdecl)s  wire [63:0] wdata;
  wire [7:0] wstrb;
  always #5 clk = ~clk;
  // JIT: the DDR ports stall arready and put gaps between beats at
  // random, as an interconnect shared with the ARM would.
  localparam JIT = %(jit)d;
%(dut)s
  // ---- DDR: weights from the image on disk, the rest in arrays
  reg [63:0] cmem [0:%(cn)d];
  reg [%(cdm)d:0] c62 [0:%(cn)d];
  reg [%(LW)d:0] km [0:%(kn)d];
  reg [%(LW)d:0] vm [0:%(vn)d];
  integer fd8, r, i, cyc = 0, t0 = 0, c0 = 0, lat;
  reg [%(LW)d:0] t;
  reg [31:0] ra;
  reg [3:0] rn;
  always @(posedge clk) cyc = cyc + 1;
  // A heartbeat, so a stalled bus reads as a stall and not as slowness.
  always @(posedge clk) if (cyc %% 10000000 == 0 && cyc > 0) begin
    $display("PROGRESS clk=%%0d core=%%0d bus_state=%%0d", cyc, core_cycles, %(fs)s);
    $fflush;
  end
  // This master reads the constants and the KV cache; the weights
  // have their own.
  function [63:0] beat_at(input [31:0] a);
    begin
      if (a < %(kb)d) beat_at = cmem[(a - %(cb)d) / 8];
      else if (a < %(vb)d) begin t = km[(a - %(kb)d) / %(KB)d]; beat_at = t[((a %% %(KB)d) / 8) * 64 +: 64]; end
      else begin t = vm[(a - %(vb)d) / %(KB)d]; beat_at = t[((a %% %(KB)d) / 8) * 64 +: 64]; end
    end
  endfunction
  // Reads: address accepted, then %(lat)d cycles of latency, then the burst.
  // Both bus processes wait for reset to be released and compare with
  // !==: before reset the master's valids are X, and !X is false, so a
  // plain test ran a phantom write at cycle 2 and then waited forever
  // for its data beat while the real first write waited for awready.
  initial begin
    @(posedge rst_n);
    forever begin
      @(posedge clk); while (arvalid !== 1'b1) @(posedge clk);
      while (JIT && {$random} %% 3 == 0) @(posedge clk);
      arready <= 1; ra = araddr; rn = arlen;
      @(posedge clk); arready <= 0;
      repeat (%(lat)d) @(posedge clk);
      for (i = 0; i <= rn; i = i + 1) begin
        while (JIT && {$random} %% 4 == 0) begin rvalid <= 0; rlast <= 0; @(posedge clk); end
        rdata <= beat_at(ra + i * 8); rvalid <= 1; rlast <= (i == rn);
        @(posedge clk);
      end
      rvalid <= 0; rlast <= 0;
    end
  end
%(wresp)s  // Writes: one beat, strobed, into the KV arrays.
  reg [31:0] wa;
  reg [%(LW)d:0] tw;              // not t: the read process's function uses t
  integer b, base;
  initial begin
    @(posedge rst_n);
    forever begin
      @(posedge clk); while (awvalid !== 1'b1) @(posedge clk);
      while (JIT && {$random} %% 3 == 0) @(posedge clk);
      awready <= 1; wa = awaddr; @(posedge clk); awready <= 0;
      while (wvalid !== 1'b1) @(posedge clk);
      wready <= 1;
      if (wa >= %(vb)d) begin tw = vm[(wa - %(vb)d) / %(KB)d]; base = ((wa - %(vb)d) %% %(KB)d) * 8; end
      else begin tw = km[(wa - %(kb)d) / %(KB)d]; base = ((wa - %(kb)d) %% %(KB)d) * 8; end
      for (b = 0; b < 8; b = b + 1) if (wstrb[b]) tw[base + b * 8 +: 8] = wdata[b * 8 +: 8];
      if (wa >= %(vb)d) vm[(wa - %(vb)d) / %(KB)d] = tw; else km[(wa - %(kb)d) / %(KB)d] = tw;
      @(posedge clk); wready <= 0;
      repeat (4) @(posedge clk); bvalid <= 1; @(posedge clk); bvalid <= 0;
    end
  end
%(step)s  initial begin
    fd8 = $fopen("weights8.bin", "rb");
    // Without it every weight read is X, and the timing, which does
    // not depend on the data, would still look right.
    if (fd8 == 0) begin $display("FAIL: no weights8.bin in the build"); $finish; end
    $readmemh("cparams.hex", c62);
    for (i = 0; i <= %(cn)d; i = i + 1) cmem[i] = c62[i];
    for (i = 0; i <= %(kn)d; i = i + 1) km[i] = 0;
    for (i = 0; i <= %(vn)d; i = i + 1) vm[i] = 0;
    repeat (4) @(negedge clk); rst_n = 1; repeat (4) @(negedge clk);
%(steps)s
    $finish;
  end
endmodule
"""


def render_tb_weights(np_, lat, wbase=0):
    """One queued DDR port per weight master: reads accepted as fast as
    they come, each answered after its latency, bursts back to back."""
    decl, conn, resp = [], [], []
    for p in range(np_):
        decl.append("  wire [31:0] w%(p)d_araddr;\n  wire [3:0] w%(p)d_arlen;\n"
                    "  wire w%(p)d_arvalid, w%(p)d_rready;\n"
                    "  reg w%(p)d_arready = 1, w%(p)d_rvalid = 0, w%(p)d_rlast = 0;\n"
                    "  reg [63:0] w%(p)d_rdata = 0;\n" % {"p": p})
        conn.append("    .w%(p)d_araddr(w%(p)d_araddr), .w%(p)d_arlen(w%(p)d_arlen),\n"
                    "    .w%(p)d_arvalid(w%(p)d_arvalid), .w%(p)d_arready(w%(p)d_arready),\n"
                    "    .w%(p)d_rdata(w%(p)d_rdata), .w%(p)d_rvalid(w%(p)d_rvalid),\n"
                    "    .w%(p)d_rlast(w%(p)d_rlast), .w%(p)d_rready(w%(p)d_rready),\n"
                    % {"p": p})
        resp.append("""  reg [31:0] qa%(p)d [0:15];
  integer qt%(p)d [0:15];
  integer qh%(p)d = 0, qn%(p)d = 0, j%(p)d;
  reg [63:0] ww%(p)d;
  always @(posedge clk) if (JIT) w%(p)d_arready <= {$random} %% 4 != 0;
  always @(posedge clk) if (rst_n && w%(p)d_arvalid && w%(p)d_arready) begin
    qa%(p)d[qn%(p)d %% 16] = w%(p)d_araddr; qt%(p)d[qn%(p)d %% 16] = cyc; qn%(p)d = qn%(p)d + 1;
  end
  initial begin
    @(posedge rst_n);
    forever begin
      @(posedge clk);
      if (qh%(p)d < qn%(p)d && cyc >= qt%(p)d[qh%(p)d %% 16] + %(lat)d) begin
        for (j%(p)d = 0; j%(p)d < 8; j%(p)d = j%(p)d + 1) begin
          while (JIT && {$random} %% 4 == 0) begin
            w%(p)d_rvalid <= 0; w%(p)d_rlast <= 0; @(posedge clk);
          end
          // The eight bytes at this beat's address, the lowest on
          // rdata[7:0] as AXI has them; $fread puts the first byte high.
          // Every port shares the file, so every beat seeks.
          r = $fseek(fd8, qa%(p)d[qh%(p)d %% 16] - %(wb)d + j%(p)d * 8, 0);
          r = $fread(ww%(p)d, fd8);
          w%(p)d_rdata <= {ww%(p)d[7:0], ww%(p)d[15:8], ww%(p)d[23:16], ww%(p)d[31:24],
                        ww%(p)d[39:32], ww%(p)d[47:40], ww%(p)d[55:48], ww%(p)d[63:56]};
          w%(p)d_rvalid <= 1; w%(p)d_rlast <= (j%(p)d == 7);
          @(posedge clk);
        end
        w%(p)d_rvalid <= 0; w%(p)d_rlast <= 0; qh%(p)d = qh%(p)d + 1;
      end
    end
  end
""" % {"p": p, "lat": lat, "wb": wbase})
    return "".join(decl), "".join(conn), "".join(resp)


DUT = """  qwen_zybo dut (.clk(clk), .rst_n(rst_n), .start(start), .head_en(head_en),
    .tok(tok), .pos(pos), .next_tok(next_tok), .best(best), .done(done),
    .busy(busy),
%(wconn)s    .araddr(araddr), .arlen(arlen), .arvalid(arvalid),
    .arready(arready), .rdata(rdata), .rvalid(rvalid), .rlast(rlast),
    .rready(rready), .awaddr(awaddr), .awlen(awlen), .awvalid(awvalid),
    .awready(awready), .wdata(wdata), .wstrb(wstrb), .wlast(wlast),
    .wvalid(wvalid), .wready(wready), .bvalid(bvalid), .bready(bready),
    .core_cycles(core_cycles));
"""

STEP = """  task step(input integer tk, input integer p, input integer he);
    begin
      tok = tk; pos = p; head_en = he;
      @(negedge clk); start = 1; t0 = cyc; c0 = core_cycles;
      @(negedge clk); while (!busy) @(negedge clk); start = 0;
      while (!done) @(negedge clk);
      $display("STEP pos=%0d tok=%0d clk_cycles=%0d core_cycles=%0d next=%0d",
               p, tk, cyc - t0, core_cycles - c0, next_tok);
      $fflush;
    end
  endtask
"""


def lanes(work):
    """The core's lane count, from the w_data port it declares."""
    core = open(os.path.join(work, "qwen_full.v")).read()
    return int(re.search(r"input \[(\d+):0\] w_data", core).group(1)) // 16 + 1


def _w8_block(blk, n):
    """weights.bin words to DDR bytes: lane j's low byte, the int8, at
    byte j of its word. The ARM copies the file into DDR byte for byte
    and AXI is little-endian, so byte j reaches the core as w_data lane
    j. weights.bin is in $fread's order, lane n - 1 first."""
    out = bytearray(len(blk) // 2)
    for j in range(n):
        out[j::n] = blk[(n - 1 - j) * 2 + 1::2 * n]
    return out


def write_w8(work):
    """The DDR image of the weights, int8, one N-byte word per core word
    (see _w8_block). Rewritten when the one on disk is not this build's,
    by size or by its first megabyte."""
    n = lanes(work)
    src = os.path.join(work, "weights.bin")
    w8 = os.path.join(work, "weights8.bin")
    with open(src, "rb") as f:
        head = _w8_block(f.read(2 << 20), n)
    if os.path.exists(w8) and os.path.getsize(w8) == os.path.getsize(src) // 2:
        with open(w8, "rb") as g:
            if g.read(len(head)) == head:
                return w8
    tmp = w8 + ".tmp"
    with open(src, "rb") as f, open(tmp, "wb") as g:
        while True:
            blk = f.read(32 << 20)
            if not blk:
                break
            g.write(_w8_block(blk, n))
    # A new file, not the old one rewritten: an SD card's hard link to
    # the old image is then seen to be stale.
    os.replace(tmp, w8)
    return w8


def layout(work, base=0):
    """Where each region sits in DDR, from a qwen_full.py build: the int8
    weights from base, then the column constants and the K and V caches,
    each on a 4 KB boundary. Addresses are absolute bus addresses."""
    core = open(os.path.join(work, "qwen_full.v")).read()
    old = open(os.path.join(work, "tb_qfull.v")).read()
    size = lambda name: int(re.search(r"%s \[0:(\d+)\]" % name, old).group(1)) + 1
    n = lanes(work)
    L = dict(W=widths(core), cn=size("cmem"), gn=size("gmem"),
             kn=size("km"), vn=size("vm"), N=n,
             words=os.path.getsize(os.path.join(work, "weights.bin")) // (2 * n))
    align = lambda x: (x + 4095) // 4096 * 4096
    # A weight word is n int8s in DDR; a KV word n 16-bit lanes.
    L["wb"] = base
    L["cb"] = align(base + L["words"] * n)
    L["kb"] = align(L["cb"] + L["cn"] * 8)
    L["vb"] = align(L["kb"] + L["kn"] * 2 * n)
    L["end"] = align(L["vb"] + L["vn"] * 2 * n)
    L["steps"] = [tuple(int(v) for v in re.findall(r"-?\d+", l))
                  for l in old.splitlines() if l.strip().startswith("step(")]
    return L


def tb_text(L, np_, lat, dut=DUT, step=STEP, fs="dut.fs", jit=0):
    wd, wc, wr = render_tb_weights(np_, lat, L["wb"])
    W = L["W"]
    return TB % dict(twm=W["tok"] - 1, pwm=W["pos"] - 1, cn=L["cn"] - 1, cdm=W["c_data"] - 1,
                     kn=L["kn"] - 1, vn=L["vn"] - 1, wb=L["wb"], cb=L["cb"],
                     LW=16 * L["N"] - 1, KB=2 * L["N"],
                     kb=L["kb"], vb=L["vb"], lat=lat, wdecl=wd, jit=jit,
                     wresp=wr, dut=dut % dict(wconn=wc), step=step, fs=fs,
                     steps="\n".join("    step(%d, %d, %d);" % s
                                     for s in L["steps"]))


def simulate(work, tb, top_srcs, sim="iverilog"):
    """Compile tb with the build's blocks and stream its output."""
    import vsim
    srcs = sorted(f for f in os.listdir(work) if f.endswith(".v")
                  and not f.startswith(("tb_", "bz_")) and f != "qwen_zybo.v")
    try:
        p = vsim.stream(work, [tb] + list(top_srcs) + srcs, sim, tag="z")
    except RuntimeError as e:
        print(str(e))
        sys.exit(1)
    t0 = time.time()
    for line in p.stdout:
        print(line.rstrip(), "(%.0f s)" % (time.time() - t0))
        sys.stdout.flush()
    p.wait()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", default=os.path.join(ROOT, "build_qfull1"))
    ap.add_argument("--latency", type=int, default=30)
    ap.add_argument("--ports", type=int, default=4,
                    help="weight read masters; the Zynq-7000 has four HP ports")
    ap.add_argument("--jitter", action="store_true",
                    help="random ready stalls and gaps between beats")
    ap.add_argument("--base", type=lambda v: int(v, 0), default=0,
                    help="DDR address of the weights")
    a = ap.parse_args()
    work = a.work
    write_w8(work)
    L = layout(work, a.base)
    with open(os.path.join(work, "qwen_zybo.v"), "w") as f:
        f.write(render_top(L["W"], L["gn"], L["cb"], L["kb"], L["vb"],
                           a.ports, L["wb"]))
    with open(os.path.join(work, "tb_zybo.v"), "w") as f:
        f.write(tb_text(L, a.ports, a.latency, jit=int(a.jitter)))
    simulate(work, "tb_zybo.v", ["qwen_zybo.v"])


if __name__ == "__main__":
    main()
