"""The Qwen sequencer on a DDR bus, as the Zybo would run it.

qwen_full.py's testbench answers every memory port the next cycle, which
no DDR does. This wraps the same generated core, unchanged, for a real
memory system: the weights, the column constants and the KV cache sit in
DDR behind one 64-bit AXI3 master, the shape of a Zynq-7000 HP port, and
the norm gains in block RAM. Each DDR-backed port gets a line buffer
filled by 16-beat bursts. When a port's word is not there yet, the core's
clock is held, which on the FPGA is a BUFGCE, so none of the generated
blocks needed a stall input: they see memory that answers the next edge
of their own clock, however long that edge takes to come. KV writes go
out as single beats with byte strobes and update any line holding them.

The testbench's DDR model has a fixed latency and serves the weights from
the same 1 GB image through $fread. The decoded token has to be the one
the integer model and the direct testbench chose.

Run: python3 zybo.py --work build_qfull1   (a qwen_full.py build)
"""
import argparse
import os
import re
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.abspath(__file__))


def widths(core_src):
    """Port widths as the generated core declares them."""
    def w(name):
        m = re.search(r"\[(\d+):0\]\s+%s\b" % name, core_src)
        return int(m.group(1)) + 1
    return {n: w(n) for n in ("tok", "pos", "w_addr", "c_addr", "g_addr",
                               "k_raddr", "v_raddr")}


def render_top(W, gwords, cb, kb, vb):
    wa, ca, ga, ka, va = (W["w_addr"], W["c_addr"], W["g_addr"],
                          W["k_raddr"], W["v_raddr"])
    return """// GENERATED by zybo.py: do not edit by hand.
// The generated Qwen sequencer on one 64-bit AXI3 master. Weights,
// column constants and the KV cache are in DDR; the gains in block RAM.
// The core's clock is held while any port's word is still on the bus.
module qwen_zybo (
  input clk, input rst_n, input start, input head_en,
  input [{twm}:0] tok, input [{pwm}:0] pos,
  output [{twm}:0] next_tok, output signed [15:0] best,
  output done, output busy,
  // Weights: their own read master, streaming ahead of the core.
  output reg [31:0] w_araddr, output [3:0] w_arlen, output reg w_arvalid,
  input w_arready, input [63:0] w_rdata, input w_rvalid, input w_rlast,
  output w_rready,
  // Constants and the KV cache.
  output reg [31:0] araddr, output [3:0] arlen, output reg arvalid,
  input arready, input [63:0] rdata, input rvalid, input rlast,
  output rready,
  output reg [31:0] awaddr, output [3:0] awlen, output reg awvalid,
  input awready, output reg [63:0] wdata, output reg [7:0] wstrb,
  output wlast, output reg wvalid, input wready, input bvalid,
  output bready,
  output reg [31:0] core_cycles
);
  assign arlen = 4'd15; assign awlen = 4'd0; assign wlast = 1'b1;
  assign w_arlen = 4'd15; assign w_rready = 1'b1;
  assign rready = 1'b1; assign bready = 1'b1;

  // ---- the core, on a clock held while memory catches up
  reg ce_l;
`ifdef SIM
  wire cclk = clk & ce_l;
`else
  wire cclk;
  BUFGCE bg (.I(clk), .CE(ce_l), .O(cclk));
`endif
  wire [{wam}:0] w_addr; wire [{cam}:0] c_addr; wire [{gam}:0] g_addr;
  wire [{kam}:0] k_raddr, kw0_addr, kw1_addr;
  wire [{vam}:0] v_raddr, vw_addr;
  wire kw0_en, kw1_en, vw_en;
  wire [3:0] kw0_lane, kw1_lane, vw_lane;
  wire signed [15:0] kw0_data, kw1_data, vw_data;
  wire [255:0] w_data, k_rdata, v_rdata;
  wire [61:0] c_data;
  reg signed [15:0] g_data;
  qwen_full core (.clk(cclk), .rst_n(rst_n), .start(start), .head_en(head_en),
    .tok(tok), .pos(pos), .w_addr(w_addr), .w_data(w_data), .c_addr(c_addr),
    .c_data(c_data), .g_addr(g_addr), .g_data(g_data), .k_raddr(k_raddr),
    .k_rdata(k_rdata), .v_raddr(v_raddr), .v_rdata(v_rdata),
    .kw0_en(kw0_en), .kw0_addr(kw0_addr), .kw0_lane(kw0_lane), .kw0_data(kw0_data),
    .kw1_en(kw1_en), .kw1_addr(kw1_addr), .kw1_lane(kw1_lane), .kw1_data(kw1_data),
    .vw_en(vw_en), .vw_addr(vw_addr), .vw_lane(vw_lane), .vw_data(vw_data),
    .next_tok(next_tok), .best(best), .done(done), .busy(busy));

  // ---- gains: block RAM, read on the core's own edge
  reg signed [15:0] gmem [0:{gn}];
  initial $readmemh("gains.hex", gmem);

  // ---- line buffers: the address each port was given at the core's
  // last edge, and the line that holds it.
  reg [{wam}:0] wq; reg [{cam}:0] cq; reg [{kam}:0] kq; reg [{vam}:0] vq;
  reg [255:0] kl [0:3], vl [0:3];
  reg [63:0] cl [0:15];
  reg [{cam}:0] cbase; reg [{kam}:0] kbl; reg [{vam}:0] vbl;
  reg cv, kv, vv;

  // ---- the weight streamer: 8 line slots, direct mapped, filled up to 4
  // bursts ahead of the line the core is on. Responses come back in
  // request order, so a line requested later always lands later.
  localparam NS = 8, MAXO = 4;
  reg [255:0] sw [0:NS * 4 - 1];
  reg [{wam}:0] stag [0:NS - 1];
  reg sval [0:NS - 1];
  wire [{wam}:0] cur = wq >> 2;
  wire [2:0] cs = cur[2:0];
  wire hw = sval[cs] && stag[cs] == cur;
  reg [{wam}:0] nreq;
  reg [2:0] outst;
  reg [{wam}:0] inflight [0:MAXO - 1];
  reg [1:0] ihead, itail;
  reg [3:0] wbeat;
  wire [2:0] ns = nreq[2:0];
  wire in_win = nreq >= cur && nreq < cur + NS;
  wire have = sval[ns] && stag[ns] == nreq;
  integer si;
  always @(posedge clk) begin
    if (!rst_n) begin
      w_arvalid <= 1'b0; nreq <= 0; outst <= 0; ihead <= 0; itail <= 0;
      wbeat <= 0;
      for (si = 0; si < NS; si = si + 1) begin sval[si] <= 1'b0; stag[si] <= 0; end
    end else begin
      // A jump, to a new projection or back to the start of one: restart
      // the stream at the core's line.
      if (!in_win && !w_arvalid) nreq <= cur;
      else if (w_arvalid) begin
        if (w_arready) begin w_arvalid <= 1'b0; nreq <= nreq + 1; end
      end else if (have) nreq <= nreq + 1;
      else if (outst < MAXO) begin
        w_araddr <= nreq * 128; w_arvalid <= 1'b1;
        sval[ns] <= 1'b0; stag[ns] <= nreq;
        inflight[itail] <= nreq; itail <= itail + 1;
      end
      if (w_rvalid) begin
        sw[inflight[ihead][2:0] * 4 + wbeat[3:2]][wbeat[1:0] * 64 +: 64] <= w_rdata;
        wbeat <= wbeat + 1;
        if (w_rlast) begin
          // Only if no later request has claimed the slot since.
          if (stag[inflight[ihead][2:0]] == inflight[ihead])
            sval[inflight[ihead][2:0]] <= 1'b1;
          ihead <= ihead + 1;
        end
      end
      case ({{w_arvalid && w_arready, w_rvalid && w_rlast}})
        2'b10: outst <= outst + 1;
        2'b01: outst <= outst - 1;
        default: ;
      endcase
    end
  end
  wire hc = cv && (cq >> 4) == (cbase >> 4);
  wire hk = kv && (kq >> 2) == (kbl >> 2);
  wire hv = vv && (vq >> 2) == (vbl >> 2);
  assign w_data = sw[cs * 4 + wq[1:0]];
  assign c_data = cl[cq[3:0]][61:0];
  assign k_rdata = kl[kq[1:0]];
  assign v_rdata = vl[vq[1:0]];

  // Writes the core has issued since its last edge, not yet on the bus.
  reg d0, d1, d2;
  wire p0 = kw0_en && !d0, p1 = kw1_en && !d1, p2 = vw_en && !d2;
  wire ce_n = hw && hc && hk && hv && !p0 && !p1 && !p2;
  always @(negedge clk) ce_l <= rst_n ? ce_n : 1'b1;

  // ---- one AXI master, one transaction at a time
  localparam F_IDLE = 3'd0, F_AR = 3'd1, F_R = 3'd2, F_AW = 3'd3, F_W = 3'd4, F_B = 3'd5;
  reg [2:0] fs;
  reg [1:0] port;               // 0 weights, 1 constants, 2 K, 3 V
  reg [3:0] beat;
  reg [1:0] wsel;
  reg [{kam}:0] waddr_w;
  reg [3:0] wlane;
  reg signed [15:0] wval;
  reg wisv;
  wire [255:0] lane_mask = 256'hffff << (wlane * 16);
  always @(posedge clk) begin
    if (!rst_n) begin
      fs <= F_IDLE; arvalid <= 1'b0; awvalid <= 1'b0; wvalid <= 1'b0;
      cv <= 1'b0; kv <= 1'b0; vv <= 1'b0; d0 <= 1'b0; d1 <= 1'b0;
      d2 <= 1'b0; wq <= 0; cq <= 0; kq <= 0; vq <= 0; core_cycles <= 0;
    end else begin
      // The core takes an edge now: capture its addresses as a registered
      // memory would, and clear the write flags for its new outputs.
      if (ce_l) begin
        wq <= w_addr; cq <= c_addr; kq <= k_raddr; vq <= v_raddr;
        g_data <= gmem[g_addr];
        d0 <= 1'b0; d1 <= 1'b0; d2 <= 1'b0;
        core_cycles <= core_cycles + 1;
      end
      case (fs)
        F_IDLE: if (!ce_l) begin
          if (p0 || p1 || p2) begin
            // A KV write: one beat, the lane's two bytes strobed.
            wsel <= p0 ? 2'd0 : p1 ? 2'd1 : 2'd2;
            waddr_w <= p0 ? kw0_addr : p1 ? kw1_addr : vw_addr;
            wlane <= p0 ? kw0_lane : p1 ? kw1_lane : vw_lane;
            wval <= p0 ? kw0_data : p1 ? kw1_data : vw_data;
            wisv <= !(p0 || p1);
            awaddr <= (p0 || p1 ? 32'd{kb} : 32'd{vb})
                      + (p0 ? kw0_addr : p1 ? kw1_addr : vw_addr) * 32
                      + ((p0 ? kw0_lane : p1 ? kw1_lane : vw_lane) >> 2) * 8;
            awvalid <= 1'b1; fs <= F_AW;
          end else if (!hc) begin
            port <= 2'd1; araddr <= 32'd{cb} + (cq >> 4) * 128; cbase <= cq; cv <= 1'b0;
            arvalid <= 1'b1; beat <= 0; fs <= F_AR;
          end else if (!hk) begin
            port <= 2'd2; araddr <= 32'd{kb} + (kq >> 2) * 128; kbl <= kq; kv <= 1'b0;
            arvalid <= 1'b1; beat <= 0; fs <= F_AR;
          end else if (!hv) begin
            port <= 2'd3; araddr <= 32'd{vb} + (vq >> 2) * 128; vbl <= vq; vv <= 1'b0;
            arvalid <= 1'b1; beat <= 0; fs <= F_AR;
          end
        end
        F_AR: if (arready) begin arvalid <= 1'b0; fs <= F_R; end
        F_R: if (rvalid) begin
          case (port)
            2'd1: cl[beat] <= rdata;
            2'd2: kl[beat[3:2]][beat[1:0] * 64 +: 64] <= rdata;
            2'd3: vl[beat[3:2]][beat[1:0] * 64 +: 64] <= rdata;
          endcase
          beat <= beat + 1;
          if (rlast) begin
            fs <= F_IDLE;
            case (port) 2'd1: cv <= 1'b1; 2'd2: kv <= 1'b1;
                        2'd3: vv <= 1'b1; endcase
          end
        end
        F_AW: if (awready) begin
          awvalid <= 1'b0; wvalid <= 1'b1;
          wdata <= {{48'd0, wval}} << (wlane[1:0] * 16);
          wstrb <= 8'b11 << (wlane[1:0] * 2);
          // A line already holding this word takes the write too.
          if (!wisv && kv && (waddr_w >> 2) == (kbl >> 2))
            kl[waddr_w[1:0]] <= (kl[waddr_w[1:0]] & ~lane_mask)
                                | ({{240'd0, wval}} << (wlane * 16));
          if (wisv && vv && (waddr_w >> 2) == (vbl >> 2))
            vl[waddr_w[1:0]] <= (vl[waddr_w[1:0]] & ~lane_mask)
                                | ({{240'd0, wval}} << (wlane * 16));
          fs <= F_W;
        end
        F_W: if (wready) begin wvalid <= 1'b0; fs <= F_B; end
        F_B: if (bvalid) begin
          case (wsel) 2'd0: d0 <= 1'b1; 2'd1: d1 <= 1'b1; default: d2 <= 1'b1; endcase
          fs <= F_IDLE;
        end
        default: fs <= F_IDLE;
      endcase
    end
  end
endmodule
""".format(twm=W["tok"] - 1, pwm=W["pos"] - 1, wam=wa - 1, cam=ca - 1,
           gam=ga - 1, kam=ka - 1, vam=va - 1, gn=gwords - 1, cb=cb, kb=kb,
           vb=vb)


TB = """`timescale 1ns/1ps
module tb_zybo;
  reg clk = 0, rst_n = 0, start = 0, head_en = 0;
  reg [%(twm)d:0] tok = 0;
  reg [%(pwm)d:0] pos = 0;
  wire [%(twm)d:0] next_tok;
  wire signed [15:0] best;
  wire done, busy;
  wire [31:0] araddr, awaddr, core_cycles;
  wire [3:0] arlen, awlen;
  wire arvalid, rready, awvalid, wvalid, wlast, bready;
  reg arready = 0, rvalid = 0, rlast = 0, awready = 0, wready = 0, bvalid = 0;
  reg [63:0] rdata = 0;
  wire [31:0] w_araddr;
  wire [3:0] w_arlen;
  wire w_arvalid, w_rready;
  reg w_arready = 1, w_rvalid = 0, w_rlast = 0;
  reg [63:0] w_rdata = 0;
  wire [63:0] wdata;
  wire [7:0] wstrb;
  always #5 clk = ~clk;
  qwen_zybo dut (.clk(clk), .rst_n(rst_n), .start(start), .head_en(head_en),
    .tok(tok), .pos(pos), .next_tok(next_tok), .best(best), .done(done),
    .busy(busy), .w_araddr(w_araddr), .w_arlen(w_arlen),
    .w_arvalid(w_arvalid), .w_arready(w_arready), .w_rdata(w_rdata),
    .w_rvalid(w_rvalid), .w_rlast(w_rlast), .w_rready(w_rready),
    .araddr(araddr), .arlen(arlen), .arvalid(arvalid),
    .arready(arready), .rdata(rdata), .rvalid(rvalid), .rlast(rlast),
    .rready(rready), .awaddr(awaddr), .awlen(awlen), .awvalid(awvalid),
    .awready(awready), .wdata(wdata), .wstrb(wstrb), .wlast(wlast),
    .wvalid(wvalid), .wready(wready), .bvalid(bvalid), .bready(bready),
    .core_cycles(core_cycles));

  // ---- DDR: weights from the image on disk, the rest in arrays
  reg [63:0] cmem [0:%(cn)d];
  reg [61:0] c62 [0:%(cn)d];
  reg [255:0] km [0:%(kn)d];
  reg [255:0] vm [0:%(vn)d];
  integer fd, r, i, cyc = 0, t0 = 0, c0 = 0, lat;
  reg [255:0] wword, t;
  integer wlast_ = -1;
  reg [31:0] ra;
  reg [3:0] rn;
  always @(posedge clk) cyc = cyc + 1;
  // A heartbeat, so a stalled bus reads as a stall and not as slowness.
  always @(posedge clk) if (cyc %% 10000000 == 0 && cyc > 0) begin
    $display("PROGRESS clk=%%0d core=%%0d bus_state=%%0d", cyc, core_cycles, dut.fs);
    $fflush;
  end
  function [63:0] beat_at(input [31:0] a);
    integer w_;
    begin
      if (a < %(cb)d) begin
        w_ = a / 32;
        if (w_ != wlast_) begin
          r = $fseek(fd, w_ * 32, 0); r = $fread(wword, fd); wlast_ = w_;
        end
        beat_at = wword[((a %% 32) / 8) * 64 +: 64];
      end else if (a < %(kb)d) beat_at = cmem[(a - %(cb)d) / 8];
      else if (a < %(vb)d) begin t = km[(a - %(kb)d) / 32]; beat_at = t[((a %% 32) / 8) * 64 +: 64]; end
      else begin t = vm[(a - %(vb)d) / 32]; beat_at = t[((a %% 32) / 8) * 64 +: 64]; end
    end
  endfunction
  // Reads: address accepted, then %(lat)d cycles of latency, then the burst.
  // Both bus processes wait for reset to be released and compare with
  // !==: before reset the master's valids are X, and !X is false, so a
  // plain test ran a phantom write at cycle 2 and then waited forever
  // for its data beat while the real first write waited for awready.
  initial begin
    @(posedge rst_n);
    forever begin
      @(posedge clk); while (arvalid !== 1'b1) @(posedge clk);
      arready <= 1; ra = araddr; rn = arlen;
      @(posedge clk); arready <= 0;
      repeat (%(lat)d) @(posedge clk);
      for (i = 0; i <= rn; i = i + 1) begin
        rdata <= beat_at(ra + i * 8); rvalid <= 1; rlast <= (i == rn);
        @(posedge clk);
      end
      rvalid <= 0; rlast <= 0;
    end
  end
  // The weight port takes reads as fast as they come, as a DDR controller
  // queues them, and answers each after its latency, bursts back to back.
  reg [31:0] qa [0:15];
  integer qt [0:15];
  integer qh = 0, qtl = 0, j;
  always @(posedge clk) if (rst_n && w_arvalid && w_arready) begin
    qa[qtl %% 16] = w_araddr; qt[qtl %% 16] = cyc; qtl = qtl + 1;
  end
  initial begin
    @(posedge rst_n);
    forever begin
      @(posedge clk);
      if (qh < qtl && cyc >= qt[qh %% 16] + %(lat)d) begin
        for (j = 0; j < 16; j = j + 1) begin
          w_rdata <= beat_at(qa[qh %% 16] + j * 8); w_rvalid <= 1; w_rlast <= (j == 15);
          @(posedge clk);
        end
        w_rvalid <= 0; w_rlast <= 0; qh = qh + 1;
      end
    end
  end
  // Writes: one beat, strobed, into the KV arrays.
  reg [31:0] wa;
  reg [255:0] tw;              // not t: the read process's function uses t
  integer b, base;
  initial begin
    @(posedge rst_n);
    forever begin
      @(posedge clk); while (awvalid !== 1'b1) @(posedge clk);
      awready <= 1; wa = awaddr; @(posedge clk); awready <= 0;
      while (wvalid !== 1'b1) @(posedge clk);
      wready <= 1;
      if (wa >= %(vb)d) begin tw = vm[(wa - %(vb)d) / 32]; base = ((wa - %(vb)d) %% 32) * 8; end
      else begin tw = km[(wa - %(kb)d) / 32]; base = ((wa - %(kb)d) %% 32) * 8; end
      for (b = 0; b < 8; b = b + 1) if (wstrb[b]) tw[base + b * 8 +: 8] = wdata[b * 8 +: 8];
      if (wa >= %(vb)d) vm[(wa - %(vb)d) / 32] = tw; else km[(wa - %(kb)d) / 32] = tw;
      @(posedge clk); wready <= 0;
      repeat (4) @(posedge clk); bvalid <= 1; @(posedge clk); bvalid <= 0;
    end
  end
  task step(input integer tk, input integer p, input integer he);
    begin
      tok = tk; pos = p; head_en = he;
      @(negedge clk); start = 1; t0 = cyc; c0 = core_cycles;
      @(negedge clk); while (!busy) @(negedge clk); start = 0;
      while (!done) @(negedge clk);
      $display("STEP pos=%%0d tok=%%0d clk_cycles=%%0d core_cycles=%%0d next=%%0d",
               p, tk, cyc - t0, core_cycles - c0, next_tok);
      $fflush;
    end
  endtask
  initial begin
    fd = $fopen("weights.bin", "rb");
    $readmemh("cparams.hex", c62);
    for (i = 0; i <= %(cn)d; i = i + 1) cmem[i] = {2'b00, c62[i]};
    for (i = 0; i <= %(kn)d; i = i + 1) km[i] = 0;
    for (i = 0; i <= %(vn)d; i = i + 1) vm[i] = 0;
    repeat (4) @(negedge clk); rst_n = 1; repeat (4) @(negedge clk);
%(steps)s
    $finish;
  end
endmodule
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", default=os.path.join(ROOT, "build_qfull1"))
    ap.add_argument("--latency", type=int, default=30)
    a = ap.parse_args()
    work = a.work
    core = open(os.path.join(work, "qwen_full.v")).read()
    W = widths(core)
    old = open(os.path.join(work, "tb_qfull.v")).read()
    size = lambda name: int(re.search(r"%s \[0:(\d+)\]" % name, old).group(1)) + 1
    cn, gn, kn, vn = size("cmem"), size("gmem"), size("km"), size("vm")
    words = os.path.getsize(os.path.join(work, "weights.bin")) // 32
    align = lambda x: (x + 4095) // 4096 * 4096
    cb = align(words * 32)
    kb = align(cb + cn * 8)
    vb = align(kb + kn * 32)
    steps = "\n".join(l for l in old.splitlines() if l.strip().startswith("step("))
    with open(os.path.join(work, "qwen_zybo.v"), "w") as f:
        f.write(render_top(W, gn, cb, kb, vb))
    with open(os.path.join(work, "tb_zybo.v"), "w") as f:
        f.write(TB % dict(twm=W["tok"] - 1, pwm=W["pos"] - 1, cn=cn - 1,
                          kn=kn - 1, vn=vn - 1, cb=cb, kb=kb, vb=vb,
                          lat=a.latency, steps=steps))
    srcs = sorted(f for f in os.listdir(work)
                  if f.endswith(".v") and f not in ("tb_qfull.v",))
    srcs = ["tb_zybo.v"] + [s for s in srcs if s != "tb_zybo.v"]
    r = subprocess.run(["iverilog", "-g2005", "-DSIM", "-o", "z.out"] + srcs,
                       cwd=work, capture_output=True, text=True)
    if r.returncode:
        print(r.stdout[-3000:], r.stderr[-3000:])
        sys.exit(1)
    t0 = time.time()
    p = subprocess.Popen(["vvp", "z.out"], cwd=work, stdout=subprocess.PIPE,
                         text=True)
    for line in p.stdout:
        print(line.rstrip(), "(%.0f s)" % (time.time() - t0))
        sys.stdout.flush()
    p.wait()


if __name__ == "__main__":
    main()
