// GENERATED by board_zybo.py: the DDR layout and registers of
// the bitstream this was generated with.
#ifndef FPGAI_LAYOUT_H
#define FPGAI_LAYOUT_H
#define FPGAI_REGS      0x43C00000U
#define FPGAI_CTRL       0x00U  /* write bit 0 to start a step; bit 1 is head_en */
#define FPGAI_TOK        0x04U  /* token id for the step */
#define FPGAI_POS        0x08U  /* position for the step */
#define FPGAI_STATUS     0x0CU  /* bit 0 busy, bit 1 done (cleared by a start) */
#define FPGAI_NEXT_TOK   0x10U  /* the head's greedy token, valid when done */
#define FPGAI_BEST       0x14U  /* its logit, sign-extended */
#define FPGAI_CORE_CYCLES 0x18U  /* core clock edges since reset */
#define FPGAI_BUS_CYCLES 0x1CU  /* bus clocks the last step took */
#define FPGAI_ID         0x20U  /* 0xF96A0001 */
#define FPGAI_WBASE      0x24U  /* DDR address of weights8.bin */
#define FPGAI_CBASE      0x28U  /* DDR address of cparams.bin */
#define FPGAI_KBASE      0x2CU  /* DDR address of the K cache */
#define FPGAI_VBASE      0x30U  /* DDR address of the V cache */
#define FPGAI_KVEND      0x34U  /* end of the V cache */
#define FPGAI_ID_VALUE  0xF96A0001U
#define WBASE           0x08000000U
#define WBYTES          493961216U
#define CBASE           0x25714000U
#define CBYTES          4864000U
#define KBASE           0x25BB8000U
#define KVEND           0x25EB8000U
#define VOCAB_BASE      0x25EB8000U
#define MAX_POS         256
#define N_GEN           16
#define CORE_MHZ        50
#endif
