// GENERATED by board_zybo.py. Bare-metal driver for the fpgai_zybo PL.
// Build it in Vitis as an application on fpgai.xsa with the xilffs
// library (FatFs) enabled in the BSP. It reads the SD card's files into
// DDR, or without a card waits for sw/load_jtag.tcl to write them there
// over JTAG, runs the prompt a position at a time, then generates N_GEN
// tokens, printing each one's text on the USB-UART at 115200.
#include <stdio.h>
#include <string.h>
#include "xil_io.h"
#include "xil_cache.h"
#include "xtime_l.h"
#include "ff.h"
#include "fpgai_layout.h"

#define REG(o) (FPGAI_REGS + (o))
static FATFS fs;

static int load(const char *name, UINTPTR addr, u32 want)
{
    FIL f;
    UINT n;
    u32 got = 0;
    if (f_open(&f, name, FA_READ) != FR_OK) {
        printf("missing %s\r\n", name);
        return -1;
    }
    if (want && f_size(&f) != want) {
        printf("%s is %lu bytes, this bitstream wants %lu\r\n", name,
               (unsigned long)f_size(&f), (unsigned long)want);
        return -1;
    }
    while (f_read(&f, (void *)(addr + got), 1 << 20, &n) == FR_OK && n) {
        got += n;
        if ((got & ((64 << 20) - 1)) == 0)
            printf("  %s: %lu MB\r\n", name, (unsigned long)(got >> 20));
    }
    f_close(&f);
    printf("%s: %lu bytes at 0x%08lx\r\n", name, (unsigned long)got,
           (unsigned long)addr);
    return (int)got;
}

// No SD card: the same files over JTAG. sw/load_jtag.tcl, run in XSCT
// while this waits, writes each to its address, then the sizes of the
// first two and last the marker. The flushes make the marker the
// debugger wrote visible here whichever way it went, through this core's
// caches or straight to DDR; the full flush after it puts every file in
// DDR, where the PL reads them.
static int wait_jtag(void)
{
    volatile u32 *mark = (volatile u32 *)JTAG_MARK;
    printf("no SD card: waiting for the files over JTAG; in XSCT run\r\n"
           "  source sw/load_jtag.tcl\r\n");
    mark[0] = 0;
    Xil_DCacheFlushRange((UINTPTR)mark, 64);
    while (mark[0] != JTAG_MAGIC)
        Xil_DCacheFlushRange((UINTPTR)mark, 64);
    Xil_DCacheFlush();
    if (mark[1] != WBYTES || mark[2] != CBYTES) {
        printf("weights8.bin is %lu bytes and cparams.bin %lu, this bitstream "
               "wants %lu and %lu\r\n", (unsigned long)mark[1],
               (unsigned long)mark[2], (unsigned long)WBYTES,
               (unsigned long)CBYTES);
        return -1;
    }
    printf("files loaded over JTAG\r\n");
    return 0;
}

static u32 step(u32 tok, u32 pos, int head)
{
    Xil_Out32(REG(FPGAI_TOK), tok);
    Xil_Out32(REG(FPGAI_POS), pos);
    Xil_Out32(REG(FPGAI_CTRL), 1 | (head ? 2 : 0));
    while (!(Xil_In32(REG(FPGAI_STATUS)) & 2))
        ;
    return Xil_In32(REG(FPGAI_NEXT_TOK));
}

static const u32 *vocab;

static void print_tok(u32 t)
{
    u32 n = vocab[0];
    const char *s = (const char *)(vocab + n + 2);
    if (t < n)
        printf("%.*s", (int)(vocab[t + 2] - vocab[t + 1]), s + vocab[t + 1]);
    fflush(stdout);
}

int main(void)
{
    static u32 prompt[MAX_POS + 1];
    XTime a, b;
    printf("\r\nfpgai: Qwen on the " FPGAI_BOARD " PL\r\n");
    if (Xil_In32(REG(FPGAI_ID)) != FPGAI_ID_VALUE ||
        Xil_In32(REG(FPGAI_WBASE)) != WBASE ||
        Xil_In32(REG(FPGAI_KVEND)) != KVEND) {
        printf("the bitstream's layout is not this program's\r\n");
        return 1;
    }
    if (f_mount(&fs, "0:/", 1) == FR_OK) {
        if (load("weights8.bin", WBASE, WBYTES) < 0 ||
            load("cparams.bin", CBASE, CBYTES) < 0 ||
            load("vocab.bin", VOCAB_BASE, 0) < 0 ||
            load("prompt.bin", (UINTPTR)prompt, 0) < 0)
            return 1;
    } else {
        if (wait_jtag() < 0)
            return 1;
        memcpy(prompt, (const void *)JTAG_PROMPT, sizeof prompt);
    }
    vocab = (const u32 *)VOCAB_BASE;
    // A new sequence starts with an empty KV cache; the PL reads DDR, so
    // everything the ARM wrote must leave its caches first.
    memset((void *)KBASE, 0, KVEND - KBASE);
    Xil_DCacheFlush();

    u32 n = prompt[0], tok = 0, pos;
    for (pos = 0; pos < n; pos++) {
        print_tok(prompt[pos + 1]);
        XTime_GetTime(&a);
        tok = step(prompt[pos + 1], pos, pos == n - 1);
        XTime_GetTime(&b);
    }
    // N_GEN tokens: each one printed, then fed back for the next.
    for (int g = 0; g < N_GEN && pos < MAX_POS; g++, pos++) {
        print_tok(tok);
        if (g + 1 == N_GEN)
            break;
        XTime_GetTime(&a);
        tok = step(tok, pos, 1);
        XTime_GetTime(&b);
    }
    // XTime counts at half the CPU clock.
    printf("\r\nlast step: %lu core cycles, %lu bus cycles, %.2f s\r\n",
           (unsigned long)Xil_In32(REG(FPGAI_CORE_CYCLES)),
           (unsigned long)Xil_In32(REG(FPGAI_BUS_CYCLES)),
           (double)(b - a) / COUNTS_PER_SECOND);
    return 0;
}
