# GENERATED by sdboot.py: board_zybo with no SD card, over JTAG, in XSCT
# (Vitis's xsct, or Vivado's on 2023.1 and later). No Vivado project:
#   xsct run.tcl          the program
#   xsct run.tcl diag     the diagnostics (sdboot/diag.c) instead
# Set the board's boot mode to JTAG and connect its JTAG and UART USB
# ports; open the UART at 115200 8N1 first. The model files are the
# package's sd/ (HANDOFF.md step 1); the weights take minutes over JTAG.
set here [file dirname [file normalize [info script]]]
set sd [file join $here .. sd]
set prog halo.elf
if {[llength $argv] && [lindex $argv 0] eq "diag"} { set prog halo_diag.elf }
foreach f [list fpgai.bit $prog ps7_init.tcl] {
    if {![file exists [file join $here $f]]} {
        error "no $f in $here: run python3 sdboot.py <package> --jtag first"
    }
}
foreach f {weights8.bin cparams.bin vocab.bin prompt.bin} {
    if {![file exists [file join $sd $f]]} { error "no $sd/$f: make the model files first" }
}
source [file join $here ps7_init.tcl]
connect
targets -set -nocase -filter {name =~ "APU*"}
rst -system
after 1000
puts "programming the PL"
fpga -file [file join $here fpgai.bit]
targets -set -nocase -filter {name =~ "*A9*#0"}
rst -processor
puts "ps7_init: DDR, clocks, MIO"
ps7_init
# The PL's clock: the IO PLL over 25 = 40 MHz (ps7_init set 50).
mwr -force 0xF8000008 0xDF0D
mwr -force 0xF8000170 0x00101900
ps7_post_config
puts "loading $prog and the model files (minutes)"
dow [file join $here $prog]
set table 0x07F00000
mwr -force $table 0 8
set slot 1
foreach {name addr} {weights8.bin 0x08000000 cparams.bin 0x25714000 vocab.bin 0x25EB8000 prompt.bin 0x07F01000} {
    set path [file join $sd $name]
    puts "  $name"
    dow -data $path $addr
    mwr -force [expr {$table + 4 * $slot}] [file size $path]
    incr slot
}
mwr -force $table 0x48414C4F
puts "running: the output is on the UART"
con
