// GENERATED by board_zybo.py: do not edit by hand.
// The Qwen sequencer for the Zybo Z7-20's PL. The ARM drives it through
// an AXI-Lite register block on GP0 (see board_zybo/README.md for the
// map); the weights come in on four AXI4 masters, one per HP port, and
// the constants and the KV cache on a fifth, on ACP. Every region is at
// its absolute DDR address, fixed at generation and readable here so the
// software can check the SD files were made for this bitstream.
module fpgai_zybo (
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 aclk CLK" *)
  (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF s_axi:m_axi_w0:m_axi_w1:m_axi_w2:m_axi_w3:m_axi_kv, ASSOCIATED_RESET aresetn" *)
  input aclk,
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 aresetn RST" *)
  (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
  input aresetn,
  input [5:0] s_axi_awaddr, input s_axi_awvalid, output reg s_axi_awready,
  input [31:0] s_axi_wdata, input [3:0] s_axi_wstrb, input s_axi_wvalid,
  output reg s_axi_wready, output [1:0] s_axi_bresp, output reg s_axi_bvalid,
  input s_axi_bready,
  input [5:0] s_axi_araddr, input s_axi_arvalid, output reg s_axi_arready,
  output reg [31:0] s_axi_rdata, output [1:0] s_axi_rresp,
  output reg s_axi_rvalid, input s_axi_rready,
  output [31:0] m_axi_w0_araddr, output [7:0] m_axi_w0_arlen,
  output [2:0] m_axi_w0_arsize, output [1:0] m_axi_w0_arburst,
  output [3:0] m_axi_w0_arcache, output [2:0] m_axi_w0_arprot,
  output m_axi_w0_arlock, output [3:0] m_axi_w0_arqos,
  output m_axi_w0_arvalid, input m_axi_w0_arready,
  input [63:0] m_axi_w0_rdata, input [1:0] m_axi_w0_rresp, input m_axi_w0_rlast,
  input m_axi_w0_rvalid, output m_axi_w0_rready,
  output [31:0] m_axi_w1_araddr, output [7:0] m_axi_w1_arlen,
  output [2:0] m_axi_w1_arsize, output [1:0] m_axi_w1_arburst,
  output [3:0] m_axi_w1_arcache, output [2:0] m_axi_w1_arprot,
  output m_axi_w1_arlock, output [3:0] m_axi_w1_arqos,
  output m_axi_w1_arvalid, input m_axi_w1_arready,
  input [63:0] m_axi_w1_rdata, input [1:0] m_axi_w1_rresp, input m_axi_w1_rlast,
  input m_axi_w1_rvalid, output m_axi_w1_rready,
  output [31:0] m_axi_w2_araddr, output [7:0] m_axi_w2_arlen,
  output [2:0] m_axi_w2_arsize, output [1:0] m_axi_w2_arburst,
  output [3:0] m_axi_w2_arcache, output [2:0] m_axi_w2_arprot,
  output m_axi_w2_arlock, output [3:0] m_axi_w2_arqos,
  output m_axi_w2_arvalid, input m_axi_w2_arready,
  input [63:0] m_axi_w2_rdata, input [1:0] m_axi_w2_rresp, input m_axi_w2_rlast,
  input m_axi_w2_rvalid, output m_axi_w2_rready,
  output [31:0] m_axi_w3_araddr, output [7:0] m_axi_w3_arlen,
  output [2:0] m_axi_w3_arsize, output [1:0] m_axi_w3_arburst,
  output [3:0] m_axi_w3_arcache, output [2:0] m_axi_w3_arprot,
  output m_axi_w3_arlock, output [3:0] m_axi_w3_arqos,
  output m_axi_w3_arvalid, input m_axi_w3_arready,
  input [63:0] m_axi_w3_rdata, input [1:0] m_axi_w3_rresp, input m_axi_w3_rlast,
  input m_axi_w3_rvalid, output m_axi_w3_rready,
  output [31:0] m_axi_kv_araddr, output [7:0] m_axi_kv_arlen,
  output [2:0] m_axi_kv_arsize, output [1:0] m_axi_kv_arburst,
  output [3:0] m_axi_kv_arcache, output [2:0] m_axi_kv_arprot,
  output m_axi_kv_arlock, output [3:0] m_axi_kv_arqos,
  output m_axi_kv_arvalid, input m_axi_kv_arready,
  input [63:0] m_axi_kv_rdata, input [1:0] m_axi_kv_rresp, input m_axi_kv_rlast,
  input m_axi_kv_rvalid, output m_axi_kv_rready,
  output [31:0] m_axi_kv_awaddr, output [7:0] m_axi_kv_awlen,
  output [2:0] m_axi_kv_awsize, output [1:0] m_axi_kv_awburst,
  output [3:0] m_axi_kv_awcache, output [2:0] m_axi_kv_awprot,
  output m_axi_kv_awlock, output [3:0] m_axi_kv_awqos,
  output m_axi_kv_awvalid, input m_axi_kv_awready,
  output [63:0] m_axi_kv_wdata, output [7:0] m_axi_kv_wstrb,
  output m_axi_kv_wlast, output m_axi_kv_wvalid, input m_axi_kv_wready,
  input [1:0] m_axi_kv_bresp, input m_axi_kv_bvalid, output m_axi_kv_bready,
  output busy_led
);
  assign m_axi_w0_arsize = 3'd3; assign m_axi_w0_arburst = 2'b01;
  assign m_axi_w0_arcache = 4'b0011; assign m_axi_w0_arprot = 3'd0;
  assign m_axi_w0_arlock = 1'b0; assign m_axi_w0_arqos = 4'd0;
  assign m_axi_w1_arsize = 3'd3; assign m_axi_w1_arburst = 2'b01;
  assign m_axi_w1_arcache = 4'b0011; assign m_axi_w1_arprot = 3'd0;
  assign m_axi_w1_arlock = 1'b0; assign m_axi_w1_arqos = 4'd0;
  assign m_axi_w2_arsize = 3'd3; assign m_axi_w2_arburst = 2'b01;
  assign m_axi_w2_arcache = 4'b0011; assign m_axi_w2_arprot = 3'd0;
  assign m_axi_w2_arlock = 1'b0; assign m_axi_w2_arqos = 4'd0;
  assign m_axi_w3_arsize = 3'd3; assign m_axi_w3_arburst = 2'b01;
  assign m_axi_w3_arcache = 4'b0011; assign m_axi_w3_arprot = 3'd0;
  assign m_axi_w3_arlock = 1'b0; assign m_axi_w3_arqos = 4'd0;
  assign m_axi_kv_arsize = 3'd3; assign m_axi_kv_arburst = 2'b01;
  assign m_axi_kv_arcache = 4'b0011; assign m_axi_kv_arprot = 3'd0;
  assign m_axi_kv_arlock = 1'b0; assign m_axi_kv_arqos = 4'd0;
  assign m_axi_kv_awsize = 3'd3; assign m_axi_kv_awburst = 2'b01;
  assign m_axi_kv_awcache = 4'b0011; assign m_axi_kv_awprot = 3'd0;
  assign m_axi_kv_awlock = 1'b0; assign m_axi_kv_awqos = 4'd0;
  assign m_axi_w0_arlen[7:4] = 4'd0;
  assign m_axi_w1_arlen[7:4] = 4'd0;
  assign m_axi_w2_arlen[7:4] = 4'd0;
  assign m_axi_w3_arlen[7:4] = 4'd0;
  assign m_axi_kv_arlen[7:4] = 4'd0; assign m_axi_kv_awlen[7:4] = 4'd0;
  assign s_axi_bresp = 2'b00; assign s_axi_rresp = 2'b00;

  reg start, head_en, done_s;
  reg [17:0] tok; reg [7:0] pos;
  reg [31:0] bus_cycles;
  wire [17:0] next_tok; wire signed [15:0] best;
  wire done, busy;
  wire [31:0] core_cycles;
  assign busy_led = busy;

  qwen_zybo br (.clk(aclk), .rst_n(aresetn), .start(start), .head_en(head_en),
    .tok(tok), .pos(pos), .next_tok(next_tok), .best(best), .done(done),
    .busy(busy),
    .w0_araddr(m_axi_w0_araddr), .w0_arlen(m_axi_w0_arlen[3:0]), .w0_arvalid(m_axi_w0_arvalid),
    .w0_arready(m_axi_w0_arready), .w0_rdata(m_axi_w0_rdata), .w0_rvalid(m_axi_w0_rvalid),
    .w0_rlast(m_axi_w0_rlast), .w0_rready(m_axi_w0_rready),
    .w1_araddr(m_axi_w1_araddr), .w1_arlen(m_axi_w1_arlen[3:0]), .w1_arvalid(m_axi_w1_arvalid),
    .w1_arready(m_axi_w1_arready), .w1_rdata(m_axi_w1_rdata), .w1_rvalid(m_axi_w1_rvalid),
    .w1_rlast(m_axi_w1_rlast), .w1_rready(m_axi_w1_rready),
    .w2_araddr(m_axi_w2_araddr), .w2_arlen(m_axi_w2_arlen[3:0]), .w2_arvalid(m_axi_w2_arvalid),
    .w2_arready(m_axi_w2_arready), .w2_rdata(m_axi_w2_rdata), .w2_rvalid(m_axi_w2_rvalid),
    .w2_rlast(m_axi_w2_rlast), .w2_rready(m_axi_w2_rready),
    .w3_araddr(m_axi_w3_araddr), .w3_arlen(m_axi_w3_arlen[3:0]), .w3_arvalid(m_axi_w3_arvalid),
    .w3_arready(m_axi_w3_arready), .w3_rdata(m_axi_w3_rdata), .w3_rvalid(m_axi_w3_rvalid),
    .w3_rlast(m_axi_w3_rlast), .w3_rready(m_axi_w3_rready),
    .araddr(m_axi_kv_araddr), .arlen(m_axi_kv_arlen[3:0]),
    .arvalid(m_axi_kv_arvalid), .arready(m_axi_kv_arready),
    .rdata(m_axi_kv_rdata), .rvalid(m_axi_kv_rvalid), .rlast(m_axi_kv_rlast),
    .rready(m_axi_kv_rready), .awaddr(m_axi_kv_awaddr),
    .awlen(m_axi_kv_awlen[3:0]), .awvalid(m_axi_kv_awvalid),
    .awready(m_axi_kv_awready), .wdata(m_axi_kv_wdata),
    .wstrb(m_axi_kv_wstrb), .wlast(m_axi_kv_wlast), .wvalid(m_axi_kv_wvalid),
    .wready(m_axi_kv_wready), .bvalid(m_axi_kv_bvalid),
    .bready(m_axi_kv_bready), .core_cycles(core_cycles));

  // ---- AXI-Lite: one write and one read at a time, both always OKAY.
  // A start is held until the core shows busy: the core's clock may be
  // stopped for a line fill, so a one-cycle pulse could fall between its
  // edges. done is its one-edge pulse, kept until the next start.
  reg [5:0] wa; reg hav_a, hav_w; reg [31:0] wd;
  always @(posedge aclk) begin
    if (!aresetn) begin
      s_axi_awready <= 1'b0; s_axi_wready <= 1'b0; s_axi_bvalid <= 1'b0;
      s_axi_arready <= 1'b0; s_axi_rvalid <= 1'b0; hav_a <= 1'b0;
      hav_w <= 1'b0; start <= 1'b0; head_en <= 1'b0; done_s <= 1'b0;
      tok <= 0; pos <= 0; bus_cycles <= 0;
    end else begin
      // Ready is one cycle, and the transfer is the edge it meets valid.
      s_axi_awready <= 1'b0; s_axi_wready <= 1'b0; s_axi_arready <= 1'b0;
      if (s_axi_awvalid && !s_axi_awready && !hav_a && !s_axi_bvalid)
        s_axi_awready <= 1'b1;
      if (s_axi_awvalid && s_axi_awready) begin wa <= s_axi_awaddr; hav_a <= 1'b1; end
      if (s_axi_wvalid && !s_axi_wready && !hav_w && !s_axi_bvalid)
        s_axi_wready <= 1'b1;
      if (s_axi_wvalid && s_axi_wready) begin wd <= s_axi_wdata; hav_w <= 1'b1; end
      if (hav_a && hav_w) begin
        hav_a <= 1'b0; hav_w <= 1'b0; s_axi_bvalid <= 1'b1;
        case (wa[5:2])
          4'h0: begin head_en <= wd[1];
                      if (wd[0]) begin start <= 1'b1; done_s <= 1'b0; bus_cycles <= 0; end end
          4'h1: tok <= wd[17:0];
          4'h2: pos <= wd[7:0];
          default: ;
        endcase
      end
      if (s_axi_bvalid && s_axi_bready) s_axi_bvalid <= 1'b0;
      if (start && busy) start <= 1'b0;
      if (done && !start) done_s <= 1'b1;
      if ((start || busy) && !done_s) bus_cycles <= bus_cycles + 1;
      if (s_axi_arvalid && !s_axi_arready && !s_axi_rvalid)
        s_axi_arready <= 1'b1;
      if (s_axi_arvalid && s_axi_arready) begin
        s_axi_rvalid <= 1'b1;
        case (s_axi_araddr[5:2])
          4'h0: s_axi_rdata <= {30'd0, head_en, 1'b0};
          4'h1: s_axi_rdata <= {14'd0, tok};
          4'h2: s_axi_rdata <= {24'd0, pos};
          4'h3: s_axi_rdata <= {30'd0, done_s, busy};
          4'h4: s_axi_rdata <= {14'd0, next_tok};
          4'h5: s_axi_rdata <= {{16{best[15]}}, best};
          4'h6: s_axi_rdata <= core_cycles;
          4'h7: s_axi_rdata <= bus_cycles;
          4'h8: s_axi_rdata <= 32'hF96A0001;
          4'h9: s_axi_rdata <= 32'h08000000;
          4'hA: s_axi_rdata <= 32'h25714000;
          4'hB: s_axi_rdata <= 32'h25BB8000;
          4'hC: s_axi_rdata <= 32'h25D38000;
          4'hD: s_axi_rdata <= 32'h25EB8000;
          default: s_axi_rdata <= 32'd0;
        endcase
      end
      if (s_axi_rvalid && s_axi_rready) s_axi_rvalid <= 1'b0;
    end
  end
endmodule
