# GENERATED by board_zybo.py. Build the Zybo Z7-20 bitstream and platform:
#   vivado -mode batch -source build.tcl
# Needs an x86 Vivado (2020.2 or later) with Digilent's board files, for
# the PS7's DDR and MIO preset. Writes fpgai.xsa for Vitis (see sw/).
create_project -force fpgai ./vivado -part xc7z020clg400-1
if {[catch {set_property board_part digilentinc.com:zybo-z7-20:part0:1.1 [current_project]}]} {
  puts "ERROR: install Digilent's board files (github.com/Digilent/vivado-boards)"
  exit 1
}
add_files [glob ./rtl/*.v]
add_files ./rtl/gains.hex
set_property file_type {Memory Initialization Files} [get_files gains.hex]
update_compile_order -fileset sources_1

create_bd_design system
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
  -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} [get_bd_cells ps7]
set_property -dict [list \
  CONFIG.PCW_USE_M_AXI_GP0 {1} \
  CONFIG.PCW_USE_S_AXI_HP0 {1} CONFIG.PCW_USE_S_AXI_HP1 {1} \
  CONFIG.PCW_USE_S_AXI_HP2 {1} CONFIG.PCW_USE_S_AXI_HP3 {1} \
  CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {64} CONFIG.PCW_S_AXI_HP1_DATA_WIDTH {64} \
  CONFIG.PCW_S_AXI_HP2_DATA_WIDTH {64} CONFIG.PCW_S_AXI_HP3_DATA_WIDTH {64} \
  CONFIG.PCW_USE_S_AXI_ACP {1} \
  CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {50}] [get_bd_cells ps7]
create_bd_cell -type module -reference fpgai_zybo fpgai

# Registers on GP0; the weights on HP0-3; constants and KV on ACP.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config {Clk_master {/ps7/FCLK_CLK0} \
  Clk_slave {/ps7/FCLK_CLK0} Clk_xbar {/ps7/FCLK_CLK0} Master {/ps7/M_AXI_GP0} \
  Slave {/fpgai/s_axi} ddr_seg {Auto} intc_ip {New AXI Interconnect} master_apm {0}} \
  [get_bd_intf_pins fpgai/s_axi]
foreach {m s} {m_axi_w0 S_AXI_HP0 m_axi_w1 S_AXI_HP1 m_axi_w2 S_AXI_HP2 m_axi_w3 S_AXI_HP3 m_axi_kv S_AXI_ACP} {
  apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config [list Clk_master /ps7/FCLK_CLK0 \
    Clk_slave /ps7/FCLK_CLK0 Clk_xbar /ps7/FCLK_CLK0 Master /fpgai/$m Slave /ps7/$s \
    ddr_seg Auto intc_ip {New AXI SmartConnect} master_apm 0] [get_bd_intf_pins ps7/$s]
}
create_bd_port -dir O busy_led
connect_bd_net [get_bd_pins fpgai/busy_led] [get_bd_ports busy_led]
assign_bd_address
set seg [get_bd_addr_segs -of_objects [get_bd_addr_spaces ps7/Data] -filter {NAME =~ "*fpgai*"}]
set_property offset 0x43C00000 $seg
set_property range 64K $seg
validate_bd_design
save_bd_design

set w [make_wrapper -files [get_files system.bd] -top]
add_files -norecurse $w
set_property top system_wrapper [current_fileset]
add_files -fileset constrs_1 ./zybo.xdc
launch_runs synth_1 -jobs 4
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
open_run impl_1
report_timing_summary -file timing.rpt
report_utilization -file utilization.rpt
write_hw_platform -fixed -include_bit -force ./fpgai.xsa
puts "platform: ./fpgai.xsa"
