// GENERATED by qwen_full.py: do not edit by hand.
// One Qwen2.5-0.5B decode step, embedding to argmax, over the
// generated blocks; weights, constants and the KV cache are external.
module qwen_full (
  input clk, input rst_n, input start, input head_en,
  input [17:0] tok, input [7:0] pos,
  output [23:0] w_addr, input [511:0] w_data,
  output [19:0] c_addr, input [61:0] c_data,
  output [15:0] g_addr, input signed [15:0] g_data,
  output [14:0] k_raddr, input [511:0] k_rdata,
  output [14:0] v_raddr, input [511:0] v_rdata,
  output reg kw0_en, output reg [14:0] kw0_addr, output reg [4:0] kw0_lane,
  output reg signed [15:0] kw0_data,
  output reg kw1_en, output reg [14:0] kw1_addr, output reg [4:0] kw1_lane,
  output reg signed [15:0] kw1_data,
  output reg vw_en, output reg [14:0] vw_addr, output reg [4:0] vw_lane,
  output reg signed [15:0] vw_data,
  output reg [17:0] next_tok, output reg signed [15:0] best,
  output reg done, output reg busy
);
  localparam S_IDLE = 5'd0, S_EMB = 5'd1, S_N1 = 5'd2, S_Q = 5'd3, S_K = 5'd4, S_V = 5'd5, S_RQ = 5'd6, S_RK = 5'd7, S_LQ = 5'd8, S_ATT = 5'd9, S_O = 5'd10, S_R1 = 5'd11, S_N2 = 5'd12, S_G = 5'd13, S_U = 5'd14, S_GLU = 5'd15, S_DN = 5'd16, S_R2 = 5'd17, S_NF = 5'd18, S_HD = 5'd19;
  reg [4:0] st;
  reg ph, hen;
  reg [4:0] lyr;
  reg [3:0] hh;
  reg [5:0] hk;
  reg [17:0] tok_r;
  reg [7:0] pos_r;
  reg signed [15:0] xm [0:895];
  reg signed [15:0] nm [0:895];
  reg signed [15:0] qlo [0:447];
  reg signed [15:0] qhi [0:447];
  reg signed [15:0] klo [0:63];
  reg signed [15:0] khi [0:63];
  reg signed [15:0] cm [0:895];
  reg signed [15:0] am [0:895];
  reg signed [15:0] gm [0:4863];
  reg signed [15:0] um [0:4863];
  reg signed [15:0] mm [0:4863];
  reg [12:0] fj, ocnt, gcnt;

  reg pj_start;
  reg [12:0] pj_depth, pj_cols;
  wire [12:0] pj_a_addr, pj_c_addr, pj_index;
  wire [19:0] pj_w_addr;
  reg signed [15:0] pj_a_data;
  wire pj_valid, pj_busy;
  wire signed [15:0] pj_data;
  projn u_proj (.clk(clk), .rst_n(rst_n), .start(pj_start),
    .depth(pj_depth), .cols(pj_cols), .scale(18'd0), .shift(7'd0),
    .a_addr(pj_a_addr), .a_data(pj_a_data), .w_addr(pj_w_addr),
    .w_data(w_data), .c_addr(pj_c_addr), .c_data(c_data),
    .o_valid(pj_valid), .o_index(pj_index), .o_data(pj_data), .busy(pj_busy));
  reg rn_start;
  reg [17:0] rn_scale;
  reg [6:0] rn_shift;
  wire [9:0] rn_x_addr, rn_g_addr, rn_index;
  reg signed [15:0] rn_x_data;
  wire rn_valid, rn_busy;
  wire signed [15:0] rn_data;
  rmsnorm u_norm (.clk(clk), .rst_n(rst_n), .start(rn_start),
    .eps(46'd1), .scale_o(rn_scale), .shift_o(rn_shift),
    .x_addr(rn_x_addr), .x_data(rn_x_data), .g_addr(rn_g_addr),
    .g_data(g_data), .o_valid(rn_valid), .o_index(rn_index),
    .o_data(rn_data), .busy(rn_busy));
  reg at_start, at_load_valid;
  reg signed [15:0] at_load_data;
  reg [4:0] at_shs;
  reg [17:0] at_scale;
  reg [6:0] at_shift;
  wire [8:0] at_k_addr;
  wire [8:0] at_v_addr;
  wire at_valid, at_busy;
  wire [5:0] at_index;
  wire signed [15:0] at_data;
  attnn u_attn (.clk(clk), .rst_n(rst_n), .load_valid(at_load_valid),
    .load_data(at_load_data), .start(at_start),
    .n({1'd0, pos_r} + 9'd1), .shift_s(at_shs),
    .scale_o(at_scale), .shift_o(at_shift), .k_addr(at_k_addr),
    .k_data(k_rdata), .v_addr(at_v_addr), .v_data(v_rdata),
    .o_valid(at_valid), .o_index(at_index), .o_data(at_data), .busy(at_busy));
  reg signed [15:0] ra_a, ra_b;
  reg ra_v;
  reg [17:0] ra_sa, ra_sb;
  reg [6:0] ra_sh;
  wire signed [15:0] ra_y;
  wire ra_vout;
  resadd u_add (.clk(clk), .rst_n(rst_n), .a(ra_a), .b(ra_b),
    .scale_a(ra_sa), .scale_b(ra_sb), .shift(ra_sh), .valid_in(ra_v),
    .y(ra_y), .valid_out(ra_vout));
  reg signed [15:0] ro_x1, ro_x2;
  reg [4:0] ro_idx;
  reg ro_v;
  wire signed [15:0] ro_y1, ro_y2;
  wire ro_vout;
  rope u_rope (.clk(clk), .rst_n(rst_n), .x1(ro_x1), .x2(ro_x2),
    .idx(ro_idx), .pos(pos_r), .valid_in(ro_v), .y1(ro_y1), .y2(ro_y2),
    .valid_out(ro_vout));
  reg signed [12:0] si_x;
  reg si_v;
  wire signed [12:0] si_y;
  wire si_vout;
  silu u_silu (.clk(clk), .rst_n(rst_n), .x(si_x), .valid_in(si_v),
    .y(si_y), .valid_out(si_vout));
  reg signed [36:0] rq_acc;
  reg rq_v;
  reg [17:0] rq_scale;
  reg [6:0] rq_shift;
  wire signed [15:0] rq_q;
  wire rq_sat, rq_vout;
  requant u_rq (.clk(clk), .rst_n(rst_n), .acc_in(rq_acc), .scale(rq_scale),
    .shift(rq_shift), .valid_in(rq_v), .q_out(rq_q), .sat(rq_sat),
    .valid_out(rq_vout));

  reg [17:0] c_n1s, c_n2s, c_ctxs, c_ms, c_r1a, c_r1b, c_r2a, c_r2b;
  reg [6:0] c_n1h, c_n2h, c_ctxh, c_mh, c_r1h, c_r2h;
  reg [4:0] c_shs;
  reg signed [4:0] c_gsh;
  always @(*) begin
    case (lyr)
      0: begin c_n1s = 251807; c_n1h = 24; c_n2s = 166365; c_n2h = 24;
        c_r1a = 40694; c_r1b = 246642; c_r1h = 18; c_r2a = 11015; c_r2b = 131236; c_r2h = 17;
        c_shs = 15; c_ctxs = 131074; c_ctxh = 32; c_gsh = -4; c_ms = 170775; c_mh = 26; end
      1: begin c_n1s = 253053; c_n1h = 24; c_n2s = 136324; c_n2h = 24;
        c_r1a = 244326; c_r1b = 60601; c_r1h = 18; c_r2a = 235588; c_r2b = 68380; c_r2h = 18;
        c_shs = 18; c_ctxs = 131443; c_ctxh = 32; c_gsh = -4; c_ms = 204462; c_mh = 26; end
      2: begin c_n1s = 136532; c_n1h = 24; c_n2s = 165793; c_n2h = 24;
        c_r1a = 172227; c_r1b = 47517; c_r1h = 17; c_r2a = 2136; c_r2b = 261391; c_r2h = 18;
        c_shs = 20; c_ctxs = 138877; c_ctxh = 32; c_gsh = -3; c_ms = 204378; c_mh = 30; end
      3: begin c_n1s = 134575; c_n1h = 24; c_n2s = 134580; c_n2h = 26;
        c_r1a = 131073; c_r1b = 143; c_r1h = 17; c_r2a = 116125; c_r2b = 146019; c_r2h = 18;
        c_shs = 20; c_ctxs = 169257; c_ctxh = 32; c_gsh = -3; c_ms = 133881; c_mh = 30; end
      4: begin c_n1s = 225021; c_n1h = 25; c_n2s = 152349; c_n2h = 25;
        c_r1a = 131079; c_r1b = 176; c_r1h = 17; c_r2a = 261843; c_r2b = 631; c_r2h = 18;
        c_shs = 20; c_ctxs = 169270; c_ctxh = 32; c_gsh = -4; c_ms = 138580; c_mh = 26; end
      5: begin c_n1s = 138038; c_n1h = 24; c_n2s = 172856; c_n2h = 26;
        c_r1a = 131119; c_r1b = 224; c_r1h = 17; c_r2a = 257655; c_r2b = 4489; c_r2h = 18;
        c_shs = 21; c_ctxs = 170241; c_ctxh = 32; c_gsh = -3; c_ms = 148591; c_mh = 28; end
      6: begin c_n1s = 171183; c_n1h = 25; c_n2s = 178694; c_n2h = 26;
        c_r1a = 131099; c_r1b = 139; c_r1h = 17; c_r2a = 261992; c_r2b = 480; c_r2h = 18;
        c_shs = 21; c_ctxs = 211215; c_ctxh = 32; c_gsh = -4; c_ms = 255888; c_mh = 26; end
      7: begin c_n1s = 189365; c_n1h = 25; c_n2s = 202569; c_n2h = 26;
        c_r1a = 131108; c_r1b = 89; c_r1h = 17; c_r2a = 261996; c_r2b = 307; c_r2h = 18;
        c_shs = 20; c_ctxs = 178502; c_ctxh = 32; c_gsh = -4; c_ms = 261348; c_mh = 26; end
      8: begin c_n1s = 195463; c_n1h = 24; c_n2s = 225892; c_n2h = 26;
        c_r1a = 131088; c_r1b = 180; c_r1h = 17; c_r2a = 261998; c_r2b = 264; c_r2h = 18;
        c_shs = 16; c_ctxs = 133225; c_ctxh = 32; c_gsh = -4; c_ms = 163041; c_mh = 26; end
      9: begin c_n1s = 132407; c_n1h = 23; c_n2s = 251887; c_n2h = 26;
        c_r1a = 131100; c_r1b = 154; c_r1h = 17; c_r2a = 261994; c_r2b = 772; c_r2h = 18;
        c_shs = 20; c_ctxs = 163680; c_ctxh = 32; c_gsh = -4; c_ms = 215318; c_mh = 25; end
      10: begin c_n1s = 135910; c_n1h = 24; c_n2s = 224921; c_n2h = 25;
        c_r1a = 131096; c_r1b = 321; c_r1h = 17; c_r2a = 261870; c_r2b = 592; c_r2h = 18;
        c_shs = 20; c_ctxs = 145292; c_ctxh = 32; c_gsh = -4; c_ms = 246165; c_mh = 26; end
      11: begin c_n1s = 161109; c_n1h = 23; c_n2s = 191010; c_n2h = 25;
        c_r1a = 131083; c_r1b = 165; c_r1h = 17; c_r2a = 261952; c_r2b = 601; c_r2h = 18;
        c_shs = 20; c_ctxs = 226720; c_ctxh = 32; c_gsh = -4; c_ms = 156072; c_mh = 25; end
      12: begin c_n1s = 169480; c_n1h = 24; c_n2s = 167072; c_n2h = 24;
        c_r1a = 262143; c_r1b = 431; c_r1h = 18; c_r2a = 261968; c_r2b = 583; c_r2h = 18;
        c_shs = 20; c_ctxs = 138353; c_ctxh = 32; c_gsh = -4; c_ms = 220993; c_mh = 26; end
      13: begin c_n1s = 135878; c_n1h = 23; c_n2s = 207633; c_n2h = 25;
        c_r1a = 131079; c_r1b = 216; c_r1h = 17; c_r2a = 262025; c_r2b = 689; c_r2h = 18;
        c_shs = 21; c_ctxs = 179791; c_ctxh = 32; c_gsh = -4; c_ms = 147704; c_mh = 25; end
      14: begin c_n1s = 181329; c_n1h = 25; c_n2s = 233395; c_n2h = 25;
        c_r1a = 262142; c_r1b = 606; c_r1h = 18; c_r2a = 261940; c_r2b = 625; c_r2h = 18;
        c_shs = 21; c_ctxs = 145785; c_ctxh = 32; c_gsh = -4; c_ms = 219364; c_mh = 26; end
      15: begin c_n1s = 244011; c_n1h = 25; c_n2s = 236702; c_n2h = 25;
        c_r1a = 262101; c_r1b = 493; c_r1h = 18; c_r2a = 261857; c_r2b = 723; c_r2h = 18;
        c_shs = 21; c_ctxs = 236886; c_ctxh = 32; c_gsh = -4; c_ms = 149912; c_mh = 26; end
      16: begin c_n1s = 231455; c_n1h = 24; c_n2s = 249029; c_n2h = 25;
        c_r1a = 262135; c_r1b = 292; c_r1h = 18; c_r2a = 262124; c_r2b = 905; c_r2h = 18;
        c_shs = 21; c_ctxs = 194453; c_ctxh = 32; c_gsh = -4; c_ms = 189936; c_mh = 27; end
      17: begin c_n1s = 197140; c_n1h = 25; c_n2s = 243884; c_n2h = 25;
        c_r1a = 261986; c_r1b = 349; c_r1h = 18; c_r2a = 131120; c_r2b = 486; c_r2h = 17;
        c_shs = 21; c_ctxs = 153295; c_ctxh = 32; c_gsh = -4; c_ms = 138192; c_mh = 26; end
      18: begin c_n1s = 228755; c_n1h = 25; c_n2s = 208121; c_n2h = 25;
        c_r1a = 262143; c_r1b = 447; c_r1h = 18; c_r2a = 131127; c_r2b = 530; c_r2h = 17;
        c_shs = 20; c_ctxs = 163616; c_ctxh = 32; c_gsh = -3; c_ms = 132374; c_mh = 27; end
      19: begin c_n1s = 259939; c_n1h = 25; c_n2s = 167374; c_n2h = 25;
        c_r1a = 262136; c_r1b = 311; c_r1h = 18; c_r2a = 131202; c_r2b = 686; c_r2h = 17;
        c_shs = 20; c_ctxs = 153138; c_ctxh = 32; c_gsh = -3; c_ms = 180664; c_mh = 27; end
      20: begin c_n1s = 228191; c_n1h = 25; c_n2s = 167104; c_n2h = 25;
        c_r1a = 262029; c_r1b = 577; c_r1h = 18; c_r2a = 131423; c_r2b = 1280; c_r2h = 17;
        c_shs = 21; c_ctxs = 143373; c_ctxh = 32; c_gsh = -3; c_ms = 181272; c_mh = 26; end
      21: begin c_n1s = 167932; c_n1h = 24; c_n2s = 133876; c_n2h = 26;
        c_r1a = 262110; c_r1b = 1846; c_r1h = 18; c_r2a = 212530; c_r2b = 206185; c_r2h = 13;
        c_shs = 21; c_ctxs = 174101; c_ctxh = 32; c_gsh = -3; c_ms = 208609; c_mh = 31; end
      22: begin c_n1s = 151328; c_n1h = 23; c_n2s = 163264; c_n2h = 24;
        c_r1a = 257705; c_r1b = 15233; c_r1h = 18; c_r2a = 134553; c_r2b = 61956; c_r2h = 17;
        c_shs = 22; c_ctxs = 252155; c_ctxh = 32; c_gsh = -3; c_ms = 204004; c_mh = 28; end
      23: begin c_n1s = 255609; c_n1h = 23; c_n2s = 253926; c_n2h = 24;
        c_r1a = 233160; c_r1b = 112906; c_r1h = 18; c_r2a = 219909; c_r2b = 233230; c_r2h = 18;
        c_shs = 21; c_ctxs = 140701; c_ctxh = 32; c_gsh = -3; c_ms = 183777; c_mh = 27; end
      default: begin c_n1s = 0; c_n1h = 0; c_n2s = 0; c_n2h = 0; c_r1a = 0;
        c_r1b = 0; c_r1h = 0; c_r2a = 0; c_r2b = 0; c_r2h = 0; c_shs = 0;
        c_ctxs = 0; c_ctxh = 0; c_gsh = 0; c_ms = 0; c_mh = 0; end
    endcase
  end

  wire [23:0] lw = lyr * 465920;
  wire [19:0] lcb = lyr * 12672;
  reg [23:0] wbase;
  reg [19:0] cbase;
  reg [15:0] gbase;
  reg [12:0] expect_n;
  wire [12:0] hcols = (hk == 31) ? 1152 : 4864;
  always @(*) begin
    wbase = 0; cbase = 0; gbase = 0; pj_depth = 896; pj_cols = 896;
    expect_n = 896; rn_scale = 0; rn_shift = 0; ra_sa = 0; ra_sb = 0; ra_sh = 0;
    at_shs = c_shs; at_scale = c_ctxs; at_shift = c_ctxh;
    case (st)
      S_EMB: begin wbase = 11182080 + (tok_r >> 5) * 896; cbase = 456064 + tok_r; end
      S_N1: begin gbase = lyr * 1792; rn_scale = c_n1s; rn_shift = c_n1h; end
      S_N2: begin gbase = lyr * 1792 + 896; rn_scale = c_n2s; rn_shift = c_n2h; end
      S_NF: begin gbase = 43008; rn_scale = 169359; rn_shift = 25; end
      S_Q: begin wbase = lw + 0; cbase = lcb + 0; pj_depth = 896; pj_cols = 896; expect_n = 896; end
      S_K: begin wbase = lw + 25088; cbase = lcb + 896; pj_depth = 896; pj_cols = 128; expect_n = 128; end
      S_V: begin wbase = lw + 28672; cbase = lcb + 1024; pj_depth = 896; pj_cols = 128; expect_n = 128; end
      S_O: begin wbase = lw + 32256; cbase = lcb + 1152; pj_depth = 896; pj_cols = 896; expect_n = 896; end
      S_G: begin wbase = lw + 57344; cbase = lcb + 2048; pj_depth = 896; pj_cols = 4864; expect_n = 4864; end
      S_U: begin wbase = lw + 193536; cbase = lcb + 6912; pj_depth = 896; pj_cols = 4864; expect_n = 4864; end
      S_DN: begin wbase = lw + 329728; cbase = lcb + 11776; pj_depth = 4864; pj_cols = 896; expect_n = 896; end
      S_HD: begin wbase = 11182080 + hk * 136192; cbase = 304128 + hk * 4864; pj_cols = hcols; expect_n = hcols; end
      S_R1: begin ra_sa = c_r1a; ra_sb = c_r1b; ra_sh = c_r1h; end
      S_R2: begin ra_sa = c_r2a; ra_sb = c_r2b; ra_sh = c_r2h; end
      S_ATT: expect_n = 64;
      S_RQ: expect_n = 448;
      S_RK: expect_n = 64;
      S_GLU: expect_n = 4864;
      default: ;
    endcase
  end
  wire in_norm = (st == S_N1) || (st == S_N2) || (st == S_NF);
  reg [12:0] ed;
  assign w_addr = wbase + ((st == S_EMB) ? ed : pj_w_addr);
  assign c_addr = cbase + ((st == S_EMB) ? 13'd0 : pj_c_addr);
  assign g_addr = gbase + rn_g_addr;
  // The KV head this query head reads.
  wire [14:0] kvsel = lyr * 2 + hh / 7;
  assign k_raddr = kvsel * 512 + at_k_addr;
  assign v_raddr = kvsel * 512 + at_v_addr;
  always @(posedge clk) begin
    rn_x_data <= xm[rn_x_addr];
    pj_a_data <= (st == S_O) ? cm[pj_a_addr] : (st == S_DN) ? mm[pj_a_addr] : nm[pj_a_addr];
  end
  wire run_proj = (st == S_Q) || (st == S_K) || (st == S_V) || (st == S_O) ||
                  (st == S_G) || (st == S_U) || (st == S_DN) || (st == S_HD);
  wire blk_busy = run_proj ? pj_busy : in_norm ? rn_busy : at_busy;
  wire pj_half = pj_index[5];
  wire [12:0] pj_hadr = ((pj_index >> 6) << 5) | (pj_index & 31);
  wire [12:0] fh = fj >> 5, fp = fj & 31;
  wire [12:0] oh = ocnt >> 5, op = ocnt & 31;
  // KV cache words: keys interleaved by position, values by dimension.
  wire [14:0] kslot = (lyr * 2 + oh) * 512 + (pos_r >> 5) * 64;
  wire [14:0] vslot = ((lyr * 2 + (pj_index >> 6)) * 256 + pos_r) * 2 + ((pj_index & 63) >> 5);
  reg ev1;
  reg [4:0] lane_r;
  wire signed [15:0] ew = w_data[lane_r * 16 +: 16];
  reg [17:0] hbase;

  always @(posedge clk) begin
    if (!rst_n) begin
      st <= S_IDLE; ph <= 1'b0; busy <= 1'b0; done <= 1'b0; hen <= 1'b0;
      lyr <= 0; hh <= 0; hk <= 0; tok_r <= 0; pos_r <= 0; next_tok <= 0;
      best <= 0; fj <= 0; ocnt <= 0; gcnt <= 0; ed <= 0; ev1 <= 1'b0; lane_r <= 0;
      pj_start <= 1'b0; rn_start <= 1'b0; at_start <= 1'b0; at_load_valid <= 1'b0;
      at_load_data <= 0; ra_a <= 0; ra_b <= 0; ra_v <= 1'b0; ro_x1 <= 0;
      ro_x2 <= 0; ro_idx <= 0; ro_v <= 1'b0; si_x <= 0; si_v <= 1'b0;
      rq_acc <= 0; rq_v <= 1'b0; rq_scale <= 0; rq_shift <= 0;
      kw0_en <= 1'b0; kw1_en <= 1'b0; vw_en <= 1'b0; kw0_addr <= 0; kw1_addr <= 0;
      vw_addr <= 0; kw0_lane <= 0; kw1_lane <= 0; vw_lane <= 0; kw0_data <= 0;
      kw1_data <= 0; vw_data <= 0; hbase <= 0;
    end else begin
      done <= 1'b0; pj_start <= 1'b0; rn_start <= 1'b0; at_start <= 1'b0;
      at_load_valid <= 1'b0; ra_v <= 1'b0; ro_v <= 1'b0; si_v <= 1'b0;
      rq_v <= 1'b0; kw0_en <= 1'b0; kw1_en <= 1'b0; vw_en <= 1'b0;
      if (run_proj && pj_valid) begin
        ocnt <= ocnt + 1;
        case (st)
          S_Q: if (pj_half) qhi[pj_hadr] <= pj_data; else qlo[pj_hadr] <= pj_data;
          S_K: if (pj_half) khi[pj_hadr] <= pj_data; else klo[pj_hadr] <= pj_data;
          S_V: begin vw_en <= 1'b1; vw_addr <= vslot; vw_lane <= pj_index[4:0];
                 vw_data <= pj_data; end
          S_O, S_DN: am[pj_index] <= pj_data;
          S_G: gm[pj_index] <= pj_data;
          S_U: um[pj_index] <= pj_data;
          S_HD: if ((hk == 0 && ocnt == 0) || pj_data > best) begin
                  best <= pj_data; next_tok <= hbase + pj_index; end
          default: ;
        endcase
      end
      if (in_norm && rn_valid) begin nm[rn_index] <= rn_data; ocnt <= ocnt + 1; end
      if (st == S_ATT && at_valid) begin
        cm[hh * 64 + at_index] <= at_data; ocnt <= ocnt + 1; end
      if ((st == S_R1 || st == S_R2) && ra_vout) begin xm[ocnt] <= ra_y; ocnt <= ocnt + 1; end
      if (st == S_RQ && ro_vout) begin qlo[ocnt] <= ro_y1; qhi[ocnt] <= ro_y2; ocnt <= ocnt + 1; end
      if (st == S_RK && ro_vout) begin
        kw0_en <= 1'b1; kw0_addr <= kslot + op; kw0_lane <= pos_r[4:0]; kw0_data <= ro_y1;
        kw1_en <= 1'b1; kw1_addr <= kslot + op + 32; kw1_lane <= pos_r[4:0]; kw1_data <= ro_y2;
        ocnt <= ocnt + 1;
      end
      if (st == S_GLU && si_vout) begin
        rq_acc <= si_y * um[gcnt]; rq_v <= 1'b1; gcnt <= gcnt + 1; end
      if ((st == S_GLU || st == S_EMB) && rq_vout) begin
        if (st == S_GLU) mm[ocnt] <= rq_q; else xm[ocnt] <= rq_q;
        ocnt <= ocnt + 1;
      end

      case (st)
        S_IDLE: if (start) begin
          tok_r <= tok; pos_r <= pos; hen <= head_en; busy <= 1'b1; lyr <= 0;
          hh <= 0; hk <= 0; st <= S_EMB; ed <= 0; ev1 <= 1'b0; ocnt <= 0; ph <= 1'b0;
          lane_r <= tok[4:0];
        end
        // The embedding row out of the head's weight words, requantized
        // with this token's own constants.
        S_EMB: begin
          rq_scale <= c_data[17:0]; rq_shift <= c_data[24:18];
          if (ed < 896) ed <= ed + 1;
          ev1 <= (ed < 896);
          if (ev1) begin rq_acc <= ew; rq_v <= 1'b1; end
          if (ocnt == 896) begin ocnt <= 0; fj <= 0; ph <= 1'b0; st <= S_N1; end
        end
        S_R1, S_R2: begin
          if (fj < 896) begin ra_a <= xm[fj]; ra_b <= am[fj]; ra_v <= 1'b1; fj <= fj + 1; end
          if (ocnt == 896) begin
            fj <= 0; ocnt <= 0; ph <= 1'b0;
            if (st == S_R1) st <= S_N2;
            else if (lyr + 1 < 24) begin lyr <= lyr + 1; st <= S_N1; end
            else if (hen) begin st <= S_NF; end
            else begin busy <= 1'b0; done <= 1'b1; st <= S_IDLE; end
          end
        end
        S_RQ, S_RK: begin
          if (fj < expect_n) begin
            ro_x1 <= (st == S_RQ) ? qlo[fj] : klo[fj];
            ro_x2 <= (st == S_RQ) ? qhi[fj] : khi[fj];
            ro_idx <= fp[4:0]; ro_v <= 1'b1; fj <= fj + 1;
          end
          if (ocnt == expect_n) begin fj <= 0; ocnt <= 0; ph <= 1'b0;
            st <= (st == S_RQ) ? S_RK : S_LQ; end
        end
        S_LQ: begin
          if (fj < 64) begin
            at_load_valid <= 1'b1;
            at_load_data <= fj[5] ? qhi[hh * 32 + fj[4:0]] : qlo[hh * 32 + fj[4:0]];
            fj <= fj + 1;
          end else begin fj <= 0; ocnt <= 0; ph <= 1'b0; st <= S_ATT; end
        end
        S_GLU: begin
          rq_scale <= c_ms; rq_shift <= c_mh;
          if (fj < 4864) begin
            si_x <= (c_gsh >= 0) ? (gm[fj] <<< c_gsh) : (gm[fj] >>> (-c_gsh));
            si_v <= 1'b1; fj <= fj + 1;
          end
          if (ocnt == 4864) begin fj <= 0; ocnt <= 0; gcnt <= 0; ph <= 1'b0; st <= S_DN; end
        end
        default: begin
          if (!ph) begin
            ph <= 1'b1; ocnt <= 0;
            if (run_proj) pj_start <= 1'b1;
            else if (in_norm) rn_start <= 1'b1;
            else at_start <= 1'b1;
            if (st == S_HD) hbase <= hk * 4864;
          end else if (!blk_busy && ocnt == expect_n && !pj_start && !rn_start && !at_start) begin
            ph <= 1'b0; ocnt <= 0; fj <= 0;
            case (st)
              S_N1: st <= S_Q;
              S_Q: st <= S_K;
              S_K: st <= S_V;
              S_V: st <= S_RQ;
              S_ATT: if (hh + 1 < 14) begin hh <= hh + 1; st <= S_LQ; end
                     else begin hh <= 0; st <= S_O; end
              S_O: st <= S_R1;
              S_N2: st <= S_G;
              S_G: st <= S_U;
              S_U: st <= S_GLU;
              S_DN: st <= S_R2;
              S_NF: st <= S_HD;
              S_HD: if (hk < 31) hk <= hk + 1;
                    else begin busy <= 1'b0; done <= 1'b1; st <= S_IDLE; end
              default: st <= S_IDLE;
            endcase
          end
        end
      endcase
    end
  end
endmodule
