// GENERATED by board.py: do not edit by hand.
// Basys 3 top level: prompt in over the USB-UART, generated text out.
module fpgai_top #(parameter DIV = 434) (
  input         clk,        // 100 MHz board oscillator
  input         btnC,       // reset
  input         RsRx,
  output        RsTx,
  output [15:0] led
);
`ifdef SIM
  wire cclk = clk;
`else
  // 100 MHz in, 50 MHz out: the decoder's clock.
  wire fb, c0;
  MMCME2_BASE #(.CLKIN1_PERIOD(10.0), .CLKFBOUT_MULT_F(10.0),
                .CLKOUT0_DIVIDE_F(20.0)) mmcm (
    .CLKIN1(clk), .CLKFBIN(fb), .CLKFBOUT(fb), .CLKOUT0(c0),
    .PWRDWN(1'b0), .RST(1'b0), .LOCKED());
  wire cclk;
  BUFG bg (.I(c0), .O(cclk));
`endif
  reg [2:0] rs = 3'b000;
  always @(posedge cclk) rs <= {rs[1:0], ~btnC};
  wire rst_n = rs[2];

  // Weights, embeddings and gains: a ROM the decoder reads through
  // its parameter port, one cycle after the address.
  reg signed [7:0] prom [0:19615];
  initial $readmemh("qwen_params.hex", prom);
  wire [14:0] p_addr;
  reg signed [7:0] p_data;
  always @(posedge cclk) p_data <= prom[p_addr];

  wire [7:0] rx_data;
  wire rx_valid;
  uart_rx #(.DIV(DIV)) urx (.clk(cclk), .rst_n(rst_n), .rx(RsRx),
    .data(rx_data), .valid(rx_valid));
  reg [7:0] tx_data;
  reg tx_send;
  wire tx_ready;
  uart_tx #(.DIV(DIV)) utx (.clk(cclk), .rst_n(rst_n), .data(tx_data),
    .send(tx_send), .tx(RsTx), .ready(tx_ready));

  reg start;
  reg [3:0] tok;
  reg [4:0] pos;
  wire lg_valid, done, busy;
  wire [3:0] lg_index, next_tok;
  wire signed [7:0] lg_data;
  qwen_decoder dec (.clk(cclk), .rst_n(rst_n), .start(start),
    .tok(tok), .pos(pos), .p_addr(p_addr), .p_data(p_data),
    .lg_valid(lg_valid), .lg_index(lg_index), .lg_data(lg_data),
    .next_tok(next_tok), .done(done), .busy(busy));

  // Character to token and back: the checkpoint's own vocabulary.
  function [4:0] to_tok(input [7:0] c);
    begin
      case (c)
        8'd32: to_tok = {1'b1, 4'd0};
        8'd46: to_tok = {1'b1, 4'd1};
        8'd97: to_tok = {1'b1, 4'd2};
        8'd99: to_tok = {1'b1, 4'd3};
        8'd100: to_tok = {1'b1, 4'd4};
        8'd101: to_tok = {1'b1, 4'd5};
        8'd103: to_tok = {1'b1, 4'd6};
        8'd104: to_tok = {1'b1, 4'd7};
        8'd105: to_tok = {1'b1, 4'd8};
        8'd108: to_tok = {1'b1, 4'd9};
        8'd110: to_tok = {1'b1, 4'd10};
        8'd111: to_tok = {1'b1, 4'd11};
        8'd114: to_tok = {1'b1, 4'd12};
        8'd115: to_tok = {1'b1, 4'd13};
        8'd116: to_tok = {1'b1, 4'd14};
        8'd119: to_tok = {1'b1, 4'd15};
        default: to_tok = 0;
      endcase
    end
  endfunction
  function [7:0] to_chr(input [3:0] t);
    begin
      case (t)
        4'd0: to_chr = 8'd32;
        4'd1: to_chr = 8'd46;
        4'd2: to_chr = 8'd97;
        4'd3: to_chr = 8'd99;
        4'd4: to_chr = 8'd100;
        4'd5: to_chr = 8'd101;
        4'd6: to_chr = 8'd103;
        4'd7: to_chr = 8'd104;
        4'd8: to_chr = 8'd105;
        4'd9: to_chr = 8'd108;
        4'd10: to_chr = 8'd110;
        4'd11: to_chr = 8'd111;
        4'd12: to_chr = 8'd114;
        4'd13: to_chr = 8'd115;
        4'd14: to_chr = 8'd116;
        4'd15: to_chr = 8'd119;
        default: to_chr = 8'd63;
      endcase
    end
  endfunction

  reg [3:0] prompt [0:23];
  reg [5:0] plen;
  reg [2:0] st;
  localparam T_IN = 3'd0, T_STEP = 3'd1, T_WAIT = 3'd2, T_SEND = 3'd3,
             T_NL = 3'd4;
  wire [4:0] rt = to_tok(rx_data);
  always @(posedge cclk) begin
    if (!rst_n) begin
      st <= T_IN; plen <= 0; start <= 1'b0; tok <= 0; pos <= 0;
      tx_send <= 1'b0; tx_data <= 0;
    end else begin
      start <= 1'b0; tx_send <= 1'b0;
      case (st)
        // Collect the prompt; enter starts the decode.
        T_IN: if (rx_valid) begin
          if ((rx_data == 8'd13 || rx_data == 8'd10) && plen != 0) begin
            pos <= 0; tok <= prompt[0]; st <= T_STEP;
          end else if (rt[4] && plen < 24) begin
            prompt[plen] <= rt[3:0]; plen <= plen + 1;
          end
        end
        T_STEP: begin start <= 1'b1; st <= T_WAIT; end
        T_WAIT: if (done) begin
          if (pos + 1 < plen) begin
            // Still in the prompt: feed the next character.
            pos <= pos + 1; tok <= prompt[pos + 1]; st <= T_STEP;
          end else begin
            tx_data <= to_chr(next_tok); st <= T_SEND;
          end
        end
        T_SEND: if (tx_ready) begin
          tx_send <= 1'b1;
          if (pos + 1 < 24) begin
            pos <= pos + 1; tok <= next_tok; st <= T_STEP;
          end else begin
            st <= T_NL;
          end
        end
        // The newline goes once the last character has left: data
        // and send change together, or the UART sends the wrong one.
        T_NL: if (tx_ready && !tx_send) begin
          tx_data <= 8'd10; tx_send <= 1'b1; plen <= 0; st <= T_IN;
        end
        default: st <= T_IN;
      endcase
    end
  end

  reg [25:0] beat;
  always @(posedge cclk) beat <= beat + 1;
  assign led = {beat[25], 14'd0, st != T_IN};
endmodule
