// GENERATED by qwen_decoder.py: do not edit by hand.
// One decode step of the Qwen-shaped checkpoint over the generated
// blocks: 2 layers, 2 query heads over 1 KV head, RoPE, SwiGLU.
module qwen_decoder (
  input                    clk,
  input                    rst_n,
  input                    start,
  input      [3:0] tok,
  input      [4:0] pos,
  output     [14:0] p_addr,
  input      signed [7:0] p_data,
  output reg               lg_valid,
  output reg [3:0] lg_index,
  output reg signed [7:0] lg_data,
  output reg [3:0] next_tok,
  output reg               done,
  output reg               busy
);
  localparam S_IDLE = 5'd0, S_CPTOK = 5'd1, S_N1 = 5'd2, S_Q = 5'd3, S_K = 5'd4, S_V = 5'd5, S_RQ = 5'd6, S_RK = 5'd7, S_LQ = 5'd8, S_ATT = 5'd9, S_O = 5'd10, S_R1 = 5'd11, S_N2 = 5'd12, S_G = 5'd13, S_U = 5'd14, S_GLU = 5'd15, S_DN = 5'd16, S_R2 = 5'd17, S_NF = 5'd18, S_HD = 5'd19, S_ARG = 5'd20;
  reg [4:0] st;
  reg ph;
  reg [1:0] lyr;
  reg [1:0] hh;
  reg [3:0] tok_r;
  reg [4:0] pos_r;
  // One memory per activation, each with a single write port.
  reg signed [7:0] xm [0:31];
  reg signed [7:0] nm [0:31];
  reg signed [7:0] qlo [0:15];
  reg signed [7:0] qhi [0:15];
  reg signed [7:0] klo [0:7];
  reg signed [7:0] khi [0:7];
  reg signed [7:0] cm [0:31];
  reg signed [7:0] am [0:31];
  reg signed [7:0] gm [0:63];
  reg signed [7:0] um [0:63];
  reg signed [7:0] mm [0:63];
  reg signed [7:0] lgm [0:15];
  // KV cache, [layer][kv head][position][...]: keys split by rotary
  // half so each half takes one write a cycle.
  reg signed [7:0] kclo [0:383];
  reg signed [7:0] kchi [0:383];
  reg signed [7:0] vc [0:767];
  reg [6:0] fj, ocnt, gcnt;
  reg cp_v;
  reg [6:0] cp_i;

  reg pj_start;
  reg [6:0] pj_depth, pj_cols;
  reg [17:0] pj_scale, rn_scale, ra_sa, ra_sb, rq_scale;
  reg [6:0] pj_shift, rn_shift, ra_sh, rq_shift;
  wire [6:0] pj_a_addr;
  wire [13:0] pj_w_addr;
  reg signed [7:0] pj_a_data;
  wire pj_valid, pj_busy;
  wire [6:0] pj_index;
  wire signed [7:0] pj_data;
  proj u_proj (.clk(clk), .rst_n(rst_n), .start(pj_start),
    .depth(pj_depth), .cols(pj_cols), .scale(pj_scale),
    .shift(pj_shift), .a_addr(pj_a_addr), .a_data(pj_a_data),
    .w_addr(pj_w_addr), .w_data(p_data), .o_valid(pj_valid),
    .o_index(pj_index), .o_data(pj_data), .busy(pj_busy));

  reg rn_start;
  wire [4:0] rn_x_addr, rn_g_addr, rn_index;
  reg signed [7:0] rn_x_data;
  wire rn_valid, rn_busy;
  wire signed [7:0] rn_data;
  rmsnorm u_norm (.clk(clk), .rst_n(rst_n), .start(rn_start),
    .eps(22'd1), .scale_o(rn_scale), .shift_o(rn_shift),
    .x_addr(rn_x_addr), .x_data(rn_x_data), .g_addr(rn_g_addr),
    .g_data(p_data), .o_valid(rn_valid), .o_index(rn_index),
    .o_data(rn_data), .busy(rn_busy));

  reg at_start, at_load_valid;
  reg signed [7:0] at_load_data;
  reg [4:0] at_shs;
  reg [17:0] at_scale;
  reg [6:0] at_shift;
  wire [8:0] at_k_addr, at_v_addr;
  reg signed [7:0] at_klo, at_khi, at_v_data;
  reg at_ksel;
  wire signed [7:0] at_k_data = at_ksel ? at_khi : at_klo;
  wire at_valid, at_busy;
  wire [3:0] at_index;
  wire signed [7:0] at_data;
  attn u_attn (.clk(clk), .rst_n(rst_n), .load_valid(at_load_valid),
    .load_data(at_load_data), .start(at_start),
    .n({1'd0, pos_r} + 6'd1), .shift_s(at_shs),
    .scale_o(at_scale), .shift_o(at_shift),
    .k_addr(at_k_addr), .k_data(at_k_data), .v_addr(at_v_addr),
    .v_data(at_v_data), .o_valid(at_valid), .o_index(at_index),
    .o_data(at_data), .busy(at_busy));

  reg signed [7:0] ra_a, ra_b;
  reg ra_v;
  wire signed [7:0] ra_y;
  wire ra_vout;
  resadd u_add (.clk(clk), .rst_n(rst_n), .a(ra_a), .b(ra_b),
    .scale_a(ra_sa), .scale_b(ra_sb), .shift(ra_sh),
    .valid_in(ra_v), .y(ra_y), .valid_out(ra_vout));

  reg signed [7:0] ro_x1, ro_x2;
  reg [2:0] ro_idx;
  reg ro_v;
  wire signed [7:0] ro_y1, ro_y2;
  wire ro_vout;
  rope u_rope (.clk(clk), .rst_n(rst_n), .x1(ro_x1), .x2(ro_x2),
    .idx(ro_idx), .pos(pos_r), .valid_in(ro_v), .y1(ro_y1),
    .y2(ro_y2), .valid_out(ro_vout));

  reg signed [12:0] si_x;
  reg si_v;
  wire signed [12:0] si_y;
  wire si_vout;
  silu u_silu (.clk(clk), .rst_n(rst_n), .x(si_x), .valid_in(si_v),
    .y(si_y), .valid_out(si_vout));
  reg signed [23:0] rq_acc;
  reg rq_v;
  wire signed [7:0] rq_q;
  wire rq_sat, rq_vout;
  requant u_rq (.clk(clk), .rst_n(rst_n), .acc_in(rq_acc),
    .scale(rq_scale), .shift(rq_shift), .valid_in(rq_v),
    .q_out(rq_q), .sat(rq_sat), .valid_out(rq_vout));

  // ---- per-state, per-layer constants and weight bases
  reg [14:0] pbase;
  reg [6:0] expect_n;
  reg [3:0] gsh;
  always @(*) begin
    pbase = 0; expect_n = 32;
    pj_depth = 0; pj_cols = 0; pj_scale = 0; pj_shift = 0;
    rn_scale = 0; rn_shift = 0; ra_sa = 0; ra_sb = 0; ra_sh = 0;
    rq_scale = 0; rq_shift = 0; at_shs = 0; at_scale = 0;
    at_shift = 0; gsh = 0;
    case (st)
      S_CPTOK: pbase = 0 + tok_r * 32;
      S_NF: begin pbase = 19072; rn_scale = 136362; rn_shift = 31; end
      S_HD: begin pbase = 19104; pj_depth = 32; pj_cols = 16;
        pj_scale = 183379; pj_shift = 26; expect_n = 16; end
      S_ARG: expect_n = 16;
      S_N1: case (lyr)
        0: begin pbase = 512; rn_scale = 141958; rn_shift = 31; end
        1: begin pbase = 9792; rn_scale = 138799; rn_shift = 31; end
        default: ;
      endcase
      S_N2: case (lyr)
        0: begin pbase = 544; rn_scale = 246031; rn_shift = 32; end
        1: begin pbase = 9824; rn_scale = 144351; rn_shift = 31; end
        default: ;
      endcase
      S_Q: case (lyr)
        0: begin pbase = 576; pj_depth = 32; pj_cols = 32; pj_scale = 226506; pj_shift = 27; expect_n = 32; end
        1: begin pbase = 9856; pj_depth = 32; pj_cols = 32; pj_scale = 145345; pj_shift = 26; expect_n = 32; end
        default: ;
      endcase
      S_K: case (lyr)
        0: begin pbase = 1600; pj_depth = 32; pj_cols = 16; pj_scale = 143112; pj_shift = 26; expect_n = 16; end
        1: begin pbase = 10880; pj_depth = 32; pj_cols = 16; pj_scale = 167594; pj_shift = 26; expect_n = 16; end
        default: ;
      endcase
      S_V: case (lyr)
        0: begin pbase = 2112; pj_depth = 32; pj_cols = 16; pj_scale = 213354; pj_shift = 26; expect_n = 16; end
        1: begin pbase = 11392; pj_depth = 32; pj_cols = 16; pj_scale = 250390; pj_shift = 26; expect_n = 16; end
        default: ;
      endcase
      S_O: case (lyr)
        0: begin pbase = 2624; pj_depth = 32; pj_cols = 32; pj_scale = 204104; pj_shift = 26; expect_n = 32; end
        1: begin pbase = 11904; pj_depth = 32; pj_cols = 32; pj_scale = 136492; pj_shift = 27; expect_n = 32; end
        default: ;
      endcase
      S_G: case (lyr)
        0: begin pbase = 3648; pj_depth = 32; pj_cols = 64; pj_scale = 222745; pj_shift = 26; expect_n = 64; end
        1: begin pbase = 12928; pj_depth = 32; pj_cols = 64; pj_scale = 143325; pj_shift = 26; expect_n = 64; end
        default: ;
      endcase
      S_U: case (lyr)
        0: begin pbase = 5696; pj_depth = 32; pj_cols = 64; pj_scale = 241784; pj_shift = 26; expect_n = 64; end
        1: begin pbase = 14976; pj_depth = 32; pj_cols = 64; pj_scale = 221495; pj_shift = 26; expect_n = 64; end
        default: ;
      endcase
      S_DN: case (lyr)
        0: begin pbase = 7744; pj_depth = 64; pj_cols = 32; pj_scale = 186240; pj_shift = 25; expect_n = 32; end
        1: begin pbase = 17024; pj_depth = 64; pj_cols = 32; pj_scale = 256048; pj_shift = 25; expect_n = 32; end
        default: ;
      endcase
      S_R1: case (lyr)
        0: begin ra_sa = 11177; ra_sb = 259755; ra_sh = 18; end
        1: begin ra_sa = 224254; ra_sb = 102693; ra_sh = 18; end
        default: ;
      endcase
      S_R2: case (lyr)
        0: begin ra_sa = 36175; ra_sb = 248429; ra_sh = 18; end
        1: begin ra_sa = 237805; ra_sb = 84368; ra_sh = 18; end
        default: ;
      endcase
      S_ATT: case (lyr)
        0: begin at_shs = 3; at_scale = 131072; at_shift = 32; expect_n = 16; end
        1: begin at_shs = 2; at_scale = 131072; at_shift = 32; expect_n = 16; end
        default: ;
      endcase
      S_GLU: case (lyr)
        0: begin rq_scale = 232128; rq_shift = 29; gsh = 5; expect_n = 64; end
        1: begin rq_scale = 239908; rq_shift = 29; gsh = 5; expect_n = 64; end
        default: ;
      endcase
      S_RQ: case (lyr)
        0: begin expect_n = 16; end
        1: begin expect_n = 16; end
        default: ;
      endcase
      S_RK: case (lyr)
        0: begin expect_n = 8; end
        1: begin expect_n = 8; end
        default: ;
      endcase
      default: ;
    endcase
  end

  wire in_norm = (st == S_N1) || (st == S_N2) || (st == S_NF);
  assign p_addr = in_norm ? pbase + rn_g_addr
                : (st == S_CPTOK) ? pbase + fj
                : pbase + pj_w_addr;
  // Where this layer's cache starts, per KV head.
  wire [5:0] kvrow = (lyr * 1 + hh / 2) * 24;
  wire [8:0] j_at = at_k_addr >> 4;
  wire [3:0] d_at = at_k_addr & 15;
  wire [5:0] kslot = (lyr * 1) * 24 + pos_r;
  always @(posedge clk) begin
    rn_x_data <= xm[rn_x_addr];
    pj_a_data <= (st == S_O) ? cm[pj_a_addr]
               : (st == S_DN) ? mm[pj_a_addr] : nm[pj_a_addr];
    at_klo <= kclo[(kvrow + j_at) * 8 + d_at[2:0]];
    at_khi <= kchi[(kvrow + j_at) * 8 + d_at[2:0]];
    at_ksel <= d_at[3];
    at_v_data <= vc[kvrow * 16 + at_v_addr];
  end

  wire run_proj = (st == S_Q) || (st == S_K) || (st == S_V) ||
                  (st == S_O) || (st == S_G) || (st == S_U) ||
                  (st == S_DN) || (st == S_HD);
  wire blk_busy = run_proj ? pj_busy : in_norm ? rn_busy : at_busy;
  // A projection output's place in a rotary-split vector.
  wire [0:0] pj_half = pj_index[3];
  wire [6:0] pj_hadr = ((pj_index >> 4) << 3) | (pj_index & 7);
  // The cache row of a key pair the rotary unit hands back.
  wire [5:0] ok_row = kslot + (ocnt >> 3) * 24;
  wire [2:0] ok_p = ocnt & 7;
  reg signed [7:0] best;
  reg [3:0] best_i;

  always @(posedge clk) begin
    if (!rst_n) begin
      st <= S_IDLE; ph <= 1'b0; busy <= 1'b0; done <= 1'b0;
      lyr <= 0; hh <= 0; tok_r <= 0; pos_r <= 0; next_tok <= 0;
      fj <= 0; ocnt <= 0; gcnt <= 0; cp_v <= 1'b0; cp_i <= 0;
      pj_start <= 1'b0; rn_start <= 1'b0; at_start <= 1'b0;
      at_load_valid <= 1'b0; at_load_data <= 0; ra_a <= 0; ra_b <= 0;
      ra_v <= 1'b0; ro_x1 <= 0; ro_x2 <= 0; ro_idx <= 0; ro_v <= 1'b0;
      si_x <= 0; si_v <= 1'b0; rq_acc <= 0; rq_v <= 1'b0;
      lg_valid <= 1'b0; lg_index <= 0; lg_data <= 0; best <= 0;
      best_i <= 0;
    end else begin
      done <= 1'b0; pj_start <= 1'b0; rn_start <= 1'b0;
      at_start <= 1'b0; at_load_valid <= 1'b0; ra_v <= 1'b0;
      ro_v <= 1'b0; si_v <= 1'b0; rq_v <= 1'b0; lg_valid <= 1'b0;
      cp_v <= 1'b0;
      if (run_proj && pj_valid) begin
        ocnt <= ocnt + 1;
        case (st)
          S_Q: if (pj_half) qhi[pj_hadr] <= pj_data;
               else qlo[pj_hadr] <= pj_data;
          S_K: if (pj_half) khi[pj_hadr] <= pj_data;
               else klo[pj_hadr] <= pj_data;
          S_V: vc[(kslot + (pj_index >> 4) * 24) * 16 + (pj_index & 15)] <= pj_data;
          S_O, S_DN: am[pj_index] <= pj_data;
          S_G: gm[pj_index] <= pj_data;
          S_U: um[pj_index] <= pj_data;
          S_HD: begin
            lgm[pj_index] <= pj_data;
            lg_valid <= 1'b1; lg_index <= pj_index[3:0];
            lg_data <= pj_data;
          end
          default: ;
        endcase
      end
      if (in_norm && rn_valid) begin
        nm[rn_index] <= rn_data; ocnt <= ocnt + 1;
      end
      if (st == S_ATT && at_valid) begin
        cm[hh * 16 + at_index] <= at_data; ocnt <= ocnt + 1;
      end
      if ((st == S_R1 || st == S_R2) && ra_vout) begin
        xm[ocnt] <= ra_y; ocnt <= ocnt + 1;
      end
      // Rotated pairs go back where they came from; keys to the cache.
      if (st == S_RQ && ro_vout) begin
        qlo[ocnt] <= ro_y1; qhi[ocnt] <= ro_y2; ocnt <= ocnt + 1;
      end
      if (st == S_RK && ro_vout) begin
        kclo[ok_row * 8 + ok_p] <= ro_y1;
        kchi[ok_row * 8 + ok_p] <= ro_y2;
        ocnt <= ocnt + 1;
      end
      // SiLU of the gate, times up, requantized: one stream.
      if (st == S_GLU && si_vout) begin
        rq_acc <= si_y * um[gcnt]; rq_v <= 1'b1; gcnt <= gcnt + 1;
      end
      if (st == S_GLU && rq_vout) begin
        mm[ocnt] <= rq_q; ocnt <= ocnt + 1;
      end
      if (cp_v) xm[cp_i] <= p_data;

      case (st)
        S_IDLE: if (start) begin
          tok_r <= tok; pos_r <= pos; busy <= 1'b1; lyr <= 0; hh <= 0;
          st <= S_CPTOK; fj <= 0; ocnt <= 0; ph <= 1'b0;
        end
        S_CPTOK: begin
          if (fj < 32) begin
            cp_v <= 1'b1; cp_i <= fj; fj <= fj + 1;
          end else if (!cp_v) begin
            fj <= 0; ocnt <= 0; st <= S_N1;
          end
        end
        S_R1, S_R2: begin
          if (fj < 32) begin
            ra_a <= xm[fj]; ra_b <= am[fj]; ra_v <= 1'b1; fj <= fj + 1;
          end
          if (ocnt == 32) begin
            fj <= 0; ocnt <= 0; ph <= 1'b0;
            if (st == S_R1) st <= S_N2;
            else if (lyr + 1 < 2) begin lyr <= lyr + 1; st <= S_N1; end
            else st <= S_NF;
          end
        end
        S_RQ, S_RK: begin
          if (fj < expect_n) begin
            ro_x1 <= (st == S_RQ) ? qlo[fj] : klo[fj];
            ro_x2 <= (st == S_RQ) ? qhi[fj] : khi[fj];
            ro_idx <= fj[2:0]; ro_v <= 1'b1; fj <= fj + 1;
          end
          if (ocnt == expect_n) begin
            fj <= 0; ocnt <= 0; ph <= 1'b0;
            st <= (st == S_RQ) ? S_RK : S_LQ;
          end
        end
        S_LQ: begin
          if (fj < 16) begin
            at_load_valid <= 1'b1;
            at_load_data <= fj[3] ? qhi[hh * 8 + fj[2:0]]
                                : qlo[hh * 8 + fj[2:0]];
            fj <= fj + 1;
          end else begin
            fj <= 0; ocnt <= 0; ph <= 1'b0; st <= S_ATT;
          end
        end
        S_GLU: begin
          if (fj < 64) begin
            si_x <= gm[fj] <<< gsh; si_v <= 1'b1; fj <= fj + 1;
          end
          if (ocnt == 64) begin
            fj <= 0; ocnt <= 0; gcnt <= 0; ph <= 1'b0; st <= S_DN;
          end
        end
        S_ARG: begin
          if (fj < 16) begin
            if (fj == 0 || lgm[fj] > best) begin
              best <= lgm[fj]; best_i <= fj[3:0];
            end
            fj <= fj + 1;
          end else begin
            next_tok <= best_i; done <= 1'b1; busy <= 1'b0;
            fj <= 0; st <= S_IDLE;
          end
        end
        default: begin
          if (!ph) begin
            ph <= 1'b1; ocnt <= 0;
            if (run_proj) pj_start <= 1'b1;
            else if (in_norm) rn_start <= 1'b1;
            else at_start <= 1'b1;
          end else if (!blk_busy && ocnt == expect_n && !pj_start
                       && !rn_start && !at_start) begin
            ph <= 1'b0; ocnt <= 0; fj <= 0;
            case (st)
              S_N1: st <= S_Q;
              S_Q: st <= S_K;
              S_K: st <= S_V;
              S_V: st <= S_RQ;
              S_ATT: if (hh + 1 < 2) begin hh <= hh + 1; st <= S_LQ; end
                     else begin hh <= 0; st <= S_O; end
              S_O: st <= S_R1;
              S_N2: st <= S_G;
              S_G: st <= S_U;
              S_U: st <= S_GLU;
              S_DN: st <= S_R2;
              S_NF: st <= S_HD;
              S_HD: st <= S_ARG;
              default: st <= S_IDLE;
            endcase
          end
        end
      endcase
    end
  end
endmodule
