// GENERATED by board.py: do not edit by hand.
// 8N1 UART, one start bit, eight data bits LSB first, one stop bit.
module uart_rx #(parameter DIV = 434) (
  input            clk,
  input            rst_n,
  input            rx,
  output reg [7:0] data,
  output reg       valid
);
  reg [1:0] sync;
  reg [15:0] cnt;
  reg [3:0] bitn;
  reg [7:0] sh;
  reg busy;
  always @(posedge clk) begin
    if (!rst_n) begin
      sync <= 2'b11; cnt <= 0; bitn <= 0; sh <= 0; busy <= 1'b0;
      data <= 0; valid <= 1'b0;
    end else begin
      sync <= {sync[0], rx};
      valid <= 1'b0;
      if (!busy) begin
        if (!sync[1]) begin
          // Start bit: sample the middle of each bit from here.
          busy <= 1'b1; cnt <= DIV / 2; bitn <= 0;
        end
      end else if (cnt != 0) begin
        cnt <= cnt - 1;
      end else begin
        cnt <= DIV - 1;
        if (bitn == 0) begin
          if (sync[1]) busy <= 1'b0;       // a glitch, not a start bit
          bitn <= 1;
        end else if (bitn <= 8) begin
          sh <= {sync[1], sh[7:1]};
          bitn <= bitn + 1;
        end else begin
          busy <= 1'b0;
          if (sync[1]) begin data <= sh; valid <= 1'b1; end
        end
      end
    end
  end
endmodule

module uart_tx #(parameter DIV = 434) (
  input        clk,
  input        rst_n,
  input  [7:0] data,
  input        send,
  output reg   tx,
  output       ready
);
  reg [15:0] cnt;
  reg [3:0] bitn;
  reg [9:0] sh;
  reg busy;
  assign ready = !busy && !send;
  always @(posedge clk) begin
    if (!rst_n) begin
      tx <= 1'b1; cnt <= 0; bitn <= 0; sh <= 10'h3ff; busy <= 1'b0;
    end else if (!busy) begin
      if (send) begin
        sh <= {1'b1, data, 1'b0}; busy <= 1'b1; cnt <= DIV - 1;
        bitn <= 0; tx <= 1'b0;
      end
    end else if (cnt != 0) begin
      cnt <= cnt - 1;
    end else begin
      cnt <= DIV - 1;
      if (bitn == 9) begin
        busy <= 1'b0; tx <= 1'b1;
      end else begin
        bitn <= bitn + 1;
        tx <= sh[bitn + 1];
      end
    end
  end
endmodule
